using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperTests;

[TestFixture]
internal sealed class TypeMapperMemberTypeCompatibilityTests
{
    [Test]
    public async Task Maps_warning_free_implicit_builtin_conversions()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System.Collections.Generic;
using Morphant;

namespace TestCase
{
    public interface IContract
    {
    }

    public class Base
    {
    }

    public sealed class Derived : Base, IContract
    {
    }

    public sealed class Source
    {
        public int Numeric { get; set; }

        public int LiftedNumeric { get; set; }

        public int? NullableNumeric { get; set; }

        public Derived Reference { get; set; } = null!;

        public Derived Interface { get; set; } = null!;

        public int Boxed { get; set; }

        public int? NullableBoxed { get; set; }

        public IEnumerable<string> Covariant { get; set; } = null!;

        public List<string> Collection { get; set; } = null!;

        public string[] Array { get; set; } = null!;

        public (string Reference, int Number) Tuple { get; set; }

        public string NullableTarget { get; set; } = null!;

        public string ToDynamic { get; set; } = null!;
    }

    public sealed class Destination
    {
        public long Numeric { get; set; }

        public long? LiftedNumeric { get; set; }

        public long? NullableNumeric { get; set; }

        public Base Reference { get; set; } = null!;

        public IContract Interface { get; set; } = null!;

        public object Boxed { get; set; } = null!;

        public object? NullableBoxed { get; set; }

        public IEnumerable<object> Covariant { get; set; } = null!;

        public IEnumerable<string> Collection { get; set; } = null!;

        public object[] Array { get; set; } = null!;

        public (object Reference, long Number) Tuple { get; set; }

        public string? NullableTarget { get; set; }

        public dynamic ToDynamic { get; set; } = null!;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Numeric = source.Numeric;
            destination.LiftedNumeric = source.LiftedNumeric;
            destination.NullableNumeric = source.NullableNumeric;
            destination.Reference = source.Reference;
            destination.Interface = source.Interface;
            destination.Boxed = source.Boxed;
            destination.NullableBoxed = source.NullableBoxed;
            destination.Covariant = source.Covariant;
            destination.Collection = source.Collection;
            destination.Array = source.Array;
            destination.Tuple = source.Tuple;
            destination.NullableTarget = source.NullableTarget;
            destination.ToDynamic = source.ToDynamic;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Numeric = source.Numeric,
                LiftedNumeric = source.LiftedNumeric,
                NullableNumeric = source.NullableNumeric,
                Reference = source.Reference,
                Interface = source.Interface,
                Boxed = source.Boxed,
                NullableBoxed = source.NullableBoxed,
                Covariant = source.Covariant,
                Collection = source.Collection,
                Array = source.Array,
                Tuple = source.Tuple,
                NullableTarget = source.NullableTarget,
                ToDynamic = source.ToDynamic
            };
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Ignores_nonimplicit_dynamic_and_nullable_warning_conversions()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System.Collections.Generic;
using Morphant;

namespace TestCase
{
    public class Base
    {
    }

    public sealed class Derived : Base
    {
    }

    public sealed class Source
    {
        public long Narrowing { get; set; }

        public Base Downcast { get; set; } = null!;

        public object Unboxing { get; set; } = null!;

        public dynamic Dynamic { get; set; } = null!;

        public dynamic DynamicToObject { get; set; } = null!;

        public int? NullableValue { get; set; }

        public string? NullableReference { get; set; }

        public IEnumerable<string?> NestedNullable { get; set; } = null!;

        public string?[] NullableArray { get; set; } = null!;

        public int? NullableBoxing { get; set; }

        public int Included { get; set; }
    }

    public sealed class Destination
    {
        public int Narrowing { get; set; }

        public Derived Downcast { get; set; } = null!;

        public int Unboxing { get; set; }

        public int Dynamic { get; set; }

        public object DynamicToObject { get; set; } = null!;

        public long NullableValue { get; set; }

        public string NullableReference { get; set; } = null!;

        public IEnumerable<string> NestedNullable { get; set; } = null!;

        public string[] NullableArray { get; set; } = null!;

        public object NullableBoxing { get; set; } = null!;

        public long Included { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.DynamicToObject = source.DynamicToObject;
            destination.Included = source.Included;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                DynamicToObject = source.DynamicToObject,
                Included = source.Included
            };
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Maps_only_warning_free_user_defined_implicit_conversions()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Target
    {
    }

    public sealed class SafeSource
    {
        public static implicit operator Target(SafeSource source) => new();
    }

    public sealed class MaybeNullSource
    {
        public static implicit operator Target?(MaybeNullSource source) => null;
    }

    public sealed class ExplicitSource
    {
        public static explicit operator Target(ExplicitSource source) => new();
    }

    public sealed class Source
    {
        public SafeSource Safe { get; set; } = null!;

        public SafeSource SafeNullableTarget { get; set; } = null!;

        public MaybeNullSource MaybeNull { get; set; } = null!;

        public MaybeNullSource MaybeNullNullableTarget { get; set; } = null!;

        public ExplicitSource Explicit { get; set; } = null!;
    }

    public sealed class Destination
    {
        public Target Safe { get; set; } = null!;

        public Target? SafeNullableTarget { get; set; }

        public Target MaybeNull { get; set; } = null!;

        public Target? MaybeNullNullableTarget { get; set; }

        public Target Explicit { get; set; } = null!;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Safe = source.Safe;
            destination.SafeNullableTarget = source.SafeNullableTarget;
            destination.MaybeNullNullableTarget = source.MaybeNullNullableTarget;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Safe = source.Safe,
                SafeNullableTarget = source.SafeNullableTarget,
                MaybeNullNullableTarget = source.MaybeNullNullableTarget
            };
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Honors_nullable_input_and_output_contract_attributes()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System.Diagnostics.CodeAnalysis;
using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        [MaybeNull]
        public string MaybeNull => null;

        [NotNull]
        public string? NotNull => "";

        public string? AcceptedByAllowNull { get; set; }

        [MaybeNull]
        public string MaybeNullAcceptedByAllowNull => null;

        public string? RejectedByDisallowNull { get; set; }

        public string NonNullAcceptedByDisallowNull { get; set; } = null!;

        [MaybeNull]
        public string MaybeNullField;

        [NotNull]
        public string? NotNullField = "";

        public string? AcceptedByAllowNullField;

        public string? RejectedByDisallowNullField;
    }

    public sealed class Destination
    {
        public string MaybeNull { get; set; } = null!;

        public string NotNull { get; set; } = null!;

        [AllowNull]
        public string AcceptedByAllowNull { get; set; } = null!;

        [AllowNull]
        public string MaybeNullAcceptedByAllowNull { get; set; } = null!;

        [DisallowNull]
        public string? RejectedByDisallowNull { get; set; }

        [DisallowNull]
        public string? NonNullAcceptedByDisallowNull { get; set; }

        public string MaybeNullField = null!;

        public string NotNullField = null!;

        [AllowNull]
        public string AcceptedByAllowNullField = null!;

        [DisallowNull]
        public string? RejectedByDisallowNullField;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.NotNull = source.NotNull;
            destination.AcceptedByAllowNull = source.AcceptedByAllowNull;
            destination.MaybeNullAcceptedByAllowNull = source.MaybeNullAcceptedByAllowNull;
            destination.NonNullAcceptedByDisallowNull = source.NonNullAcceptedByDisallowNull;
            destination.NotNullField = source.NotNullField;
            destination.AcceptedByAllowNullField = source.AcceptedByAllowNullField;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                NotNull = source.NotNull,
                AcceptedByAllowNull = source.AcceptedByAllowNull,
                MaybeNullAcceptedByAllowNull = source.MaybeNullAcceptedByAllowNull,
                NonNullAcceptedByDisallowNull = source.NonNullAcceptedByDisallowNull,
                NotNullField = source.NotNullField,
                AcceptedByAllowNullField = source.AcceptedByAllowNullField
            };
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Follows_oblivious_nullable_contracts()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
#nullable disable
    public sealed class LegacySource
    {
        public string ToNonNullable { get; set; }

        public string ToNullable { get; set; }
    }

    public sealed class LegacyDestination
    {
        public string FromNullable { get; set; }
    }
#nullable enable

    public sealed class ModernSource
    {
        public string? FromNullable { get; set; }
    }

    public sealed class ModernDestination
    {
        public string ToNonNullable { get; set; } = null!;

        public string? ToNullable { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<LegacySource, ModernDestination>();
            builder.Map<ModernSource, LegacyDestination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.LegacySource, global::TestCase.ModernDestination>,
        global::Morphant.ITypeMapper<global::TestCase.ModernSource, global::TestCase.LegacyDestination>
    {
        /// <inheritdoc/>
        global::TestCase.ModernDestination? global::Morphant.ITypeMapper<global::TestCase.LegacySource, global::TestCase.ModernDestination>.Map(
            global::TestCase.LegacySource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.ModernDestination? global::Morphant.ITypeMapper<global::TestCase.LegacySource, global::TestCase.ModernDestination>.Map(
            global::TestCase.LegacySource? source,
            global::TestCase.ModernDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.ToNonNullable = source.ToNonNullable;
            destination.ToNullable = source.ToNullable;

            return destination;
        }

        private global::TestCase.ModernDestination? MapNewImpl(
            global::TestCase.LegacySource source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.ModernDestination()
            {
                ToNonNullable = source.ToNonNullable,
                ToNullable = source.ToNullable
            };
        }

        /// <inheritdoc/>
        global::TestCase.LegacyDestination? global::Morphant.ITypeMapper<global::TestCase.ModernSource, global::TestCase.LegacyDestination>.Map(
            global::TestCase.ModernSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.LegacyDestination? global::Morphant.ITypeMapper<global::TestCase.ModernSource, global::TestCase.LegacyDestination>.Map(
            global::TestCase.ModernSource? source,
            global::TestCase.LegacyDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.FromNullable = source.FromNullable;

            return destination;
        }

        private global::TestCase.LegacyDestination? MapNewImpl1(
            global::TestCase.ModernSource source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.LegacyDestination()
            {
                FromNullable = source.FromNullable
            };
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Applies_compatibility_to_init_only_and_required_members()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Compatible { get; set; }

        public string? Incompatible { get; set; }
    }

    public sealed class SafeInitDestination
    {
        public long Compatible { get; init; }
    }

    public sealed class RequiredDestination
    {
        public required long Compatible { get; init; }

        public required string Incompatible { get; init; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, SafeInitDestination>();
            builder.Map<Source, RequiredDestination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SafeInitDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>
    {
        /// <inheritdoc/>
        global::TestCase.SafeInitDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SafeInitDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.SafeInitDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SafeInitDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.SafeInitDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.SafeInitDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.SafeInitDestination()
            {
                Compatible = source.Compatible
            };
        }

        /// <inheritdoc/>
        global::TestCase.RequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.RequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.RequiredDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            return destination;
        }

        private global::TestCase.RequiredDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Maps_implicit_type_parameter_conversions()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public class Base
    {
    }

    public sealed class Source<TValue>
        where TValue : Base
    {
        public TValue Reference { get; set; } = null!;

        public TValue Boxed { get; set; } = null!;
    }

    public sealed class Destination
    {
        public Base Reference { get; set; } = null!;

        public object Boxed { get; set; } = null!;
    }

    public partial class Container<TOuter>
        where TOuter : Base
    {
        [MorphantMapper]
        public partial class TestMapper<TValue> : TypeMapper
            where TValue : TOuter
        {
            protected override void Configure(MapperBuilder builder)
            {
                builder.Map<Source<TValue>, Destination>();
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    partial class Container<TOuter>
    {
        public partial class TestMapper<TValue> :
            global::Morphant.ITypeMapper<global::TestCase.Source<TValue>, global::TestCase.Destination>
        {
            /// <inheritdoc/>
            global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source<TValue>, global::TestCase.Destination>.Map(
                global::TestCase.Source<TValue>? source,
                global::Morphant.MappingContext context)
            {
                if (source is null)
                {
                    return default;
                }

                return MapNewImpl(source, context);
            }

            /// <inheritdoc/>
            global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source<TValue>, global::TestCase.Destination>.Map(
                global::TestCase.Source<TValue>? source,
                global::TestCase.Destination? destination,
                global::Morphant.MappingContext context)
            {
                if (source is null)
                {
                    return default;
                }

                if (destination is null)
                {
                    return MapNewImpl(source, context);
                }

                destination.Reference = source.Reference;
                destination.Boxed = source.Boxed;

                return destination;
            }

            private global::TestCase.Destination? MapNewImpl(
                global::TestCase.Source<TValue> source,
                global::Morphant.MappingContext context)
            {
                return new global::TestCase.Destination()
                {
                    Reference = source.Reference,
                    Boxed = source.Boxed
                };
            }
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_Container_1_TestMapper_1.g.cs",
                expected
            ));
    }
}
