using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperTests;

[TestFixture]
internal sealed class TypeMapperControlFlowTemplateTests
{
    [Test]
    public async Task Maps_direct_templates_from_block_lambdas_with_ordered_value_locals()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public bool UseOffset { get; set; }

        public int Offset { get; set; }

        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, int>()
                .Template(source =>
                {
                    var offset = source.Offset + 1;
                    var value = source.UseOffset
                        ? offset
                        : source.Value;

                    return value;
                });
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int>
    {
        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::TestCase.Source, int>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapByTemplate(source);
        }

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::TestCase.Source, int>.Map(
            global::TestCase.Source? source,
            int destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapByTemplate(source);
        }

        private int MapByTemplate(global::TestCase.Source source)
        {
            var offset = source.Offset + 1;
            var value = source.UseOffset ? offset : source.Value;
            return value;
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.System_Int32.g.cs",
                BuildExpectedExtension(
                    "int",
                    "int",
                    "int")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Preserves_mode_relevant_locals_and_applies_with_overlays_to_the_selected_construction()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using TestCase.Morphant.Generated;

namespace TestCase
{
    public sealed class Source
    {
        public bool UseFactory { get; set; }

        public int FactoryId { get; set; }

        public int Id { get; set; }

        public bool UseFirstName { get; set; }

        public string FirstName { get; set; } = null!;

        public string LastName { get; set; } = null!;

        public int Discarded { get; set; }

        public int Replacement { get; set; }
    }

    public sealed class Destination
    {
        public Destination(int id)
        {
            Id = id;
        }

        public int Id { get; set; }

        public string DisplayName { get; set; } = null!;

        public int Replaced { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    var result = source.UseFactory
                        ? new DestinationMorphantTemplate(
                            ByFactory(
                                () => new Destination(
                                    source.FactoryId)))
                        : new DestinationMorphantTemplate(source.Id);
                    var displayName = source.UseFirstName
                        ? source.FirstName
                        : source.LastName;

                    return result with
                    {
                        DisplayName = displayName,
                        Replaced = source.Discarded
                    } with
                    {
                        Replaced = source.Replacement
                    };
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Markers.IByFactoryMarker<
                global::TestCase.Destination> marker)
        {
        }

        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> id)
        {
        }

        public global::Morphant.Members.Member<int> Id
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<string> DisplayName
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Replaced
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            var displayName = source.UseFirstName ? source.FirstName : source.LastName;

            destination.DisplayName = displayName;
            destination.Replaced = source.Replacement;
            destination.Id = source.Id;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            var result = source.UseFactory;
            var displayName = source.UseFirstName ? source.FirstName : source.LastName;

            if (result)
            {
                global::TestCase.Destination CreateByFactory(global::TestCase.Source source1) => new global::TestCase.Destination(source1.FactoryId);

                global::TestCase.Destination destination = CreateByFactory(source);
                destination.DisplayName = displayName;
                destination.Replaced = source.Replacement;
                destination.Id = source.Id;

                return destination;
            }
            else
            {
                return new global::TestCase.Destination(
                    id: source.Id)
                {
                    DisplayName = displayName,
                    Replaced = source.Replacement
                };
            }
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Branches_a_local_member_marker_and_omits_an_init_only_decision_from_MapExisting()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public bool IncludeValue { get; set; }

        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public required int Value { get; init; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    var value = source.IncludeValue
                        ? source.Value
                        : Ignore<int>();

                    return new()
                    {
                        Value = value
                    };
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            var value = source.IncludeValue;

            if (value)
            {
                return new global::TestCase.Destination()
                {
                    Value = source.Value
                };
            }
            else
            {
                throw new global::System.NotImplementedException();
            }
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Collapses_a_conditional_nested_map_independently_for_each_mapping_mode()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class ChildSource
    {
    }

    public sealed class ChildDestination
    {
    }

    public sealed class Source
    {
        public bool UseExistingChild { get; set; }

        public ChildSource? Child { get; set; }
    }

    public sealed class Destination
    {
        public ChildDestination? Child { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source => new()
                {
                    Child = Map(source.Child)
                })
                .Template((source, destination) => new()
                {
                    Child = source.UseExistingChild
                        ? Map(source.Child, destination.Child)
                        : Map(source.Child)
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public global::Morphant.Members.Member<
            global::TestCase.ChildDestination?> Child
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            if (source.UseExistingChild)
            {
                global::TestCase.ChildDestination? child = context.Mapper.Map<global::TestCase.ChildSource?, global::TestCase.ChildDestination?>(source.Child, destination.Child, context);

                destination.Child = child;

                return destination;
            }
            else
            {
                destination.Child = context.Mapper.Map<global::TestCase.ChildSource?, global::TestCase.ChildDestination?>(source.Child, context);

                return destination;
            }
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Child = context.Mapper.Map<global::TestCase.ChildSource?, global::TestCase.ChildDestination?>(source.Child, context)
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Branches_Auto_and_explicit_values_while_caching_existing_state_before_assignments()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public bool UseAutomatic { get; set; }

        public int First { get; set; }

        public int Value { get; set; }

        public int Fallback { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class Destination
    {
        public int First { get; set; }

        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source => new()
                {
                    First = 0 + source.First,
                    Value = source.UseAutomatic
                        ? Auto()
                        : source.Fallback
                })
                .Template((source, destination) => new()
                {
                    First =
                        destination.First + source.First,
                    Value = source.UseAutomatic
                        ? Auto()
                        : destination.Value
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public global::Morphant.Members.Member<int> First
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            if (source.UseAutomatic)
            {
                int first = destination.First + source.First;

                destination.First = first;
                destination.Value = source.Value;
                destination.Remaining = source.Remaining;

                return destination;
            }
            else
            {
                int first = destination.First + source.First;
                int value = destination.Value;

                destination.First = first;
                destination.Value = value;
                destination.Remaining = source.Remaining;

                return destination;
            }
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            if (source.UseAutomatic)
            {
                return new global::TestCase.Destination()
                {
                    First = 0 + source.First,
                    Value = source.Value,
                    Remaining = source.Remaining
                };
            }
            else
            {
                return new global::TestCase.Destination()
                {
                    First = 0 + source.First,
                    Value = source.Fallback,
                    Remaining = source.Remaining
                };
            }
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Branches_full_templates_with_if_multiple_returns_and_throw_expressions()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using System;
using TestCase.Morphant.Generated;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class AlwaysThrowSource
    {
    }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    if (source.Value > 0)
                    {
                        return new()
                        {
                            Value = source.Value + 1
                        };
                    }

                    return (source.Value == 0
                        ? throw new InvalidOperationException()
                        : new DestinationMorphantTemplate()) with
                    {
                        Value = source.Value - 1
                    };
                });

            builder.Map<AlwaysThrowSource, Destination>()
                .Template(source =>
                {
                    throw new InvalidOperationException();
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>,
        global::Morphant.ITypeMapper<global::TestCase.AlwaysThrowSource, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            if (source.Value > 0)
            {
                destination.Value = source.Value + 1;

                return destination;
            }
            else
            {
                if (source.Value == 0)
                {
                    throw new global::System.InvalidOperationException();
                }
                else
                {
                    destination.Value = source.Value - 1;

                    return destination;
                }
            }
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            if (source.Value > 0)
            {
                return new global::TestCase.Destination()
                {
                    Value = source.Value + 1
                };
            }
            else
            {
                if (source.Value == 0)
                {
                    throw new global::System.InvalidOperationException();
                }
                else
                {
                    return new global::TestCase.Destination()
                    {
                        Value = source.Value - 1
                    };
                }
            }
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.AlwaysThrowSource, global::TestCase.Destination>.Map(
            global::TestCase.AlwaysThrowSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.AlwaysThrowSource, global::TestCase.Destination>.Map(
            global::TestCase.AlwaysThrowSource? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            throw new global::System.InvalidOperationException();
        }

        private global::TestCase.Destination? MapNewImpl1(
            global::TestCase.AlwaysThrowSource source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.InvalidOperationException();
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Removes_statement_branches_and_locals_that_only_select_MapNew_construction()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public bool UseFactory { get; set; }

        public int FactoryId { get; set; }

        public int Value { get; set; }

        public int Observe(int value) => value;
    }

    public sealed class Destination
    {
        public Destination()
        {
        }

        public Destination(int id)
        {
            Id = id;
        }

        public int Id { get; set; }

        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    if (source.UseFactory)
                    {
                        var factoryId = source.Observe(
                            source.FactoryId);

                        return new(
                            ByFactory(
                                () => new Destination(factoryId)))
                        {
                            Value = source.Value
                        };
                    }

                    return new()
                    {
                        Value = source.Value
                    };
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Markers.IByFactoryMarker<
                global::TestCase.Destination> marker)
        {
        }

        public DestinationMorphantTemplate()
        {
        }

        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> id)
        {
        }

        public global::Morphant.Members.Member<int> Id
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            if (source.UseFactory)
            {
                var factoryId = source.Observe(source.FactoryId);

                global::TestCase.Destination CreateByFactory() => new global::TestCase.Destination(factoryId);

                global::TestCase.Destination destination = CreateByFactory();
                destination.Value = source.Value;

                return destination;
            }
            else
            {
                return new global::TestCase.Destination()
                {
                    Value = source.Value
                };
            }
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Keeps_locals_on_their_execution_paths_and_emits_throwing_branches()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public bool Reject { get; set; }

        public bool Increment { get; set; }

        public int Value { get; set; }

        public int Observe(int value) => value;
    }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    var value = source.Observe(source.Value);

                    if (source.Reject)
                    {
                        throw new InvalidOperationException(
                            value.ToString());
                    }

                    else if (source.Increment)
                    {
                        const int offset = 1;
                        var adjusted = source.Observe(
                            value + offset);

                        return new()
                        {
                            Value = adjusted
                        };
                    }
                    else
                    {
                        {
                            var adjusted = source.Observe(
                                value - 1);

                            return new()
                            {
                                Value = adjusted
                            };
                        }
                    }
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            var value = source.Observe(source.Value);

            if (source.Reject)
            {
                throw new global::System.InvalidOperationException(value.ToString());
            }
            else
            {
                if (source.Increment)
                {
                    const int offset = 1;
                    var adjusted = source.Observe(value + offset);

                    destination.Value = adjusted;

                    return destination;
                }
                else
                {
                    var adjusted = source.Observe(value - 1);

                    destination.Value = adjusted;

                    return destination;
                }
            }
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            var value = source.Observe(source.Value);

            if (source.Reject)
            {
                throw new global::System.InvalidOperationException(value.ToString());
            }
            else
            {
                if (source.Increment)
                {
                    const int offset = 1;
                    var adjusted = source.Observe(value + offset);

                    return new global::TestCase.Destination()
                    {
                        Value = adjusted
                    };
                }
                else
                {
                    var adjusted = source.Observe(value - 1);

                    return new global::TestCase.Destination()
                    {
                        Value = adjusted
                    };
                }
            }
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Keeps_mutable_loop_control_flow_unsupported()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    var value = 0;

                    while (value < source.Value)
                    {
                        value++;
                    }

                    return new()
                    {
                        Value = value
                    };
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            throw new global::System.NotSupportedException(
                "Template block lambda contains a statement that is not supported.");
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotSupportedException(
                "Template block lambda contains a statement that is not supported.");
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Generates_throwing_mappings_for_unsupported_Template_captures()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class ConditionalSource
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            var offset = GetOffset();

            static bool SelectBranch()
            {
                if (DateTime.UtcNow.Ticks > 0)
                {
                    return true;
                }

                return false;
            }

            builder.Map<Source, Destination>()
                .Template(source => new()
                {
                    Value = source.Value + offset
                });

            builder.Map<ConditionalSource, Destination>()
                .Template(source => SelectBranch()
                    ? new()
                    {
                        Value = source.Value
                    }
                    : new()
                    {
                        Value = source.Value + 1
                    });
        }

        private int GetOffset() => 1;
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>,
        global::Morphant.ITypeMapper<global::TestCase.ConditionalSource, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            throw new global::System.NotSupportedException(
                "Template contains a capture that cannot be transferred to the generated mapper.");
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotSupportedException(
                "Template contains a capture that cannot be transferred to the generated mapper.");
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.ConditionalSource, global::TestCase.Destination>.Map(
            global::TestCase.ConditionalSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.ConditionalSource, global::TestCase.Destination>.Map(
            global::TestCase.ConditionalSource? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            throw new global::System.NotSupportedException(
                "Template contains a capture that cannot be transferred to the generated mapper.");
        }

        private global::TestCase.Destination? MapNewImpl1(
            global::TestCase.ConditionalSource source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotSupportedException(
                "Template contains a capture that cannot be transferred to the generated mapper.");
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Hoists_constructor_Auto_and_explicit_values_into_locals_only_for_MapNew()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public interface IValue
    {
    }

    public sealed class AutomaticValue : IValue
    {
    }

    public sealed class ExplicitValue : IValue
    {
    }

    public sealed class Source
    {
        public bool UseAutomatic { get; set; }

        public int First { get; set; }

        public AutomaticValue Value { get; set; } = new();

        public ExplicitValue Explicit { get; set; } = new();

        public int Other { get; set; }

        public int ExplicitOther { get; set; }

        public int Observe(int value) => value;
    }

    public sealed class Destination
    {
        public Destination(
            int first,
            IValue value,
            int other)
        {
            First = first;
            Value = value;
            Other = other;
        }

        public int First { get; }

        public IValue Value { get; }

        public int Other { get; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source => new(
                    source.Observe(source.First),
                    source.UseAutomatic
                        ? Auto()
                        : source.Explicit,
                    source.UseAutomatic
                        ? source.ExplicitOther
                        : Auto()));
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate(
        global::Morphant.Members.ConstructorMember<int> first,
        global::Morphant.Members.ConstructorMember<global::TestCase.IValue> value,
        global::Morphant.Members.ConstructorMember<int> other);
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            int first = source.Observe(source.First);
            global::TestCase.IValue value = source.UseAutomatic ? source.Value : source.Explicit;
            int other = source.UseAutomatic ? source.ExplicitOther : source.Other;

            return new global::TestCase.Destination(
                first: first,
                value: value,
                other: other);
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Branches_ByConvention_constructor_members_only_for_MapNew()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public bool UseAutomatic { get; set; }

        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public Destination(int value = 17)
        {
            Value = value;
        }

        public int Value { get; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source => new(
                    ByConvention(),
                    new()
                    {
                        value = source.UseAutomatic
                            ? Auto()
                            : Ignore<int>()
                    }));
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed class DestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> value = null!;
    }

    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationMorphantTemplateConstructorMembers? members = null)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            if (source.UseAutomatic)
            {
                return new global::TestCase.Destination(
                    value: source.Value);
            }
            else
            {
                return new global::TestCase.Destination();
            }
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Keeps_constructor_value_locals_only_in_MapNew()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public Destination(int value)
        {
            Value = value;
        }

        public int Value { get; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    var value = source.Value + 1;

                    return new(value);
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate(
        global::Morphant.Members.ConstructorMember<int> value);
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            var value = source.Value + 1;

            return new global::TestCase.Destination(
                value: value);
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Keeps_ByConvention_constructor_member_locals_only_in_MapNew()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public Destination(int value)
        {
            Value = value;
        }

        public int Value { get; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    var adjusted = source.Value + 1;

                    return new(
                        ByConvention(),
                        new()
                        {
                            value = adjusted
                        });
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed class DestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> value = null!;
    }

    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationMorphantTemplateConstructorMembers? members = null)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            var adjusted = source.Value + 1;

            return new global::TestCase.Destination(
                value: adjusted);
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Preserves_local_names_and_suffixes_only_real_method_conflicts()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(source =>
                {
                    var __morphantTemplateLocal0 = source.Value;
                    var destination =
                        __morphantTemplateLocal0 + 1;

                    return new()
                    {
                        Value = destination
                    };
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            var __morphantTemplateLocal0 = source.Value;
            var destination1 = __morphantTemplateLocal0 + 1;

            destination.Value = destination1;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            var __morphantTemplateLocal0 = source.Value;
            var destination = __morphantTemplateLocal0 + 1;

            return new global::TestCase.Destination()
            {
                Value = destination
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    private static string BuildExpectedExtension(
        string destinationType,
        string existingDestinationType,
        string templateResultType)
    {
        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace Morphant
                 {
                     internal static partial class MorphantGeneratedTemplateExtensions
                     {
                         /// <summary>
                         /// Configures a mapping template.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

                         /// <summary>
                         /// Configures a mapping template for an existing destination.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and the non-null
                         /// existing destination and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{existingDestinationType.TrimEnd('?')}}, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
                     }
                 }
                 """;
    }
}
