using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperTests;

[TestFixture]
internal sealed class TypeMapperBasicTemplateTests
{
    [Test]
    public async Task Maps_explicit_generated_members_before_remaining_convention_members()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using static System.Math;

namespace TestCase
{
    public sealed class Source
    {
        public int First { get; set; }

        public int Second { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class Destination
    {
        public Destination()
        {
        }

        public Destination(int first)
        {
            First = first;
        }

        public int First { get; set; }

        public int Second { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(s => new()
                {
                    Second = Abs(s.Second),
                    First = s.First + 10
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate()
        {
        }

        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> first)
        {
        }

        public global::Morphant.Members.Member<int> First
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Second
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Second = global::System.Math.Abs(source.Second);
            destination.First = source.First + 10;
            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Second = global::System.Math.Abs(source.Second),
                First = source.First + 10,
                Remaining = source.Remaining
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Returns_direct_template_values_from_both_mapping_modes()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Number { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, int>()
                .Template(source => source.Number + 1);

            builder.Map<Source, string>()
                .Template(_ => "constant");
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int>,
        global::Morphant.ITypeMapper<global::TestCase.Source, string>
    {
        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::TestCase.Source, int>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return source.Number + 1;
        }

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::TestCase.Source, int>.Map(
            global::TestCase.Source? source,
            int destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return source.Number + 1;
        }

        /// <inheritdoc/>
        string? global::Morphant.ITypeMapper<global::TestCase.Source, string>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        string? global::Morphant.ITypeMapper<global::TestCase.Source, string>.Map(
            global::TestCase.Source? source,
            string? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return "constant";
        }

        private string? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return "constant";
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.System_Int32.g.cs",
                BuildExpectedExtension(
                    "int",
                    "int",
                    "int")
            ),
            (
                "Morphant.Generated.TemplateExtension.System_String.g.cs",
                BuildExpectedExtension(
                    "string",
                    "string?",
                    "string")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Maps_block_lambdas_with_a_final_return()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class ConstructorDestination
    {
        public ConstructorDestination(int value)
        {
            Value = value;
        }

        public int Value { get; set; }
    }

    public sealed class BlockDestination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, ConstructorDestination>()
                .Template(s => new(s.Value));

            builder.Map<Source, BlockDestination>()
                .Template(s =>
                {
                    return new()
                    {
                        Value = s.Value + 1
                    };
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record ConstructorDestinationMorphantTemplate(
        global::Morphant.Members.ConstructorMember<int> value);

    internal sealed record BlockDestinationMorphantTemplate
    {
        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ConstructorDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.BlockDestination>
    {
        /// <inheritdoc/>
        global::TestCase.ConstructorDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ConstructorDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.ConstructorDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ConstructorDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.ConstructorDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.ConstructorDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.ConstructorDestination(
                value: source.Value);
        }

        /// <inheritdoc/>
        global::TestCase.BlockDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.BlockDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.BlockDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.BlockDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.BlockDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Value = source.Value + 1;

            return destination;
        }

        private global::TestCase.BlockDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.BlockDestination()
            {
                Value = source.Value + 1
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_BlockDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.BlockDestination",
                    "global::TestCase.BlockDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "BlockDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TemplateExtension.TestCase_ConstructorDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.ConstructorDestination",
                    "global::TestCase.ConstructorDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "ConstructorDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Maps_nullable_struct_template_members_in_both_mapping_modes()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public struct Destination
    {
        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination?>()
                .Template(s => new()
                {
                    Value = s.Value + 1
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination?>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination?>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination?>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            var destinationValue = destination.Value;
            destinationValue.Value = source.Value + 1;
            destinationValue.Remaining = source.Remaining;

            return destinationValue;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Value = source.Value + 1,
                Remaining = source.Remaining
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "System_Nullable_1_global__TestCase_Destination_.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination?",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate?")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Applies_required_init_and_SetsRequiredMembers_contracts()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using System.Diagnostics.CodeAnalysis;

namespace TestCase
{
    public sealed class Source
    {
        public int ExplicitRequired { get; set; }

        public int ConventionRequired { get; set; }

        public int InitOnly { get; set; }

        public int Remaining { get; set; }

        public int Value { get; set; }
    }

    public sealed class RequiredDestination
    {
        public required int ExplicitRequired { get; init; }

        public required int ConventionRequired { get; set; }

        public int InitOnly { get; init; }

        public int Remaining { get; set; }
    }

    public sealed class SetsRequiredDestination
    {
        [SetsRequiredMembers]
        public SetsRequiredDestination()
        {
        }

        public required int Missing { get; init; }

        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, RequiredDestination>()
                .Template(s => new()
                {
                    InitOnly = s.InitOnly + 1,
                    ExplicitRequired = s.ExplicitRequired + 2
                });

            builder.Map<Source, SetsRequiredDestination>()
                .Template(s => new()
                {
                    Value = s.Value + 3
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record RequiredDestinationMorphantTemplate
    {
        public global::Morphant.Members.Member<int> ExplicitRequired
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> ConventionRequired
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> InitOnly
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }

    internal sealed record SetsRequiredDestinationMorphantTemplate
    {
        public global::Morphant.Members.Member<int> Missing
        {
            get => null!;
            set { }
        }

        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>
    {
        /// <inheritdoc/>
        global::TestCase.RequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.RequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.RequiredDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.ConventionRequired = source.ConventionRequired;
            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.RequiredDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.RequiredDestination()
            {
                InitOnly = source.InitOnly + 1,
                ExplicitRequired = source.ExplicitRequired + 2,
                ConventionRequired = source.ConventionRequired,
                Remaining = source.Remaining
            };
        }

        /// <inheritdoc/>
        global::TestCase.SetsRequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.SetsRequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.SetsRequiredDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Value = source.Value + 3;

            return destination;
        }

        private global::TestCase.SetsRequiredDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.SetsRequiredDestination()
            {
                Value = source.Value + 3
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_RequiredDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.RequiredDestination",
                    "global::TestCase.RequiredDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "RequiredDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_SetsRequiredDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.SetsRequiredDestination",
                    "global::TestCase.SetsRequiredDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "SetsRequiredDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Preserves_nameof_alias_and_extension_method_semantics()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using TestCase.Extensions;
using TextAlias = System.String;

namespace TestCase
{
    public sealed class Source
    {
        public string Text { get; set; } = string.Empty;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, string>()
                .Template(s =>
                    s.Text.Wrap(nameof(s)) + TextAlias.Empty);
        }
    }
}

namespace TestCase.Extensions
{
    public static class TextExtensions
    {
        public static string Wrap(
            this string value,
            string name) =>
            name + value;
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, string>
    {
        /// <inheritdoc/>
        string? global::Morphant.ITypeMapper<global::TestCase.Source, string>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        string? global::Morphant.ITypeMapper<global::TestCase.Source, string>.Map(
            global::TestCase.Source? source,
            string? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return global::TestCase.Extensions.TextExtensions.Wrap(source.Text, "s") + string.Empty;
        }

        private string? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return global::TestCase.Extensions.TextExtensions.Wrap(source.Text, "s") + string.Empty;
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.System_String.g.cs",
                BuildExpectedExtension(
                    "string",
                    "string?",
                    "string")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    private static string BuildExpectedExtension(
        string destinationType,
        string existingDestinationType,
        string templateResultType)
    {
        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace Morphant
                 {
                     internal static partial class MorphantGeneratedTemplateExtensions
                     {
                         /// <summary>
                         /// Configures a mapping template.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

                         /// <summary>
                         /// Configures a mapping template for an existing destination.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and the non-null
                         /// existing destination and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{existingDestinationType.TrimEnd('?')}}, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
                     }
                 }
                 """;
    }
}
