using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperTests;

[TestFixture]
internal sealed class TypeMapperByConventionTemplateTests
{
    [Test]
    public async Task Uses_unambiguous_convention_constructor_and_preserves_outer_initializer_order()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; set; }

        public string Name { get; set; } = string.Empty;

        public int Explicit { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class Destination
    {
        public Destination()
        {
            Name = string.Empty;
        }

        public Destination(int id, string name)
        {
            Id = id;
            Name = name;
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public int Explicit { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(s => new(ByConvention())
                {
                    Explicit = Adjust(s.Explicit)
                });
        }

        private int Adjust(int value) => value + 1;
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed class DestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> id = null!;

        public global::Morphant.Members.ConstructorMember<string> name = null!;
    }

    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationMorphantTemplateConstructorMembers? members = null)
        {
        }

        public global::Morphant.Members.Member<int> Explicit
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Explicit = Adjust(source.Explicit);
            destination.Id = source.Id;
            destination.Name = source.Name;
            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination(
                id: source.Id,
                name: source.Name)
            {
                Explicit = Adjust(source.Explicit),
                Remaining = source.Remaining
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Applies_explicit_constructor_mappings_before_automatic_arguments_in_written_order()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int First { get; set; }

        public string Second { get; set; } = string.Empty;

        public int Third { get; set; }

        public int ExternalFirst { get; set; }

        public int ExternalThird { get; set; }

        public int Explicit { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class Destination
    {
        public Destination(
            int first,
            string second,
            int third,
            bool enabled = true,
            params string[] tags)
        {
            First = first;
            Second = second;
            Third = third;
            Enabled = enabled;
            Tags = tags;
        }

        public int First { get; set; }

        public string Second { get; set; }

        public int Third { get; set; }

        public bool Enabled { get; set; }

        public string[] Tags { get; set; }

        public int Explicit { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(s => new(
                    members: new()
                    {
                        third = Adjust(s.ExternalThird),
                        first = Adjust(s.ExternalFirst)
                    },
                    marker: ByConvention())
                {
                    Explicit = Adjust(s.Explicit)
                });
        }

        private int Adjust(int value) => value + 1;
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed class DestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> first = null!;

        public global::Morphant.Members.ConstructorMember<string> second = null!;

        public global::Morphant.Members.ConstructorMember<int> third = null!;

        public global::Morphant.Members.ConstructorMember<bool> enabled = null!;

        public global::Morphant.Members.ConstructorMember<string[]> tags = null!;
    }

    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationMorphantTemplateConstructorMembers? members = null)
        {
        }

        public global::Morphant.Members.Member<int> Explicit
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Explicit = Adjust(source.Explicit);
            destination.First = source.First;
            destination.Second = source.Second;
            destination.Third = source.Third;
            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination(
                third: Adjust(source.ExternalThird),
                first: Adjust(source.ExternalFirst),
                second: source.Second)
            {
                Explicit = Adjust(source.Explicit),
                Remaining = source.Remaining
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Preserves_required_member_and_SetsRequiredMembers_contracts()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using System.Diagnostics.CodeAnalysis;

namespace TestCase
{
    public sealed class Source
    {
        public int ExternalId { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class RequiredDestination
    {
        public RequiredDestination(int id)
        {
        }

        public required int Id { get; init; }

        public int Remaining { get; set; }
    }

    public sealed class SetsRequiredDestination
    {
        [SetsRequiredMembers]
        public SetsRequiredDestination(int id)
        {
            Id = id;
            Missing = string.Empty;
        }

        public int Id { get; set; }

        public required string Missing { get; init; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, RequiredDestination>()
                .Template(s => new(
                    ByConvention(),
                    new()
                    {
                        id = s.ExternalId + 1
                    })
                {
                    Id = s.ExternalId + 2
                });

            builder.Map<Source, SetsRequiredDestination>()
                .Template(s => new(
                    ByConvention(),
                    new()
                    {
                        id = s.ExternalId + 3
                    }));
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed class RequiredDestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> id = null!;
    }

    internal sealed record RequiredDestinationMorphantTemplate
    {
        public RequiredDestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            RequiredDestinationMorphantTemplateConstructorMembers? members = null)
        {
        }

        public global::Morphant.Members.Member<int> Id
        {
            get => null!;
            set { }
        }
    }

    internal sealed class SetsRequiredDestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> id = null!;
    }

    internal sealed record SetsRequiredDestinationMorphantTemplate
    {
        public SetsRequiredDestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            SetsRequiredDestinationMorphantTemplateConstructorMembers? members = null)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>
    {
        /// <inheritdoc/>
        global::TestCase.RequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.RequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.RequiredDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.RequiredDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.RequiredDestination(
                id: source.ExternalId + 1)
            {
                Id = source.ExternalId + 2,
                Remaining = source.Remaining
            };
        }

        /// <inheritdoc/>
        global::TestCase.SetsRequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.SetsRequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.SetsRequiredDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.SetsRequiredDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.SetsRequiredDestination(
                id: source.ExternalId + 3)
            {
                Remaining = source.Remaining
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_RequiredDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.RequiredDestination",
                    "global::TestCase.RequiredDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "RequiredDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_SetsRequiredDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.SetsRequiredDestination",
                    "global::TestCase.SetsRequiredDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "SetsRequiredDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Evaluates_explicit_mappings_before_a_shared_automatic_required_value()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using System.Diagnostics.CodeAnalysis;

namespace TestCase
{
    public sealed class Source
    {
        public int Explicit { get; set; }

        public int Shared { get; set; }
    }

    public sealed class Destination
    {
        public Destination(
            [AllowNull] string label,
            int explicitValue,
            int shared)
        {
            Label = label ?? string.Empty;
            ExplicitValue = explicitValue;
            Shared = shared;
        }

        public string Label { get; set; }

        public int ExplicitValue { get; set; }

        public required int Shared { get; init; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(s => new(
                    ByConvention(),
                    new()
                    {
                        label = null,
                        explicitValue = Observe(s.Explicit)
                    }));
        }

        private int Observe(int value) => value;
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed class DestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<string>? label = null!;

        public global::Morphant.Members.ConstructorMember<int> explicitValue = null!;

        public global::Morphant.Members.ConstructorMember<int> shared = null!;
    }

    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationMorphantTemplateConstructorMembers? members = null)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            string? templateLabel = null;
            int templateExplicitValue = Observe(source.Explicit);
            var sourceShared = source.Shared;

            return new global::TestCase.Destination(
                label: templateLabel,
                explicitValue: templateExplicitValue,
                shared: sourceShared)
            {
                Shared = sourceShared
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Does_not_use_explicit_mappings_to_select_a_constructor_and_applies_Auto()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class AmbiguousDestination
    {
        public AmbiguousDestination(int id)
        {
            Value = id;
        }

        public AmbiguousDestination(long id)
        {
            Value = id;
        }

        public long Value { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class MarkerDestination
    {
        public MarkerDestination(int value)
        {
            Value = value;
        }

        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, AmbiguousDestination>()
                .Template(s => new(
                    ByConvention(),
                    new()
                    {
                        idInt = s.Value + 1
                    })
                {
                    Remaining = s.Remaining + 1
                });

            builder.Map<Source, MarkerDestination>()
                .Template(s => new(
                    ByConvention(),
                    new()
                    {
                        value = Auto()
                    })
                {
                    Remaining = s.Remaining + 2
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed class AmbiguousDestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> idInt = null!;

        public global::Morphant.Members.ConstructorMember<long> idLong = null!;
    }

    internal sealed record AmbiguousDestinationMorphantTemplate
    {
        public AmbiguousDestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            AmbiguousDestinationMorphantTemplateConstructorMembers? members = null)
        {
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }

    internal sealed class MarkerDestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> value = null!;
    }

    internal sealed record MarkerDestinationMorphantTemplate
    {
        public MarkerDestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            MarkerDestinationMorphantTemplateConstructorMembers? members = null)
        {
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AmbiguousDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.MarkerDestination>
    {
        /// <inheritdoc/>
        global::TestCase.AmbiguousDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AmbiguousDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.AmbiguousDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AmbiguousDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.AmbiguousDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Remaining = source.Remaining + 1;
            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.AmbiguousDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::TestCase.MarkerDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.MarkerDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.MarkerDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.MarkerDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.MarkerDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Remaining = source.Remaining + 2;
            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.MarkerDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.MarkerDestination(
                value: source.Value)
            {
                Remaining = source.Remaining + 2
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_AmbiguousDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.AmbiguousDestination",
                    "global::TestCase.AmbiguousDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "AmbiguousDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_MarkerDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.MarkerDestination",
                    "global::TestCase.MarkerDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "MarkerDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Maps_nullable_struct_and_constructed_generic_destinations()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public struct ValueDestination
    {
        public ValueDestination(int value)
        {
            Value = value;
            Remaining = 0;
        }

        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class GenericDestination<T>
    {
        public GenericDestination(T value)
        {
            Value = value;
        }

        public T Value { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, ValueDestination?>()
                .Template(s => new(
                    ByConvention(),
                    new()
                    {
                        value = s.Value + 1
                    })
                {
                    Remaining = s.Remaining + 1
                });

            builder.Map<Source, GenericDestination<int>>()
                .Template(s => new(
                    ByConvention(),
                    new()
                    {
                        value = s.Value + 2
                    })
                {
                    Remaining = s.Remaining + 2
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed class ValueDestinationMorphantTemplateConstructorMembers
    {
        public global::Morphant.Members.ConstructorMember<int> value = null!;
    }

    internal sealed record ValueDestinationMorphantTemplate
    {
        public ValueDestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            ValueDestinationMorphantTemplateConstructorMembers? members = null)
        {
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }

    internal sealed class GenericDestinationMorphantTemplateConstructorMembers<T>
    {
        public global::Morphant.Members.ConstructorMember<T> value = null!;
    }

    internal sealed record GenericDestinationMorphantTemplate<T>
    {
        public GenericDestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker,
            GenericDestinationMorphantTemplateConstructorMembers<T>? members = null)
        {
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ValueDestination?>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.GenericDestination<int>>
    {
        /// <inheritdoc/>
        global::TestCase.ValueDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ValueDestination?>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.ValueDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ValueDestination?>.Map(
            global::TestCase.Source? source,
            global::TestCase.ValueDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            var destinationValue = destination.Value;
            destinationValue.Remaining = source.Remaining + 1;
            destinationValue.Value = source.Value;

            return destinationValue;
        }

        private global::TestCase.ValueDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.ValueDestination(
                value: source.Value + 1)
            {
                Remaining = source.Remaining + 1
            };
        }

        /// <inheritdoc/>
        global::TestCase.GenericDestination<int>? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.GenericDestination<int>>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.GenericDestination<int>? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.GenericDestination<int>>.Map(
            global::TestCase.Source? source,
            global::TestCase.GenericDestination<int>? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Remaining = source.Remaining + 2;
            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.GenericDestination<int>? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.GenericDestination<int>(
                value: source.Value + 2)
            {
                Remaining = source.Remaining + 2
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "System_Nullable_1_global__TestCase_ValueDestination_.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.ValueDestination?",
                    "global::TestCase.ValueDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "ValueDestinationMorphantTemplate?")
            ),
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_GenericDestination_1_int_.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.GenericDestination<int>",
                    "global::TestCase.GenericDestination<int>?",
                    "global::TestCase.Morphant.Generated." +
                    "GenericDestinationMorphantTemplate<int>")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Keeps_MapNew_unsupported_for_abstract_and_interface_destinations_while_mapping_existing_values()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public abstract class AbstractDestination
    {
        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public interface IInterfaceDestination
    {
        int Value { get; set; }

        int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, AbstractDestination>()
                .Template(s => new(ByConvention())
                {
                    Remaining = s.Remaining + 1
                });

            builder.Map<Source, IInterfaceDestination>()
                .Template(s => new(ByConvention())
                {
                    Remaining = s.Remaining + 2
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record AbstractDestinationMorphantTemplate
    {
        public AbstractDestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }

    internal sealed record IInterfaceDestinationMorphantTemplate
    {
        public IInterfaceDestinationMorphantTemplate(
            global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AbstractDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.IInterfaceDestination>
    {
        /// <inheritdoc/>
        global::TestCase.AbstractDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AbstractDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.AbstractDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AbstractDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.AbstractDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Remaining = source.Remaining + 1;
            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.AbstractDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::TestCase.IInterfaceDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.IInterfaceDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.IInterfaceDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.IInterfaceDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.IInterfaceDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Remaining = source.Remaining + 2;
            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.IInterfaceDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_AbstractDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.AbstractDestination",
                    "global::TestCase.AbstractDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "AbstractDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_IInterfaceDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.IInterfaceDestination",
                    "global::TestCase.IInterfaceDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "IInterfaceDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    private static string BuildExpectedExtension(
        string destinationType,
        string existingDestinationType,
        string templateResultType)
    {
        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace Morphant
                 {
                     internal static partial class MorphantGeneratedTemplateExtensions
                     {
                         /// <summary>
                         /// Configures a mapping template.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

                         /// <summary>
                         /// Configures a mapping template for an existing destination.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and the non-null
                         /// existing destination and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{existingDestinationType.TrimEnd('?')}}, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
                     }
                 }
                 """;
    }
}
