using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperTests;

[TestFixture]
internal sealed class TypeMapperMappingTypeSupportTests
{
    [Test]
    public async Task Generates_all_supported_concrete_mapping_type_forms()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using Morphant;

namespace TestCase
{
    public class ClassSource
    {
    }

    public interface IInterfaceDestination
    {
    }

    public delegate void SourceDelegate(string value);

    public readonly struct StructDestination
    {
    }

    public enum SourceEnum
    {
        None
    }

    public sealed class Generic<T>
    {
    }

    public sealed class Outer<T>
    {
        public sealed class Nested<TNested>
        {
        }
    }

    [MorphantMapper]
    public partial class ConcreteMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<ClassSource, IInterfaceDestination>();
            builder.Map<SourceDelegate, StructDestination>();
            builder.Map<SourceEnum?, int?>();
            builder.Map<string?[], object[,]>();
            builder.Map<
                (ClassSource Source, int Count),
                (string? Text, SourceEnum Kind)>();
            builder.Map<
                Generic<List<string?>>,
                Outer<int>.Nested<ClassSource>>();
            builder.Map<dynamic, Action>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class ConcreteMapper :
        global::Morphant.ITypeMapper<global::TestCase.ClassSource, global::TestCase.IInterfaceDestination>,
        global::Morphant.ITypeMapper<global::TestCase.SourceDelegate, global::TestCase.StructDestination>,
        global::Morphant.ITypeMapper<global::TestCase.SourceEnum?, int?>,
        global::Morphant.ITypeMapper<string?[], object[,]>,
        global::Morphant.ITypeMapper<(global::TestCase.ClassSource Source, int Count), (string? Text, global::TestCase.SourceEnum Kind)>,
        global::Morphant.ITypeMapper<global::TestCase.Generic<global::System.Collections.Generic.List<string?>>, global::TestCase.Outer<int>.Nested<global::TestCase.ClassSource>>,
        global::Morphant.ITypeMapper<object, global::System.Action>
    {
        global::TestCase.IInterfaceDestination global::Morphant.ITypeMapper<global::TestCase.ClassSource, global::TestCase.IInterfaceDestination>.Map(
            global::TestCase.ClassSource source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::TestCase.IInterfaceDestination global::Morphant.ITypeMapper<global::TestCase.ClassSource, global::TestCase.IInterfaceDestination>.Map(
            global::TestCase.ClassSource source,
            global::TestCase.IInterfaceDestination destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::TestCase.StructDestination global::Morphant.ITypeMapper<global::TestCase.SourceDelegate, global::TestCase.StructDestination>.Map(
            global::TestCase.SourceDelegate source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::TestCase.StructDestination global::Morphant.ITypeMapper<global::TestCase.SourceDelegate, global::TestCase.StructDestination>.Map(
            global::TestCase.SourceDelegate source,
            global::TestCase.StructDestination destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        int? global::Morphant.ITypeMapper<global::TestCase.SourceEnum?, int?>.Map(
            global::TestCase.SourceEnum? source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        int? global::Morphant.ITypeMapper<global::TestCase.SourceEnum?, int?>.Map(
            global::TestCase.SourceEnum? source,
            int? destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        object[,] global::Morphant.ITypeMapper<string?[], object[,]>.Map(
            string?[] source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        object[,] global::Morphant.ITypeMapper<string?[], object[,]>.Map(
            string?[] source,
            object[,] destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        (string? Text, global::TestCase.SourceEnum Kind) global::Morphant.ITypeMapper<(global::TestCase.ClassSource Source, int Count), (string? Text, global::TestCase.SourceEnum Kind)>.Map(
            (global::TestCase.ClassSource Source, int Count) source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        (string? Text, global::TestCase.SourceEnum Kind) global::Morphant.ITypeMapper<(global::TestCase.ClassSource Source, int Count), (string? Text, global::TestCase.SourceEnum Kind)>.Map(
            (global::TestCase.ClassSource Source, int Count) source,
            (string? Text, global::TestCase.SourceEnum Kind) destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::TestCase.Outer<int>.Nested<global::TestCase.ClassSource> global::Morphant.ITypeMapper<global::TestCase.Generic<global::System.Collections.Generic.List<string?>>, global::TestCase.Outer<int>.Nested<global::TestCase.ClassSource>>.Map(
            global::TestCase.Generic<global::System.Collections.Generic.List<string?>> source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Outer<int>.Nested<global::TestCase.ClassSource>();
        }

        global::TestCase.Outer<int>.Nested<global::TestCase.ClassSource> global::Morphant.ITypeMapper<global::TestCase.Generic<global::System.Collections.Generic.List<string?>>, global::TestCase.Outer<int>.Nested<global::TestCase.ClassSource>>.Map(
            global::TestCase.Generic<global::System.Collections.Generic.List<string?>> source,
            global::TestCase.Outer<int>.Nested<global::TestCase.ClassSource> destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::System.Action global::Morphant.ITypeMapper<object, global::System.Action>.Map(
            object source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::System.Action global::Morphant.ITypeMapper<object, global::System.Action>.Map(
            object source,
            global::System.Action destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_ConcreteMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Generates_types_using_mapper_and_containing_type_parameters()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source<TOuter, TValue>
    {
    }

    public sealed class Destination<TOuter, TValue>
    {
    }

    public partial class Container<TOuter>
    {
        [MorphantMapper]
        public partial class TestMapper<TValue> : TypeMapper
        {
            protected override void Configure(MapperBuilder builder)
            {
                builder.Map<
                    Source<TOuter, TValue>,
                    Destination<TOuter, TValue>>();
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    partial class Container<TOuter>
    {
        public partial class TestMapper<TValue> :
            global::Morphant.ITypeMapper<global::TestCase.Source<TOuter, TValue>, global::TestCase.Destination<TOuter, TValue>>
        {
            global::TestCase.Destination<TOuter, TValue> global::Morphant.ITypeMapper<global::TestCase.Source<TOuter, TValue>, global::TestCase.Destination<TOuter, TValue>>.Map(
                global::TestCase.Source<TOuter, TValue> source,
                global::Morphant.MappingContext context)
            {
                return new global::TestCase.Destination<TOuter, TValue>();
            }

            global::TestCase.Destination<TOuter, TValue> global::Morphant.ITypeMapper<global::TestCase.Source<TOuter, TValue>, global::TestCase.Destination<TOuter, TValue>>.Map(
                global::TestCase.Source<TOuter, TValue> source,
                global::TestCase.Destination<TOuter, TValue> destination,
                global::Morphant.MappingContext context)
                => throw new global::System.NotImplementedException();
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_Container_1_TestMapper_1.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Deduplicates_clr_equivalent_types_and_preserves_the_first_representable_shape()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System;
using Morphant;

namespace TestCase
{
    public sealed class Box<T>
    {
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<dynamic, object?>();
            builder.Map<object?, dynamic>();

            builder.Map<
                Box<(dynamic Item, string? Name)[]>,
                (object? Value, int Count)>();
            builder.Map<
                Box<(object Value, string Name)[]>,
                (dynamic Other, int Total)>();

            builder.Map<nint, nuint>();
            builder.Map<IntPtr, UIntPtr>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<object, object?>,
        global::Morphant.ITypeMapper<global::TestCase.Box<(object Item, string? Name)[]>, (object? Value, int Count)>,
        global::Morphant.ITypeMapper<nint, nuint>
    {
        object? global::Morphant.ITypeMapper<object, object?>.Map(
            object source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        object? global::Morphant.ITypeMapper<object, object?>.Map(
            object source,
            object? destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        (object? Value, int Count) global::Morphant.ITypeMapper<global::TestCase.Box<(object Item, string? Name)[]>, (object? Value, int Count)>.Map(
            global::TestCase.Box<(object Item, string? Name)[]> source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        (object? Value, int Count) global::Morphant.ITypeMapper<global::TestCase.Box<(object Item, string? Name)[]>, (object? Value, int Count)>.Map(
            global::TestCase.Box<(object Item, string? Name)[]> source,
            (object? Value, int Count) destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        nuint global::Morphant.ITypeMapper<nint, nuint>.Map(
            nint source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        nuint global::Morphant.ITypeMapper<nint, nuint>.Map(
            nint source,
            nuint destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Skips_file_local_types_at_any_depth()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    file sealed class FileLocal
    {
    }

    file sealed class FileContainer
    {
        public sealed class Nested
        {
        }
    }

    public sealed class Envelope<T>
    {
    }

    public sealed class Outer<T>
    {
        public sealed class Nested<TNested>
        {
        }
    }

    public sealed class SafeSource
    {
    }

    public sealed class SafeDestination
    {
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<FileLocal, SafeDestination>();
            builder.Map<Envelope<FileLocal[]>, SafeDestination>();
            builder.Map<Outer<FileLocal>.Nested<int>, SafeDestination>();
            builder.Map<FileContainer.Nested, SafeDestination>();
            builder.Map<
                SafeSource,
                Envelope<Outer<int>.Nested<FileLocal>>>();
            builder.Map<SafeSource, SafeDestination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.SafeSource, global::TestCase.SafeDestination>
    {
        global::TestCase.SafeDestination global::Morphant.ITypeMapper<global::TestCase.SafeSource, global::TestCase.SafeDestination>.Map(
            global::TestCase.SafeSource source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.SafeDestination();
        }

        global::TestCase.SafeDestination global::Morphant.ITypeMapper<global::TestCase.SafeSource, global::TestCase.SafeDestination>.Map(
            global::TestCase.SafeSource source,
            global::TestCase.SafeDestination destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Skips_pointer_and_function_pointer_compositions()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Envelope<T>
    {
    }

    public sealed class SafeSource
    {
    }

    public sealed class SafeDestination
    {
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override unsafe void Configure(MapperBuilder builder)
        {
            builder.Map<int*[], SafeDestination>();
            builder.Map<
                Envelope<delegate*<int, void>[]>,
                SafeDestination>();
            builder.Map<SafeSource, int*[,]>();
            builder.Map<
                SafeSource,
                Envelope<delegate* unmanaged<int, void>[]>>();
            builder.Map<SafeSource, SafeDestination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.SafeSource, global::TestCase.SafeDestination>
    {
        global::TestCase.SafeDestination global::Morphant.ITypeMapper<global::TestCase.SafeSource, global::TestCase.SafeDestination>.Map(
            global::TestCase.SafeSource source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.SafeDestination();
        }

        global::TestCase.SafeDestination global::Morphant.ITypeMapper<global::TestCase.SafeSource, global::TestCase.SafeDestination>.Map(
            global::TestCase.SafeSource source,
            global::TestCase.SafeDestination destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            allowUnsafe: true,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Does_not_generate_a_mapper_when_two_mappings_can_unify()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using System;
using Morphant;

namespace TestCase
{
    public sealed class Box<T>
    {
    }

    public sealed class Pair<TFirst, TSecond>
    {
    }

    public sealed class Outer<TOuter>
    {
        public sealed class Nested<TInner>
        {
        }
    }

    [MorphantMapper]
    public partial class DirectMapper<T> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<string, bool>();
            builder.Map<T, object>();
            builder.Map<int, object>();
        }
    }

    [MorphantMapper]
    public partial class ConstraintsIgnoredMapper<T> : TypeMapper
        where T : class
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<T, object>();
            builder.Map<int, object>();
        }
    }

    [MorphantMapper]
    public partial class CrossMapper<T, U> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<T, U>();
            builder.Map<U, T>();
        }
    }

    [MorphantMapper]
    public partial class NestedMapper<T, U> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Box<T>, Pair<U, T>>();
            builder.Map<Box<int>, Pair<string, int>>();
        }
    }

    [MorphantMapper]
    public partial class ArrayMapper<T> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<T[], object>();
            builder.Map<int[], object>();
        }
    }

    [MorphantMapper]
    public partial class NestedContainingTypeMapper<T, U> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Outer<T>.Nested<U>, object>();
            builder.Map<Outer<int>.Nested<string>, object>();
        }
    }

    public partial class Container<TOuter>
    {
        [MorphantMapper]
        public partial class ContainingParameterMapper<TInner> : TypeMapper
        {
            protected override void Configure(MapperBuilder builder)
            {
                builder.Map<TOuter, TInner>();
                builder.Map<int, string>();
            }
        }
    }

    [MorphantMapper]
    public partial class ControlMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Guid, DateTime>();
        }
    }
}
""";

        // lang=c#
        const string expectedControl =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class ControlMapper :
        global::Morphant.ITypeMapper<global::System.Guid, global::System.DateTime>
    {
        global::System.DateTime global::Morphant.ITypeMapper<global::System.Guid, global::System.DateTime>.Map(
            global::System.Guid source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::System.DateTime global::Morphant.ITypeMapper<global::System.Guid, global::System.DateTime>.Map(
            global::System.Guid source,
            global::System.DateTime destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_ControlMapper.g.cs",
                expectedControl
            ));
    }

    [Test]
    public async Task Generates_generic_mappings_when_their_types_cannot_unify()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using System.Collections.Generic;
using Morphant;

namespace TestCase
{
    [MorphantMapper]
    public partial class TestMapper<T, U> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<T, T>();
            builder.Map<int, string>();
            builder.Map<T, List<T>>();
            builder.Map<List<U>, U>();
            builder.Map<T[], int>();
            builder.Map<T[,], int>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper<T, U> :
        global::Morphant.ITypeMapper<T, T>,
        global::Morphant.ITypeMapper<int, string>,
        global::Morphant.ITypeMapper<T, global::System.Collections.Generic.List<T>>,
        global::Morphant.ITypeMapper<global::System.Collections.Generic.List<U>, U>,
        global::Morphant.ITypeMapper<T[], int>,
        global::Morphant.ITypeMapper<T[,], int>
    {
        T global::Morphant.ITypeMapper<T, T>.Map(
            T source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        T global::Morphant.ITypeMapper<T, T>.Map(
            T source,
            T destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        string global::Morphant.ITypeMapper<int, string>.Map(
            int source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        string global::Morphant.ITypeMapper<int, string>.Map(
            int source,
            string destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::System.Collections.Generic.List<T> global::Morphant.ITypeMapper<T, global::System.Collections.Generic.List<T>>.Map(
            T source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        global::System.Collections.Generic.List<T> global::Morphant.ITypeMapper<T, global::System.Collections.Generic.List<T>>.Map(
            T source,
            global::System.Collections.Generic.List<T> destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        U global::Morphant.ITypeMapper<global::System.Collections.Generic.List<U>, U>.Map(
            global::System.Collections.Generic.List<U> source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        U global::Morphant.ITypeMapper<global::System.Collections.Generic.List<U>, U>.Map(
            global::System.Collections.Generic.List<U> source,
            U destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        int global::Morphant.ITypeMapper<T[], int>.Map(
            T[] source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        int global::Morphant.ITypeMapper<T[], int>.Map(
            T[] source,
            int destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        int global::Morphant.ITypeMapper<T[,], int>.Map(
            T[,] source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();

        int global::Morphant.ITypeMapper<T[,], int>.Map(
            T[,] source,
            int destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotImplementedException();
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper_2.g.cs",
                expected
            ));
    }
}
