using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperTests;

[TestFixture]
internal sealed class TypeMapperNullHandlingTests
{
    [Test]
    public void Defines_stable_public_enum_values()
    {
        Assert.Multiple(() =>
        {
            Assert.That(
                (int)NullSourceHandling.Default,
                Is.Zero);
            Assert.That(
                (int)NullSourceHandling.ReturnNull,
                Is.EqualTo(1));
            Assert.That(
                (int)NullSourceHandling.ReturnDestination,
                Is.EqualTo(2));
            Assert.That(
                (int)NullSourceHandling.Throw,
                Is.EqualTo(3));

            Assert.That(
                (int)NullDestinationHandling.Default,
                Is.Zero);
            Assert.That(
                (int)NullDestinationHandling.CreateNew,
                Is.EqualTo(1));
            Assert.That(
                (int)NullDestinationHandling.Throw,
                Is.EqualTo(2));
        });
    }

    [TestCase(null, null)]
    [TestCase("", "")]
    [TestCase("Default", "Default")]
    [TestCase("default", "default")]
    public async Task Applies_library_defaults_when_assembly_values_inherit(
        string? nullSourceHandling,
        string? nullDestinationHandling)
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination!.Value = source.Value;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Value = source.Value
            };
        }
    }
}
""";

        var expectedSource =
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            );

        if (nullSourceHandling is null)
        {
            await TypeMapperGeneratorTest.RunAndAssert(
                LanguageVersion.CSharp9,
                source,
                expectedSource);
            return;
        }

        await TypeMapperGeneratorTest.RunAndAssertWithAnalyzerConfig(
            LanguageVersion.CSharp9,
            source,
            $$"""
is_global = true

build_property.MorphantNullSourceHandling = {{nullSourceHandling}}
build_property.MorphantNullDestinationHandling = {{nullDestinationHandling}}
""",
            expectedSource);
    }

    [Test]
    public async Task Allocates_collision_safe_MapNewImpl_names()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
    }

    public sealed class FirstDestination
    {
    }

    public sealed class SecondDestination
    {
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, FirstDestination>();
            builder.Map<Source, SecondDestination>();
        }

        private void MapNewImpl()
        {
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.FirstDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SecondDestination>
    {
        /// <inheritdoc/>
        global::TestCase.FirstDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.FirstDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.FirstDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.FirstDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.FirstDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            return destination;
        }

        private global::TestCase.FirstDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.FirstDestination();
        }

        /// <inheritdoc/>
        global::TestCase.SecondDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SecondDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl2(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.SecondDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SecondDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.SecondDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl2(source, context);
            }

            return destination;
        }

        private global::TestCase.SecondDestination? MapNewImpl2(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.SecondDestination();
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Resolves_map_then_mapper_then_assembly_precedence()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
    }

    public sealed class AssemblyDestination
    {
    }

    public sealed class RootDestination
    {
    }

    public sealed class MappingDestination
    {
    }

    [MorphantMapper]
    public partial class AssemblyMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.NullSourceHandling(
                NullSourceHandling.ReturnDestination);
            builder.NullDestinationHandling(
                NullDestinationHandling.CreateNew);
            builder.Map<Source, AssemblyDestination>();
            builder.NullSourceHandling(
                NullSourceHandling.Default);
            builder.NullDestinationHandling(
                NullDestinationHandling.Default);
        }
    }

    [MorphantMapper]
    public partial class RootMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, RootDestination>();
            builder.NullSourceHandling(
                NullSourceHandling.ReturnDestination);
            builder.NullDestinationHandling(
                NullDestinationHandling.CreateNew);
        }
    }

    [MorphantMapper]
    public partial class MappingMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.NullSourceHandling(
                NullSourceHandling.Throw);
            builder.NullDestinationHandling(
                NullDestinationHandling.Throw);

            builder.Map<Source, MappingDestination>()
                .NullSourceHandling(
                    NullSourceHandling.ReturnNull)
                .NullDestinationHandling(
                    NullDestinationHandling.CreateNew);
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssertWithAnalyzerConfig(
            LanguageVersion.CSharp9,
            source,
            """
is_global = true

build_property.MorphantNullSourceHandling = Throw
build_property.MorphantNullDestinationHandling = Throw
""",
            (
                "Morphant.Generated.TypeMapper." +
                "TestCase_AssemblyMapper.g.cs",
                BuildExpectedSimpleMapper(
                    "AssemblyMapper",
                    "AssemblyDestination",
                    """
                    throw new global::System.ArgumentNullException(nameof(source));
                    """,
                    """
                    throw new global::System.ArgumentNullException(nameof(source));
                    """,
                    """
                    throw new global::System.ArgumentNullException(nameof(destination));
                    """)
            ),
            (
                "Morphant.Generated.TypeMapper." +
                "TestCase_MappingMapper.g.cs",
                BuildExpectedSimpleMapper(
                    "MappingMapper",
                    "MappingDestination",
                    """
                    return default;
                    """,
                    """
                    return default;
                    """,
                    """
                    return new global::TestCase.MappingDestination();
                    """,
                    useMapNewImpl: true)
            ),
            (
                "Morphant.Generated.TypeMapper." +
                "TestCase_RootMapper.g.cs",
                BuildExpectedSimpleMapper(
                    "RootMapper",
                    "RootDestination",
                    """
                    return default;
                    """,
                    """
                    return destination;
                    """,
                    """
                    return new global::TestCase.RootDestination();
                    """,
                    useMapNewImpl: true)
            ));
    }

    [Test]
    public async Task Creates_new_destination_inside_MapExisting_and_keeps_previous_null()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, int?>(MappingMode.MapExisting)
                .NullSourceHandling(
                    NullSourceHandling.ReturnDestination)
                .NullDestinationHandling(
                    NullDestinationHandling.CreateNew)
                .Template((source, previous) =>
                    (previous ?? -1) + source.Value);
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int?>
    {
        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotSupportedException(
                "The effective MappingMode does not include MapNew.");

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Map(
            global::TestCase.Source? source,
            int? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return destination;
            }

            if (destination is null)
            {
                return -1 + source.Value;
            }

            return (destination ?? -1) + source.Value;
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "System_Nullable_1_int_.g.cs",
                BuildExpectedExtension(
                    "int?",
                    "int?",
                    "int?")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Keeps_invalid_values_and_allows_more_specific_overrides()
    {
        // lang=c#
        const string invalidRootSource =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
    }

    public sealed class InheritedDestination
    {
    }

    public sealed class SourceOverrideDestination
    {
    }

    public sealed class FullOverrideDestination
    {
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.NullSourceHandling(GetNullSourceHandling());
            builder.NullDestinationHandling(
                (NullDestinationHandling)3);

            builder.Map<Source, InheritedDestination>();

            builder.Map<Source, SourceOverrideDestination>()
                .NullSourceHandling(
                    NullSourceHandling.ReturnNull);

            builder.Map<Source, FullOverrideDestination>()
                .NullSourceHandling(
                    NullSourceHandling.ReturnDestination)
                .NullDestinationHandling(
                    NullDestinationHandling.CreateNew);
        }

        private static NullSourceHandling GetNullSourceHandling() =>
            NullSourceHandling.Throw;
    }
}
""";

        // lang=c#
        const string invalidAssemblySource =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
    }

    public sealed class InheritedDestination
    {
    }

    public sealed class SourceOverrideDestination
    {
    }

    public sealed class FullOverrideDestination
    {
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, InheritedDestination>();

            builder.Map<Source, SourceOverrideDestination>()
                .NullSourceHandling(
                    NullSourceHandling.ReturnNull);

            builder.Map<Source, FullOverrideDestination>()
                .NullSourceHandling(
                    NullSourceHandling.ReturnDestination)
                .NullDestinationHandling(
                    NullDestinationHandling.CreateNew);
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.InheritedDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SourceOverrideDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.FullOverrideDestination>
    {
        /// <inheritdoc/>
        global::TestCase.InheritedDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.InheritedDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
            => throw new global::System.NotSupportedException(
                "The effective NullSourceHandling is invalid.");

        /// <inheritdoc/>
        global::TestCase.InheritedDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.InheritedDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.InheritedDestination? destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotSupportedException(
                "The effective NullSourceHandling is invalid.");

        /// <inheritdoc/>
        global::TestCase.SourceOverrideDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SourceOverrideDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return new global::TestCase.SourceOverrideDestination();
        }

        /// <inheritdoc/>
        global::TestCase.SourceOverrideDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SourceOverrideDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.SourceOverrideDestination? destination,
            global::Morphant.MappingContext context)
            => throw new global::System.NotSupportedException(
                "The effective NullDestinationHandling is invalid.");

        /// <inheritdoc/>
        global::TestCase.FullOverrideDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.FullOverrideDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.FullOverrideDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.FullOverrideDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.FullOverrideDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return destination;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.FullOverrideDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.FullOverrideDestination();
        }
    }
}
""";

        var expectedSource =
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            );

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            invalidRootSource,
            expectedSource);

        await TypeMapperGeneratorTest.RunAndAssertWithAnalyzerConfig(
            LanguageVersion.CSharp9,
            invalidAssemblySource,
            """
is_global = true

build_property.MorphantNullSourceHandling = Unexpected
build_property.MorphantNullDestinationHandling = Unexpected
""",
            expectedSource);
    }

    [Test]
    public async Task Checks_nullable_values_but_not_non_nullable_values()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public struct ValueSource
    {
    }

    public struct ValueDestination
    {
    }

    public struct NullableSourceDestination
    {
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<ValueSource, ValueDestination>()
                .NullSourceHandling(NullSourceHandling.Throw)
                .NullDestinationHandling(
                    NullDestinationHandling.Throw);

            builder.Map<ValueSource?, NullableSourceDestination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.ValueSource, global::TestCase.ValueDestination>,
        global::Morphant.ITypeMapper<global::TestCase.ValueSource?, global::TestCase.NullableSourceDestination>
    {
        /// <inheritdoc/>
        global::TestCase.ValueDestination global::Morphant.ITypeMapper<global::TestCase.ValueSource, global::TestCase.ValueDestination>.Map(
            global::TestCase.ValueSource source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.ValueDestination();
        }

        /// <inheritdoc/>
        global::TestCase.ValueDestination global::Morphant.ITypeMapper<global::TestCase.ValueSource, global::TestCase.ValueDestination>.Map(
            global::TestCase.ValueSource source,
            global::TestCase.ValueDestination destination,
            global::Morphant.MappingContext context)
            => destination;

        /// <inheritdoc/>
        global::TestCase.NullableSourceDestination global::Morphant.ITypeMapper<global::TestCase.ValueSource?, global::TestCase.NullableSourceDestination>.Map(
            global::TestCase.ValueSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return new global::TestCase.NullableSourceDestination();
        }

        /// <inheritdoc/>
        global::TestCase.NullableSourceDestination global::Morphant.ITypeMapper<global::TestCase.ValueSource?, global::TestCase.NullableSourceDestination>.Map(
            global::TestCase.ValueSource? source,
            global::TestCase.NullableSourceDestination destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return destination;
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    private static string BuildExpectedSimpleMapper(
        string mapperName,
        string destinationName,
        string mapNewNullSourceStatement,
        string mapExistingNullSourceStatement,
        string nullDestinationStatement,
        bool useMapNewImpl = false)
    {
        var mapNewStatement = useMapNewImpl
            ? "return MapNewImpl(source, context);"
            : $"return new global::TestCase.{destinationName}();";
        var effectiveNullDestinationStatement =
            useMapNewImpl
                ? "return MapNewImpl(source, context);"
                : nullDestinationStatement;
        var mapNewImpl = useMapNewImpl
            ? $$"""


                         private global::TestCase.{{destinationName}}? MapNewImpl(
                             global::TestCase.Source source,
                             global::Morphant.MappingContext context)
                         {
                             return new global::TestCase.{{destinationName}}();
                         }
                 """
            : string.Empty;

        // lang=c#
        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace TestCase
                 {
                     public partial class {{mapperName}} :
                         global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.{{destinationName}}>
                     {
                         /// <inheritdoc/>
                         global::TestCase.{{destinationName}}? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.{{destinationName}}>.Map(
                             global::TestCase.Source? source,
                             global::Morphant.MappingContext context)
                         {
                             if (source is null)
                             {
                                 {{mapNewNullSourceStatement}}
                             }

                             {{mapNewStatement}}
                         }

                         /// <inheritdoc/>
                         global::TestCase.{{destinationName}}? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.{{destinationName}}>.Map(
                             global::TestCase.Source? source,
                             global::TestCase.{{destinationName}}? destination,
                             global::Morphant.MappingContext context)
                         {
                             if (source is null)
                             {
                                 {{mapExistingNullSourceStatement}}
                             }

                             if (destination is null)
                             {
                                 {{effectiveNullDestinationStatement}}
                             }

                             return destination;
                         }{{mapNewImpl}}
                     }
                 }
                 """;
    }

    private static string BuildExpectedExtension(
        string destinationType,
        string existingDestinationType,
        string templateResultType)
    {
        // lang=c#
        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace Morphant
                 {
                     internal static partial class MorphantGeneratedTemplateExtensions
                     {
                         /// <summary>
                         /// Configures a mapping template.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

                         /// <summary>
                         /// Configures a mapping template that depends on the destination's previous state.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and the destination's
                         /// previous value and describes the mapping. The previous value is
                         /// <see langword="default"/> when no destination exists.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{existingDestinationType}}, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
                     }
                 }
                 """;
    }
}
