using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperTests;

[TestFixture]
internal sealed class TypeMapperExplicitConstructorTemplateTests
{
    [Test]
    public async Task Maps_constructor_arguments_in_written_order_before_initializer_and_convention_members()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using System;
using static System.Math;

namespace TestCase
{
    public sealed class Source
    {
        public int First { get; set; }

        public string Second { get; set; } = string.Empty;

        public string? Label { get; set; }

        public bool Enabled { get; set; }

        public string[] Tags { get; set; } = Array.Empty<string>();

        public int Explicit { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class Destination
    {
        public Destination(
            int first,
            string second,
            string? label = "default",
            bool enabled = true,
            params string[] tags)
        {
            First = first;
            Second = second;
            Label = label;
            Enabled = enabled;
            Tags = tags;
        }

        public int First { get; set; }

        public string Second { get; set; }

        public string? Label { get; set; }

        public bool Enabled { get; set; }

        public string[] Tags { get; set; }

        public int Explicit { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(s => new(
                    Adjust(Abs(s.First)),
                    tags: s.Tags,
                    second: s.Second.Trim(),
                    label: null)
                {
                    Explicit = s.Explicit + 1
                });
        }

        private int Adjust(int value) => value + 1;
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> first,
            global::Morphant.Members.ConstructorMember<string> second,
            global::Morphant.Members.ConstructorMember<string?>? label = null,
            global::Morphant.Members.ConstructorMember<bool> enabled = null!,
            global::Morphant.Members.ConstructorMember<string[]> tags = null!)
        {
        }

        public global::Morphant.Members.Member<int> Explicit
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Explicit = source.Explicit + 1;
            destination.First = source.First;
            destination.Second = source.Second;
            destination.Label = source.Label;
            destination.Enabled = source.Enabled;
            destination.Tags = source.Tags;
            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination(
                first: Adjust(global::System.Math.Abs(source.First)),
                tags: source.Tags,
                second: source.Second.Trim(),
                label: null)
            {
                Explicit = source.Explicit + 1,
                Remaining = source.Remaining
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Uses_constructor_member_cast_to_select_an_overload()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Members;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public Destination(int value)
        {
            Value = value;
        }

        public Destination(long value)
        {
            Value = value;
        }

        public long Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(s => new(
                    (ConstructorMember<long>)s.Value));
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> value)
        {
        }

        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<long> value)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination(
                value: (long)source.Value);
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Uses_destination_defaults_when_all_optional_and_params_arguments_are_omitted()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
    }

    public sealed class Destination
    {
        public Destination(
            int seed = 42,
            params string[] tags)
        {
        }

        public Destination(string required)
        {
        }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(_ => new());
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> seed = null!,
            global::Morphant.Members.ConstructorMember<string[]> tags = null!)
        {
        }

        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<string> required)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination();
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Does_not_map_members_corresponding_to_selected_constructor_parameters_when_optional_arguments_are_omitted()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int SuppliedSet { get; set; }

        public int SuppliedInit { get; set; }

        public int OmittedSet { get; set; }

        public int OmittedInit { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class Destination
    {
        public Destination(
            int suppliedSet,
            int suppliedInit,
            int omittedSet = 10,
            int omittedInit = 20)
        {
            SuppliedSet = suppliedSet;
            SuppliedInit = suppliedInit;
            OmittedSet = omittedSet;
            OmittedInit = omittedInit;
        }

        public int SuppliedSet { get; set; }

        public int SuppliedInit { get; init; }

        public int OmittedSet { get; set; }

        public int OmittedInit { get; init; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(s => new(
                    s.SuppliedSet,
                    s.SuppliedInit));
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> suppliedSet,
            global::Morphant.Members.ConstructorMember<int> suppliedInit,
            global::Morphant.Members.ConstructorMember<int> omittedSet = null!,
            global::Morphant.Members.ConstructorMember<int> omittedInit = null!)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.SuppliedSet = source.SuppliedSet;
            destination.OmittedSet = source.OmittedSet;
            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination(
                suppliedSet: source.SuppliedSet,
                suppliedInit: source.SuppliedInit)
            {
                Remaining = source.Remaining
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Maps_nullable_struct_and_constructed_generic_destinations()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public struct ValueDestination
    {
        public ValueDestination(int value)
        {
            Value = value;
            Remaining = 0;
        }

        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class GenericDestination<T>
    {
        public GenericDestination(T value)
        {
            Value = value;
        }

        public T Value { get; set; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, ValueDestination?>()
                .Template(s => new(s.Value + 1)
                {
                    Remaining = s.Remaining + 1
                });

            builder.Map<Source, GenericDestination<int>>()
                .Template(s => new(s.Value + 2)
                {
                    Remaining = s.Remaining + 2
                });
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record ValueDestinationMorphantTemplate
    {
        public ValueDestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> value)
        {
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }

    internal sealed record GenericDestinationMorphantTemplate<T>
    {
        public GenericDestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<T> value)
        {
        }

        public global::Morphant.Members.Member<int> Remaining
        {
            get => null!;
            set { }
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ValueDestination?>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.GenericDestination<int>>
    {
        /// <inheritdoc/>
        global::TestCase.ValueDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ValueDestination?>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.ValueDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ValueDestination?>.Map(
            global::TestCase.Source? source,
            global::TestCase.ValueDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            var destinationValue = destination.Value;
            destinationValue.Remaining = source.Remaining + 1;
            destinationValue.Value = source.Value;

            return destinationValue;
        }

        private global::TestCase.ValueDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.ValueDestination(
                value: source.Value + 1)
            {
                Remaining = source.Remaining + 1
            };
        }

        /// <inheritdoc/>
        global::TestCase.GenericDestination<int>? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.GenericDestination<int>>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.GenericDestination<int>? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.GenericDestination<int>>.Map(
            global::TestCase.Source? source,
            global::TestCase.GenericDestination<int>? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Remaining = source.Remaining + 2;
            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.GenericDestination<int>? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.GenericDestination<int>(
                value: source.Value + 2)
            {
                Remaining = source.Remaining + 2
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "System_Nullable_1_global__TestCase_ValueDestination_.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.ValueDestination?",
                    "global::TestCase.ValueDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "ValueDestinationMorphantTemplate?")
            ),
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_GenericDestination_1_int_.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.GenericDestination<int>",
                    "global::TestCase.GenericDestination<int>?",
                    "global::TestCase.Morphant.Generated." +
                    "GenericDestinationMorphantTemplate<int>")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Applies_Auto_to_an_explicit_constructor_parameter()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public Destination(int value)
        {
            Value = value;
        }

        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Template(_ => new(Auto()));
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record DestinationMorphantTemplate
    {
        public DestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> value)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination(
                value: source.Value);
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TemplateExtension.TestCase_Destination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.Destination",
                    "global::TestCase.Destination?",
                    "global::TestCase.Morphant.Generated." +
                    "DestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    [Test]
    public async Task Preserves_required_member_and_SetsRequiredMembers_contracts()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using System.Diagnostics.CodeAnalysis;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }

        public int Remaining { get; set; }
    }

    public sealed class RequiredDestination
    {
        public RequiredDestination(int value)
        {
        }

        public required int Value { get; init; }

        public int Remaining { get; set; }
    }

    public sealed class SetsRequiredDestination
    {
        [SetsRequiredMembers]
        public SetsRequiredDestination(int value)
        {
            Value = value;
            Missing = string.Empty;
        }

        public int Value { get; set; }

        public required string Missing { get; init; }

        public int Remaining { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, RequiredDestination>()
                .Template(s => new(s.Value + 1));

            builder.Map<Source, SetsRequiredDestination>()
                .Template(s => new(s.Value + 2));
        }
    }
}

namespace TestCase.Morphant.Generated
{
    internal sealed record RequiredDestinationMorphantTemplate
    {
        public RequiredDestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> value)
        {
        }
    }

    internal sealed record SetsRequiredDestinationMorphantTemplate
    {
        public SetsRequiredDestinationMorphantTemplate(
            global::Morphant.Members.ConstructorMember<int> value)
        {
        }
    }
}
""";

        // lang=c#
        const string expectedMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>
    {
        /// <inheritdoc/>
        global::TestCase.RequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.RequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RequiredDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.RequiredDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.RequiredDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.RequiredDestination(
                value: source.Value + 1)
            {
                Value = source.Value,
                Remaining = source.Remaining
            };
        }

        /// <inheritdoc/>
        global::TestCase.SetsRequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.SetsRequiredDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.SetsRequiredDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.SetsRequiredDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Value = source.Value;
            destination.Remaining = source.Remaining;

            return destination;
        }

        private global::TestCase.SetsRequiredDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.SetsRequiredDestination(
                value: source.Value + 2)
            {
                Remaining = source.Remaining
            };
        }
    }
}
""";

        await TemplateMappingGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_RequiredDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.RequiredDestination",
                    "global::TestCase.RequiredDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "RequiredDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TemplateExtension." +
                "TestCase_SetsRequiredDestination.g.cs",
                BuildExpectedExtension(
                    "global::TestCase.SetsRequiredDestination",
                    "global::TestCase.SetsRequiredDestination?",
                    "global::TestCase.Morphant.Generated." +
                    "SetsRequiredDestinationMorphantTemplate")
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedMapper
            ));
    }

    private static string BuildExpectedExtension(
        string destinationType,
        string existingDestinationType,
        string templateResultType)
    {
        return $$"""
                 // <auto-generated />
                 #nullable enable

                 namespace Morphant
                 {
                     internal static partial class MorphantGeneratedTemplateExtensions
                     {
                         /// <summary>
                         /// Configures a mapping template.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

                         /// <summary>
                         /// Configures a mapping template for an existing destination.
                         /// </summary>
                         /// <typeparam name="TSource">The source type.</typeparam>
                         /// <param name="builder">The mapping builder to configure.</param>
                         /// <param name="template">
                         /// A lambda expression that receives the non-null source value and the non-null
                         /// existing destination and describes the mapping.
                         /// </param>
                         /// <returns>The <paramref name="builder"/> instance.</returns>
                         public static global::Morphant.MapperBuilder<TSource, {{destinationType}}> Template<TSource>(
                             this global::Morphant.MapperBuilder<TSource, {{destinationType}}> builder,
                             global::System.Func<TSource, {{existingDestinationType.TrimEnd('?')}}, {{templateResultType}}> template)
                             => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
                     }
                 }
                 """;
    }
}
