using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperTests;

[TestFixture]
internal sealed class TypeMapperDestinationVarietyTests
{
    [Test]
    public async Task Maps_reference_record_abstract_interface_and_nullable_destinations()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; set; }

        public string Name { get; set; } = null!;
    }

    public sealed class ClassDestination
    {
        public int Id { get; set; }
    }

    public sealed record RecordDestination(int Id)
    {
        public string Name { get; set; } = null!;
    }

    public abstract class AbstractDestination
    {
        public int Id { get; set; }
    }

    public interface IInterfaceDestination
    {
        int Id { get; set; }
    }

    public sealed class NullableDestination
    {
        public int Id { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, ClassDestination>();
            builder.Map<Source, RecordDestination>();
            builder.Map<Source, AbstractDestination>();
            builder.Map<Source, IInterfaceDestination>();
            builder.Map<Source, NullableDestination?>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ClassDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RecordDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AbstractDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.IInterfaceDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.NullableDestination?>
    {
        /// <inheritdoc/>
        global::TestCase.ClassDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ClassDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.ClassDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ClassDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.ClassDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Id = source.Id;

            return destination;
        }

        private global::TestCase.ClassDestination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.ClassDestination()
            {
                Id = source.Id
            };
        }

        /// <inheritdoc/>
        global::TestCase.RecordDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RecordDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.RecordDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RecordDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.RecordDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Name = source.Name;

            return destination;
        }

        private global::TestCase.RecordDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.RecordDestination(
                Id: source.Id)
            {
                Name = source.Name
            };
        }

        /// <inheritdoc/>
        global::TestCase.AbstractDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AbstractDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl2(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.AbstractDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.AbstractDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.AbstractDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl2(source, context);
            }

            destination.Id = source.Id;

            return destination;
        }

        private global::TestCase.AbstractDestination? MapNewImpl2(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::TestCase.IInterfaceDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.IInterfaceDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl3(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.IInterfaceDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.IInterfaceDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.IInterfaceDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl3(source, context);
            }

            destination.Id = source.Id;

            return destination;
        }

        private global::TestCase.IInterfaceDestination? MapNewImpl3(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::TestCase.NullableDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.NullableDestination?>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl4(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.NullableDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.NullableDestination?>.Map(
            global::TestCase.Source? source,
            global::TestCase.NullableDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl4(source, context);
            }

            destination.Id = source.Id;

            return destination;
        }

        private global::TestCase.NullableDestination? MapNewImpl4(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.NullableDestination()
            {
                Id = source.Id
            };
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Maps_struct_record_readonly_and_constructed_generic_destinations()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; set; }

        public string Name { get; set; } = null!;
    }

    public sealed class GenericSource<T>
    {
        public T Value { get; set; } = default!;
    }

    public struct StructDestination
    {
        public int Id { get; set; }
    }

    public record struct RecordStructDestination(int Id)
    {
        public string Name { get; set; } = null!;
    }

    public readonly struct ReadonlyStructDestination
    {
        public int Id { get; init; }
    }

    public sealed class GenericDestination<T>
    {
        public T Value { get; set; } = default!;
    }

    public struct GenericStructDestination<T>
    {
        public T Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, StructDestination>();
            builder.Map<Source, RecordStructDestination>();
            builder.Map<Source, ReadonlyStructDestination>();
            builder.Map<GenericSource<int>, GenericDestination<int>>();
            builder.Map<
                GenericSource<string>,
                GenericStructDestination<string>>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.StructDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RecordStructDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ReadonlyStructDestination>,
        global::Morphant.ITypeMapper<global::TestCase.GenericSource<int>, global::TestCase.GenericDestination<int>>,
        global::Morphant.ITypeMapper<global::TestCase.GenericSource<string>, global::TestCase.GenericStructDestination<string>>
    {
        /// <inheritdoc/>
        global::TestCase.StructDestination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.StructDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return new global::TestCase.StructDestination()
            {
                Id = source.Id
            };
        }

        /// <inheritdoc/>
        global::TestCase.StructDestination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.StructDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.StructDestination destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            destination.Id = source.Id;

            return destination;
        }

        /// <inheritdoc/>
        global::TestCase.RecordStructDestination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RecordStructDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return new global::TestCase.RecordStructDestination(
                Id: source.Id)
            {
                Name = source.Name
            };
        }

        /// <inheritdoc/>
        global::TestCase.RecordStructDestination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.RecordStructDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.RecordStructDestination destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            destination.Id = source.Id;
            destination.Name = source.Name;

            return destination;
        }

        /// <inheritdoc/>
        global::TestCase.ReadonlyStructDestination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ReadonlyStructDestination>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return new global::TestCase.ReadonlyStructDestination()
            {
                Id = source.Id
            };
        }

        /// <inheritdoc/>
        global::TestCase.ReadonlyStructDestination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ReadonlyStructDestination>.Map(
            global::TestCase.Source? source,
            global::TestCase.ReadonlyStructDestination destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return destination;
        }

        /// <inheritdoc/>
        global::TestCase.GenericDestination<int>? global::Morphant.ITypeMapper<global::TestCase.GenericSource<int>, global::TestCase.GenericDestination<int>>.Map(
            global::TestCase.GenericSource<int>? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.GenericDestination<int>? global::Morphant.ITypeMapper<global::TestCase.GenericSource<int>, global::TestCase.GenericDestination<int>>.Map(
            global::TestCase.GenericSource<int>? source,
            global::TestCase.GenericDestination<int>? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Value = source.Value;

            return destination;
        }

        private global::TestCase.GenericDestination<int>? MapNewImpl(
            global::TestCase.GenericSource<int> source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.GenericDestination<int>()
            {
                Value = source.Value
            };
        }

        /// <inheritdoc/>
        global::TestCase.GenericStructDestination<string> global::Morphant.ITypeMapper<global::TestCase.GenericSource<string>, global::TestCase.GenericStructDestination<string>>.Map(
            global::TestCase.GenericSource<string>? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return new global::TestCase.GenericStructDestination<string>()
            {
                Value = source.Value
            };
        }

        /// <inheritdoc/>
        global::TestCase.GenericStructDestination<string> global::Morphant.ITypeMapper<global::TestCase.GenericSource<string>, global::TestCase.GenericStructDestination<string>>.Map(
            global::TestCase.GenericSource<string>? source,
            global::TestCase.GenericStructDestination<string> destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            destination.Value = source.Value;

            return destination;
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp10,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Maps_nullable_structs_and_guards_null_existing_destinations()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; set; }
    }

    public struct Destination
    {
        public int Id { get; set; }
    }

    public readonly struct ReadonlyDestination
    {
        public int Id { get; init; }
    }

    [MorphantMapper]
    public partial class TestMapper<destinationValue> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination?>();
            builder.Map<Source, ReadonlyDestination?>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper<destinationValue> :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination?>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ReadonlyDestination?>
    {
        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination?>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination?>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            var destinationValue1 = destination.Value;
            destinationValue1.Id = source.Id;

            return destinationValue1;
        }

        private global::TestCase.Destination? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Id = source.Id
            };
        }

        /// <inheritdoc/>
        global::TestCase.ReadonlyDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ReadonlyDestination?>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.ReadonlyDestination? global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.ReadonlyDestination?>.Map(
            global::TestCase.Source? source,
            global::TestCase.ReadonlyDestination? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            return destination;
        }

        private global::TestCase.ReadonlyDestination? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            return new global::TestCase.ReadonlyDestination()
            {
                Id = source.Id
            };
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper_1.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Supports_destination_type_parameters_according_to_their_constraints()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public interface IDestination
    {
        int Value { get; set; }
    }

    public class DestinationBase
    {
        public int Value { get; set; }
    }

    public sealed class ClassNewSource
    {
        public int Value { get; set; }
    }

    public sealed class InterfaceSource
    {
        public int Value { get; set; }
    }

    public sealed class StructSource
    {
        public int Value { get; set; }
    }

    public sealed class TransitiveSource
    {
        public int Value { get; set; }
    }

    public sealed class NullableStructSource
    {
        public int Value { get; set; }
    }

    public sealed class UnmanagedSource
    {
    }

    public sealed class NewSource
    {
    }

    public sealed class ClassSource
    {
    }

    public sealed class UnconstrainedSource
    {
    }

    [MorphantMapper]
    public partial class TestMapper<
        TClassNew,
        TInterface,
        TTransitive,
        TStruct,
        TUnmanaged,
        TNew,
        TClass,
        TUnconstrained> : TypeMapper
        where TClassNew : DestinationBase, new()
        where TInterface : IDestination
        where TTransitive : TInterface
        where TStruct : struct, IDestination
        where TUnmanaged : unmanaged
        where TNew : new()
        where TClass : class
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<ClassNewSource, TClassNew>();
            builder.Map<InterfaceSource, TInterface>();
            builder.Map<TransitiveSource, TTransitive>();
            builder.Map<StructSource, TStruct>();
            builder.Map<NullableStructSource, TStruct?>();
            builder.Map<UnmanagedSource, TUnmanaged>();
            builder.Map<NewSource, TNew>();
            builder.Map<ClassSource, TClass>();
            builder.Map<UnconstrainedSource, TUnconstrained>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper<TClassNew, TInterface, TTransitive, TStruct, TUnmanaged, TNew, TClass, TUnconstrained> :
        global::Morphant.ITypeMapper<global::TestCase.ClassNewSource, TClassNew>,
        global::Morphant.ITypeMapper<global::TestCase.InterfaceSource, TInterface>,
        global::Morphant.ITypeMapper<global::TestCase.TransitiveSource, TTransitive>,
        global::Morphant.ITypeMapper<global::TestCase.StructSource, TStruct>,
        global::Morphant.ITypeMapper<global::TestCase.NullableStructSource, TStruct?>,
        global::Morphant.ITypeMapper<global::TestCase.UnmanagedSource, TUnmanaged>,
        global::Morphant.ITypeMapper<global::TestCase.NewSource, TNew>,
        global::Morphant.ITypeMapper<global::TestCase.ClassSource, TClass>,
        global::Morphant.ITypeMapper<global::TestCase.UnconstrainedSource, TUnconstrained>
    {
        /// <inheritdoc/>
        TClassNew? global::Morphant.ITypeMapper<global::TestCase.ClassNewSource, TClassNew>.Map(
            global::TestCase.ClassNewSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        TClassNew? global::Morphant.ITypeMapper<global::TestCase.ClassNewSource, TClassNew>.Map(
            global::TestCase.ClassNewSource? source,
            TClassNew? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            destination.Value = source.Value;

            return destination;
        }

        private TClassNew? MapNewImpl(
            global::TestCase.ClassNewSource source,
            global::Morphant.MappingContext context)
        {
            return new TClassNew()
            {
                Value = source.Value
            };
        }

        /// <inheritdoc/>
        TInterface? global::Morphant.ITypeMapper<global::TestCase.InterfaceSource, TInterface>.Map(
            global::TestCase.InterfaceSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        TInterface? global::Morphant.ITypeMapper<global::TestCase.InterfaceSource, TInterface>.Map(
            global::TestCase.InterfaceSource? source,
            TInterface? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            destination.Value = source.Value;

            return destination;
        }

        private TInterface? MapNewImpl1(
            global::TestCase.InterfaceSource source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        TTransitive? global::Morphant.ITypeMapper<global::TestCase.TransitiveSource, TTransitive>.Map(
            global::TestCase.TransitiveSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl2(source, context);
        }

        /// <inheritdoc/>
        TTransitive? global::Morphant.ITypeMapper<global::TestCase.TransitiveSource, TTransitive>.Map(
            global::TestCase.TransitiveSource? source,
            TTransitive? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl2(source, context);
            }

            destination.Value = source.Value;

            return destination;
        }

        private TTransitive? MapNewImpl2(
            global::TestCase.TransitiveSource source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        TStruct global::Morphant.ITypeMapper<global::TestCase.StructSource, TStruct>.Map(
            global::TestCase.StructSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return new TStruct()
            {
                Value = source.Value
            };
        }

        /// <inheritdoc/>
        TStruct global::Morphant.ITypeMapper<global::TestCase.StructSource, TStruct>.Map(
            global::TestCase.StructSource? source,
            TStruct destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            destination.Value = source.Value;

            return destination;
        }

        /// <inheritdoc/>
        TStruct? global::Morphant.ITypeMapper<global::TestCase.NullableStructSource, TStruct?>.Map(
            global::TestCase.NullableStructSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl3(source, context);
        }

        /// <inheritdoc/>
        TStruct? global::Morphant.ITypeMapper<global::TestCase.NullableStructSource, TStruct?>.Map(
            global::TestCase.NullableStructSource? source,
            TStruct? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl3(source, context);
            }

            var destinationValue = destination.Value;
            destinationValue.Value = source.Value;

            return destinationValue;
        }

        private TStruct? MapNewImpl3(
            global::TestCase.NullableStructSource source,
            global::Morphant.MappingContext context)
        {
            return new TStruct()
            {
                Value = source.Value
            };
        }

        /// <inheritdoc/>
        TUnmanaged global::Morphant.ITypeMapper<global::TestCase.UnmanagedSource, TUnmanaged>.Map(
            global::TestCase.UnmanagedSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return new TUnmanaged();
        }

        /// <inheritdoc/>
        TUnmanaged global::Morphant.ITypeMapper<global::TestCase.UnmanagedSource, TUnmanaged>.Map(
            global::TestCase.UnmanagedSource? source,
            TUnmanaged destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        TNew? global::Morphant.ITypeMapper<global::TestCase.NewSource, TNew>.Map(
            global::TestCase.NewSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl4(source, context);
        }

        /// <inheritdoc/>
        TNew? global::Morphant.ITypeMapper<global::TestCase.NewSource, TNew>.Map(
            global::TestCase.NewSource? source,
            TNew? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl4(source, context);
            }

            throw new global::System.NotImplementedException();
        }

        private TNew? MapNewImpl4(
            global::TestCase.NewSource source,
            global::Morphant.MappingContext context)
        {
            return new TNew();
        }

        /// <inheritdoc/>
        TClass? global::Morphant.ITypeMapper<global::TestCase.ClassSource, TClass>.Map(
            global::TestCase.ClassSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl5(source, context);
        }

        /// <inheritdoc/>
        TClass? global::Morphant.ITypeMapper<global::TestCase.ClassSource, TClass>.Map(
            global::TestCase.ClassSource? source,
            TClass? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl5(source, context);
            }

            return destination;
        }

        private TClass? MapNewImpl5(
            global::TestCase.ClassSource source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        TUnconstrained? global::Morphant.ITypeMapper<global::TestCase.UnconstrainedSource, TUnconstrained>.Map(
            global::TestCase.UnconstrainedSource? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl6(source, context);
        }

        /// <inheritdoc/>
        TUnconstrained? global::Morphant.ITypeMapper<global::TestCase.UnconstrainedSource, TUnconstrained>.Map(
            global::TestCase.UnconstrainedSource? source,
            TUnconstrained? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl6(source, context);
            }

            throw new global::System.NotImplementedException();
        }

        private TUnconstrained? MapNewImpl6(
            global::TestCase.UnconstrainedSource source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper_8.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Keeps_direct_destination_types_unimplemented_until_explicit_templates()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System;
using Morphant;

namespace TestCase
{
    public sealed class Source
    {
    }

    public enum DestinationEnum
    {
        Value
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, int>();
            builder.Map<Source, string>();
            builder.Map<Source, object>();
            builder.Map<Source, DestinationEnum>();
            builder.Map<Source, Guid>();
            builder.Map<Source, Guid?>();
            builder.Map<Source, Uri>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int>,
        global::Morphant.ITypeMapper<global::TestCase.Source, string>,
        global::Morphant.ITypeMapper<global::TestCase.Source, object>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.DestinationEnum>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Guid>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Guid?>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Uri>
    {
        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::TestCase.Source, int>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::TestCase.Source, int>.Map(
            global::TestCase.Source? source,
            int destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        string? global::Morphant.ITypeMapper<global::TestCase.Source, string>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl(source, context);
        }

        /// <inheritdoc/>
        string? global::Morphant.ITypeMapper<global::TestCase.Source, string>.Map(
            global::TestCase.Source? source,
            string? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl(source, context);
            }

            throw new global::System.NotImplementedException();
        }

        private string? MapNewImpl(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        object? global::Morphant.ITypeMapper<global::TestCase.Source, object>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl1(source, context);
        }

        /// <inheritdoc/>
        object? global::Morphant.ITypeMapper<global::TestCase.Source, object>.Map(
            global::TestCase.Source? source,
            object? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl1(source, context);
            }

            throw new global::System.NotImplementedException();
        }

        private object? MapNewImpl1(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::TestCase.DestinationEnum global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.DestinationEnum>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::TestCase.DestinationEnum global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.DestinationEnum>.Map(
            global::TestCase.Source? source,
            global::TestCase.DestinationEnum destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::System.Guid global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Guid>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::System.Guid global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Guid>.Map(
            global::TestCase.Source? source,
            global::System.Guid destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::System.Guid? global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Guid?>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl2(source, context);
        }

        /// <inheritdoc/>
        global::System.Guid? global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Guid?>.Map(
            global::TestCase.Source? source,
            global::System.Guid? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl2(source, context);
            }

            throw new global::System.NotImplementedException();
        }

        private global::System.Guid? MapNewImpl2(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }

        /// <inheritdoc/>
        global::System.Uri? global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Uri>.Map(
            global::TestCase.Source? source,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            return MapNewImpl3(source, context);
        }

        /// <inheritdoc/>
        global::System.Uri? global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Uri>.Map(
            global::TestCase.Source? source,
            global::System.Uri? destination,
            global::Morphant.MappingContext context)
        {
            if (source is null)
            {
                return default;
            }

            if (destination is null)
            {
                return MapNewImpl3(source, context);
            }

            throw new global::System.NotImplementedException();
        }

        private global::System.Uri? MapNewImpl3(
            global::TestCase.Source source,
            global::Morphant.MappingContext context)
        {
            throw new global::System.NotImplementedException();
        }
    }
}
""";

        await TypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }
}
