using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Morphant.Generator.TemplateSurface.TemplateType;

internal static class TemplateTypePipeline
{
    public static void Register(
        IncrementalGeneratorInitializationContext context,
        IncrementalValueProvider<CompilationContext> compilationContext,
        IncrementalValuesProvider<MapperBuilderMapInfo> mapUsages)
    {
        var templateTypeIdentities = mapUsages
            .Collect()
            .SelectMany(static (usages, _) =>
                BuildTemplateTypeIdentities(usages))
            .WithTrackingName("MorphantGeneratorStageNames.BuildTemplateTypeIdentities");

        var templateTypeRequests = templateTypeIdentities
            .Combine(compilationContext)
            .Select(static (x, cancellationToken) =>
            {
                var (identity, compilationContext) = x;

                return TryBuild(
                    identity,
                    compilationContext,
                    cancellationToken);
            })
            .Where(x => x.HasValue)
            .Select((x, _) => x!.Value)
            .WithTrackingName("MorphantGeneratorStageNames.BuildTemplateTypeRequests");

        context.RegisterSourceOutput(
            templateTypeRequests,
            static (context, request) =>
            {
                context.AddSource(
                    request.HintName,
                    SourceText.From(request.Source, Encoding.UTF8));
            });
    }

    private static ImmutableArray<TemplateTypeIdentity> BuildTemplateTypeIdentities(
        ImmutableArray<MapperBuilderMapInfo> mapUsages)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var builder = ImmutableArray.CreateBuilder<TemplateTypeIdentity>();

        foreach (var usage in mapUsages)
        {
            if (!seen.Add(usage.DestinationType.MetadataName))
            {
                continue;
            }

            builder.Add(new TemplateTypeIdentity(usage.DestinationType));
        }

        return builder.ToImmutable();
    }

    private static TemplateTypeRequest? TryBuild(
        TemplateTypeIdentity identity,
        CompilationContext context,
        CancellationToken cancellationToken)
    {
        var destinationType = context.Compilation.GetTypeByMetadataName(
            identity.DestinationType.MetadataName);

        if (destinationType is null)
        {
            return null;
        }

        var hintName =
            "Morphant.TemplateType." +
            HintNameHelper.ToHintNamePart(identity.DestinationType.MetadataName) +
            ".g.cs";

        var source = Generate(
            destinationType,
            identity.DestinationType,
            context,
            cancellationToken);

        return new TemplateTypeRequest(hintName, source);
    }

    private static string Generate(
        INamedTypeSymbol destinationType,
        DestinationTypeReference destinationTypeReference,
        CompilationContext context,
        CancellationToken cancellationToken)
    {
        var constructors = BuildConstructors(
            destinationType,
            destinationTypeReference,
            context,
            cancellationToken);

        var members = BuildMembers(
            destinationType,
            context,
            cancellationToken);

        return $@"// <auto-generated />
#nullable enable

namespace {destinationTypeReference.TemplateNamespace};

internal sealed record class {destinationTypeReference.TemplateTypeName}
{{
{constructors}
{members}
}}
";
    }

    private static string BuildConstructors(
        INamedTypeSymbol destinationType,
        DestinationTypeReference destinationTypeReference,
        CompilationContext context,
        CancellationToken cancellationToken)
    {
        var builder = new StringBuilder();

        builder.AppendLine($"    public {destinationTypeReference.TemplateTypeName}(global::Morphant.ByConventionMarker _)");
        builder.AppendLine("        => throw new global::Morphant.RuntimeInvocationNotSupportedException();");
        builder.AppendLine();

        foreach (var constructor in destinationType.InstanceConstructors)
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (!IsAccessibleFromGeneratedCode(constructor, context))
            {
                continue;
            }

            var parameters = constructor.Parameters;

            if (parameters.Length == 0)
            {
                builder.AppendLine($"    public {destinationTypeReference.TemplateTypeName}()");
                builder.AppendLine("        => throw new global::Morphant.RuntimeInvocationNotSupportedException();");
                builder.AppendLine();
                continue;
            }

            builder.Append($"    public {destinationTypeReference.TemplateTypeName}(");

            for (var i = 0; i < parameters.Length; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                var parameter = parameters[i];
                var typeName = parameter.Type.ToDisplayString(SymbolDisplayFormats.FullyQualifiedNullable);

                builder.Append("global::Morphant.ConstructorMember<");
                builder.Append(typeName);
                builder.Append("> @");
                builder.Append(parameter.Name);
            }

            builder.AppendLine(")");
            builder.AppendLine("        => throw new global::Morphant.RuntimeInvocationNotSupportedException();");
            builder.AppendLine();
        }

        return builder.ToString().TrimEnd();
    }

    private static string BuildMembers(
        INamedTypeSymbol destinationType,
        CompilationContext context,
        CancellationToken cancellationToken)
    {
        var builder = new StringBuilder();

        foreach (var member in GetAssignableMembers(destinationType, context)
                     .OrderBy(static x => x.Name, StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();

            var typeName = member.Type.ToDisplayString(SymbolDisplayFormats.FullyQualifiedNullable);

            builder.Append("    public global::Morphant.Member<");
            builder.Append(typeName);
            builder.Append("> @");
            builder.Append(member.Name);
            builder.AppendLine(" { get => throw new global::Morphant.RuntimeInvocationNotSupportedException(); init => throw new global::Morphant.RuntimeInvocationNotSupportedException(); }");
        }

        return builder.ToString().TrimEnd();
    }

    private static IEnumerable<(string Name, ITypeSymbol Type)> GetAssignableMembers(
        INamedTypeSymbol destinationType,
        CompilationContext context)
    {
        foreach (var member in destinationType.GetMembers())
        {
            if (member is IPropertySymbol property)
            {
                if (property.IsStatic ||
                    property.IsIndexer ||
                    property.SetMethod is null ||
                    !IsAccessibleFromGeneratedCode(property, context) ||
                    !IsAccessibleFromGeneratedCode(property.SetMethod, context))
                {
                    continue;
                }

                yield return (property.Name, property.Type);
                continue;
            }

            if (member is IFieldSymbol field)
            {
                if (field.IsStatic ||
                    field.IsConst ||
                    field.IsReadOnly ||
                    field.IsImplicitlyDeclared ||
                    !IsAccessibleFromGeneratedCode(field, context))
                {
                    continue;
                }

                yield return (field.Name, field.Type);
            }
        }
    }

    private static bool IsAccessibleFromGeneratedCode(
        ISymbol symbol,
        CompilationContext context)
    {
        return symbol.DeclaredAccessibility switch
        {
            Accessibility.Public => true,

            Accessibility.Internal => SymbolEqualityComparer.Default.Equals(
                symbol.ContainingAssembly,
                context.Compilation.Assembly),

            Accessibility.ProtectedOrInternal => SymbolEqualityComparer.Default.Equals(
                symbol.ContainingAssembly,
                context.Compilation.Assembly),

            _ => false
        };
    }
}
