using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.RuntimePolymorphismTests;

[TestFixture]
internal sealed class DispatchTests
{
    [Test]
    public void Routes_create_and_strict_update_through_the_exact_derived_pair()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System;
using Morphant;
using Morphant.Exceptions;

namespace TestCase
{
    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<object, object>()
                .ForDerived<string, string>()
                .Convert(source => source!);
            builder.Map<string, string>()
                .Convert(source => source!);
        }
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper = (ITypeMapper<object, object>)new TestMapper();
            object source = "derived";
            var created = mapper.Create(source);
            var updated = mapper.Update(source, "previous");
            var updatedFromNull = mapper.Update(source, null);

            if (created is not string ||
                updated is not string ||
                updatedFromNull is not string)
            {
                throw new InvalidOperationException(
                    "The derived string mapping was not selected.");
            }

            try
            {
                mapper.Update(source, new object());
                throw new InvalidOperationException(
                    "An incompatible destination was accepted.");
            }
            catch (PolymorphicDestinationTypeMismatchException exception)
            {
                if (exception.SourceType != typeof(object) ||
                    exception.DestinationType != typeof(object) ||
                    exception.ActualSourceType != typeof(string) ||
                    exception.BranchSourceType != typeof(string) ||
                    exception.ExpectedDestinationType != typeof(string) ||
                    exception.ActualDestinationType != typeof(object))
                {
                    throw new InvalidOperationException(
                        "The mismatch exception lost its branch details.");
                }
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<object, object>,
        global::Morphant.ITypeMapper<string, string>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(object) &&
                    destinationType == typeof(object)) ||
                (sourceType == typeof(string) &&
                    destinationType == typeof(string)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        object global::Morphant.ITypeMapper<object, object>.Create(
            object? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is not null)
            {
                if (source.GetType() != typeof(object))
                {
                    if (source is string polymorphicSource0)
                    {
                        return context.Mapper.Map<string, string>(polymorphicSource0);
                    }

                }

            }

            return __ConvertDestination(source);
        }

        /// <inheritdoc/>
        object global::Morphant.ITypeMapper<object, object>.Update(
            object? source,
            object? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is not null)
            {
                if (source.GetType() != typeof(object))
                {
                    if (source is string polymorphicSource0)
                    {
                        if (destination is null)
                        {
                            return context.Mapper.Map<string, string>(polymorphicSource0, default(string));
                        }

                        if (destination is string polymorphicDestination)
                        {
                            return context.Mapper.Map<string, string>(polymorphicSource0, polymorphicDestination);
                        }

                        throw new global::Morphant.Exceptions.PolymorphicDestinationTypeMismatchException(
                            global::Morphant.Context.MappingOperation.Update,
                            typeof(object),
                            typeof(object),
                            polymorphicSource0.GetType(),
                            typeof(string),
                            typeof(string),
                            destination.GetType());
                    }

                }

            }

            return __ConvertDestination(source);
        }

        private object __ConvertDestination(object? source) => source!;

        /// <inheritdoc/>
        string global::Morphant.ITypeMapper<string, string>.Create(
            string? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination1(source);

        /// <inheritdoc/>
        string global::Morphant.ITypeMapper<string, string>.Update(
            string? source,
            string? destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination1(source);

        private string __ConvertDestination1(string? source) => source!;
    }
}
""";

        var result = GeneratorTestDriver.Run(
            "RuntimePolymorphismDispatch",
            source,
            LanguageVersion.CSharp9);

        Assert.Multiple(() =>
        {
            Assert.That(result.EffectiveDiagnostics, Is.Empty);
            Assert.That(result.CompilerWarningsAndErrors, Is.Empty);
            Assert.That(
                result.GeneratedSources.Select(static generated =>
                    generated.HintName).ToArray(),
                Is.EqualTo(new[]
                {
                    "Morphant.Generated.MappingExtension.System_Object__System_Object.g.cs",
                    "Morphant.Generated.MappingExtension.System_String__System_String.g.cs",
                    "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs"
                }));
        });

        Assert.That(
            result.TypeMapperSource.ReplaceLineEndings("\n"),
            Is.EqualTo(expected + "\n"));

        GeneratedCodeExecution.AssertScenario(
            "runtime polymorphism dispatch",
            result.OutputCompilation,
            "TestCase.Scenario");
    }
}
