namespace Morphant.Generator.UnitTests.ExtensionInvocationTests.Usage;

internal sealed partial class ExtensionInvocationTests
{
    // lang=c#
    private const string ImplicitAwaitSource =
"""
global using static Existing.Operations;
#nullable enable
#pragma warning disable CS1591
using System.Collections;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Morphant;
using Alternate;
namespace Existing
{
    public static class Operations
    {
        public static TaskAwaiter<int> GetAwaiter(this ExtensionCases.AwaitableBase value) => Task.FromResult(3).GetAwaiter();
        public static void Deconstruct(this ExtensionCases.PairBase value, out int first, out int second) { first = 1; second = 2; }
        public static void Add(this ExtensionCases.BagBase value, int item) => value.Items.Add(item + 1);
    }
}
namespace Alternate
{
    public static class Operations
    {
        public static int Extra(this int value) => value + 10;
        public static TaskAwaiter<int> GetAwaiter(this ExtensionCases.Awaitable value) => Task.FromResult(99).GetAwaiter();
        public static void Deconstruct(this ExtensionCases.Pair value, out int first, out int second) { first = 9; second = 9; }
        public static void Add(this ExtensionCases.Bag value, int item) => value.Items.Add(99);
    }
}
namespace ExtensionCases
{
    using static Existing.Operations;
    public class AwaitableBase { }
    public sealed class Awaitable : AwaitableBase { }
    public class PairBase { }
    public sealed class Pair : PairBase { }
    public class BagBase : IEnumerable
    {
        public List<int> Items { get; } = new();
        public IEnumerator GetEnumerator() => Items.GetEnumerator();
    }
    public sealed class Bag : BagBase { }
    public sealed class Source
    {
        public int Number { get; set; } = 4;
        public Awaitable Awaitable { get; } = new();
        public Pair Pair { get; } = new();
    }
    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Task<int>>().Convert(async source => await source!.Awaitable + source!.Number.Extra());
    }
}
""";

    private static readonly (string Hint, string Source)[] ImplicitAwait10Sources =
    [
        ("Morphant.Generated.MappingExtension.Mapper.SourceToTask__f893e467346ab06eb514349607a94ae3.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant;

internal static partial class MorphantGeneratedMappingExtensions
{
    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> builder,
        global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> builder,
        global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Source, global::Morphant.Context.MappingContext, global::System.Threading.Tasks.Task<int>> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> builder,
        global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>, global::System.Threading.Tasks.Task<int>> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> builder,
        global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>, global::Morphant.Context.MappingContext, global::System.Threading.Tasks.Task<int>> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, global::System.Threading.Tasks.Task<int>> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, global::System.Threading.Tasks.Task<int>, global::System.Threading.Tasks.Task<int>> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, global::System.Threading.Tasks.Task<int>, global::Morphant.Context.MappingContext, global::System.Threading.Tasks.Task<int>> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__f76b1361cb552263930ff9b2ca8cd52b.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace ExtensionCases;

public partial class Mapper :
    global::Morphant.ITypeMapper<global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>>
{
    /// <inheritdoc/>
    protected override bool Supports(
        global::System.Type sourceType,
        global::System.Type destinationType) =>
            (sourceType == typeof(global::ExtensionCases.Source) &&
                destinationType == typeof(global::System.Threading.Tasks.Task<int>)) ||
            base.Supports(sourceType, destinationType);

    /// <inheritdoc/>
    global::System.Threading.Tasks.Task<int> global::Morphant.ITypeMapper<global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>>.Create(
        global::ExtensionCases.Source? source,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination(source);

    /// <inheritdoc/>
    global::System.Threading.Tasks.Task<int> global::Morphant.ITypeMapper<global::ExtensionCases.Source, global::System.Threading.Tasks.Task<int>>.Update(
        global::ExtensionCases.Source? source,
        global::System.Threading.Tasks.Task<int>? destination,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination(source);

    private async global::System.Threading.Tasks.Task<int> __ConvertDestination(global::ExtensionCases.Source? source) => await source!.Awaitable + global::Alternate.Operations.Extra(source!.Number);
}
"""),
    ];
}
