namespace Morphant.Generator.UnitTests.ExtensionInvocationTests.Usage;

internal sealed partial class ExtensionInvocationTests
{
    // lang=c#
    private const string ImportIsolationSource =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using System.Collections.Generic;
using Calls;
using SafeCalls;
using Morphant;
namespace Calls
{
    public static class Operations
    {
        public static int Extra(this string value) => value.Length;
        public static IEnumerable<int> Select(this int[] value, Func<int, int> selector) => new[] { 99 };
        public static int Describe(this string value) => 99;
        public static int Count(this string value) => 99;
    }
}
namespace SafeCalls
{
    public static class SafeOperations
    {
        public static int Twice(this int value) => value * 2;
    }
}
namespace ExtensionCases
{
    using System.Linq;
    public sealed class Source
    {
        public int[] Values { get; set; } = new[] { 1, 2 };
        public string Text { get; set; } = "abc";
        public int Increment(int value) => value + 1;
    }
    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<string, int>().Convert(source => source!.Extra() + source!.Length.Twice());
            builder.Map<Source, string>().Convert(source =>
            {
                Func<int, int> increment = source!.Increment;
                return string.Join(",", from value in source!.Values select increment(value));
            });
        }
    }
}
""";

    private static readonly (string Hint, string Source)[] ImportIsolation9Sources =
    [
        ("Morphant.Generated.MappingExtension.Mapper.SourceToString__67a1a4c287510f0b14b8ebcdd91f470a.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> ConstructUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
            global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Source, string> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> ConstructUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
            global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Source, global::Morphant.Context.MappingContext, string> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> ResolveUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
            global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Source, string, string> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> ResolveUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
            global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Source, string, global::Morphant.Context.MappingContext, string> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, string> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, string, string> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, string, global::Morphant.Context.MappingContext, string> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
        ("Morphant.Generated.MappingExtension.Mapper.StringToInt32__a24af9cda25b847750bccc2c7ef592ed.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> ConstructUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
            global::Morphant.Delegates.ConstructUsing<string, int> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> ConstructUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
            global::Morphant.Delegates.ConstructUsing<string, global::Morphant.Context.MappingContext, int> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> ResolveUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
            global::Morphant.Delegates.ResolveUsing<string, int, int> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> ResolveUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
            global::Morphant.Delegates.ResolveUsing<string, int, global::Morphant.Context.MappingContext, int> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
            global::Morphant.Delegates.Convert<string?, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
            global::Morphant.Delegates.Convert<string?, int, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
            global::Morphant.Delegates.Convert<string?, int, global::Morphant.Context.MappingContext, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__f76b1361cb552263930ff9b2ca8cd52b.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

using global::System.Linq;
using static global::SafeCalls.SafeOperations;

namespace ExtensionCases
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<string, int>,
        global::Morphant.ITypeMapper<global::ExtensionCases.Source, string>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(string) &&
                    destinationType == typeof(int)) ||
                (sourceType == typeof(global::ExtensionCases.Source) &&
                    destinationType == typeof(string)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<string, int>.Create(
            string? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<string, int>.Update(
            string? source,
            int destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        private int __ConvertDestination(string? source) => global::Calls.Operations.Extra(source!) + source!.Length.Twice();

        /// <inheritdoc/>
        string global::Morphant.ITypeMapper<global::ExtensionCases.Source, string>.Create(
            global::ExtensionCases.Source? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination1(source);

        /// <inheritdoc/>
        string global::Morphant.ITypeMapper<global::ExtensionCases.Source, string>.Update(
            global::ExtensionCases.Source? source,
            string? destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination1(source);

        private string __ConvertDestination1(global::ExtensionCases.Source? source)
        {
            global::System.Func<int, int> increment = source!.Increment;
            return string.Join(",", from value in source!.Values select increment(value));
        }
    }
}
"""),
    ];

    private static readonly (string Hint, string Source)[] ImportIsolation10Sources =
    [
        ("Morphant.Generated.MappingExtension.Mapper.SourceToString__67a1a4c287510f0b14b8ebcdd91f470a.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant;

internal static partial class MorphantGeneratedMappingExtensions
{
    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
        global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Source, string> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
        global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Source, global::Morphant.Context.MappingContext, string> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
        global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Source, string, string> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
        global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Source, string, global::Morphant.Context.MappingContext, string> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, string> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, string, string> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, global::ExtensionCases.Source, string> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Source?, string, global::Morphant.Context.MappingContext, string> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
}
"""),
        ("Morphant.Generated.MappingExtension.Mapper.StringToInt32__a24af9cda25b847750bccc2c7ef592ed.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant;

internal static partial class MorphantGeneratedMappingExtensions
{
    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
        global::Morphant.Delegates.ConstructUsing<string, int> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
        global::Morphant.Delegates.ConstructUsing<string, global::Morphant.Context.MappingContext, int> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
        global::Morphant.Delegates.ResolveUsing<string, int, int> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
        global::Morphant.Delegates.ResolveUsing<string, int, global::Morphant.Context.MappingContext, int> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
        global::Morphant.Delegates.Convert<string?, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
        global::Morphant.Delegates.Convert<string?, int, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mapper, string, int> builder,
        global::Morphant.Delegates.Convert<string?, int, global::Morphant.Context.MappingContext, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__f76b1361cb552263930ff9b2ca8cd52b.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

using global::System.Linq;
using static global::SafeCalls.SafeOperations;

namespace ExtensionCases;

public partial class Mapper :
    global::Morphant.ITypeMapper<string, int>,
    global::Morphant.ITypeMapper<global::ExtensionCases.Source, string>
{
    /// <inheritdoc/>
    protected override bool Supports(
        global::System.Type sourceType,
        global::System.Type destinationType) =>
            (sourceType == typeof(string) &&
                destinationType == typeof(int)) ||
            (sourceType == typeof(global::ExtensionCases.Source) &&
                destinationType == typeof(string)) ||
            base.Supports(sourceType, destinationType);

    /// <inheritdoc/>
    int global::Morphant.ITypeMapper<string, int>.Create(
        string? source,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination(source);

    /// <inheritdoc/>
    int global::Morphant.ITypeMapper<string, int>.Update(
        string? source,
        int destination,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination(source);

    private int __ConvertDestination(string? source) => global::Calls.Operations.Extra(source!) + source!.Length.Twice();

    /// <inheritdoc/>
    string global::Morphant.ITypeMapper<global::ExtensionCases.Source, string>.Create(
        global::ExtensionCases.Source? source,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination1(source);

    /// <inheritdoc/>
    string global::Morphant.ITypeMapper<global::ExtensionCases.Source, string>.Update(
        global::ExtensionCases.Source? source,
        string? destination,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination1(source);

    private string __ConvertDestination1(global::ExtensionCases.Source? source)
    {
        global::System.Func<int, int> increment = source!.Increment;
        return string.Join(",", from value in source!.Values select increment(value));
    }
}
"""),
    ];
}
