using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.ExtensionInvocationTests.Usage;

internal sealed partial class ExtensionInvocationTests
{
    [TestCase(LanguageVersion.CSharp9)]
    [TestCase(LanguageVersion.CSharp10)]
    public void Receiver_interface_edits_reconsider_generic_extension_applicability(LanguageVersion version)
    {
        const string interfaceDeclaration = "    public interface ISubject {}";
        var mapper = InterfaceSource.Replace(interfaceDeclaration, "", StringComparison.Ordinal);
        Assert.That(mapper, Is.Not.EqualTo(InterfaceSource));
        const string beforeInterface = "#nullable enable\n#pragma warning disable CS1591\nnamespace ExtensionCases { public interface ISubject {} }";
        var afterInterface = beforeInterface.Replace("ISubject {}", "ISubject : IRequired {}", StringComparison.Ordinal);
        var initial = GeneratorTestDriver.Run("ExtensionInvocation", new[]
        {
            new GeneratorTestSourceFile("Mapper.cs", mapper),
            new GeneratorTestSourceFile("Interface.cs", beforeInterface)
        }, version);
        var before = version == LanguageVersion.CSharp9 ? Interface9BeforeSources : Interface10BeforeSources;
        var after = version == LanguageVersion.CSharp9 ? Interface9AfterSources : Interface10AfterSources;
        var driver = initial.Driver;
        var compilation = initial.OutputCompilation.RemoveSyntaxTrees(driver.GetRunResult().GeneratedTrees);
        var mapperTree = compilation.SyntaxTrees.Single(tree => tree.FilePath == "Mapper.cs");
        var interfaceTree = compilation.SyntaxTrees.Single(tree => tree.FilePath == "Interface.cs");
        VerifyIncrementalExtensions(driver, initial.OutputCompilation, before);
        foreach (var (source, expected) in new[] { (afterInterface, after), (beforeInterface, before) })
        {
            var updatedTree = interfaceTree.WithChangedText(SourceText.From(source, Encoding.UTF8));
            compilation = compilation.ReplaceSyntaxTree(interfaceTree, updatedTree);
            interfaceTree = updatedTree;
            Assert.That(compilation.SyntaxTrees.Single(tree => tree.FilePath == "Mapper.cs"), Is.SameAs(mapperTree));
            driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var output, out var diagnostics);
            Assert.That(diagnostics, Is.Empty);
            VerifyIncrementalExtensions(driver, output, expected);
        }
    }

    // lang=c#
    private const string InterfaceSource =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;
namespace Imported
{
    public static class Operations
    {
        public static int Describe(this object value) => 11;
        public static int Independent(this int value) => value * 2;
    }
}
namespace ExtensionCases
{
    public interface IRequired {}
    public interface ISubject {}
    public sealed class Subject : ISubject
    {
        public int Length => 3;
    }
    public static class CloserOperations
    {
        public static int Describe<T>(this T value) where T : IRequired => 99;
    }
    namespace Mappers
    {
        using Imported;
        [MorphantMapper]
        public partial class Mapper : TypeMapper<Mapper>
        {
            protected override void Configure(MapperBuilder builder) =>
                builder.Map<Subject, int>().Convert(source =>
                    source!.Describe() + source!.Length.Independent());
        }
    }
}
""";

    private static readonly (string Hint, string Source)[] Interface9BeforeSources =
    [
        ("Morphant.Generated.MappingExtension.Mapper.SubjectToInt32__b45ced3083ed2e90fe76416ccd04ee3e.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ConstructUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Subject, int> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ConstructUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Subject, global::Morphant.Context.MappingContext, int> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ResolveUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Subject, int, int> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ResolveUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Subject, int, global::Morphant.Context.MappingContext, int> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int, global::Morphant.Context.MappingContext, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__f34b12dab1f8727313c364da14516bae.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

using static global::Imported.Operations;

namespace ExtensionCases.Mappers
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::ExtensionCases.Subject) &&
                    destinationType == typeof(int)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>.Create(
            global::ExtensionCases.Subject? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>.Update(
            global::ExtensionCases.Subject? source,
            int destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        private int __ConvertDestination(global::ExtensionCases.Subject? source) => source!.Describe() + source!.Length.Independent();
    }
}
"""),
    ];

    private static readonly (string Hint, string Source)[] Interface9AfterSources =
    [
        ("Morphant.Generated.MappingExtension.Mapper.SubjectToInt32__b45ced3083ed2e90fe76416ccd04ee3e.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ConstructUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Subject, int> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ConstructUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Subject, global::Morphant.Context.MappingContext, int> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ResolveUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Subject, int, int> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ResolveUsing(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Subject, int, global::Morphant.Context.MappingContext, int> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
            this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
            global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int, global::Morphant.Context.MappingContext, int> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__f34b12dab1f8727313c364da14516bae.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

using static global::Imported.Operations;

namespace ExtensionCases.Mappers
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::ExtensionCases.Subject) &&
                    destinationType == typeof(int)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>.Create(
            global::ExtensionCases.Subject? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>.Update(
            global::ExtensionCases.Subject? source,
            int destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        private int __ConvertDestination(global::ExtensionCases.Subject? source) => global::Imported.Operations.Describe(source!) + source!.Length.Independent();
    }
}
"""),
    ];

    private static readonly (string Hint, string Source)[] Interface10BeforeSources =
    [
        ("Morphant.Generated.MappingExtension.Mapper.SubjectToInt32__b45ced3083ed2e90fe76416ccd04ee3e.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant;

internal static partial class MorphantGeneratedMappingExtensions
{
    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Subject, int> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Subject, global::Morphant.Context.MappingContext, int> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Subject, int, int> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Subject, int, global::Morphant.Context.MappingContext, int> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int, global::Morphant.Context.MappingContext, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__f34b12dab1f8727313c364da14516bae.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

using static global::Imported.Operations;

namespace ExtensionCases.Mappers;

public partial class Mapper :
    global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>
{
    /// <inheritdoc/>
    protected override bool Supports(
        global::System.Type sourceType,
        global::System.Type destinationType) =>
            (sourceType == typeof(global::ExtensionCases.Subject) &&
                destinationType == typeof(int)) ||
            base.Supports(sourceType, destinationType);

    /// <inheritdoc/>
    int global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>.Create(
        global::ExtensionCases.Subject? source,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination(source);

    /// <inheritdoc/>
    int global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>.Update(
        global::ExtensionCases.Subject? source,
        int destination,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination(source);

    private int __ConvertDestination(global::ExtensionCases.Subject? source) => source!.Describe() + source!.Length.Independent();
}
"""),
    ];

    private static readonly (string Hint, string Source)[] Interface10AfterSources =
    [
        ("Morphant.Generated.MappingExtension.Mapper.SubjectToInt32__b45ced3083ed2e90fe76416ccd04ee3e.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant;

internal static partial class MorphantGeneratedMappingExtensions
{
    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Subject, int> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ConstructUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.ConstructUsing<global::ExtensionCases.Subject, global::Morphant.Context.MappingContext, int> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Subject, int, int> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> ResolveUsing(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.ResolveUsing<global::ExtensionCases.Subject, int, global::Morphant.Context.MappingContext, int> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> Convert(
        this global::Morphant.MappingBuilder<global::ExtensionCases.Mappers.Mapper, global::ExtensionCases.Subject, int> builder,
        global::Morphant.Delegates.Convert<global::ExtensionCases.Subject?, int, global::Morphant.Context.MappingContext, int> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__f34b12dab1f8727313c364da14516bae.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

using static global::Imported.Operations;

namespace ExtensionCases.Mappers;

public partial class Mapper :
    global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>
{
    /// <inheritdoc/>
    protected override bool Supports(
        global::System.Type sourceType,
        global::System.Type destinationType) =>
            (sourceType == typeof(global::ExtensionCases.Subject) &&
                destinationType == typeof(int)) ||
            base.Supports(sourceType, destinationType);

    /// <inheritdoc/>
    int global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>.Create(
        global::ExtensionCases.Subject? source,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination(source);

    /// <inheritdoc/>
    int global::Morphant.ITypeMapper<global::ExtensionCases.Subject, int>.Update(
        global::ExtensionCases.Subject? source,
        int destination,
        global::Morphant.Context.MappingContext context)
        => __ConvertDestination(source);

    private int __ConvertDestination(global::ExtensionCases.Subject? source) => global::Imported.Operations.Describe(source!) + source!.Length.Independent();
}
"""),
    ];
}
