namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Lifecycle;

internal sealed partial class LifecycleTests
{
    private static readonly (string HintName, string Source)[] SystemTupleResolveReusesOrConstructsReplacementSurfaces =
    [
            ("Morphant.Generated.Construction.Tuple_S2_ccb1d38f95b5177b3d475773e5a40e78.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae
{
    /// <summary>
    /// Maps constructor arguments for <see cref="T:System.Tuple`2"/>.
    /// </summary>
    internal sealed class TupleConstructorParameters
    {
        /// <summary>
        /// Maps the <c>Item1</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<int> Item1 = null!;

        /// <summary>
        /// Maps the <c>Item2</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string> Item2 = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="T:System.Tuple`2"/>.
    /// </summary>
    internal sealed class TupleConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public TupleConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            TupleConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="Item1">Maps the <c>Item1</c> argument.</param>
        /// <param name="Item2">Maps the <c>Item2</c> argument.</param>
        public TupleConstruction(
            global::Morphant.Members.ConstructorParameter<int> Item1,
            global::Morphant.Members.ConstructorParameter<string> Item2)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator TupleConstruction(
            global::Morphant.Option<global::System.Tuple<int, string>> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.MappingExtension.TestCase_Source__System_Tuple_System_Int32__System_String___TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae.TupleConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae.TupleConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning previous or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::System.Tuple<int, string>, global::Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae.TupleConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning previous or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::System.Tuple<int, string>, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae.TupleConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::System.Tuple<int, string>> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::System.Tuple<int, string>> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::System.Tuple<int, string>, global::System.Tuple<int, string>> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::System.Tuple<int, string>, global::Morphant.Context.MappingContext, global::System.Tuple<int, string>> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::System.Tuple<int, string>> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::System.Tuple<int, string>, global::System.Tuple<int, string>> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::System.Tuple<int, string>, global::Morphant.Context.MappingContext, global::System.Tuple<int, string>> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.Member.Tuple_S2_ccb1d38f95b5177b3d475773e5a40e78.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae
{
    /// <summary>
    /// Maps members of <see cref="T:System.Tuple`2"/>.
    /// </summary>
    internal sealed record TupleMembers
    {
        /// <summary>
        /// Maps tuple element <c>Item1</c>.
        /// </summary>
        public global::Morphant.Members.Member<int> Item1
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps tuple element <c>Item2</c>.
        /// </summary>
        public global::Morphant.Members.Member<string> Item2
        {
            get => null!;
            set { }
        }

        public bool Equals(TupleMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
"""),
            ("Morphant.Generated.MemberExtension.TestCase_Source__System_Tuple_System_Int32__System_String___TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae.TupleMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::System.Tuple<int, string>, global::Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae.TupleMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::System.Tuple<int, string>, global::System.Tuple<int, string>, global::Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae.TupleMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<int, string>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::System.Tuple<int, string>, global::System.Tuple<int, string>, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_caea12a00fdfde028ac36275c1a7a6ae.TupleMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""")
    ];
}
