using System.Text;

namespace Morphant.Generator.UnitTests.TestUtils;

internal static class ConstructionSurfaceExpectedSource
{
    public static string Plan(
        string @namespace,
        string constructionType,
        string constructorParametersType = "")
    {
        var declarations = string.IsNullOrEmpty(constructorParametersType)
            ? constructionType
            : constructorParametersType + "\n\n" + constructionType;

        return
            "// <auto-generated />\n" +
            "#nullable enable\n\n" +
            $"namespace {@namespace}\n" +
            "{\n" +
            Indent(declarations, 1) + "\n" +
            "}\n";
    }

    public static string ConstructorParametersType(
        string typeDeclaration,
        string destinationCref,
        params string[] fields)
    {
        return
            "/// <summary>\n" +
            "/// Contains mappings for constructor arguments of " +
            $"<see cref=\"{destinationCref}\"/>.\n" +
            "/// </summary>\n" +
            typeDeclaration + "\n" +
            "{\n" +
            Indent(string.Join("\n\n", fields), 1) + "\n" +
            "}";
    }

    public static string ConstructorParameterField(
        string parameterName,
        string declaration)
    {
        return
            "/// <summary>\n" +
            $"/// Configures the <c>{parameterName}</c> constructor argument.\n" +
            "/// </summary>\n" +
            declaration;
    }

    public static string ConstructionType(
        string documentation,
        string typeDeclaration,
        string constructorName,
        string constructionTypeReference,
        string destinationType,
        string destinationConstructors = "",
        string? constructorParametersTypeReference = null,
        string obsoleteAttribute = "")
    {
        var declarations = new List<string>
        {
            BuildByConventionConstructor(
                constructorName,
                constructorParametersTypeReference),
            BuildByFactoryConstructor(constructorName, destinationType)
        };

        if (!string.IsNullOrEmpty(destinationConstructors))
        {
            declarations.Add(destinationConstructors);
        }

        declarations.Add(
            BuildPreviousConversion(
                constructionTypeReference,
                destinationType));

        var attribute = string.IsNullOrEmpty(obsoleteAttribute)
            ? string.Empty
            : obsoleteAttribute + "\n";

        return
            documentation + "\n" +
            attribute +
            typeDeclaration + "\n" +
            "{\n" +
            Indent(string.Join("\n\n", declarations), 1) + "\n" +
            "}";
    }

    public static string FallbackPlanDocumentation(string destinationCref)
    {
        return
            "/// <summary>\n" +
            "/// Describes construction of " +
            $"<see cref=\"{destinationCref}\"/>.\n" +
            "/// </summary>";
    }

    public static string InheritDocumentation(string cref)
    {
        return $"/// <inheritdoc cref=\"{cref}\"/>";
    }

    public static string MappingExtension(
        string builderType,
        string declarativeSourceType,
        string manualSourceType,
        string destinationType,
        string previousDestinationType,
        string constructionResultType,
        string methodTypeParameterList = "",
        string typeParameterDocumentation = "",
        string constraints = "")
    {
        var methods = string.Join(
            "\n\n",
            BuildSourceOnlyConstruct(
                builderType,
                declarativeSourceType,
                constructionResultType,
                methodTypeParameterList,
                typeParameterDocumentation,
                constraints),
            BuildPreviousAwareConstruct(
                builderType,
                declarativeSourceType,
                previousDestinationType,
                constructionResultType,
                methodTypeParameterList,
                typeParameterDocumentation,
                constraints),
            BuildConvert(
                builderType,
                manualSourceType,
                previousDestinationType,
                destinationType,
                methodTypeParameterList,
                typeParameterDocumentation,
                constraints));

        return
            "// <auto-generated />\n" +
            "#nullable enable\n\n" +
            "namespace Morphant\n" +
            "{\n" +
            "    internal static partial class " +
            "MorphantGeneratedMappingExtensions\n" +
            "    {\n" +
            Indent(methods, 2) + "\n" +
            "    }\n" +
            "}\n";
    }

    private static string BuildByConventionConstructor(
        string constructorName,
        string? constructorParametersTypeReference)
    {
        if (constructorParametersTypeReference is null)
        {
            return
                "/// <summary>\n" +
                "/// Creates a destination instance using " +
                "convention-based mapping.\n" +
                "/// </summary>\n" +
                "/// <param name=\"marker\">Selects convention-based " +
                "construction.</param>\n" +
                $"public {constructorName}(global::Morphant.Markers." +
                "ByConventionMarker marker)\n" +
                "{\n" +
                "}";
        }

        return
            "/// <summary>\n" +
            "/// Creates a destination instance using convention-based " +
            "mapping.\n" +
            "/// </summary>\n" +
            "/// <param name=\"marker\">Selects convention-based " +
            "construction.</param>\n" +
            "/// <param name=\"parameters\">Specifies optional mappings " +
            "for constructor arguments.</param>\n" +
            $"public {constructorName}(\n" +
            "    global::Morphant.Markers.ByConventionMarker marker,\n" +
            $"    {constructorParametersTypeReference}? parameters = null)\n" +
            "{\n" +
            "}";
    }

    private static string BuildByFactoryConstructor(
        string constructorName,
        string destinationType)
    {
        return
            "/// <summary>\n" +
            "/// Creates a destination instance using factory-based " +
            "construction.\n" +
            "/// </summary>\n" +
            "/// <param name=\"marker\">Selects factory-based " +
            "construction.</param>\n" +
            $"public {constructorName}(global::Morphant.Markers." +
            $"IByFactoryMarker<{destinationType}> marker)\n" +
            "{\n" +
            "}";
    }

    private static string BuildPreviousConversion(
        string constructionTypeReference,
        string destinationType)
    {
        return
            "/// <summary>\n" +
            "/// Selects an existing destination as the mapping result.\n" +
            "/// </summary>\n" +
            "/// <param name=\"previous\">The existing destination to " +
            "select.</param>\n" +
            "public static implicit operator " +
            $"{constructionTypeReference}(\n" +
            $"    global::Morphant.Option<{destinationType}> previous) =>\n" +
            "    throw new global::Morphant.Exceptions." +
            "RuntimeInvocationNotSupportedException();";
    }

    private static string BuildSourceOnlyConstruct(
        string builderType,
        string sourceType,
        string constructionResultType,
        string typeParameterList,
        string typeParameterDocumentation,
        string constraints)
    {
        return
            "/// <summary>\n" +
            "/// Configures how to construct a destination when no " +
            "existing destination is used.\n" +
            "/// </summary>\n" +
            BuildTypeParameterDocumentation(typeParameterDocumentation) +
            "/// <param name=\"builder\">The mapping builder to " +
            "configure.</param>\n" +
            "/// <param name=\"construct\">A lambda expression that " +
            "receives the non-null source and describes destination " +
            "construction.</param>\n" +
            "/// <returns>The <paramref name=\"builder\"/> " +
            "instance.</returns>\n" +
            $"public static {builderType} Construct{typeParameterList}(\n" +
            $"    this {builderType} builder,\n" +
            $"    global::System.Func<{sourceType}, " +
            $"{constructionResultType}> construct)\n" +
            BuildMethodEnd(constraints);
    }

    private static string BuildPreviousAwareConstruct(
        string builderType,
        string sourceType,
        string previousDestinationType,
        string constructionResultType,
        string typeParameterList,
        string typeParameterDocumentation,
        string constraints)
    {
        return
            "/// <summary>\n" +
            "/// Configures how to select or construct the destination " +
            "from the source and an optional existing destination.\n" +
            "/// </summary>\n" +
            BuildTypeParameterDocumentation(typeParameterDocumentation) +
            "/// <param name=\"builder\">The mapping builder to " +
            "configure.</param>\n" +
            "/// <param name=\"construct\">A lambda expression that " +
            "receives the non-null source and the optional existing " +
            "destination and describes destination construction.</param>\n" +
            "/// <returns>The <paramref name=\"builder\"/> " +
            "instance.</returns>\n" +
            $"public static {builderType} Construct{typeParameterList}(\n" +
            $"    this {builderType} builder,\n" +
            $"    global::System.Func<{sourceType}, " +
            $"global::Morphant.Option<{previousDestinationType}>, " +
            $"{constructionResultType}> construct)\n" +
            BuildMethodEnd(constraints);
    }

    private static string BuildConvert(
        string builderType,
        string sourceType,
        string previousDestinationType,
        string destinationType,
        string typeParameterList,
        string typeParameterDocumentation,
        string constraints)
    {
        return
            "/// <summary>\n" +
            "/// Configures a fully manual mapping algorithm.\n" +
            "/// </summary>\n" +
            BuildTypeParameterDocumentation(typeParameterDocumentation) +
            "/// <param name=\"builder\">The mapping builder to " +
            "configure.</param>\n" +
            "/// <param name=\"mapping\">A lambda expression that " +
            "receives the original source, the optional existing " +
            "destination, and the current mapping context.</param>\n" +
            "/// <returns>The <paramref name=\"builder\"/> " +
            "instance.</returns>\n" +
            $"public static {builderType} Convert{typeParameterList}(\n" +
            $"    this {builderType} builder,\n" +
            $"    global::System.Func<{sourceType}, " +
            $"global::Morphant.Option<{previousDestinationType}>, " +
            "global::Morphant.Context.MappingContext, " +
            $"{destinationType}> mapping)\n" +
            BuildMethodEnd(constraints);
    }

    private static string BuildTypeParameterDocumentation(
        string typeParameterDocumentation)
    {
        return string.IsNullOrEmpty(typeParameterDocumentation)
            ? string.Empty
            : typeParameterDocumentation.Trim('\r', '\n') + "\n";
    }

    private static string BuildMethodEnd(string constraints)
    {
        var constraintsBlock = string.IsNullOrEmpty(constraints)
            ? string.Empty
            : Indent(constraints, 1) + "\n";

        return
            constraintsBlock +
            "    => throw new global::Morphant.Exceptions." +
            "RuntimeInvocationNotSupportedException();";
    }

    private static string Indent(string value, int level)
    {
        var indentation = new string(' ', level * 4);
        var normalized = value
            .Replace("\r\n", "\n")
            .Replace('\r', '\n')
            .Trim('\n');
        var builder = new StringBuilder();
        var lines = normalized.Split('\n');

        for (var index = 0; index < lines.Length; index++)
        {
            if (lines[index].Length > 0)
            {
                builder.Append(indentation);
                builder.Append(lines[index]);
            }

            if (index < lines.Length - 1)
            {
                builder.Append('\n');
            }
        }

        return builder.ToString();
    }
}
