using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Morphant.Generator.PairConfiguration;
using Morphant.Generator.Settings;
using Morphant.Generator.TypeMapperConfigure;

namespace Morphant.Generator.UnitTests.TestUtils;

internal sealed class TestPairConfigurationGenerator :
    IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
                SymbolDisplayMiscellaneousOptions
                    .IncludeNullableReferenceTypeModifier |
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(
        IncrementalGeneratorInitializationContext context)
    {
        var compilationContext = CompilationContextPipeline.Build(context);
        var assemblySettings =
            AssemblyMappingSettingsPipeline.Build(context);
        var configureInfos = TypeMapperConfigurePipeline.Build(
            context,
            compilationContext);
        var configurations = PairConfigurationPipeline.Build(configureInfos)
            .Collect()
            .Combine(assemblySettings);

        context.RegisterSourceOutput(
            configurations,
            static (sourceProductionContext, source) =>
                sourceProductionContext.AddSource(
                    "PairConfigurationModel.g.cs",
                    Emit(source.Left, source.Right)));
    }

    private static SourceText Emit(
        ImmutableArray<MapperPairConfigurationModel> models,
        MappingSettings assemblySettings)
    {
        const string newLine = "\r\n";
        var builder = new StringBuilder();
        var orderedModels = models
            .OrderBy(
                static model => model.MappingPairs.MapperIdentity,
                StringComparer.Ordinal)
            .ToArray();

        builder.Append("// <auto-generated />").Append(newLine);
        builder.Append("#nullable enable").Append(newLine);
        builder.Append(newLine);

        if (assemblySettings.UnmappedMemberValidation !=
            UnmappedMemberValidationValue.Default)
        {
            builder.Append("// Assembly UnmappedMemberValidation: ")
                .Append(
                    assemblySettings.UnmappedMemberValidation?.ToString() ??
                    "Invalid")
                .Append(newLine);
        }

        builder.Append("// Mappers: ")
            .Append(orderedModels.Length)
            .Append(newLine);

        for (var mapperIndex = 0;
             mapperIndex < orderedModels.Length;
             mapperIndex++)
        {
            var model = orderedModels[mapperIndex];

            builder.Append("// Mapper ")
                .Append(mapperIndex)
                .Append(": ")
                .Append(model.MappingPairs.MapperIdentity)
                .Append(newLine);
            builder.Append("// Unifiable: ")
                .Append(model.MappingPairs.HasUnifiablePairs)
                .Append(newLine);
            WriteSettings(builder, "Root", model.RootSettings, newLine);

            if (!model.BaseRootSettings.IsEmpty)
            {
                builder.Append("// Base roots: ")
                    .Append(model.BaseRootSettings.Length)
                    .Append(newLine);

                for (var rootIndex = 0;
                     rootIndex < model.BaseRootSettings.Length;
                     rootIndex++)
                {
                    WriteSettings(
                        builder,
                        "Base root " + rootIndex,
                        model.BaseRootSettings[rootIndex],
                        newLine);
                }
            }

            if (model.HasInvalidBaseConfiguration)
            {
                builder.Append("// Invalid base configuration: True")
                    .Append(newLine);
            }

            builder.Append("// Pairs: ")
                .Append(model.Pairs.Length)
                .Append(newLine);

            for (var pairIndex = 0;
                 pairIndex < model.Pairs.Length;
                 pairIndex++)
            {
                WritePair(
                    builder,
                    pairIndex,
                    model.Pairs[pairIndex],
                    newLine);
            }
        }

        return SourceText.From(builder.ToString(), Encoding.UTF8);
    }

    private static void WritePair(
        StringBuilder builder,
        int index,
        PairConfigurationModel model,
        string newLine)
    {
        builder.Append("// Pair ")
            .Append(index)
            .Append(": ")
            .Append(model.Pair.Identity.Source.DisplayName)
            .Append(" -> ")
            .Append(model.Pair.Identity.Destination.DisplayName)
            .Append(newLine);
        builder.Append("// Map: ")
            .Append(NormalizeSyntax(model.Pair.Registration.Syntax))
            .Append(newLine);
        WriteSettings(builder, "Map", model.Settings, newLine);
        builder.Append("// Declarative: ResultPolicies=")
            .Append(model.Declarative.ResultPolicies.Length)
            .Append("; Members=")
            .Append(model.Declarative.Members.Length)
            .Append(newLine);

        for (var callIndex = 0;
             callIndex < model.Declarative.ResultPolicies.Length;
             callIndex++)
        {
            var call = model.Declarative.ResultPolicies[callIndex];

            WriteExpression(
                builder,
                call.Kind.ToString(),
                callIndex,
                call.Form.ToString(),
                call.Expression,
                newLine);
        }

        for (var callIndex = 0;
             callIndex < model.Declarative.Members.Length;
             callIndex++)
        {
            var call = model.Declarative.Members[callIndex];

            WriteExpression(
                builder,
                "Members",
                callIndex,
                call.Form.ToString(),
                call.Expression,
                newLine);
        }

        if (!model.Declarative.IncludeMembers.IsEmpty)
        {
            builder.Append("// IncludeMembers: ")
                .Append(model.Declarative.IncludeMembers.Length)
                .Append(newLine);

            for (var callIndex = 0;
                 callIndex < model.Declarative.IncludeMembers.Length;
                 callIndex++)
            {
                var call = model.Declarative.IncludeMembers[callIndex];

                WriteExpression(
                    builder,
                    "IncludeMembers",
                    callIndex,
                    "Selector",
                    call.Expression,
                    newLine);
            }
        }

        builder.Append("// Manual: Converts=")
            .Append(model.Manual.Conversions.Length)
            .Append(newLine);

        for (var callIndex = 0;
             callIndex < model.Manual.Conversions.Length;
             callIndex++)
        {
            WriteExpression(
                builder,
                "Convert",
                callIndex,
                model.Manual.Conversions[callIndex].Form.ToString(),
                model.Manual.Conversions[callIndex].Expression,
                newLine);
        }

        builder.Append("// IncludeBase: ")
            .Append(model.Composition.IncludeBaseCalls.Length)
            .Append(newLine);

        for (var callIndex = 0;
             callIndex < model.Composition.IncludeBaseCalls.Length;
             callIndex++)
        {
            var call = model.Composition.IncludeBaseCalls[callIndex];

            builder.Append("// IncludeBase ")
                .Append(callIndex)
                .Append(": ")
                .Append(call.SourceType.ToDisplayString(TypeDisplayFormat))
                .Append(" -> ")
                .Append(call.DestinationType.ToDisplayString(TypeDisplayFormat))
                .Append(newLine);
        }

        if (!model.Composition.IncludedBaseSettings.IsEmpty)
        {
            builder.Append("// Included settings: ")
                .Append(model.Composition.IncludedBaseSettings.Length)
                .Append(newLine);

            for (var settingsIndex = 0;
                 settingsIndex <
                     model.Composition.IncludedBaseSettings.Length;
                 settingsIndex++)
            {
                WriteSettings(
                    builder,
                    "Included " + settingsIndex,
                    model.Composition.IncludedBaseSettings[settingsIndex],
                    newLine);
            }
        }

        builder.Append("// Conflicts: ")
            .Append(model.Conflicts)
            .Append(newLine);
    }

    private static void WriteExpression(
        StringBuilder builder,
        string kind,
        int index,
        string form,
        BoundConfigurationExpression expression,
        string newLine)
    {
        builder.Append("// ")
            .Append(kind)
            .Append(' ')
            .Append(index)
            .Append(": Form=")
            .Append(form)
            .Append("; Inputs=(")
            .Append(string.Join(
                ", ",
                expression.DelegateInvokeMethod.Parameters.Select(
                    static parameter =>
                        parameter.Type.ToDisplayString(TypeDisplayFormat))))
            .Append("); Output=")
            .Append(expression.DelegateInvokeMethod.ReturnType.ToDisplayString(
                TypeDisplayFormat))
            .Append("; Operation=")
            .Append(expression.Operation?.Kind.ToString() ?? "None")
            .Append("; Syntax=")
            .Append(NormalizeSyntax(expression.Syntax))
            .Append(newLine);
    }

    private static void WriteSettings(
        StringBuilder builder,
        string level,
        PairConfigurationSettings settings,
        string newLine)
    {
        builder.Append("// ")
            .Append(level)
            .Append(" settings: MappingMode=")
            .Append(FormatSetting(settings.MappingMode))
            .Append("; NullSourceHandling=")
            .Append(FormatSetting(settings.NullSourceHandling))
            .Append("; NullDestinationHandling=")
            .Append(FormatSetting(settings.NullDestinationHandling))
            .Append("; ConstructorSelection=")
            .Append(FormatSetting(settings.ConstructorSelection))
            .Append("; MemberSelection=")
            .Append(FormatSetting(settings.MemberSelection))
            .Append("; Flattening=")
            .Append(FormatSetting(settings.Flattening))
            .Append("; UnmappedMemberValidation=")
            .Append(FormatSetting(settings.UnmappedMemberValidation))
            .Append(newLine);
    }

    private static string FormatSetting<TValue>(
        PairConfigurationSetting<TValue> setting)
        where TValue : struct, Enum
    {
        return setting.Origin == PairConfigurationSettingOrigin.Unset
            ? "Unset"
            : setting.Origin + "(" +
              (setting.Value?.ToString() ?? "Invalid") + ")";
    }

    private static string NormalizeSyntax(SyntaxNode syntax)
    {
        return syntax
            .NormalizeWhitespace()
            .ToFullString()
            .Replace("\r\n", " ")
            .Replace('\r', ' ')
            .Replace('\n', ' ')
            .Replace(" !", "!");
    }
}
