using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.GeneratedCodeReviewTests;

[TestFixture]
internal sealed class SupportingConvertedTests
{
    [Test]
    public async Task Keeps_independent_user_defined_conversions_before_member_writes()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using System.Collections.Generic;
using Morphant;

namespace TestCase
{
    public sealed class WriteException : Exception { }
    public sealed class Source
    {
        public readonly List<string> Events = new List<string>();
        public Action? Mutate;
        public bool Throw;
        public int Conversions;
        public string Initial() { Events.Add("initial"); return "initial"; }
        public bool Remember(Action action) { Events.Add("remember"); Mutate = action; return true; }
    }
    public sealed class Destination
    {
        private readonly Source _source;
        private string _name;
        private string _label = "unset";
        public Destination(Source owner, string name) { _source = owner; _name = name; owner.Events.Add("construct"); }
        public string Name
        {
            get { _source.Events.Add("read"); return _name; }
            set { _source.Events.Add("name:" + value); if (_source.Throw) throw new WriteException(); _name = value; _source.Mutate?.Invoke(); }
        }
        public string Label { get => _label; set { _source.Events.Add("label:" + value); _label = value; } }
        public string ReadName() => _name;
    }
    public readonly struct Input
    {
        private readonly Source _source;
        private readonly string _value;
        public Input(Source source, string value) { _source = source; _value = value; }
        public static implicit operator string(Input value)
        {
            var count = ++value._source.Conversions;
            value._source.Events.Add("convert:" + count);
            return value._value + ":" + count;
        }
    }
    public sealed class BoxedDestination
    {
        public BoxedDestination(object first) { First = first; }
        public object First { get; set; }
        public object Second { get; set; } = 0;
    }

    [MorphantMapper]
    public partial class ConvertedConstructMapper : TypeMapper<ConvertedConstructMapper>
    {
        protected override void Configure(MapperBuilder builder) => builder.Map<Source, Destination>()
            .Construct(source => new(source, source.Initial()))
            .Members((source, previous, result) =>
            {
                var normalized = new Input(source, result.Name.ToUpperInvariant());
                return new() { Name = (string)normalized, Label = (string)normalized };
            });
    }

    [MorphantMapper]
    public partial class ConvertedResolveMapper : TypeMapper<ConvertedResolveMapper>
    {
        protected override void Configure(MapperBuilder builder) => builder.Map<Source, Destination>()
            .Resolve((source, previous) => new(source, source.Initial()))
            .Members((source, previous, result) =>
            {
                var normalized = new Input(source, result.Name.ToUpperInvariant());
                return new() { Name = (string)normalized, Label = (string)normalized };
            });
    }
}
""";

        await ProductionGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9, source,
            ("Morphant.Generated.Construction.Destination__5e01468111660761710199b9666fe80e.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_5e01468111660761710199b9666fe80e
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Maps the <c>owner</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<global::TestCase.Source> owner = null!;

        /// <summary>
        /// Maps the <c>name</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string> name = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="owner">Maps the <c>owner</c> argument.</param>
        /// <param name="name">Maps the <c>name</c> argument.</param>
        public DestinationConstruction(
            global::Morphant.Members.ConstructorParameter<global::TestCase.Source> owner,
            global::Morphant.Members.ConstructorParameter<string> name)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::TestCase.Destination previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.MappingExtension.ConvertedConstructMapper.SourceToDestination__f3f78209b15ecc0b02a238f3c319fbfb.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::TestCase.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::TestCase.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.MappingExtension.ConvertedResolveMapper.SourceToDestination__8d8679dc9ed8d65a037199305a3495e1.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::TestCase.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::TestCase.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.Member.Destination__5e01468111660761710199b9666fe80e.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_5e01468111660761710199b9666fe80e
{
    /// <summary>
    /// Maps members of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Name"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Name
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Label"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Label
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
"""),
            ("Morphant.Generated.MemberExtension.ConvertedConstructMapper.SourceToDestination__f3f78209b15ecc0b02a238f3c319fbfb.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures destination members and matching automatic constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching automatic constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching automatic constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching automatic constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedConstructMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.MemberExtension.ConvertedResolveMapper.SourceToDestination__8d8679dc9ed8d65a037199305a3495e1.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures destination members and matching automatic constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching automatic constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching automatic constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching automatic constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.ConvertedResolveMapper, global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.TypeMapper.ConvertedConstructMapper__76eee94a104247eff96df28df6512c6f.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class ConvertedConstructMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source);
            }

            return __Update(source, destination);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source)
        {
            var result = new global::TestCase.Destination(
                owner: source,
                name: source.Initial());

            var normalized = new global::TestCase.Input(source, result.Name.ToUpperInvariant());

            string name = (string)normalized;
            string label = (string)normalized;

            result.Name = name;
            result.Label = label;

            return result;
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination)
        {
            var normalized = new global::TestCase.Input(source, destination.Name.ToUpperInvariant());

            string name = (string)normalized;
            string label = (string)normalized;

            destination.Name = name;
            destination.Label = label;

            return destination;
        }
    }
}
"""),
            ("Morphant.Generated.TypeMapper.ConvertedResolveMapper__ba8ad6962a0fb394ea1595af5f6ec6a8.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class ConvertedResolveMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source);
            }

            return __Update(source);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source)
        {
            var result = new global::TestCase.Destination(
                owner: source,
                name: source.Initial());

            var normalized = new global::TestCase.Input(source, result.Name.ToUpperInvariant());

            string name = (string)normalized;
            string label = (string)normalized;

            result.Name = name;
            result.Label = label;

            return result;
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source)
        {
            return __Create(source);
        }
    }
}
"""));
    }
}
