using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.IntegrationTests.TestUtils;

namespace Morphant.Generator.IntegrationTests.TypeMapperInheritanceTests;

[TestFixture]
internal sealed class GeneratedCodeTests
{
    [Test]
    public async Task Emits_the_complete_surface_for_a_cross_pair_include()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public class Animal
    {
        public int Value { get; init; }
    }

    public sealed class Dog : Animal
    {
        public string Breed { get; init; } = string.Empty;
    }

    public class AnimalDto
    {
        public int Value { get; set; }
    }

    public sealed class DogDto : AnimalDto
    {
        public string Breed { get; set; } = string.Empty;
    }

    public abstract class BaseMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Animal, AnimalDto>(MappingMode.Create)
                .Members((source, _) => new()
                {
                    Value = source.Value
                });
    }

    [MorphantMapper]
    public partial class DerivedMapper : BaseMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            base.Configure(builder);
            builder.Map<Dog, DogDto>()
                .IncludeBase<Animal, AnimalDto>()
                .Members((source, _) => new()
                {
                    Breed = source.Breed
                });
        }
    }
}
""";

        // lang=c#
        const string animalConstruction =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes construction of <see cref="global::TestCase.AnimalDto"/>.
    /// </summary>
    internal sealed class AnimalDtoConstruction
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        public AnimalDtoConstruction(global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using factory-based construction.
        /// </summary>
        /// <param name="marker">Selects factory-based construction.</param>
        public AnimalDtoConstruction(global::Morphant.Markers.IByFactoryMarker<global::TestCase.AnimalDto> marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using a corresponding constructor.
        /// </summary>
        public AnimalDtoConstruction()
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator AnimalDtoConstruction(
            global::Morphant.Option<global::TestCase.AnimalDto> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string dogConstruction =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes construction of <see cref="global::TestCase.DogDto"/>.
    /// </summary>
    internal sealed class DogDtoConstruction
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        public DogDtoConstruction(global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using factory-based construction.
        /// </summary>
        /// <param name="marker">Selects factory-based construction.</param>
        public DogDtoConstruction(global::Morphant.Markers.IByFactoryMarker<global::TestCase.DogDto> marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using a corresponding constructor.
        /// </summary>
        public DogDtoConstruction()
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator DogDtoConstruction(
            global::Morphant.Option<global::TestCase.DogDto> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string animalConstructionExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures how to construct a destination when no existing destination is used.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Animal, global::TestCase.Morphant.Generated.AnimalDtoConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures how to select or construct the destination from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and the optional existing destination and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Animal, global::TestCase.AnimalDto, global::TestCase.Morphant.Generated.AnimalDtoConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A lambda expression that receives the original source, the optional existing destination, and the current mapping context.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Animal?, global::TestCase.AnimalDto, global::TestCase.AnimalDto> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string dogConstructionExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures how to construct a destination when no existing destination is used.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Dog, global::TestCase.Morphant.Generated.DogDtoConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures how to select or construct the destination from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and the optional existing destination and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Dog, global::TestCase.DogDto, global::TestCase.Morphant.Generated.DogDtoConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A lambda expression that receives the original source, the optional existing destination, and the current mapping context.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Dog?, global::TestCase.DogDto, global::TestCase.DogDto> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string animalMembers =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes member mappings for <see cref="global::TestCase.AnimalDto"/>.
    /// </summary>
    internal sealed record AnimalDtoMembers
    {
        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.AnimalDto.Value"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }

        public bool Equals(AnimalDtoMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string dogMembers =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes member mappings for <see cref="global::TestCase.DogDto"/>.
    /// </summary>
    internal sealed record DogDtoMembers
    {
        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.AnimalDto.Value"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }

        #nullable disable annotations
        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.DogDto.Breed"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Breed
        {
            get => null!;
            set { }
        }
        #nullable enable annotations

        public bool Equals(DogDtoMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string animalMemberExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures mappings for destination members from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="members">A lambda expression that receives the non-null source and the optional existing destination and describes destination member mappings.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> builder,
            global::Morphant.Delegates.Members<global::TestCase.Animal, global::TestCase.AnimalDto, global::TestCase.Morphant.Generated.AnimalDtoMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures mappings for destination members with access to the selected mapping result.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="members">A lambda expression that receives the non-null source, the optional existing destination, and the non-null selected result and describes destination member mappings.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Animal, global::TestCase.AnimalDto> builder,
            global::Morphant.Delegates.Members<global::TestCase.Animal, global::TestCase.AnimalDto, global::TestCase.AnimalDto, global::TestCase.Morphant.Generated.AnimalDtoMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string dogMemberExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures mappings for destination members from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="members">A lambda expression that receives the non-null source and the optional existing destination and describes destination member mappings.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> builder,
            global::Morphant.Delegates.Members<global::TestCase.Dog, global::TestCase.DogDto, global::TestCase.Morphant.Generated.DogDtoMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures mappings for destination members with access to the selected mapping result.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="members">A lambda expression that receives the non-null source, the optional existing destination, and the non-null selected result and describes destination member mappings.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Dog, global::TestCase.DogDto> builder,
            global::Morphant.Delegates.Members<global::TestCase.Dog, global::TestCase.DogDto, global::TestCase.DogDto, global::TestCase.Morphant.Generated.DogDtoMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string mapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class DerivedMapper :
        global::Morphant.ITypeMapper<global::TestCase.Dog, global::TestCase.DogDto>
    {
        /// <inheritdoc/>
        global::TestCase.DogDto global::Morphant.ITypeMapper<global::TestCase.Dog, global::TestCase.DogDto>.Create(
            global::TestCase.Dog? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.DogDto global::Morphant.ITypeMapper<global::TestCase.Dog, global::TestCase.DogDto>.Update(
            global::TestCase.Dog? source,
            global::TestCase.DogDto? destination,
            global::Morphant.Context.MappingContext context)
            => throw new global::System.NotSupportedException(
                "The effective MappingMode does not include Update.");

        private global::TestCase.DogDto __Create(
            global::TestCase.Dog source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.DogDto()
            {
                Value = source.Value,
                Breed = source.Breed
            };
        }
    }
}
""";

        await ProductionGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_AnimalDto.g.cs",
                animalConstruction
            ),
            (
                "Morphant.Generated.Construction.TestCase_DogDto.g.cs",
                dogConstruction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Animal__TestCase_AnimalDto.g.cs",
                animalConstructionExtension
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Dog__TestCase_DogDto.g.cs",
                dogConstructionExtension
            ),
            (
                "Morphant.Generated.Member.TestCase_AnimalDto.g.cs",
                animalMembers
            ),
            (
                "Morphant.Generated.Member.TestCase_DogDto.g.cs",
                dogMembers
            ),
            (
                "Morphant.Generated.MemberExtension.TestCase_Animal__TestCase_AnimalDto.g.cs",
                animalMemberExtension
            ),
            (
                "Morphant.Generated.MemberExtension.TestCase_Dog__TestCase_DogDto.g.cs",
                dogMemberExtension
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_DerivedMapper.g.cs",
                mapper
            ));
    }
}
