using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Morphant.Generator.TemplateSurface.TemplateExtension;

internal static class TemplateExtensionPipeline
{
    public static void Register(
        IncrementalGeneratorInitializationContext context,
        IncrementalValueProvider<CompilationContext> compilationContext,
        IncrementalValuesProvider<MapperBuilderMapInfo> mapUsages)
    {
        var templateExtensionIdentities = mapUsages
            .Collect()
            .SelectMany(static (usages, _) =>
                BuildTemplateExtensionIdentities(usages))
            .WithTrackingName("MorphantGeneratorStageNames.BuildTemplateExtensionIdentities");

        var templateExtensionRequests = templateExtensionIdentities
            .Select(static (identity, _) =>
                Build(identity))
            .WithTrackingName("MorphantGeneratorStageNames.BuildTemplateExtensionRequests");

        context.RegisterSourceOutput(
            templateExtensionRequests,
            static (context, request) =>
            {
                context.AddSource(
                    request.HintName,
                    Generate(request));
            });
    }

    private static ImmutableArray<TemplateExtensionIdentity> BuildTemplateExtensionIdentities(
        ImmutableArray<MapperBuilderMapInfo> mapUsages)
    {
        var seen = new HashSet<string>();
        var builder = ImmutableArray.CreateBuilder<TemplateExtensionIdentity>();

        foreach (var usage in mapUsages)
        {
            if (!seen.Add(usage.DestinationType.MetadataName))
            {
                continue;
            }

            builder.Add(new TemplateExtensionIdentity(usage.DestinationType));
        }

        return builder.ToImmutable();
    }

    public static TemplateExtensionRequest Build(TemplateExtensionIdentity identity)
    {
        var hintName =
            "Morphant.TemplateExtensions." +
            HintNameHelper.ToHintNamePart(identity.DestinationType.MetadataName) +
            ".g.cs";

        return new TemplateExtensionRequest(
            identity.DestinationType,
            hintName);
    }

    public static SourceText Generate(TemplateExtensionRequest request)
    {
        var destinationType = request.DestinationType;

        var source = $@"// <auto-generated />
#nullable enable

namespace Morphant;

internal static partial class MorphantGeneratedTemplateExtensions
{{
    public static global::Morphant.MapperBuilder<TSource, {destinationType.FullyQualifiedName}> Template<TSource>(
        this global::Morphant.MapperBuilder<TSource, {destinationType.FullyQualifiedName}> builder,
        global::System.Func<TSource, {destinationType.TemplateTypeFullyQualifiedName}> template)
        => throw new global::Morphant.RuntimeInvocationNotSupportedException();

    public static global::Morphant.MapperBuilder<TSource, {destinationType.FullyQualifiedName}> Template<TSource>(
        this global::Morphant.MapperBuilder<TSource, {destinationType.FullyQualifiedName}> builder,
        global::System.Func<TSource, {destinationType.FullyQualifiedName}, {destinationType.TemplateTypeFullyQualifiedName}> template)
        => throw new global::Morphant.RuntimeInvocationNotSupportedException();
}}
";

        return SourceText.From(source, Encoding.UTF8);
    }
}
