using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Morphant.Generator.UnitTests.GeneratorFailureDiagnosticsTests;

[TestFixture]
internal sealed class BehaviorTests
{
    private const string ExceptionDetails =
        "TestGeneratorException: deliberate failure\r\n" +
        "   at TestFailureStage.Transform()";

    private const string TransformFailureHintName =
        "Morphant.Generated.GeneratorFailure." +
        "TestTransform__e9212180604c97fd.g.cs";

    private const string OutputFailureHintName =
        "Morphant.Generated.GeneratorFailure." +
        "TestOutput__a614156a89149f2f.g.cs";

    private const string InitializationFailureHintName =
        "Morphant.Generated.GeneratorFailure." +
        "TestInitialize__9cd49714a095fd82.g.cs";

    private const string LocationlessFailureHintName =
        "Morphant.Generated.GeneratorFailure." +
        "TestLocationlessTransform__f2ead8d79af163de.g.cs";

    private const string ValueFailureHintName =
        "Morphant.Generated.GeneratorFailure." +
        "TestValueTransform__a8c4eb9fc5bd9ac9.g.cs";

    private const string CommentTerminatorFailureHintName =
        "Morphant.Generated.GeneratorFailure." +
        "TestCommentTerminator__1808d56308b9d249.g.cs";

    // lang=c#
    private const string BrokenSource =
"""
#nullable enable
class BrokenMapper { }
class HealthyMapper { }
""";

    // lang=c#
    private const string RecoveredSource =
"""
#nullable enable
class RecoveredMapper { }
class HealthyMapper { }
""";

    // lang=c#
    private const string HealthyMapperOutput =
"""
// <auto-generated />
#nullable enable

// HealthyMapper
""";

    // lang=c#
    private const string RecoveredMapperOutput =
"""
// <auto-generated />
#nullable enable

// RecoveredMapper
""";

    // lang=c#
    private const string HealthyOutputOutput =
"""
// <auto-generated />
#nullable enable

// HealthyOutput
""";

    // lang=c#
    private const string FallbackOutput =
"""
// <auto-generated />
#nullable enable

// Fallback: 42
""";

    // lang=c#
    private const string TransformFailureReport =
"""
// <auto-generated />
#nullable enable

/*
MORPH0057: Morphant generator 0.4.0 failed unexpectedly.
Stage: TestTransform

TestGeneratorException: deliberate failure
   at TestFailureStage.Transform()
*/
""";

    // lang=c#
    private const string OutputFailureReport =
"""
// <auto-generated />
#nullable enable

/*
MORPH0057: Morphant generator 0.4.0 failed unexpectedly.
Stage: TestOutput

TestGeneratorException: deliberate failure
   at TestFailureStage.Transform()
*/
""";

    // lang=c#
    private const string InitializationFailureReport =
"""
// <auto-generated />
#nullable enable

/*
MORPH0057: Morphant generator 0.4.0 failed unexpectedly.
Stage: TestInitialize

TestGeneratorException: deliberate failure
   at TestFailureStage.Transform()
*/
""";

    // lang=c#
    private const string LocationlessFailureReport =
"""
// <auto-generated />
#nullable enable

/*
MORPH0057: Morphant generator 0.4.0 failed unexpectedly.
Stage: TestLocationlessTransform

TestGeneratorException: deliberate failure
   at TestFailureStage.Transform()
*/
""";

    // lang=c#
    private const string ValueFailureReport =
"""
// <auto-generated />
#nullable enable

/*
MORPH0057: Morphant generator 0.4.0 failed unexpectedly.
Stage: TestValueTransform

TestGeneratorException: deliberate failure
   at TestFailureStage.Transform()
*/
""";

    // lang=c#
    private const string CommentTerminatorFailureReport =
"""
// <auto-generated />
#nullable enable

/*
MORPH0057: Morphant generator 0.4.0 failed unexpectedly.
Stage: TestCommentTerminator

CommentTerminatorException: before * / after
*/
""";

    private static readonly ImmutableArray<MetadataReference>
        FrameworkReferences = BuildFrameworkReferences();

    [Test]
    public void Reports_a_transform_failure_and_keeps_independent_output()
    {
        var run = Run(
            BrokenSource,
            new TransformFailureGenerator());
        var diagnostic = run.Result.Diagnostics.Single();
        var exceptionType = typeof(TestGeneratorException).FullName!;

        Assert.Multiple(() =>
        {
            Assert.That(run.Result.Exception, Is.Null);
            Assert.That(diagnostic.Id, Is.EqualTo("MORPH0057"));
            Assert.That(
                diagnostic.Severity,
                Is.EqualTo(DiagnosticSeverity.Error));
            Assert.That(
                diagnostic.GetMessage(),
                Is.EqualTo(
                    "Morphant generator 0.4.0 failed unexpectedly in " +
                    $"stage 'TestTransform': {exceptionType}: deliberate " +
                    "failure. Full exception details are available in " +
                    $"generated file '{TransformFailureHintName}'."));
            Assert.That(
                diagnostic.Location.SourceTree,
                Is.SameAs(run.InputTree));
            Assert.That(
                diagnostic.Location.SourceSpan.Start,
                Is.EqualTo(BrokenSource.IndexOf(
                    "BrokenMapper",
                    StringComparison.Ordinal)));
            Assert.That(
                diagnostic.Location.SourceSpan.Length,
                Is.EqualTo("BrokenMapper".Length));
            Assert.That(diagnostic.AdditionalLocations, Is.Empty);
            Assert.That(
                diagnostic.Properties,
                Is.EqualTo(
                    ImmutableDictionary<string, string?>.Empty
                        .Add("ExceptionDetails", ExceptionDetails)
                        .Add("ExceptionMessage", "deliberate failure")
                        .Add("ExceptionType", exceptionType)
                        .Add("GeneratorVersion", "0.4.0")
                        .Add(
                            "ReportHintName",
                            TransformFailureHintName)
                        .Add("StageName", "TestTransform")));
            Assert.That(
                SnapshotSources(run.Result),
                Is.EqualTo(new[]
                {
                    new GeneratedSource(
                        "HealthyMapper.g.cs",
                        NormalizeExpected(HealthyMapperOutput)),
                    new GeneratedSource(
                        TransformFailureHintName,
                        NormalizeExpected(TransformFailureReport))
                }));
        });
    }

    [Test]
    public void Rebinds_a_cached_failure_and_recovers_after_the_edit()
    {
        var first = Run(
            BrokenSource,
            new TransformFailureGenerator());
        var recreated = Run(
            BrokenSource,
            new TransformFailureGenerator(),
            first.Driver);
        var recovered = Run(
            RecoveredSource,
            new TransformFailureGenerator(),
            recreated.Driver);

        Assert.Multiple(() =>
        {
            Assert.That(
                recreated.Result.Diagnostics.Single().Location.SourceTree,
                Is.SameAs(recreated.InputTree));
            Assert.That(recreated.Result.Exception, Is.Null);
            Assert.That(recovered.Result.Exception, Is.Null);
            Assert.That(recovered.Result.Diagnostics, Is.Empty);
            Assert.That(
                SnapshotSources(recovered.Result),
                Is.EqualTo(new[]
                {
                    new GeneratedSource(
                        "HealthyMapper.g.cs",
                        NormalizeExpected(HealthyMapperOutput)),
                    new GeneratedSource(
                        "RecoveredMapper.g.cs",
                        NormalizeExpected(RecoveredMapperOutput))
                }));
        });
    }

    [Test]
    public void Failure_hint_is_stable_across_platform_source_forms()
    {
        const string lfSource =
            "#nullable enable\n" +
            "class BrokenMapper { }\n" +
            "class HealthyMapper { }\n";
        var crlfSource = lfSource.Replace("\n", "\r\n");

        var lf = Run(
            lfSource,
            new TransformFailureGenerator(),
            sourcePath: "folder/TestCase.cs");
        var crlf = Run(
            crlfSource,
            new TransformFailureGenerator(),
            sourcePath: @"folder\TestCase.cs");

        var lfHint = lf.Result.Diagnostics.Single().Properties[
            "ReportHintName"];
        var crlfHint = crlf.Result.Diagnostics.Single().Properties[
            "ReportHintName"];

        Assert.Multiple(() =>
        {
            Assert.That(lfHint, Is.Not.Null);
            Assert.That(crlfHint, Is.EqualTo(lfHint));
        });
    }

    [Test]
    public void Reports_an_output_failure_when_its_identity_also_fails()
    {
        var run = Run(
            "class BrokenOutput { }\nclass HealthyOutput { }",
            new OutputFailureGenerator());

        Assert.Multiple(() =>
        {
            Assert.That(run.Result.Exception, Is.Null);
            Assert.That(
                run.Result.Diagnostics.Select(static value => value.Id),
                Is.EqualTo(new[] { "MORPH0057" }));
            Assert.That(
                run.Result.Diagnostics.Single().Location,
                Is.EqualTo(Location.None));
            Assert.That(
                run.Result.Diagnostics.Single().Properties["ExceptionType"],
                Is.EqualTo(typeof(TestGeneratorException).FullName));
            Assert.That(
                run.Result.Diagnostics.Single().Properties[
                    "ExceptionDetails"],
                Is.EqualTo(ExceptionDetails));
            Assert.That(
                SnapshotSources(run.Result),
                Is.EqualTo(new[]
                {
                    new GeneratedSource(
                        "HealthyOutput.g.cs",
                        NormalizeExpected(HealthyOutputOutput)),
                    new GeneratedSource(
                        OutputFailureHintName,
                        NormalizeExpected(OutputFailureReport))
                }));
        });
    }

    [Test]
    public void Reports_an_initialization_failure_and_emits_the_report()
    {
        var run = Run(
            "class Input { }",
            new InitializationFailureGenerator());

        Assert.Multiple(() =>
        {
            Assert.That(run.Result.Exception, Is.Null);
            Assert.That(
                run.Result.Diagnostics.Select(static value => value.Id),
                Is.EqualTo(new[] { "MORPH0057" }));
            Assert.That(
                SnapshotSources(run.Result),
                Is.EqualTo(new[]
                {
                    new GeneratedSource(
                        InitializationFailureHintName,
                        NormalizeExpected(InitializationFailureReport))
                }));
        });
    }

    [Test]
    public void Coalesces_repeated_locationless_failures_with_a_report()
    {
        var run = Run(
            "class BrokenOne { }\n" +
            "class BrokenTwo { }\n" +
            "class HealthyOutput { }",
            new LocationlessFailureGenerator());

        Assert.Multiple(() =>
        {
            Assert.That(run.Result.Exception, Is.Null);
            Assert.That(
                run.Result.Diagnostics.Select(static value => value.Id),
                Is.EqualTo(new[] { "MORPH0057" }));
            Assert.That(
                run.Result.Diagnostics.Single().Location,
                Is.EqualTo(Location.None));
            Assert.That(
                SnapshotSources(run.Result),
                Is.EqualTo(new[]
                {
                    new GeneratedSource(
                        "HealthyOutput.g.cs",
                        NormalizeExpected(HealthyOutputOutput)),
                    new GeneratedSource(
                        LocationlessFailureHintName,
                        NormalizeExpected(LocationlessFailureReport))
                }));
        });
    }

    [Test]
    public void Reports_a_value_failure_and_supplies_the_fallback()
    {
        var run = Run(
            "class Input { }",
            new ValueFailureGenerator());

        Assert.Multiple(() =>
        {
            Assert.That(run.Result.Exception, Is.Null);
            Assert.That(
                run.Result.Diagnostics.Select(static value => value.Id),
                Is.EqualTo(new[] { "MORPH0057" }));
            Assert.That(
                SnapshotSources(run.Result),
                Is.EqualTo(new[]
                {
                    new GeneratedSource(
                        "FallbackOutput.g.cs",
                        NormalizeExpected(FallbackOutput)),
                    new GeneratedSource(
                        ValueFailureHintName,
                        NormalizeExpected(ValueFailureReport))
                }));
        });
    }

    [Test]
    public void Escapes_a_comment_terminator_in_the_failure_report()
    {
        var run = Run(
            "class Input { }",
            new CommentTerminatorFailureGenerator());

        Assert.Multiple(() =>
        {
            Assert.That(run.Result.Exception, Is.Null);
            Assert.That(
                run.Result.Diagnostics.Select(static value => value.Id),
                Is.EqualTo(new[] { "MORPH0057" }));
            Assert.That(
                SnapshotSources(run.Result),
                Is.EqualTo(new[]
                {
                    new GeneratedSource(
                        CommentTerminatorFailureHintName,
                        NormalizeExpected(
                            CommentTerminatorFailureReport))
                }));
        });
    }

    [Test]
    public void Propagates_requested_cancellation()
    {
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();

        Assert.That(
            () => GeneratorStageGuard.Execute<int, int>(
                0,
                "TestCancellation",
                static (_, token) =>
                    throw new OperationCanceledException(token),
                static _ => Location.None,
                cancellation.Token),
            Throws.InstanceOf<OperationCanceledException>());
    }

    [Test]
    public void Reports_an_unrequested_cancellation()
    {
        var result = GeneratorStageGuard.Execute<int, int>(
            0,
            "TestUnrequestedCancellation",
            static (_, _) =>
                throw new OperationCanceledException(
                    CancellationToken.None),
            static _ => Location.None,
            CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.IsSuccess, Is.False);
            Assert.That(
                result.Failure.ExceptionType,
                Is.EqualTo(
                    typeof(OperationCanceledException).FullName));
        });
    }

    [Test]
    public void Propagates_fatal_failures()
    {
        Assert.Multiple(() =>
        {
            AssertFatalFailure(new OutOfMemoryException());
            AssertFatalFailure(new StackOverflowException());
            AssertFatalFailure(new AccessViolationException());
        });
    }

    [Test]
    public void A_location_failure_does_not_hide_the_stage_failure()
    {
        var result = GeneratorStageGuard.Execute<int, int>(
            0,
            "TestLocationFailure",
            static (_, _) => throw new TestGeneratorException(),
            static _ => throw new InvalidOperationException(
                "location failed"),
            CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.IsSuccess, Is.False);
            Assert.That(
                result.Failure.ExceptionType,
                Is.EqualTo(typeof(TestGeneratorException).FullName));
            Assert.That(result.Failure.Location, Is.EqualTo(Location.None));
        });
    }

    private static TestRun Run(
        string source,
        IIncrementalGenerator generator,
        GeneratorDriver? driver = null,
        string sourcePath = "TestCase.cs")
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.CSharp9);
        var syntaxTree = CSharpSyntaxTree.ParseText(
            SourceText.From(source, Encoding.UTF8),
            parseOptions,
            sourcePath);
        var compilation = CSharpCompilation.Create(
            "GeneratorFailureTests",
            [syntaxTree],
            FrameworkReferences,
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));
        driver ??= CSharpGeneratorDriver.Create(
            [generator.AsSourceGenerator()],
            parseOptions: parseOptions);
        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out var outputCompilation,
            out var driverDiagnostics);
        var result = driver.GetRunResult().Results.Single();

        Assert.That(
            driverDiagnostics,
            Has.None.Matches<Diagnostic>(diagnostic =>
                diagnostic.Id is "CS8784" or "CS8785"));
        Assert.That(
            outputCompilation.GetDiagnostics(),
            Has.None.Matches<Diagnostic>(diagnostic =>
                diagnostic.Severity is
                    DiagnosticSeverity.Warning or DiagnosticSeverity.Error));

        return new TestRun(driver, result, syntaxTree);
    }

    private static void AssertFatalFailure(Exception exception)
    {
        Assert.That(
            () => GeneratorStageGuard.Execute<int, int>(
                0,
                "TestFatalFailure",
                (_, _) => throw exception,
                static _ => Location.None,
                CancellationToken.None),
            Throws.TypeOf(exception.GetType()));
    }

    private static GeneratedSource[] SnapshotSources(
        GeneratorRunResult result)
    {
        return result.GeneratedSources
            .Select(static source => new GeneratedSource(
                source.HintName,
                source.SourceText.ToString()))
            .OrderBy(static source => source.HintName, StringComparer.Ordinal)
            .ToArray();
    }

    private static string NormalizeExpected(string source) =>
        source.Replace("\r\n", "\n")
            .Replace('\r', '\n')
            .Replace("\n", "\r\n") +
        "\r\n";

    private static ImmutableArray<MetadataReference>
        BuildFrameworkReferences()
    {
        var trustedPlatformAssemblies =
            (string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ??
            throw new InvalidOperationException(
                "Trusted platform assemblies are unavailable.");

        return trustedPlatformAssemblies
            .Split(Path.PathSeparator)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Select(static path =>
                (MetadataReference)MetadataReference.CreateFromFile(path))
            .ToImmutableArray();
    }

    private sealed class TransformFailureGenerator : IIncrementalGenerator
    {
        public void Initialize(
            IncrementalGeneratorInitializationContext context)
        {
            var candidates = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is ClassDeclarationSyntax,
                    static (syntaxContext, _) => new Candidate(
                        (ClassDeclarationSyntax)syntaxContext.Node))
                .WithComparer(CandidateComparer.Instance);
            var outputs = GeneratorStageGuard.Select(
                context,
                candidates,
                "TestTransform",
                Transform,
                static candidate =>
                    candidate.Declaration.Identifier.GetLocation());

            context.RegisterSourceOutput(
                outputs,
                static (productionContext, output) =>
                    productionContext.AddSource(
                        output.Name + ".g.cs",
                        SourceText.From(
                            output.Source,
                            Encoding.UTF8)));
        }

        private static TestOutput Transform(
            Candidate candidate,
            CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var name = candidate.Declaration.Identifier.ValueText;

            if (name.StartsWith("Broken", StringComparison.Ordinal))
            {
                throw new TestGeneratorException();
            }

            return new TestOutput(name, BuildGeneratedOutput(name));
        }
    }

    private sealed class OutputFailureGenerator : IIncrementalGenerator
    {
        public void Initialize(
            IncrementalGeneratorInitializationContext context)
        {
            var outputs = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntaxContext, _) =>
                    ((ClassDeclarationSyntax)syntaxContext.Node)
                    .Identifier.ValueText);

            GeneratorStageGuard.RegisterSourceOutput(
                context,
                outputs,
                "TestOutput",
                static name => name.StartsWith(
                    "Broken",
                    StringComparison.Ordinal)
                        ? throw new InvalidOperationException(
                            "identity failed")
                        : name,
                static (productionContext, name) =>
                {
                    if (name.StartsWith("Broken", StringComparison.Ordinal))
                    {
                        throw new TestGeneratorException();
                    }

                    productionContext.AddSource(
                        name + ".g.cs",
                        SourceText.From(
                            BuildGeneratedOutput(name),
                            Encoding.UTF8));
                });
        }
    }

    private sealed class LocationlessFailureGenerator :
        IIncrementalGenerator
    {
        public void Initialize(
            IncrementalGeneratorInitializationContext context)
        {
            var names = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (syntaxContext, _) =>
                    ((ClassDeclarationSyntax)syntaxContext.Node)
                    .Identifier.ValueText);
            var outputs = GeneratorStageGuard.Select(
                context,
                names,
                "TestLocationlessTransform",
                static (name, _) => name.StartsWith(
                    "Broken",
                    StringComparison.Ordinal)
                        ? throw new TestGeneratorException()
                        : new TestOutput(
                            name,
                            BuildGeneratedOutput(name)),
                static _ => Location.None);

            context.RegisterSourceOutput(
                outputs,
                static (productionContext, output) =>
                    productionContext.AddSource(
                        output.Name + ".g.cs",
                        SourceText.From(
                            output.Source,
                            Encoding.UTF8)));
        }
    }

    private static string BuildGeneratedOutput(string name)
    {
        return "// <auto-generated />\r\n" +
               "#nullable enable\r\n\r\n" +
               "// " + name + "\r\n";
    }

    private sealed class InitializationFailureGenerator :
        IIncrementalGenerator
    {
        public void Initialize(
            IncrementalGeneratorInitializationContext context)
        {
            try
            {
                throw new TestGeneratorException();
            }
            catch (Exception exception) when (
                GeneratorStageGuard.CanReport(
                    exception,
                    CancellationToken.None))
            {
                GeneratorStageGuard.RegisterInitializationFailure(
                    context,
                    "TestInitialize",
                    exception);
            }
        }
    }

    private sealed class ValueFailureGenerator : IIncrementalGenerator
    {
        public void Initialize(
            IncrementalGeneratorInitializationContext context)
        {
            var value = GeneratorStageGuard.Select<Compilation, int>(
                context,
                context.CompilationProvider,
                "TestValueTransform",
                static (_, _) => throw new TestGeneratorException(),
                fallback: 42);

            context.RegisterSourceOutput(
                value,
                static (productionContext, fallback) =>
                    productionContext.AddSource(
                        "FallbackOutput.g.cs",
                        SourceText.From(
                            "// <auto-generated />\r\n" +
                            "#nullable enable\r\n\r\n" +
                            "// Fallback: " + fallback + "\r\n",
                            Encoding.UTF8)));
        }
    }

    private sealed class CommentTerminatorFailureGenerator :
        IIncrementalGenerator
    {
        public void Initialize(
            IncrementalGeneratorInitializationContext context)
        {
            GeneratorStageGuard.RegisterInitializationFailure(
                context,
                "TestCommentTerminator",
                new CommentTerminatorException());
        }
    }

    private sealed class TestGeneratorException : Exception
    {
        public TestGeneratorException()
            : base("deliberate failure")
        {
        }

        public override string ToString() => ExceptionDetails;
    }

    private sealed class CommentTerminatorException : Exception
    {
        public CommentTerminatorException()
            : base("before */ after")
        {
        }

        public override string ToString() =>
            "CommentTerminatorException: before */ after";
    }

    private sealed class CandidateComparer : IEqualityComparer<Candidate>
    {
        public static CandidateComparer Instance { get; } = new();

        public bool Equals(Candidate left, Candidate right)
        {
            return StringComparer.Ordinal.Equals(
                left.Declaration.ToFullString(),
                right.Declaration.ToFullString());
        }

        public int GetHashCode(Candidate value)
        {
            return StringComparer.Ordinal.GetHashCode(
                value.Declaration.ToFullString());
        }
    }

    private readonly record struct Candidate(
        ClassDeclarationSyntax Declaration);

    private readonly record struct TestOutput(
        string Name,
        string Source);

    private readonly record struct TestRun(
        GeneratorDriver Driver,
        GeneratorRunResult Result,
        SyntaxTree InputTree);

    private readonly record struct GeneratedSource(
        string HintName,
        string Source);
}
