namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Tuples;

internal sealed partial class TuplesTests
{
    [Test]
    [Description("The logical Item8 member corresponds to an element inside System.Tuple.Rest.")]
    public void LongSystemTupleOverridesAnElementInsideRest()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using Morphant;
using Morphant.Context;

namespace TestCase
{
    public sealed class Source
    {
        public int Id => 7;
        public string Name => "from convention";
        public int Item1 => 7;
        public string Item2 => "from convention";
        public string FromConstruct() => "from constructor";
        public string FromMembers() => "from members";
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Tuple<int, int, int, int, int, int, int, Tuple<int, int>>>()
                .MemberSelection(MemberSelection.Explicit)
                .Construct(_ => new(1, 2, 3, 4, 5, 6, 7, 8, 9))
                .Members(source => new() { Item8 = source.Id + 100 });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.Mapper__b93622f58bb33946b8901b3146112f51.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>>>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>>)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>> global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>>>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>> global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>>>.Update(
            global::TestCase.Source? source,
            global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>>? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>> __Create(
            global::TestCase.Source source)
        {
            int item8 = 8;
            item8 = source.Id + 100;

            return new global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>>(
                item1: 1,
                item2: 2,
                item3: 3,
                item4: 4,
                item5: 5,
                item6: 6,
                item7: 7,
                rest: new global::System.Tuple<int, int>(
                    item1: item8,
                    item2: 9));
        }

        private global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>> __Update(
            global::System.Tuple<int, int, int, int, int, int, int, global::System.Tuple<int, int>> destination)
        {
            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: LongSystemTupleOverridesAnElementInsideRestSurfaces);
    }
}
