namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Tuples;

internal sealed partial class TuplesTests
{
    [Test]
    [Description("Resolve preserves initial ValueTuple element reads before member changes on both reuse and replacement.")]
    public void ResolveValueTupleWithCrossElementReads()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using Morphant;
using Morphant.Context;

namespace TestCase
{
    public sealed class Source
    {
        public bool Reuse { get; set; }
        public int Id => 7;
        public string Name => "from convention";
        public int Item1 => 7;
        public string Item2 => "from convention";
        public string FromConstruct() => "from constructor";
        public string FromMembers() => "from members";
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, (int Id, string Name)>()
                .MemberSelection(MemberSelection.Explicit)
                .Resolve((source, previous) =>
                {
                    if (previous.TryGetValue(out var current) && source.Reuse)
                        return current;
                    return new(source.Id, source.FromConstruct());
                })
                .Members((source, previous, result) => new()
                {
                    Id = result.Name.Length,
                    Name = result.Id.ToString()
                });
    }
}
""";

        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.Mapper__b93622f58bb33946b8901b3146112f51.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof((int Id, string Name))) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        (int Id, string Name) global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source);
        }

        /// <inheritdoc/>
        (int Id, string Name) global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>.Update(
            global::TestCase.Source? source,
            (int Id, string Name) destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Update(source, destination);
        }

        private (int Id, string Name) __Create(
            global::TestCase.Source source)
        {
            (int Id, string Name) result = (
                Id: source.Id,
                Name: source.FromConstruct());

            int id = result.Name.Length;
            string name = result.Id.ToString();

            result.Id = id;
            result.Name = name;

            return result;
        }

        private (int Id, string Name) __Update(
            global::TestCase.Source source,
            (int Id, string Name) destination)
        {
            if (source.Reuse)
            {
                int id = destination.Name.Length;
                string name = destination.Id.ToString();

                destination.Id = id;
                destination.Name = name;

                return destination;
            }
            else
            {
                (int Id, string Name) result = (
                    Id: source.Id,
                    Name: source.FromConstruct());

                int id = result.Name.Length;
                string name = result.Id.ToString();

                result.Id = id;
                result.Name = name;

                return result;
            }
        }
    }
}
""")
            ],
            expectedSurfaces: ValueTupleWithDifferentExpressionsForOneElementSurfaces);
    }
}
