namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Tuples;

internal sealed partial class TuplesTests
{
    [Test]
    [Description("One element is computed from another element supplied by Construct.")]
    public void SystemTupleReadingAnotherInitialElement()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using Morphant;
using Morphant.Context;

namespace TestCase
{
    public sealed class Source
    {
        public int Id => 7;
        public string Name => "from convention";
        public int Item1 => 7;
        public string Item2 => "from convention";
        public string FromConstruct() => "from constructor";
        public string FromMembers() => "from members";
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Tuple<int, string>>()
                .MemberSelection(MemberSelection.Explicit)
                .Construct(source => new(Auto(), source.FromConstruct()))
                .Members((source, previous, result) => new() { Item1 = result.Item2.Length });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, string>>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::System.Tuple<int, string>)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::System.Tuple<int, string> global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, string>>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, global::Morphant.Context.MappingOperation.Create, context);
        }

        /// <inheritdoc/>
        global::System.Tuple<int, string> global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, string>>.Update(
            global::TestCase.Source? source,
            global::System.Tuple<int, string>? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, global::Morphant.Context.MappingOperation.Update, context);
            }

            return __Update(source, destination, context);
        }

        private global::System.Tuple<int, string> __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingOperation operation,
            global::Morphant.Context.MappingContext context)
        {
            throw new global::Morphant.Exceptions.MappingConfigurationException(
                operation,
                typeof(global::TestCase.Source),
                typeof(global::System.Tuple<int, string>),
                "This Construct or Resolve expression is not supported.");
        }

        private global::System.Tuple<int, string> __Update(
            global::TestCase.Source source,
            global::System.Tuple<int, string> destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: SystemTupleWithDifferentExpressionsForOneElementSurfaces,
            expectedDiagnostics: """
MORPH0037 Error: Rule for constructor parameter 'Item1' is invalid in mapping 'TestCase.Source -> System.Tuple<int, string>': Auto could not find exactly one compatible source member.
  at TestCase.cs(25,42-25,46); <no source>
""");
    }
}
