namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Tuples;

internal sealed partial class TuplesTests
{
    [Test]
    [Description("The tuple constructor element is ignored while Members provides a value.")]
    public void ValueTupleWithIgnoredConstructorAndExplicitMember()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using Morphant;
using Morphant.Context;

namespace TestCase
{
    public sealed class Source
    {
        public int Id => 7;
        public string Name => "from convention";
        public int Item1 => 7;
        public string Item2 => "from convention";
        public string FromConstruct() => "from constructor";
        public string FromMembers() => "from members";
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, (int Id, string Name)>()
                .MemberSelection(MemberSelection.Explicit)
                .Construct(source => new(source.Id, Ignore()))
                .Members(source => new() { Name = source.FromMembers() });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof((int Id, string Name))) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        (int Id, string Name) global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        (int Id, string Name) global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>.Update(
            global::TestCase.Source? source,
            (int Id, string Name) destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Update(source, destination, context);
        }

        private (int Id, string Name) __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return (Id: source.Id, Name: source.FromMembers());
        }

        private (int Id, string Name) __Update(
            global::TestCase.Source source,
            (int Id, string Name) destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Name = source.FromMembers();

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: ValueTupleWithDifferentExpressionsForOneElementSurfaces);
    }
}
