<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>9.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(MorphantGeneratedFilesPath)</CompilerGeneratedFilesOutputPath>
        <MorphantUnmappedMemberValidation>Strict</MorphantUnmappedMemberValidation>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="MorphantUnmappedMemberValidation" />
        <Reference Include="Morphant">
            <HintPath>$(MorphantRuntimePath)</HintPath>
            <Private>false</Private>
        </Reference>
        <Analyzer Include="$(MorphantGeneratorPath)" />
    </ItemGroup>

</Project>
