namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.EvaluationOrder;

internal sealed partial class EvaluationOrderTests
{
    [Test]
    [Description("An automatic constructor uses independent source values before a result-dependent condition.")]
    public void AutomaticConstructorBeforeResultCondition()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using Morphant;
using Morphant.Context;

namespace TestCase
{
    public sealed class Source
    {
        public int Left => 1;
        public int Right => 2;
    }

    public sealed class Destination
    {
        public Destination(int left, int right) { Left = left; Right = right; }
        public int Left { get; set; }
        public int Right { get; set; }
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Members((_, _, result) =>
                {
                    if (result.Left > 0)
                        return new() { Left = 10, Right = 20 };
                    return new() { Left = 30, Right = 40 };
                });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            var result = new global::TestCase.Destination(
                left: source.Left,
                right: source.Right);

            if (result.Left > 0)
            {
                result.Left = 10;
                result.Right = 20;

                return result;
            }
            else
            {
                result.Left = 30;
                result.Right = 40;

                return result;
            }
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            if (destination.Left > 0)
            {
                destination.Left = 10;
                destination.Right = 20;

                return destination;
            }
            else
            {
                destination.Left = 30;
                destination.Right = 40;

                return destination;
            }
        }
    }
}
""")
            ],
            expectedSurfaces: OrdinaryMembersSwapInitialValuesSurfaces);
    }
}
