namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.EvaluationOrder;

internal sealed partial class EvaluationOrderTests
{
    [Test]
    [Description("Passing a struct source as an earlier argument captures its value before a later method mutates the source parameter.")]
    public void ComplexArgumentKeepsEarlierStructCopy()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;
namespace TestCase
{
    public struct Source
    {
        public int Value { get; set; }
        public bool AdvanceAndSelectConstructorValue() { Value++; return true; }
        public int ReadPreferredConstructorValue() => Value + 10;
        public int ReadFallbackConstructorValue() => Value + 20;
    }
    public sealed class Destination
    {
        public Destination(Source original, int value) { Original = original; Value = value; }
        public Source Original { get; }
        public int Value { get; }
    }
    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Construct(source => new(source,
                    source.AdvanceAndSelectConstructorValue()
                        ? source.ReadPreferredConstructorValue()
                        : source.ReadFallbackConstructorValue()));
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.Mapper__b93622f58bb33946b8901b3146112f51.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
            => __Create(source);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (destination is null)
            {
                return __Create(source);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source)
        {
            return new global::TestCase.Destination(
                original: source,
                value: source.AdvanceAndSelectConstructorValue()
                    ? source.ReadPreferredConstructorValue()
                    : source.ReadFallbackConstructorValue());
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Destination destination)
        {
            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: ComplexArgumentKeepsEarlierStructCopySurfaces);
    }
}
