namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.EvaluationOrder;

internal sealed partial class EvaluationOrderTests
{
    [Test]
    [Description("Long single-line switches retain their layout in user locals, arguments and members.")]
    public void LongSingleLineSwitchesKeepTheirLayout()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public bool Enabled => true;
        public int Read(int value) => value;
    }

    public sealed class Destination
    {
        public Destination(int first, int value) { First = first; Value = value; }
        public int First { get; }
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Construct(source =>
                {
                    var first = source.Enabled switch { true => source.Read(source.Read(1) + source.Read(2)), false => source.Read(source.Read(3) + source.Read(4)) };
                    return new(first, source.Read(source.Enabled switch { true => source.Read(source.Read(5)), false => source.Read(source.Read(6)) }));
                })
                .Members(source => new()
                {
                    Value = (source.Enabled switch { true => source.Read(source.Read(7) + source.Read(8)), false => source.Read(source.Read(9) + source.Read(10)) })
                });
    }
}
""";

        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
                ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
                // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            var first = source.Enabled switch { true => source.Read(source.Read(1) + source.Read(2)), false => source.Read(source.Read(3) + source.Read(4))};

            return new global::TestCase.Destination(
                first: first,
                value: source.Read(source.Enabled switch { true => source.Read(source.Read(5)), false => source.Read(source.Read(6))}))
            {
                Value = source.Enabled switch { true => source.Read(source.Read(7) + source.Read(8)), false => source.Read(source.Read(9) + source.Read(10))}
            };
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Value = source.Enabled switch { true => source.Read(source.Read(7) + source.Read(8)), false => source.Read(source.Read(9) + source.Read(10))};

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: ComplexConstructorValuesKeepIndependentMemberEvaluationSurfaces);
    }
}
