namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.EvaluationOrder;

internal sealed partial class EvaluationOrderTests
{
    [Test]
    [Description("A result-dependent branch cannot supply the constructor needed to evaluate that branch.")]
    public void ResultConditionWithoutIndependentConstructorValues()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using Morphant;
using Morphant.Context;

namespace TestCase
{
    public sealed class Source
    {
        
    }

    public sealed class Destination
    {
        public Destination(int left, int right) { Left = left; Right = right; }
        public int Left { get; set; }
        public int Right { get; set; }
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Members((_, _, result) =>
                {
                    if (result.Left > 0)
                        return new() { Left = 10, Right = 20 };
                    return new() { Left = 30, Right = 40 };
                });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, global::Morphant.Context.MappingOperation.Create, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, global::Morphant.Context.MappingOperation.Update, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingOperation operation,
            global::Morphant.Context.MappingContext context)
        {
            throw new global::Morphant.Exceptions.MappingConfigurationException(
                operation,
                typeof(global::TestCase.Source),
                typeof(global::TestCase.Destination),
                "This member cannot be assigned in this Create or Update case.");
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            if (destination.Left > 0)
            {
                destination.Left = 10;
                destination.Right = 20;

                return destination;
            }

            destination.Left = 30;
            destination.Right = 40;

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: OrdinaryMembersSwapInitialValuesSurfaces,
            expectedDiagnostics: """
MORPH0042 Error: Rule for destination member 'Left' cannot be applied in mapping 'TestCase.Source -> TestCase.Destination': member rule uses 'result' before the destination is created; its value is required by constructor parameter 'left'. Affected cases: Create; Update without an existing destination.
  at TestCase.cs(29,40-29,44); TestCase.cs(28,25-28,31)
MORPH0042 Error: Rule for destination member 'Right' cannot be applied in mapping 'TestCase.Source -> TestCase.Destination': member rule uses 'result' before the destination is created; its value is required by constructor parameter 'right'. Affected cases: Create; Update without an existing destination.
  at TestCase.cs(29,51-29,56); TestCase.cs(28,25-28,31)
""");
    }
}
