namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.EvaluationOrder;

internal sealed partial class EvaluationOrderTests
{
    [TestCase(false)]
    [TestCase(true)]
    [Description("Preserves user-written computation structure and C# evaluation order.")]
    public void UserComputationsKeepTheirWrittenPositions(bool multiline)
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public bool Enabled => true;
        public int Read(int value) => value;
    }

    public sealed class Destination
    {
        public Destination(int first, int value) { First = first; Value = value; }
        public int First { get; }
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Construct(source => new(
                    source.Read(source.Read(1)) + 2,
                    source.Enabled switch { true => source.Read(3),__BREAK__false => source.Read(4) }))
                .Members(source => new()
                {
                    Value = source.Enabled__BREAK__? source.Read(5) : source.Read(6)
                });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source.Replace("__BREAK__", multiline ? "\n" : " "),
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination(
                first: source.Read(source.Read(1)) + 2,
                value: source.Enabled switch
                {
                    true => source.Read(3),
                    false => source.Read(4)
                })
            {
                Value = source.Enabled ? source.Read(5) : source.Read(6)
            };
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Value = source.Enabled ? source.Read(5) : source.Read(6);

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: ComplexConstructorValuesKeepIndependentMemberEvaluationSurfaces);
    }
}
