namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.StructuredResults;

internal sealed partial class StructuredResultsTests
{
    [Test]
    public void ResolveEnumSwitch()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;
using Construction = Morphant.Generated.N_78409e4ae9aaeef534a067d95eb70f27.DestinationConstruction;
namespace TestCase
{
    public enum Choice { First, Second }
    public sealed class Source
    {
        public bool Reuse => true;
        public string Name => "from convention";
        public string FromConstruct() => "from constructor";
        public string FromMembers() => "from members";
        public Choice Choice => (Choice)2;
    }
    public sealed class Destination
    {
        public Destination(string name) => Name = name;
        public string Name { get; set; }
    }
    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Resolve((source, previous) =>
                {
                    if (previous.TryGetValue(out var existing) && source.Reuse) return existing;
                    Construction selected = source.Choice switch
                    {
                        Choice.First => new Construction(source.FromConstruct()),
                        Choice.Second => new Construction(source.FromMembers())
                    };
                    return selected;
                })
                .Members(source => new() { Name = source.Name });
    }
}
""";
        ConstructionAndMembersSnapshot.Verify(source, expectedMappers:
        [
            ("Morphant.Generated.TypeMapper.Mapper__b93622f58bb33946b8901b3146112f51.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, global::Morphant.Context.MappingOperation.Create, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, global::Morphant.Context.MappingOperation.Update, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingOperation operation)
        {
            _ = global::Morphant.Option<global::TestCase.Destination>.None.TryGetValue(out global::TestCase.Destination? existing) && source.Reuse;

            var selected = source.Choice;

            switch (selected)
            {
                case global::TestCase.Choice.First:
                {
                    return __Construct(source);
                }
                case global::TestCase.Choice.Second:
                {
                    return __Construct1(source);
                }
            }

            throw new global::Morphant.Exceptions.UnmatchedMappingSwitchException(operation, typeof(global::TestCase.Source), typeof(global::TestCase.Destination));
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination)
        {
            if (global::Morphant.Option<global::TestCase.Destination>.Some(destination).TryGetValue(out global::TestCase.Destination? existing) && source.Reuse)
            {
                destination.Name = source.Name;

                return destination;
            }

            var selected = source.Choice;

            switch (selected)
            {
                case global::TestCase.Choice.First:
                {
                    return __Construct(source);
                }
                case global::TestCase.Choice.Second:
                {
                    return __Construct1(source);
                }
            }

            throw new global::Morphant.Exceptions.UnmatchedMappingSwitchException(global::Morphant.Context.MappingOperation.Update, typeof(global::TestCase.Source), typeof(global::TestCase.Destination));
        }

        private global::TestCase.Destination __Construct(
            global::TestCase.Source source)
        {
            return new global::TestCase.Destination(
                name: source.FromConstruct())
            {
                Name = source.Name
            };
        }

        private global::TestCase.Destination __Construct1(
            global::TestCase.Source source)
        {
            return new global::TestCase.Destination(
                name: source.FromMembers())
            {
                Name = source.Name
            };
        }
    }
}
""")
        ], expectedSurfaces: Surfaces, expectedDiagnostics:
"""
CS8524 Warning: The switch expression does not handle some values of its input type (it is not exhaustive) involving an unnamed enum value. For example, the pattern '(TestCase.Choice)2' is not covered.
  at TestCase.cs(29,59-29,65)
""");
    }
}
