using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.MemberSurfaceTests;

[TestFixture]
internal sealed class MemberSurfaceMemberTests
{
    [Test]
    public async Task Includes_the_supported_property_and_field_matrix()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }

    public interface IExplicitMember
    {
        int Explicit { get; set; }
    }

    public class Destination : IExplicitMember
    {
        public required string RequiredSet { get; set; }

        public required string RequiredInit { get; init; }

        public required int RequiredField;

        public int MutableField = 0;

        public bool WriteOnly
        {
            set { }
        }

        public decimal PrivateGetter { private get; set; }

        public int ReadOnlyProperty { get; }

        public int PrivateSetter { get; private set; }

        public int ProtectedSetter { get; protected set; }

        public static int StaticProperty { get; set; }

        public const int ConstantField = 0;

        public readonly int ReadOnlyField;

        public int this[int index]
        {
            get => index;
            set { }
        }

        int IExplicitMember.Explicit { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string members =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes member mappings for <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.Destination.RequiredSet"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> RequiredSet
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.Destination.RequiredInit"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> RequiredInit
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.Destination.RequiredField"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> RequiredField
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.Destination.MutableField"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> MutableField
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.Destination.WriteOnly"/>.
        /// </summary>
        public global::Morphant.Members.Member<bool> WriteOnly
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.Destination.PrivateGetter"/>.
        /// </summary>
        public global::Morphant.Members.Member<decimal> PrivateGetter
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures mappings for destination members from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="members">A lambda expression that receives the non-null source and the optional existing destination and describes destination member mappings.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::System.Func<global::TestCase.Source, global::Morphant.Option<global::TestCase.Destination>, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures mappings for destination members with access to the selected mapping result.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="members">A lambda expression that receives the non-null source, the optional existing destination, and the non-null selected result and describes destination member mappings.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::System.Func<global::TestCase.Source, global::Morphant.Option<global::TestCase.Destination>, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        await MemberSurfaceGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            (
                "Morphant.Generated.Member.TestCase_Destination.g.cs",
                members
            ),
            (
                "Morphant.Generated.MemberExtension.TestCase_Source__TestCase_Destination.g.cs",
                extension
            ));
    }
}
