<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>$(MorphantStrongNameKeyFile)</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Morphant\Morphant.csproj" />
    </ItemGroup>

</Project>
