<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Morphant.TestRuntimeV2</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyMetadata Include="Morphant.GeneratorContractVersion"
                          Value="2" />
    </ItemGroup>

</Project>
