using Microsoft.CodeAnalysis;

namespace Morphant.Generator.UnitTests.MappingCompositionTests;

[TestFixture]
internal sealed class RecoveryAndActualizationTests
{
    [Test]
    public void Suppressed_duplicate_generates_the_exact_throwing_contract()
    {
        // lang=c#
        const string source =
"""
#nullable enable

using Morphant;

#pragma warning disable CS1591

namespace TestCase;

public sealed class Source { }
public sealed class Destination { }

[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Construct(source => new())
            .Resolve((source, previous) => new());
}
""";

        // lang=c#
        const string expectedConstruction =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Defines construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        public DestinationConstruction(global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        public DestinationConstruction()
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::TestCase.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedMappingExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination construction when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::TestCase.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination construction using the current operation.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::TestCase.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines how to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Resolve(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination selection using the current operation.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Resolve(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::TestCase.Morphant.Generated.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to construct a destination when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> ConstructUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::TestCase.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to construct a destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> ConstructUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::TestCase.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> ResolveUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> ResolveUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination and context as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedTypeMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
            => throw new global::Morphant.Exceptions.MappingConfigurationException(
                global::Morphant.Context.MappingOperation.Create,
                typeof(global::TestCase.Source),
                typeof(global::TestCase.Destination),
                "The mapping configuration is invalid: Construct or Resolve is configured more than once.");

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
            => throw new global::Morphant.Exceptions.MappingConfigurationException(
                global::Morphant.Context.MappingOperation.Update,
                typeof(global::TestCase.Source),
                typeof(global::TestCase.Destination),
                "The mapping configuration is invalid: Construct or Resolve is configured more than once.");
    }
}
""";

        var result = MappingCompositionGeneratorTest.Run(
            source,
            diagnosticOptions: new Dictionary<string, ReportDiagnostic>
            {
                ["MORPH0019"] = ReportDiagnostic.Suppress
            });

        Assert.Multiple(() =>
        {
            Assert.That(result.EffectiveDiagnostics, Is.Empty);
            Assert.That(
                result.GeneratedSources.Select(static generated =>
                    (generated.HintName,
                        generated.SourceText.ToString())),
                Is.EqualTo(new[]
                {
                    (
                        "Morphant.Generated.Construction." +
                        "TestCase_Destination.g.cs",
                        NormalizeExpected(expectedConstruction)),
                    (
                        "Morphant.Generated.MappingExtension." +
                        "TestCase_Source__TestCase_Destination.g.cs",
                        NormalizeExpected(expectedMappingExtension)),
                    (
                        "Morphant.Generated.TypeMapper." +
                        "TestCase_TestMapper.g.cs",
                        NormalizeExpected(expectedTypeMapper))
                }));
            Assert.That(result.CompilerWarningsAndErrors, Is.Empty);
        });
    }

    [TestCase("MORPH0019")]
    [TestCase("MORPH0020")]
    public void Suppression_and_severity_change_only_presentation(string id)
    {
        var source = id == "MORPH0019"
            ? DuplicateSource
            : MixedSource;
        var visible = MappingCompositionGeneratorTest.Run(source);
        var suppressed = MappingCompositionGeneratorTest.Run(
            source,
            diagnosticOptions: new Dictionary<string, ReportDiagnostic>
            {
                [id] = ReportDiagnostic.Suppress
            });
        var warning = MappingCompositionGeneratorTest.Run(
            source,
            diagnosticOptions: new Dictionary<string, ReportDiagnostic>
            {
                [id] = ReportDiagnostic.Warn
            });

        Assert.Multiple(() =>
        {
            Assert.That(
                visible.Diagnostics.Select(static diagnostic => diagnostic.Id),
                Is.EqualTo(new[] { id }));
            Assert.That(suppressed.EffectiveDiagnostics, Is.Empty);
            Assert.That(
                warning.EffectiveDiagnostics.Single().Severity,
                Is.EqualTo(DiagnosticSeverity.Warning));
            Assert.That(Artifacts(suppressed), Is.EqualTo(Artifacts(visible)));
            Assert.That(Artifacts(warning), Is.EqualTo(Artifacts(visible)));
            Assert.That(visible.CompilerWarningsAndErrors, Is.Empty);
            Assert.That(suppressed.CompilerWarningsAndErrors, Is.Empty);
            Assert.That(warning.CompilerWarningsAndErrors, Is.Empty);
        });
    }

    [Test]
    public void One_driver_actualizes_every_slot_conflict_and_restores()
    {
        var validResult = MappingCompositionGeneratorTest.Run(ValidResultSource);
        var duplicateResult = MappingCompositionGeneratorTest.Run(
            DuplicateSource,
            driver: validResult.Driver);
        var duplicateResultOverload = MappingCompositionGeneratorTest.Run(
            DuplicateResultOverloadSource,
            driver: duplicateResult.Driver);
        var duplicateMembers = MappingCompositionGeneratorTest.Run(
            DuplicateMembersSource,
            driver: duplicateResultOverload.Driver);
        var duplicateConvert = MappingCompositionGeneratorTest.Run(
            DuplicateConvertSource,
            driver: duplicateMembers.Driver);
        var declarativeThenConvert = MappingCompositionGeneratorTest.Run(
            MixedSource,
            driver: duplicateConvert.Driver);
        var convertThenDeclarative = MappingCompositionGeneratorTest.Run(
            ReorderedMixedSource,
            driver: declarativeThenConvert.Driver);
        var restored = MappingCompositionGeneratorTest.Run(
            ValidConvertSource,
            driver: convertThenDeclarative.Driver);

        Assert.Multiple(() =>
        {
            Assert.That(validResult.Diagnostics, Is.Empty);
            AssertDiagnostic(duplicateResult, "MORPH0019", "Resolve");
            AssertDiagnostic(
                duplicateResultOverload,
                "MORPH0019",
                "Construct");
            AssertDiagnostic(duplicateMembers, "MORPH0019", "Members");
            AssertDiagnostic(duplicateConvert, "MORPH0019", "Convert");
            AssertDiagnostic(declarativeThenConvert, "MORPH0020", "Convert");
            AssertDiagnostic(
                convertThenDeclarative,
                "MORPH0020",
                "ResolveUsing");
            Assert.That(restored.Diagnostics, Is.Empty);
            Assert.That(restored.CompilerWarningsAndErrors, Is.Empty);
        });
    }

    [Test]
    public void Publication_order_is_by_id_mapper_pair_and_location()
    {
        // lang=c#
        const string source =
"""
#nullable enable

using Morphant;

#pragma warning disable CS1591

namespace TestCase;

public sealed class Source { public int Value { get; set; } }
public sealed class DestinationA { public int Value { get; set; } }
public sealed class DestinationB { public int Value { get; set; } }
public sealed class DestinationZ { public int Value { get; set; } }

[MorphantMapper]
public partial class ZMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, DestinationZ>()
            .Convert(source => new DestinationZ())
            .Members(source => new() { Value = source.Value });
}

[MorphantMapper]
public partial class AMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder)
    {
        builder.Map<Source, DestinationB>()
            .Members(source => new() { Value = source.Value })
            .Members(source => new() { Value = source.Value + 1 });

        builder.Map<Source, DestinationA>()
            .Convert(source => new DestinationA())
            .Convert(source => new DestinationA())
            .Construct(source => new());
    }
}
""";

        var result = MappingCompositionGeneratorTest.Run(source);

        Assert.Multiple(() =>
        {
            Assert.That(
                result.Diagnostics.Select(static diagnostic => diagnostic.Id),
                Is.EqualTo(new[]
                {
                    "MORPH0019",
                    "MORPH0019",
                    "MORPH0020",
                    "MORPH0020"
                }));
            Assert.That(
                result.Diagnostics.Select(static diagnostic =>
                    diagnostic.GetMessage()),
                Is.EqualTo(new[]
                {
                    "'Convert' is configured more than once for mapping " +
                    "'TestCase.Source -> TestCase.DestinationA' in mapper " +
                    "'global::TestCase.AMapper'.",
                    "'Members' is configured more than once for mapping " +
                    "'TestCase.Source -> TestCase.DestinationB' in mapper " +
                    "'global::TestCase.AMapper'.",
                    "Convert cannot be combined with Construct, Resolve, or " +
                    "Members for mapping 'TestCase.Source -> " +
                    "TestCase.DestinationA' in mapper " +
                    "'global::TestCase.AMapper'.",
                    "Convert cannot be combined with Construct, Resolve, or " +
                    "Members for mapping 'TestCase.Source -> " +
                    "TestCase.DestinationZ' in mapper " +
                    "'global::TestCase.ZMapper'."
                }));
            Assert.That(result.CompilerWarningsAndErrors, Is.Empty);
        });
    }

    private static void AssertDiagnostic(
        MappingCompositionGeneratorResult result,
        string id,
        string primaryText)
    {
        var diagnostic = result.Diagnostics.Single();

        Assert.That(diagnostic.Id, Is.EqualTo(id));
        Assert.That(
            MappingCompositionGeneratorTest.SourceText(diagnostic.Location),
            Is.EqualTo(primaryText));
        Assert.That(result.CompilerWarningsAndErrors, Is.Empty);
    }

    private static (string HintName, string Source)[] Artifacts(
        MappingCompositionGeneratorResult result)
    {
        return result.GeneratedSources
            .Select(static generated =>
                (generated.HintName, generated.SourceText.ToString()))
            .ToArray();
    }

    private static string NormalizeExpected(string source)
    {
        return source.ReplaceLineEndings("\r\n") + "\r\n";
    }

    // lang=c#
    private const string ValidResultSource =
"""
#nullable enable
using Morphant;
#pragma warning disable CS1591
namespace TestCase;
public sealed class Source { public int Value { get; set; } }
public sealed class Destination { public int Value { get; set; } }
[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Construct(source => new());
}
""";

    // lang=c#
    private const string DuplicateSource =
"""
#nullable enable
using Morphant;
#pragma warning disable CS1591
namespace TestCase;
public sealed class Source { public int Value { get; set; } }
public sealed class Destination { public int Value { get; set; } }
[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Construct(source => new())
            .Resolve((source, previous) => new());
}
""";

    // lang=c#
    private const string DuplicateResultOverloadSource =
"""
#nullable enable
using Morphant;
#pragma warning disable CS1591
namespace TestCase;
public sealed class Source { public int Value { get; set; } }
public sealed class Destination { public int Value { get; set; } }
[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Construct(source => new())
            .Construct((source, context) => new());
}
""";

    // lang=c#
    private const string DuplicateMembersSource =
"""
#nullable enable
using Morphant;
#pragma warning disable CS1591
namespace TestCase;
public sealed class Source { public int Value { get; set; } }
public sealed class Destination { public int Value { get; set; } }
[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Members(source => new() { Value = source.Value })
            .Members(source => new() { Value = source.Value + 1 });
}
""";

    // lang=c#
    private const string DuplicateConvertSource =
"""
#nullable enable
using Morphant;
#pragma warning disable CS1591
namespace TestCase;
public sealed class Source { public int Value { get; set; } }
public sealed class Destination { public int Value { get; set; } }
[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Convert(source => new Destination())
            .Convert((source, previous, context) => new Destination());
}
""";

    // lang=c#
    private const string MixedSource =
"""
#nullable enable
using Morphant;
#pragma warning disable CS1591
namespace TestCase;
public sealed class Source { public int Value { get; set; } }
public sealed class Destination { public int Value { get; set; } }
[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Members(source => new() { Value = source.Value })
            .Convert(source => new Destination());
}
""";

    // lang=c#
    private const string ReorderedMixedSource =
"""
#nullable enable
using Morphant;
#pragma warning disable CS1591
namespace TestCase;
public sealed class Source { public int Value { get; set; } }
public sealed class Destination { public int Value { get; set; } }
[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Convert(source => new Destination())
            .ResolveUsing((source, previous) => new Destination());
}
""";

    // lang=c#
    private const string ValidConvertSource =
"""
#nullable enable
using Morphant;
#pragma warning disable CS1591
namespace TestCase;
public sealed class Source { public int Value { get; set; } }
public sealed class Destination { public int Value { get; set; } }
[MorphantMapper]
public partial class TestMapper : TypeMapper
{
    protected override void Configure(MapperBuilder builder) =>
        builder.Map<Source, Destination>()
            .Convert(source => new Destination());
}
""";
}
