using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.PairConfigurationTests;

[TestFixture]
internal sealed class PairConfigurationBoundaryTests
{
    [Test]
    public async Task Ignores_false_configuration_methods_aliases_helpers_and_branches()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS0219
#pragma warning disable CS1591

using System;
using Morphant;

namespace TestCase
{
    public sealed class Source { }
    public sealed class Destination { }
    public sealed class MembersSource { }
    public sealed class MembersDestination { }
    public sealed class ConvertSource { }
    public sealed class ConvertDestination { }
    public sealed class VisibleSource { }
    public sealed class VisibleDestination { }
    public sealed class AliasSource { }
    public sealed class AliasDestination { }
    public sealed class HelperSource { }
    public sealed class HelperDestination { }
    public sealed class DelegateSource { }
    public sealed class DelegateDestination { }
    public sealed class ConditionalSource { }
    public sealed class ConditionalDestination { }
    public sealed class OtherSource { }
    public sealed class OtherDestination { }

    public sealed class OtherBuilder
    {
        public OtherBuilder Map<TSource, TDestination>() => this;
    }

    public static class OtherConfigurationExtensions
    {
        public static MapperBuilder<TSource, TDestination> Construct<TSource, TDestination>(
            this MapperBuilder<TSource, TDestination> builder,
            int value) => builder;

        public static MapperBuilder<TSource, TDestination> Members<TSource, TDestination>(
            this MapperBuilder<TSource, TDestination> builder,
            int value) => builder;

        public static MapperBuilder<TSource, TDestination> Convert<TSource, TDestination>(
            this MapperBuilder<TSource, TDestination> builder,
            int value) => builder;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            void ConfigureHelper(MapperBuilder value) =>
                value.Map<HelperSource, HelperDestination>();

            var alias = builder.Map<AliasSource, AliasDestination>();
            Action<MapperBuilder> configureDelegate = value =>
                value.Map<DelegateSource, DelegateDestination>();

            ConfigureHelper(builder);
            configureDelegate(builder);

            if (DateTime.UtcNow.Ticks > 0)
            {
                builder.Map<ConditionalSource, ConditionalDestination>();
            }

            new OtherBuilder().Map<OtherSource, OtherDestination>();

            builder.Map<Source, Destination>().Construct(1);
            builder.Map<MembersSource, MembersDestination>().Members(2);
            builder.Map<ConvertSource, ConvertDestination>().Convert(3);
            builder.Map<VisibleSource, VisibleDestination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

// Mappers: 1
// Mapper 0: TestCase.TestMapper
// Unifiable: False
// Root settings: MappingMode=Unset; NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Pairs: 4
// Pair 0: global::TestCase.Source -> global::TestCase.Destination
// Map: builder.Map<Source, Destination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: Constructs=0; Members=0
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
// Pair 1: global::TestCase.MembersSource -> global::TestCase.MembersDestination
// Map: builder.Map<MembersSource, MembersDestination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: Constructs=0; Members=0
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
// Pair 2: global::TestCase.ConvertSource -> global::TestCase.ConvertDestination
// Map: builder.Map<ConvertSource, ConvertDestination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: Constructs=0; Members=0
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
// Pair 3: global::TestCase.VisibleSource -> global::TestCase.VisibleDestination
// Map: builder.Map<VisibleSource, VisibleDestination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: Constructs=0; Members=0
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
""";

        await PairConfigurationGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }

    [Test]
    public async Task Keeps_same_pair_descriptors_per_mapper_and_marks_generic_unification()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }
    public sealed class Destination { }
    public sealed class Envelope<T> { }

    [MorphantMapper]
    public partial class FirstMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    [MorphantMapper]
    public partial class SecondMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    [MorphantMapper]
    public partial class GenericMapper<T> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Envelope<T>, Destination>();
            builder.Map<Envelope<int>, Destination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

// Mappers: 3
// Mapper 0: TestCase.FirstMapper
// Unifiable: False
// Root settings: MappingMode=Unset; NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Pairs: 1
// Pair 0: global::TestCase.Source -> global::TestCase.Destination
// Map: builder.Map<Source, Destination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: Constructs=0; Members=0
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
// Mapper 1: TestCase.GenericMapper`1
// Unifiable: True
// Root settings: MappingMode=Unset; NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Pairs: 2
// Pair 0: global::TestCase.Envelope<T> -> global::TestCase.Destination
// Map: builder.Map<Envelope<T>, Destination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: Constructs=0; Members=0
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
// Pair 1: global::TestCase.Envelope<global::System.Int32> -> global::TestCase.Destination
// Map: builder.Map<Envelope<int>, Destination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: Constructs=0; Members=0
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
// Mapper 2: TestCase.SecondMapper
// Unifiable: False
// Root settings: MappingMode=Unset; NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Pairs: 1
// Pair 0: global::TestCase.Source -> global::TestCase.Destination
// Map: builder.Map<Source, Destination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: Constructs=0; Members=0
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
""";

        await PairConfigurationGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }
}
