using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.PairConfigurationTests;

[TestFixture]
internal sealed class PairConfigurationDiscoveryTests
{
    [Test]
    public async Task Discovers_block_and_expression_bodied_fluent_chains_in_written_order()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    public sealed class OtherSource { }

    public sealed class OtherDestination
    {
        public int Value { get; set; }
    }

    public sealed class ExpressionSource { }

    public sealed class ExpressionDestination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class BlockMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, Destination>()
                .Members((source, previous) => default!)
                .Resolve((source, previous) => default!);

            builder.Map<OtherSource, OtherDestination>()
                .Construct(source => default!);
        }
    }

    [MorphantMapper]
    public partial class ExpressionMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<ExpressionSource, ExpressionDestination>()
                .Construct(source => default!)
                .Members((source, previous, result) => default!);
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

// Mappers: 2
// Mapper 0: TestCase.BlockMapper
// Unifiable: False
// Root settings: MappingMode=Unset; NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Pairs: 2
// Pair 0: global::TestCase.Source -> global::TestCase.Destination
// Map: builder.Map<Source, Destination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: ResultPolicies=1; Members=1
// Resolve 0: Form=SourceAndPrevious; Inputs=(global::TestCase.Source, global::Morphant.Option<global::TestCase.Destination>); Output=global::TestCase.Morphant.Generated.DestinationConstruction; Operation=AnonymousFunction; Syntax=(source, previous) => default!
// Members 0: Form=SourceAndPrevious; Inputs=(global::TestCase.Source, global::Morphant.Option<global::TestCase.Destination>); Output=global::TestCase.Morphant.Generated.DestinationMembers; Operation=AnonymousFunction; Syntax=(source, previous) => default!
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
// Pair 1: global::TestCase.OtherSource -> global::TestCase.OtherDestination
// Map: builder.Map<OtherSource, OtherDestination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: ResultPolicies=1; Members=0
// Construct 0: Form=Source; Inputs=(global::TestCase.OtherSource); Output=global::TestCase.Morphant.Generated.OtherDestinationConstruction; Operation=AnonymousFunction; Syntax=source => default!
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
// Mapper 1: TestCase.ExpressionMapper
// Unifiable: False
// Root settings: MappingMode=Unset; NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Pairs: 1
// Pair 0: global::TestCase.ExpressionSource -> global::TestCase.ExpressionDestination
// Map: builder.Map<ExpressionSource, ExpressionDestination>()
// Map settings: MappingMode=Implicit(Default); NullSourceHandling=Unset; NullDestinationHandling=Unset; ConstructorSelection=Unset; MemberSelection=Unset; UnmappedMemberValidation=Unset
// Declarative: ResultPolicies=1; Members=1
// Construct 0: Form=Source; Inputs=(global::TestCase.ExpressionSource); Output=global::TestCase.Morphant.Generated.ExpressionDestinationConstruction; Operation=AnonymousFunction; Syntax=source => default!
// Members 0: Form=SourcePreviousAndResult; Inputs=(global::TestCase.ExpressionSource, global::Morphant.Option<global::TestCase.ExpressionDestination>, global::TestCase.ExpressionDestination); Output=global::TestCase.Morphant.Generated.ExpressionDestinationMembers; Operation=AnonymousFunction; Syntax=(source, previous, result) => default!
// Manual: Converts=0
// IncludeBase: 0
// Conflicts: None
""";

        await PairConfigurationGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }
}
