namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.ResultDependencies;

internal sealed partial class ResultDependenciesTests
{
    [Test]
    [Description("The constructor parameter list does not associate Name with any argument; Members reads the required property.")]
    public void RequiredSetReadsResultAfterAttributedParameterlessConstructor()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;
using Morphant.Context;
using System.Diagnostics.CodeAnalysis;

namespace TestCase
{
    public sealed class Source
    {
        public string Name => "from convention";
        public string FromConstruct() => "from constructor";
        public string FromMembers() => "from members";
    }

    public sealed class Destination
    {
        [SetsRequiredMembers]
        public Destination() => Name = "constructor value";
        public required string Name { get; set; }
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Construct(_ => new())
                .Members((source, previous, result, context) => new() { Name = result.Name + " updated" });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            var result = new global::TestCase.Destination();

            result.Name = result.Name + " updated";

            return result;
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Name = destination.Name + " updated";

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: RequiredSetReadsResultAfterAttributedParameterlessConstructorSurfaces,
            languageVersion: Microsoft.CodeAnalysis.CSharp.LanguageVersion.CSharp11);
    }
}
