namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.ResultDependencies;

internal sealed partial class ResultDependenciesTests
{
    [Test]
    [Description("A local shared by the constructor and another property reads result.")]
    public void SharedLocalDependsOnResultBeforeConstruction()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;
using Morphant.Context;
using System.Diagnostics.CodeAnalysis;

namespace TestCase
{
    public sealed class Source
    {
        public string Name => "from convention";
        public string FromConstruct() => "from constructor";
        public string FromMembers() => "from members";
    }

    public sealed class Destination
    {
        public Destination(string name) => Name = name;
        public string Name { get; set; }
        public string Label { get; set; } = "";
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Members((source, previous, result) =>
                {
                    var normalized = result.Name.ToUpperInvariant();
                    return new() { Name = normalized, Label = normalized };
                });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, global::Morphant.Context.MappingOperation.Create, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, global::Morphant.Context.MappingOperation.Update, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingOperation operation,
            global::Morphant.Context.MappingContext context)
        {
            throw new global::Morphant.Exceptions.MappingConfigurationException(
                operation,
                typeof(global::TestCase.Source),
                typeof(global::TestCase.Destination),
                "This member cannot be assigned in this Create or Update case.");
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            var normalized = destination.Name.ToUpperInvariant();

            destination.Name = normalized;
            destination.Label = normalized;

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: OneLocalFeedsConstructorAndAnotherMemberSurfaces,
            expectedDiagnostics: """
MORPH0042 Error: Rule for destination member 'Name' cannot be applied in mapping 'TestCase.Source -> TestCase.Destination': member rule uses 'result' before the destination is created; its value is required by constructor parameter 'name'. Affected cases: Create; Update without an existing destination.
  at TestCase.cs(31,36-31,40); TestCase.cs(30,38-30,44)
""");
    }
}
