namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.OrdinaryTypes;

internal sealed partial class OrdinaryTypesTests
{
    [Test]
    [Description("Written ByConvention arguments, Auto, and remaining conventions meet member rules.")]
    public void ConventionWithWrittenAndAutomaticArguments()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;
using Morphant.Context;
using System.Diagnostics.CodeAnalysis;

namespace TestCase
{
    public sealed class Source
    {
        public string Name => "automatic name";
        public int Age => 42;
        public int Score => 10;
        public string FromConstruct() => "constructor name";
        public string FromMembers() => "member name";
    }

    public sealed class Destination
    {
        public Destination(string name, int age, int score) { Name = name; Age = age; Score = score; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Score { get; set; }
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Construct(source => new(ByConvention(), new()
                {
                    name = source.FromConstruct(),
                    age = Auto()
                }))
                .Members(source => new() { Name = source.FromMembers(), Age = 50 });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            string sourceName = source.FromMembers();
            int sourceAge = 50;

            return new global::TestCase.Destination(
                name: sourceName,
                age: sourceAge,
                score: source.Score);
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Name = source.FromMembers();
            destination.Age = 50;
            destination.Score = source.Score;

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: ConventionWithWrittenAndAutomaticArgumentsSurfaces);
    }
}
