using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.ConstructionSurfaceTests;

[TestFixture]
internal sealed class ConstructionSurfaceDocumentationTests
{
    [Test]
    public async Task Inherits_destination_documentation_and_supplies_complete_fallbacks()
    {
        // lang=c#
        const string source =
"""
#nullable enable

using Morphant;

namespace TestCase
{
    /// <summary>Source documentation.</summary>
    public sealed class Source { }

    /// <summary>Destination documentation.</summary>
    public sealed class Destination
    {
        /// <summary>Creates a destination from its value.</summary>
        /// <param name="value">The initial value.</param>
        public Destination(int value) { }
    }

    /// <summary>Test mapper.</summary>
    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        /// <summary>Configures test mappings.</summary>
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string construction =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Contains mappings for constructor arguments of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Configures the <c>value</c> constructor argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<int> value = null!;
    }

    /// <inheritdoc cref="global::TestCase.Destination"/>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        /// <param name="parameters">Specifies optional mappings for constructor arguments.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Creates a destination instance using factory-based construction.
        /// </summary>
        /// <param name="marker">Selects factory-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.IByFactoryMarker<global::TestCase.Destination> marker)
        {
        }

        /// <inheritdoc cref="global::TestCase.Destination.Destination(global::System.Int32)"/>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<int> value)
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::TestCase.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures how to construct a destination when no existing destination is used.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::TestCase.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures how to select or construct the destination from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and the optional existing destination and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A lambda expression that receives the original source, the optional existing destination, and the current mapping context.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        await ConstructionSurfaceGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination.g.cs",
                construction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__TestCase_Destination.g.cs",
                extension
            ));
    }

    [Test]
    public async Task Generates_a_meaningful_plan_summary_without_destination_docs()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }
    public sealed class Destination { }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string construction =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using factory-based construction.
        /// </summary>
        /// <param name="marker">Selects factory-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.IByFactoryMarker<global::TestCase.Destination> marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using a corresponding constructor.
        /// </summary>
        public DestinationConstruction()
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::TestCase.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures how to construct a destination when no existing destination is used.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::TestCase.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures how to select or construct the destination from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and the optional existing destination and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A lambda expression that receives the original source, the optional existing destination, and the current mapping context.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        await ConstructionSurfaceGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination.g.cs",
                construction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__TestCase_Destination.g.cs",
                extension
            ));
    }

}
