using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.ConstructionSurfaceTests;

[TestFixture]
internal sealed class ConstructionSurfaceUsageTests
{
    [Test]
    public async Task Resolves_every_result_and_manual_callback_overload()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System;
using Morphant;
using Morphant.Context;
using Morphant.Members;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; init; }
    }

    public sealed class Destination
    {
        public Destination(int id) { }

        public Destination(string? label) { }

        public Destination(
            Guid id,
            bool enabled = true,
            params string[] tags) { }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper<TestMapper>
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source?, Destination?>()
                .Construct(source => new(source.Id))
                .Construct(_ => new(label: null))
                .Construct((source, context) =>
                    context.Operation == MappingOperation.Create
                        ? new(source.Id)
                        : new(label: null))
                .Resolve((source, previous) =>
                {
                    if (previous.HasValue)
                        return previous;

                    return new(
                            ByConvention(),
                            new()
                            {
                                idInt = source.Id,
                                enabled = Auto(),
                                tags = new[] { "generated" }
                            });
                })
                .Resolve((source, previous, context) =>
                {
                    if (context.Operation == MappingOperation.Update)
                        return previous;

                    return new(source.Id);
                })
                .Construct(source => new(
                    (ConstructorParameter<Guid>)Guid.NewGuid(),
                    tags: Array.Empty<string>()))
                .ConstructUsing(source => new Destination(source.Id))
                .ConstructUsing((source, context) =>
                    new Destination(context.Operation.ToString()))
                .ResolveUsing((source, previous) =>
                    previous.HasValue
                        ? previous.Value
                        : new Destination(source.Id))
                .ResolveUsing((source, previous, context) =>
                    context.Operation == MappingOperation.Update &&
                    previous.HasValue
                        ? previous.Value
                        : new Destination(source.Id))
                .Convert(source => source is null
                    ? null
                    : new Destination(source.Id))
                .Convert((source, previous) =>
                    previous.HasValue
                        ? previous.Value
                        : source is null
                            ? null
                            : new Destination(source.Id))
                .Convert((source, previous, context) =>
                    previous.HasValue
                        ? previous.Value
                        : new Destination(source!.Id));
        }
    }
}
""";

        // lang=c#
        const string construction =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.N_TestCase.Plans
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Maps the <c>id</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<int> idInt = null!;

        /// <summary>
        /// Maps the <c>label</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string?>? label = null!;

        /// <summary>
        /// Maps the <c>id</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<global::System.Guid> idGuid = null!;

        /// <summary>
        /// Maps the <c>enabled</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<bool> enabled = null!;

        /// <summary>
        /// Maps the <c>tags</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string[]> tags = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="id">Maps the <c>id</c> argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<int> id)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="label">Maps the <c>label</c> argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<string?>? label)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="id">Maps the <c>id</c> argument.</param>
        /// <param name="enabled">Maps the <c>enabled</c> argument. If omitted, uses <c>true</c>.</param>
        /// <param name="tags">Maps the <c>tags</c> argument.</param>
        public DestinationConstruction(
            global::Morphant.Members.ConstructorParameter<global::System.Guid> id,
            global::Morphant.Members.ConstructorParameter<bool> enabled = null!,
            global::Morphant.Members.ConstructorParameter<string[]> tags = null!)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::TestCase.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination construction when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline lambda using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination construction with access to the current mapping context.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline lambda using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines how to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline lambda returning previous or using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination resolution with access to the current mapping context.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline lambda returning previous or using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to construct a destination when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::TestCase.Destination?> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to construct a destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::TestCase.Destination?> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination?> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination?> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination and context as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        await ConstructionSurfaceGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination.g.cs",
                construction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__TestCase_Destination__TestCase_TestMapper.g.cs",
                extension
            ));
    }

    [Test]
    public async Task Resolves_direct_method_groups_and_previous_aware_replacement()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System;
using Morphant;

namespace TestCase
{
    [MorphantMapper]
    public partial class TestMapper : TypeMapper<TestMapper>
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<string?, Guid>()
                .ConstructUsing(Guid.Parse)
                .ResolveUsing((source, previous) =>
                    previous.HasValue
                        ? previous.Value
                        : Guid.Parse(source))
                .Convert((source, previous, _) =>
                    source is null
                        ? previous.HasValue
                            ? previous.Value
                            : Guid.Empty
                        : Guid.Parse(source));
        }
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Uses a callback to construct a destination when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> builder,
            global::Morphant.Delegates.ConstructUsing<string, global::System.Guid> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to construct a destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> builder,
            global::Morphant.Delegates.ConstructUsing<string, global::Morphant.Context.MappingContext, global::System.Guid> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> builder,
            global::Morphant.Delegates.ResolveUsing<string, global::System.Guid, global::System.Guid> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> builder,
            global::Morphant.Delegates.ResolveUsing<string, global::System.Guid, global::Morphant.Context.MappingContext, global::System.Guid> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> builder,
            global::Morphant.Delegates.Convert<string?, global::System.Guid> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> builder,
            global::Morphant.Delegates.Convert<string?, global::System.Guid, global::System.Guid> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination and context as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, string?, global::System.Guid> builder,
            global::Morphant.Delegates.Convert<string?, global::System.Guid, global::Morphant.Context.MappingContext, global::System.Guid> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        await ConstructionSurfaceGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.MappingExtension.System_String__System_Guid__TestCase_TestMapper.g.cs",
                extension
            ));
    }

}
