using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.ConstructionSurfaceTests;

[TestFixture]
internal sealed class ConstructionSurfaceNullabilityUsageTests
{
    [Test]
    public async Task Checks_constructor_inputs_and_existing_reference_result_flow()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System.Diagnostics.CodeAnalysis;
using Morphant;
using Construction = Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction;

namespace TestCase
{
    public sealed class Source { }

    public sealed class Destination
    {
        // Every parameter is required. Nullable annotations describe whether
        // an explicitly supplied null value is accepted.
        public Destination(
            string nonNullableReference,
            string? nullableReference,
            [AllowNull] string allowNullReference,
            [DisallowNull] string? disallowNullReference,
            int? nullableValue) { }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper<TestMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source?, Destination?>()
                .Construct(source =>
                {
                    _ = source.GetType();
                    return new("name", null, null, "name", null);
                })
                .Construct(source => new(
                    {|CS8625:null|}, null, null, {|CS8625:null|}, null))
                .Construct(source =>
                {
                    string? value = ReadNullable();
                    return new(
                        {|CS8604:value|}, value,
                        value, {|CS8604:value|}, (int?)null);
                })
                .Construct(source => {|CS8603:null|})
                .Resolve((source, previous) =>
                {
                    if (previous.HasValue)
                    {
                        Construction construction = previous.Value;
                        _ = construction.GetType();
                        return construction;
                    }

                    return new("name", null, null, "name", null);
                })
                .Resolve((source, previous) =>
                {
                    if (previous.TryGetValue(out var existing))
                    {
                        _ = existing.GetType();
                        return existing;
                    }

                    return {|CS8604:existing|};
                })
                .Resolve((source, previous) => {|CS8603:null|})
                .ConstructUsing(source => null)
                .ResolveUsing((source, previous) => null);

        private static Construction ConvertExisting(Destination destination) =>
            destination;

        private static Construction ConvertPossiblyNull(Destination? destination) =>
            {|CS8604:destination|};

        private static string? ReadNullable() => null;
    }
}
""";

        // lang=c#
        const string construction =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_5e01468111660761710199b9666fe80e
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Maps the <c>nonNullableReference</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string> nonNullableReference = null!;

        /// <summary>
        /// Maps the <c>nullableReference</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string?>? nullableReference = null!;

        /// <summary>
        /// Maps the <c>allowNullReference</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string?>? allowNullReference = null!;

        /// <summary>
        /// Maps the <c>disallowNullReference</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string> disallowNullReference = null!;

        /// <summary>
        /// Maps the <c>nullableValue</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<int?>? nullableValue = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="nonNullableReference">Maps the <c>nonNullableReference</c> argument.</param>
        /// <param name="nullableReference">Maps the <c>nullableReference</c> argument.</param>
        /// <param name="allowNullReference">Maps the <c>allowNullReference</c> argument.</param>
        /// <param name="disallowNullReference">Maps the <c>disallowNullReference</c> argument.</param>
        /// <param name="nullableValue">Maps the <c>nullableValue</c> argument.</param>
        public DestinationConstruction(
            global::Morphant.Members.ConstructorParameter<string> nonNullableReference,
            global::Morphant.Members.ConstructorParameter<string?>? nullableReference,
            global::Morphant.Members.ConstructorParameter<string?>? allowNullReference,
            global::Morphant.Members.ConstructorParameter<string> disallowNullReference,
            global::Morphant.Members.ConstructorParameter<int?>? nullableValue)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::TestCase.Destination previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_5e01468111660761710199b9666fe80e.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::TestCase.Destination?> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::TestCase.Destination?> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination?> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination?> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source?, global::TestCase.Destination?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        await ConstructionSurfaceGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination.g.cs",
                construction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__TestCase_Destination__TestCase_TestMapper.g.cs",
                extension
            ));
    }

    [Test]
    public async Task Checks_nullable_struct_roots_and_nested_generic_value_flow()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System.Collections.Generic;
using Morphant;

namespace TestCase
{
    public struct Source<T>
    {
        public T Value { get; set; }
    }

    public struct Destination<T>
    {
        public Destination(T value) { Value = value; }

        public T Value { get; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper<TestMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source<List<string?>>?, Destination<List<string?>>?>()
                .Construct(source =>
                {
                    List<string?> values = source.Value;
                    return new(values);
                })
                .Resolve((source, previous) =>
                {
                    if (previous.TryGetValue(out var existing))
                    {
                        List<string?> values = existing.Value;
                        _ = values[0]?.Length;
                        _ = {|CS8602:values[0]|}.Length;
                        return existing;
                    }

                    return new(source.Value);
                })
                .Resolve((source, previous) =>
                {
                    if (previous.HasValue)
                        return previous.Value;

                    return new(source.Value);
                })
                .Construct(source => {|CS8603:null|})
                .ConstructUsing(source => null)
                .ResolveUsing((source, previous) => null);
    }
}
""";

        // lang=c#
        const string construction =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_44357adb1d8d62d938f9f3f63376f435
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::TestCase.Destination&lt;T&gt;"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters<T>
    {
        /// <summary>
        /// Maps the <c>value</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<T> value = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::TestCase.Destination&lt;T&gt;"/>.
    /// </summary>
    internal sealed class DestinationConstruction<T>
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters<T>? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="value">Maps the <c>value</c> argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<T> value)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        public DestinationConstruction()
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction<T>(
            global::TestCase.Destination<T> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source<global::System.Collections.Generic.List<string?>>, global::Morphant.Generated.N_44357adb1d8d62d938f9f3f63376f435.DestinationConstruction<global::System.Collections.Generic.List<string?>>> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source<global::System.Collections.Generic.List<string?>>, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_44357adb1d8d62d938f9f3f63376f435.DestinationConstruction<global::System.Collections.Generic.List<string?>>> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source<global::System.Collections.Generic.List<string?>>, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>, global::Morphant.Generated.N_44357adb1d8d62d938f9f3f63376f435.DestinationConstruction<global::System.Collections.Generic.List<string?>>> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source<global::System.Collections.Generic.List<string?>>, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_44357adb1d8d62d938f9f3f63376f435.DestinationConstruction<global::System.Collections.Generic.List<string?>>> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source<global::System.Collections.Generic.List<string?>>, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source<global::System.Collections.Generic.List<string?>>, global::Morphant.Context.MappingContext, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source<global::System.Collections.Generic.List<string?>>, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source<global::System.Collections.Generic.List<string?>>, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>, global::Morphant.Context.MappingContext, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source<global::System.Collections.Generic.List<string?>>?, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>, global::Morphant.Context.MappingContext, global::TestCase.Destination<global::System.Collections.Generic.List<string?>>?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        await ConstructionSurfaceGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination_1.g.cs",
                construction
            ),
            (
                "Morphant.Generated.MappingExtension.System_Nullable_TestCase_Source_System_Collections_Generic_List_System_String_____System_Nullable_TestCase_Destination_System_Collections_Generic_List_System_Str__e0b3ec9201c15390.g.cs",
                extension
            ));
    }

}
