namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.NestedUpdates;

internal sealed partial class NestedUpdatesTests
{
    [Test]
    [Description("An in-place Update has no child object to mutate when the readonly reference is null.")]
    public void NullReadonlyChildSkipsStandaloneUpdate()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using Morphant;
using Morphant.Context;
using DestinationMembers = Morphant.Generated.N_78409e4ae9aaeef534a067d95eb70f27.DestinationMembers;

namespace TestCase
{
    public sealed class ChildSource { public string Name => "nested source"; }

    public sealed class Source
    {
        public bool Reuse => true;
        public ChildSource Child { get; } = new();
    }

    public sealed class ChildDestination
    {
        public string Name { get; set; } = "constructor child";
    }

    public sealed class Destination
    {
        public Destination(ChildDestination? child) => Child = child;
        public ChildDestination? Child { get; }
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<ChildSource, ChildDestination>()
                .Members((source, previous, result, context) => new()
                {
                    Name = context.Operation + ":" + source.Name
                });

            builder.Map<Source, Destination>()
                .MemberSelection(MemberSelection.Explicit)
                .ConstructUsing(_ => new Destination(null))
                .Members((source, previous) =>
                {
                    var members = new DestinationMembers();
                    Update<ChildDestination>(source.Child, members.Child);
                    return members;
                });
        }
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.ChildSource, global::TestCase.ChildDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.ChildSource) &&
                    destinationType == typeof(global::TestCase.ChildDestination)) ||
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.ChildDestination global::Morphant.ITypeMapper<global::TestCase.ChildSource, global::TestCase.ChildDestination>.Create(
            global::TestCase.ChildSource? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.ChildDestination global::Morphant.ITypeMapper<global::TestCase.ChildSource, global::TestCase.ChildDestination>.Update(
            global::TestCase.ChildSource? source,
            global::TestCase.ChildDestination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.ChildDestination __Create(
            global::TestCase.ChildSource source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.ChildDestination()
            {
                Name = context.Operation + ":" + source.Name
            };
        }

        private global::TestCase.ChildDestination __Update(
            global::TestCase.ChildSource source,
            global::TestCase.ChildDestination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Name = context.Operation + ":" + source.Name;

            return destination;
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create1(source, context);
            }

            return __Update1(source, destination, context);
        }

        private global::TestCase.Destination __Create1(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            global::TestCase.Destination result = __ConstructUsing(source);

            if (result is null)
            {
                return default!;
            }

            if (result.Child is { } childDestination)
            {
                var childSource = source.Child;

                _ = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(
                    childSource,
                    destination: childDestination);
            }

            return result;
        }

        private global::TestCase.Destination __Update1(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            if (destination.Child is { } childDestination)
            {
                var childSource = source.Child;

                _ = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(
                    childSource,
                    destination: childDestination);
            }

            return destination;
        }

        private global::TestCase.Destination __ConstructUsing(global::TestCase.Source source) => new global::TestCase.Destination(null);
    }
}
""")
            ],
            expectedSurfaces: NullReadonlyChildSkipsStandaloneUpdateSurfaces);
    }
}
