namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.NestedUpdates;

internal sealed partial class NestedUpdatesTests
{
    private static readonly (string HintName, string Source)[] SystemTupleConstructorChildAndNestedMapAssignmentSurfaces =
    [
            ("Morphant.Generated.Construction.TestCase_ChildDestination.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e
{
    /// <summary>
    /// Defines construction of <see cref="global::TestCase.ChildDestination"/>.
    /// </summary>
    internal sealed class ChildDestinationConstruction
    {
        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        public ChildDestinationConstruction()
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator ChildDestinationConstruction(
            global::Morphant.Option<global::TestCase.ChildDestination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.Construction.Tuple_S2_577d537dcf1e48934fddc5771d0d846d.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52
{
    /// <summary>
    /// Maps constructor arguments for <see cref="T:System.Tuple`2"/>.
    /// </summary>
    internal sealed class TupleConstructorParameters
    {
        /// <summary>
        /// Maps the <c>Item1</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<global::TestCase.ChildDestination> Item1 = null!;

        /// <summary>
        /// Maps the <c>Item2</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<int> Item2 = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="T:System.Tuple`2"/>.
    /// </summary>
    internal sealed class TupleConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public TupleConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            TupleConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="Item1">Maps the <c>Item1</c> argument.</param>
        /// <param name="Item2">Maps the <c>Item2</c> argument.</param>
        public TupleConstruction(
            global::Morphant.Members.ConstructorParameter<global::TestCase.ChildDestination> Item1,
            global::Morphant.Members.ConstructorParameter<int> Item2)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator TupleConstruction(
            global::Morphant.Option<global::System.Tuple<global::TestCase.ChildDestination, int>> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.MappingExtension.TestCase_ChildSource__TestCase_ChildDestination__TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.ChildSource, global::Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e.ChildDestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.ChildSource, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e.ChildDestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning previous or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.ChildSource, global::TestCase.ChildDestination, global::Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e.ChildDestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning previous or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.ChildSource, global::TestCase.ChildDestination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e.ChildDestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.ChildSource, global::TestCase.ChildDestination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.ChildSource, global::Morphant.Context.MappingContext, global::TestCase.ChildDestination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.ChildSource, global::TestCase.ChildDestination, global::TestCase.ChildDestination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.ChildSource, global::TestCase.ChildDestination, global::Morphant.Context.MappingContext, global::TestCase.ChildDestination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.ChildSource?, global::TestCase.ChildDestination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.ChildSource?, global::TestCase.ChildDestination, global::TestCase.ChildDestination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.ChildSource?, global::TestCase.ChildDestination, global::Morphant.Context.MappingContext, global::TestCase.ChildDestination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.MappingExtension.TestCase_Source__System_Tuple_TestCase_ChildDestination__System_Int32___TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52.TupleConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52.TupleConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning previous or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>, global::Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52.TupleConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning previous or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52.TupleConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::System.Tuple<global::TestCase.ChildDestination, int>> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>, global::System.Tuple<global::TestCase.ChildDestination, int>> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>, global::Morphant.Context.MappingContext, global::System.Tuple<global::TestCase.ChildDestination, int>> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::System.Tuple<global::TestCase.ChildDestination, int>> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::System.Tuple<global::TestCase.ChildDestination, int>, global::System.Tuple<global::TestCase.ChildDestination, int>> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::System.Tuple<global::TestCase.ChildDestination, int>, global::Morphant.Context.MappingContext, global::System.Tuple<global::TestCase.ChildDestination, int>> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.Member.TestCase_ChildDestination.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e
{
    /// <summary>
    /// Maps members of <see cref="global::TestCase.ChildDestination"/>.
    /// </summary>
    internal sealed record ChildDestinationMembers
    {
        /// <summary>
        /// Maps <see cref="global::TestCase.ChildDestination.Name"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Name
        {
            get => null!;
            set { }
        }

        public bool Equals(ChildDestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
"""),
            ("Morphant.Generated.Member.Tuple_S2_577d537dcf1e48934fddc5771d0d846d.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52
{
    /// <summary>
    /// Maps members of <see cref="T:System.Tuple`2"/>.
    /// </summary>
    internal sealed record TupleMembers
    {
        /// <summary>
        /// Maps tuple element <c>Item1</c>.
        /// </summary>
        public global::Morphant.Members.Member<global::TestCase.ChildDestination> Item1
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps tuple element <c>Item2</c>.
        /// </summary>
        public global::Morphant.Members.Member<int> Item2
        {
            get => null!;
            set { }
        }

        public bool Equals(TupleMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
"""),
            ("Morphant.Generated.MemberExtension.TestCase_ChildSource__TestCase_ChildDestination__TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Members<global::TestCase.ChildSource, global::Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e.ChildDestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Members<global::TestCase.ChildSource, global::TestCase.ChildDestination, global::Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e.ChildDestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Members<global::TestCase.ChildSource, global::TestCase.ChildDestination, global::TestCase.ChildDestination, global::Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e.ChildDestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.ChildSource, global::TestCase.ChildDestination> builder,
            global::Morphant.Delegates.Members<global::TestCase.ChildSource, global::TestCase.ChildDestination, global::TestCase.ChildDestination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_84787c77b0a7ad9c72dc5a9ea98c202e.ChildDestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
            ("Morphant.Generated.MemberExtension.TestCase_Source__System_Tuple_TestCase_ChildDestination__System_Int32___TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52.TupleMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>, global::Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52.TupleMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>, global::System.Tuple<global::TestCase.ChildDestination, int>, global::Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52.TupleMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> Members(
            this global::Morphant.MappingBuilder<global::TestCase.Mapper, global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::System.Tuple<global::TestCase.ChildDestination, int>, global::System.Tuple<global::TestCase.ChildDestination, int>, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_3e0a23cbdd408bf28b29b7275af80d52.TupleMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""")
    ];
}
