using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperMemberTests;

[TestFixture]
internal sealed class ExplicitMemberPlanTests
{
    [Test]
    public async Task Emits_the_complete_basic_explicit_member_plan()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; init; }
        public string Name { get; init; } = string.Empty;
        public int Automatic { get; init; }
        public string Ignored { get; init; } = string.Empty;
        public int Initial { get; init; }
        public int Field { get; init; }
        public string Convention { get; init; } = string.Empty;
    }

    public sealed class Destination
    {
        public Destination(int id) => Id = id;

        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public int Automatic { get; set; }
        public string Ignored { get; set; } = "preserved";
        public int Initial { get; init; }
        public int Field;
        public string Convention { get; set; } = string.Empty;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper<TestMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Construct(source => new(id: source.Id))
                .Members((source, _) => new()
                {
                    Field = source.Field + 1,
                    Id = source.Id + 10,
                    Name = source.Name,
                    Automatic = Auto(),
                    Ignored = Ignore(),
                    Initial = source.Initial
                });
    }
}
""";

        // lang=c#
        const string expectedConstruction =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.N_TestCase.Plans
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Maps the <c>id</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<int> id = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="id">Maps the <c>id</c> argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<int> id)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::TestCase.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedMappingExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination construction when none exists.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline lambda using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Construct<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination construction with access to the current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline lambda using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Construct<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines how to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline lambda returning previous or using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Resolve<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination resolution with access to the current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline lambda returning previous or using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Resolve<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to construct a destination when none exists.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::TestCase.Destination> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to construct a destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::TestCase.Destination> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination and context as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedMember =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.N_TestCase.Plans
{
    /// <summary>
    /// Maps members of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Id"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Id
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Name"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Name
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Automatic"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Automatic
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Ignored"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Ignored
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Initial"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Initial
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Field"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Field
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Convention"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Convention
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string expectedMemberExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination member mappings.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the optional existing destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the selected result.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings with access to the selected result and current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedTypeMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            int sourceId = source.Id;

            return new global::TestCase.Destination(
                id: sourceId)
            {
                Field = source.Field + 1,
                Id = sourceId + 10,
                Name = source.Name,
                Automatic = source.Automatic,
                Initial = source.Initial,
                Convention = source.Convention
            };
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Field = source.Field + 1;
            destination.Id = source.Id + 10;
            destination.Name = source.Name;
            destination.Automatic = source.Automatic;
            destination.Convention = source.Convention;

            return destination;
        }
    }
}
""";

        await BasicMembersTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination.g.cs",
                expectedConstruction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__TestCase_Destination.g.cs",
                expectedMappingExtension
            ),
            (
                "Morphant.Generated.Member.TestCase_Destination.g.cs",
                expectedMember
            ),
            (
                "Morphant.Generated.MemberExtension.TestCase_Source__TestCase_Destination.g.cs",
                expectedMemberExtension
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedTypeMapper
            ));
    }

    [Test]
    public async Task Emits_the_complete_previous_and_result_aware_lifecycle()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; init; }

        public int Delta { get; init; }

        public bool Reuse { get; init; }
    }

    public sealed class Destination
    {
        public Destination(int seed)
        {
            Seed = seed;
            Value = seed * 10;
        }

        public int Seed { get; }

        public int Initial { get; init; }

        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper<TestMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Resolve((source, previous) =>
                {
                    if (previous.HasValue && source.Reuse)
                    {
                        return previous;
                    }

                    return new(seed: source.Id);
                })
                .Members((source, previous, result) => new()
                {
                    Initial = previous.HasValue
                        ? previous.Value.Seed
                        : source.Id,
                    Value = result.Value + source.Delta
                });
    }
}
""";

        // lang=c#
        const string expectedConstruction =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.N_TestCase.Plans
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Maps the <c>seed</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<int> seed = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="seed">Maps the <c>seed</c> argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<int> seed)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::TestCase.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedMappingExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination construction when none exists.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline lambda using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Construct<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination construction with access to the current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline lambda using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Construct<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines how to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline lambda returning previous or using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Resolve<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination resolution with access to the current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline lambda returning previous or using new(...); an explicit generated type name is also supported.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Resolve<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to construct a destination when none exists.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::TestCase.Destination> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to construct a destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::TestCase.Destination> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination and context as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedMember =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.N_TestCase.Plans
{
    /// <summary>
    /// Maps members of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Initial"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Initial
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Value"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string expectedMemberExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination member mappings.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the optional existing destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the selected result.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings with access to the selected result and current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedTypeMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            var result = new global::TestCase.Destination(
                seed: source.Id)
            {
                Initial = source.Id
            };

            result.Value = result.Value + source.Delta;

            return result;
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source.Reuse)
            {
                destination.Value = destination.Value + source.Delta;

                return destination;
            }
            else
            {
                var result = new global::TestCase.Destination(
                    seed: source.Id)
                {
                    Initial = destination.Seed
                };

                result.Value = result.Value + source.Delta;

                return result;
            }
        }
    }
}
""";

        await BasicMembersTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination.g.cs",
                expectedConstruction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__TestCase_Destination.g.cs",
                expectedMappingExtension
            ),
            (
                "Morphant.Generated.Member.TestCase_Destination.g.cs",
                expectedMember
            ),
            (
                "Morphant.Generated.MemberExtension.TestCase_Source__TestCase_Destination.g.cs",
                expectedMemberExtension
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedTypeMapper
            ));
    }
}
