using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperMemberTests;

[TestFixture]
internal sealed class MemberSelectionTests
{
    [Test]
    public async Task Resolves_Default_to_the_assembly_MemberSelection()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; init; }
    }

    public sealed class Destination
    {
        public int Value { get; set; } = 41;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder
                .MemberSelection(MemberSelection.Default)
                .Map<Source, Destination>()
                .MemberSelection(MemberSelection.Default);
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return CreateImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return CreateImpl(source, context);
            }

            return UpdateImpl(source, destination, context);
        }

        private global::TestCase.Destination CreateImpl(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination();
        }

        private global::TestCase.Destination UpdateImpl(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest
            .RunAndAssertWithAnalyzerConfig(
                LanguageVersion.CSharp9,
                source,
                """
is_global = true

build_property.MorphantMemberSelection = Explicit
""",
                (
                    "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                    expected
                ));
    }

    [Test]
    public void Resolves_mapper_and_pair_MemberSelection_with_Default_inheritance()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public int Explicit { get; init; }

        public int Convention { get; init; }
    }

    public sealed class ExplicitDestination
    {
        public int Explicit { get; set; }

        public int Convention { get; set; } = -1;
    }

    public sealed class AutoDestination
    {
        public int Explicit { get; set; }

        public int Convention { get; set; } = -1;
    }

    public sealed class DefaultDestination
    {
        public int Explicit { get; set; }

        public int Convention { get; set; } = -1;
    }

    public sealed class LibraryDefaultDestination
    {
        public int Explicit { get; set; }

        public int Convention { get; set; } = -1;
    }

    [MorphantMapper]
    public partial class ExplicitMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder
                .MemberSelection(MemberSelection.Explicit)
                .Map<Source, ExplicitDestination>()
                .Members((source, _) => new()
                {
                    Explicit = source.Explicit + 1
                });

            builder.Map<Source, AutoDestination>()
                .MemberSelection(MemberSelection.Auto)
                .Members((source, _) => new()
                {
                    Explicit = source.Explicit + 2
                });

            builder.Map<Source, DefaultDestination>()
                .MemberSelection(MemberSelection.Default)
                .Members((source, _) => new()
                {
                    Explicit = source.Explicit + 3
                });
        }
    }

    [MorphantMapper]
    public partial class LibraryDefaultMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, LibraryDefaultDestination>()
                .Members((source, _) => new()
                {
                    Explicit = source.Explicit + 4
                });
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var source = new Source
            {
                Explicit = 10,
                Convention = 20
            };
            var context = default(MappingContext);
            var explicitMapper = new ExplicitMapper();
            var explicitResult =
                ((ITypeMapper<Source, ExplicitDestination>)
                    explicitMapper).Create(source, context);
            var autoResult =
                ((ITypeMapper<Source, AutoDestination>)
                    explicitMapper).Create(source, context);
            var defaultResult =
                ((ITypeMapper<Source, DefaultDestination>)
                    explicitMapper).Create(source, context);
            var libraryDefaultResult =
                ((ITypeMapper<Source, LibraryDefaultDestination>)
                    new LibraryDefaultMapper()).Create(source, context);

            if (explicitResult.Explicit != 11 ||
                explicitResult.Convention != -1 ||
                autoResult.Explicit != 12 ||
                autoResult.Convention != 20 ||
                defaultResult.Explicit != 13 ||
                defaultResult.Convention != -1 ||
                libraryDefaultResult.Explicit != 14 ||
                libraryDefaultResult.Convention != 20)
            {
                throw new InvalidOperationException(
                    "MemberSelection precedence was not preserved.");
            }
        }
    }
}
""";

        BasicMembersTypeMapperGeneratorTest.RunAndExecute(
            LanguageVersion.CSharp9,
            source,
            "TestCase.Scenario");
    }
}
