using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;
using static Morphant.Generator.UnitTests.TestUtils.GeneratorActualizationTest;

namespace Morphant.Generator.UnitTests.ActualizationTests;

[TestFixture]
internal sealed class ConstructionReferenceActualizationTests
{
    [Test]
    public void Actualizes_construction_surface_when_a_reference_changes()
    {
        // lang=c#
        const string referenceV1Source =
"""
#nullable enable
#pragma warning disable CS1591

namespace ExternalModels
{
    public sealed class Destination
    {
        public int Value { get; set; }
    }
}
""";

        // lang=c#
        const string referenceV2Source =
"""
#nullable enable
#pragma warning disable CS1591

namespace ExternalModels
{
    public sealed class Destination
    {
        public Destination(string label) => Label = label;

        public string Label { get; }
    }
}
""";

        // lang=c#
        const string consumerSource =
"""
#nullable enable
#pragma warning disable CS1591

using ExternalModels;
using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; init; }

        public string Label { get; init; } = string.Empty;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper<TestMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string parameterlessConstruction =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.A_MorphantActualization.N_ExternalModels.Plans
{
    /// <summary>
    /// Defines construction of <see cref="global::ExternalModels.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        public DestinationConstruction()
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::ExternalModels.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string constructorConstruction =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.A_MorphantActualization.N_ExternalModels.Plans
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::ExternalModels.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Maps the <c>label</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string> label = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::ExternalModels.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="label">Maps the <c>label</c> argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<string> label)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::ExternalModels.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination construction when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline construction lambda.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.Types.A_MorphantActualization.N_ExternalModels.Plans.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination construction with access to the current mapping context.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline construction lambda.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> Construct(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.A_MorphantActualization.N_ExternalModels.Plans.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines how to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline resolution lambda.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::ExternalModels.Destination, global::Morphant.Generated.Types.A_MorphantActualization.N_ExternalModels.Plans.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination resolution with access to the current mapping context.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline resolution lambda.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> Resolve(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::ExternalModels.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.A_MorphantActualization.N_ExternalModels.Plans.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to construct a destination when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::ExternalModels.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to construct a destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::ExternalModels.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::ExternalModels.Destination, global::ExternalModels.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::ExternalModels.Destination, global::Morphant.Context.MappingContext, global::ExternalModels.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::ExternalModels.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::ExternalModels.Destination, global::ExternalModels.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination and context as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> Convert(
            this global::Morphant.MappingBuilder<global::TestCase.TestMapper, global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::ExternalModels.Destination, global::Morphant.Context.MappingContext, global::ExternalModels.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        var referenceV1 = CreateReference(
            "ExternalModels",
            referenceV1Source);
        var referenceV2 = CreateReference(
            "ExternalModels",
            referenceV2Source);
        const string constructionHint =
            "Morphant.Generated.Construction.ExternalModels_Destination.g.cs";
        const string extensionHint =
            "Morphant.Generated.MappingExtension.TestCase_Source__ExternalModels_Destination__TestCase_TestMapper.g.cs";

        RunAndAssert(
            LanguageVersion.CSharp9,
            new TestConstructionSurfaceGenerator(),
            StepWithReferences(
                "reference version one",
                consumerSource,
                [referenceV1],
                (constructionHint, parameterlessConstruction),
                (extensionHint, extension)),
            StepWithReferences(
                "reference version two",
                consumerSource,
                [referenceV2],
                (constructionHint, constructorConstruction),
                (extensionHint, extension)),
            StepWithReferences(
                "reference version one restored",
                consumerSource,
                [referenceV1],
                (constructionHint, parameterlessConstruction),
                (extensionHint, extension)));
    }
}
