using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;
using static Morphant.Generator.UnitTests.TestUtils.GeneratorActualizationTest;

namespace Morphant.Generator.UnitTests.ActualizationTests;

[TestFixture]
internal sealed class ConstructionReferenceActualizationTests
{
    [Test]
    public void Actualizes_construction_surface_when_a_reference_changes()
    {
        // lang=c#
        const string referenceV1Source =
"""
#nullable enable
#pragma warning disable CS1591

namespace ExternalModels
{
    public sealed class Destination
    {
        public int Value { get; set; }
    }
}
""";

        // lang=c#
        const string referenceV2Source =
"""
#nullable enable
#pragma warning disable CS1591

namespace ExternalModels
{
    public sealed class Destination
    {
        public Destination(string label) => Label = label;

        public string Label { get; }
    }
}
""";

        // lang=c#
        const string consumerSource =
"""
#nullable enable
#pragma warning disable CS1591

using ExternalModels;
using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; init; }

        public string Label { get; init; } = string.Empty;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string parameterlessConstruction =
"""
// <auto-generated />
#nullable enable

namespace ExternalModels.Morphant.Generated
{
    /// <summary>
    /// Describes construction of <see cref="global::ExternalModels.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using a corresponding constructor.
        /// </summary>
        public DestinationConstruction()
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::ExternalModels.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string constructorConstruction =
"""
// <auto-generated />
#nullable enable

namespace ExternalModels.Morphant.Generated
{
    /// <summary>
    /// Contains mappings for constructor arguments of <see cref="global::ExternalModels.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Configures the <c>label</c> constructor argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string> label = null!;
    }

    /// <summary>
    /// Describes construction of <see cref="global::ExternalModels.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        /// <param name="parameters">Specifies optional mappings for constructor arguments.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Creates a destination instance using a corresponding constructor.
        /// </summary>
        /// <param name="label">Configures the <c>label</c> constructor argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<string> label)
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::ExternalModels.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures structured destination construction when no existing destination is used.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::ExternalModels.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures structured destination construction with declarative operation context.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and declarative mapping context and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::ExternalModels.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures structured destination resolution from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="resolve">A lambda expression that receives the non-null source and the optional existing destination and describes destination resolution.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> Resolve(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::ExternalModels.Destination, global::ExternalModels.Morphant.Generated.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures structured destination resolution with declarative operation context.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="resolve">A lambda expression that receives the non-null source, the optional existing destination, and declarative mapping context and describes destination resolution.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> Resolve(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::ExternalModels.Destination, global::Morphant.Context.MappingContextMarker, global::ExternalModels.Morphant.Generated.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures runtime destination construction when no existing destination is used.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A callback that receives the non-null source and returns the destination.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> ConstructUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::ExternalModels.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures runtime destination construction with mapping context.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A callback that receives the non-null source and current mapping context and returns the destination.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> ConstructUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::ExternalModels.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures runtime destination resolution from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="resolve">A callback that receives the non-null source and optional existing destination and returns the destination.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> ResolveUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::ExternalModels.Destination, global::ExternalModels.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures runtime destination resolution with mapping context.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="resolve">A callback that receives the non-null source, optional existing destination, and current mapping context and returns the destination.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> ResolveUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::ExternalModels.Destination, global::Morphant.Context.MappingContext, global::ExternalModels.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm from the original source.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A callback that receives the original source and returns the destination.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::ExternalModels.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm with access to an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A callback that receives the original source and optional existing destination and returns the destination.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::ExternalModels.Destination, global::ExternalModels.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm with mapping context.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A callback that receives the original source, optional existing destination, and current mapping context and returns the destination.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::ExternalModels.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::ExternalModels.Destination, global::Morphant.Context.MappingContext, global::ExternalModels.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        var referenceV1 = CreateReference(
            "ExternalModels",
            referenceV1Source);
        var referenceV2 = CreateReference(
            "ExternalModels",
            referenceV2Source);
        const string constructionHint =
            "Morphant.Generated.Construction.ExternalModels_Destination.g.cs";
        const string extensionHint =
            "Morphant.Generated.MappingExtension." +
            "TestCase_Source__ExternalModels_Destination.g.cs";

        RunAndAssert(
            LanguageVersion.CSharp9,
            new TestConstructionSurfaceGenerator(),
            StepWithReferences(
                "reference version one",
                consumerSource,
                [referenceV1],
                (constructionHint, parameterlessConstruction),
                (extensionHint, extension)),
            StepWithReferences(
                "reference version two",
                consumerSource,
                [referenceV2],
                (constructionHint, constructorConstruction),
                (extensionHint, extension)),
            StepWithReferences(
                "reference version one restored",
                consumerSource,
                [referenceV1],
                (constructionHint, parameterlessConstruction),
                (extensionHint, extension)));
    }
}
