using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;
using static Morphant.Generator.UnitTests.TestUtils.GeneratorActualizationTest;

namespace Morphant.Generator.UnitTests.ActualizationTests;

[TestFixture]
internal sealed class ConstructionConstraintActualizationTests
{
    [Test]
    public void Actualizes_generic_plan_and_extension_constraints()
    {
        // lang=c#
        const string referenceSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source<T>
        where T : class
    {
    }

    public sealed class Destination<T>
        where T : class
    {
    }

    [MorphantMapper]
    public partial class TestMapper<T> : TypeMapper
        where T : class
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source<T>, Destination<T>>();
    }
}
""";

        // lang=c#
        const string valueSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source<T>
        where T : struct
    {
    }

    public sealed class Destination<T>
        where T : struct
    {
    }

    [MorphantMapper]
    public partial class TestMapper<T> : TypeMapper
        where T : struct
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source<T>, Destination<T>>();
    }
}
""";

        // lang=c#
        const string referenceConstruction =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes construction of <see cref="global::TestCase.Destination&lt;T&gt;"/>.
    /// </summary>
    internal sealed class DestinationConstruction<T>
        where T : class
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using factory-based construction.
        /// </summary>
        /// <param name="marker">Selects factory-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.IByFactoryMarker<global::TestCase.Destination<T>> marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using a corresponding constructor.
        /// </summary>
        public DestinationConstruction()
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator DestinationConstruction<T>(
            global::Morphant.Option<global::TestCase.Destination<T>> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string valueConstruction =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes construction of <see cref="global::TestCase.Destination&lt;T&gt;"/>.
    /// </summary>
    internal sealed class DestinationConstruction<T>
        where T : struct
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using factory-based construction.
        /// </summary>
        /// <param name="marker">Selects factory-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.IByFactoryMarker<global::TestCase.Destination<T>> marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using a corresponding constructor.
        /// </summary>
        public DestinationConstruction()
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator DestinationConstruction<T>(
            global::Morphant.Option<global::TestCase.Destination<T>> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string referenceExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures how to construct a destination when no existing destination is used.
        /// </summary>
        /// <typeparam name="T">A type used by the mapping pair.</typeparam>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> Construct<T>(
            this global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source<T>, global::TestCase.Morphant.Generated.DestinationConstruction<T>> construct)
            where T : class
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures how to select or construct the destination from the source and an optional existing destination.
        /// </summary>
        /// <typeparam name="T">A type used by the mapping pair.</typeparam>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and the optional existing destination and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> Construct<T>(
            this global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source<T>, global::TestCase.Destination<T>, global::TestCase.Morphant.Generated.DestinationConstruction<T>> construct)
            where T : class
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm.
        /// </summary>
        /// <typeparam name="T">A type used by the mapping pair.</typeparam>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A lambda expression that receives the original source, the optional existing destination, and the current mapping context.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> Convert<T>(
            this global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source<T>?, global::TestCase.Destination<T>, global::TestCase.Destination<T>> mapping)
            where T : class
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string valueExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures how to construct a destination when no existing destination is used.
        /// </summary>
        /// <typeparam name="T">A type used by the mapping pair.</typeparam>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> Construct<T>(
            this global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source<T>, global::TestCase.Morphant.Generated.DestinationConstruction<T>> construct)
            where T : struct
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures how to select or construct the destination from the source and an optional existing destination.
        /// </summary>
        /// <typeparam name="T">A type used by the mapping pair.</typeparam>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and the optional existing destination and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> Construct<T>(
            this global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source<T>, global::TestCase.Destination<T>, global::TestCase.Morphant.Generated.DestinationConstruction<T>> construct)
            where T : struct
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm.
        /// </summary>
        /// <typeparam name="T">A type used by the mapping pair.</typeparam>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A lambda expression that receives the original source, the optional existing destination, and the current mapping context.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> Convert<T>(
            this global::Morphant.MapperBuilder<global::TestCase.Source<T>, global::TestCase.Destination<T>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source<T>?, global::TestCase.Destination<T>, global::TestCase.Destination<T>> mapping)
            where T : struct
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        const string constructionHint =
            "Morphant.Generated.Construction.TestCase_Destination_1.g.cs";
        const string extensionHint =
            "Morphant.Generated.MappingExtension." +
            "TestCase_Source_T___TestCase_Destination_T_.g.cs";

        RunAndAssert(
            LanguageVersion.CSharp9,
            new TestConstructionSurfaceGenerator(),
            Step(
                "reference constraints",
                referenceSource,
                (constructionHint, referenceConstruction),
                (extensionHint, referenceExtension)),
            Step(
                "value constraints",
                valueSource,
                (constructionHint, valueConstruction),
                (extensionHint, valueExtension)),
            Step(
                "reference constraints restored",
                referenceSource,
                (constructionHint, referenceConstruction),
                (extensionHint, referenceExtension)));
    }
}
