using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;
using static Morphant.Generator.UnitTests.TestUtils.GeneratorActualizationTest;

namespace Morphant.Generator.UnitTests.ActualizationTests;

[TestFixture]
internal sealed class MemberSurfaceActualizationTests
{
    [Test]
    public void Actualizes_member_plans_extensions_and_capabilities()
    {
        // lang=c#
        const string absentSource =
"""
#nullable enable
#pragma warning disable CS1591

namespace TestCase
{
    public sealed class Source { }
    public sealed class Destination { }
}
""";

        // lang=c#
        const string unrelatedSource =
"""
#nullable enable
#pragma warning disable CS1591

namespace Unrelated
{
    public static class Helper
    {
        public static int Value => 1;
    }
}
""";

        // lang=c#
        const string structuredSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }

    public sealed class Destination
    {
        public string Name { get; set; } = string.Empty;

        public string Token { get; init; } = string.Empty;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string sharedDestinationSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }
    public sealed class AlternativeSource { }

    public sealed class Destination
    {
        public string Name { get; set; } = string.Empty;

        public string Token { get; init; } = string.Empty;
    }

    [MorphantMapper]
    public partial class FirstMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    [MorphantMapper]
    public partial class SecondMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<AlternativeSource, Destination>();
    }
}
""";

        // lang=c#
        const string documentedSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }

    /// <summary>A documented destination.</summary>
    public sealed class Destination
    {
        /// <summary>A documented member.</summary>
        public int Documented { get; set; }

        public int Undocumented { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string directSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }

    public interface Destination
    {
        string Name { get; set; }

        string Token { get; init; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string unsupportedSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }
    public enum Destination { None }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string structuredMembers =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Maps members of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Name"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Name
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Token"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Token
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string documentedMembers =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Maps members of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Documented"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Documented
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Undocumented"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Undocumented
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string directMembers =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Maps members of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Name"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Name
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination member mappings.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the selected result.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings with access to the selected result and current mapping context.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string alternativeExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination member mappings.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.AlternativeSource, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.AlternativeSource, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.AlternativeSource, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.AlternativeSource, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.AlternativeSource, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.AlternativeSource, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the selected result.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.AlternativeSource, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.AlternativeSource, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.AlternativeSource, global::TestCase.Destination, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings with access to the selected result and current mapping context.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.AlternativeSource, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.AlternativeSource, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.AlternativeSource, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        const string memberHint =
            "Morphant.Generated.Member.TestCase_Destination.g.cs";
        const string extensionHint =
            "Morphant.Generated.MemberExtension." +
            "TestCase_Source__TestCase_Destination.g.cs";
        const string alternativeExtensionHint =
            "Morphant.Generated.MemberExtension." +
            "TestCase_AlternativeSource__TestCase_Destination.g.cs";

        RunAndAssert(
            LanguageVersion.CSharp9,
            new TestMemberSurfaceGenerator(),
            Step("no registration", absentSource),
            Step(
                "structured member capability added",
                structuredSource,
                (memberHint, structuredMembers),
                (extensionHint, extension)),
            Step(
                "irrelevant source added",
                [
                    SourceFile("TestCase.cs", structuredSource),
                    SourceFile("Unrelated.cs", unrelatedSource)
                ],
                (memberHint, structuredMembers),
                (extensionHint, extension)),
            Step(
                "same destination registered by another mapper",
                sharedDestinationSource,
                (memberHint, structuredMembers),
                (alternativeExtensionHint, alternativeExtension),
                (extensionHint, extension)),
            Step(
                "members and documentation changed",
                documentedSource,
                (memberHint, documentedMembers),
                (extensionHint, extension)),
            Step(
                "destination became direct",
                directSource,
                (memberHint, directMembers),
                (extensionHint, extension)),
            Step(
                "member capability disappeared",
                unsupportedSource),
            Step("last registration removed", absentSource),
            Step(
                "structured member capability restored",
                structuredSource,
                (memberHint, structuredMembers),
                (extensionHint, extension)));
    }
}
