using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;
using static Morphant.Generator.UnitTests.TestUtils.GeneratorActualizationTest;

namespace Morphant.Generator.UnitTests.ActualizationTests;

[TestFixture]
internal sealed class TypeMapperConstraintActualizationTests
{
    [Test]
    public void Rebinds_generic_constraints_without_rewriting_the_equivalent_mapper()
    {
        // lang=c#
        const string referenceSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public readonly struct Source<T>
        where T : class
    {
        public T Value { get; init; }
    }

    public sealed class Destination<T>
        where T : class
    {
        public T Value { get; set; } = null!;
    }

    [MorphantMapper]
    public partial class TestMapper<T> : TypeMapper
        where T : class
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source<T>, Destination<T>>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source<string>, Destination<string>>)
                new TestMapper<string>();
            var result = mapper.Create(
                new Source<string> { Value = "reference" },
                default(MappingContext));

            if (result.Value != "reference")
            {
                throw new InvalidOperationException(
                    "The reference constraint was not actualized.");
            }
        }
    }
}
""";

        // lang=c#
        const string valueSource =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public readonly struct Source<T>
        where T : struct
    {
        public T Value { get; init; }
    }

    public sealed class Destination<T>
        where T : struct
    {
        public T Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper<T> : TypeMapper
        where T : struct
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source<T>, Destination<T>>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source<int>, Destination<int>>)
                new TestMapper<int>();
            var result = mapper.Create(
                new Source<int> { Value = 37 },
                default(MappingContext));

            if (result.Value != 37)
            {
                throw new InvalidOperationException(
                    "The value constraint was not actualized.");
            }
        }
    }
}
""";

        // lang=c#
        const string referenceMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper<T> :
        global::Morphant.ITypeMapper<global::TestCase.Source<T>, global::TestCase.Destination<T>>
    {
        /// <inheritdoc/>
        global::TestCase.Destination<T> global::Morphant.ITypeMapper<global::TestCase.Source<T>, global::TestCase.Destination<T>>.Create(
            global::TestCase.Source<T> source,
            global::Morphant.Context.MappingContext context)
            => __Create(source, context);

        /// <inheritdoc/>
        global::TestCase.Destination<T> global::Morphant.ITypeMapper<global::TestCase.Source<T>, global::TestCase.Destination<T>>.Update(
            global::TestCase.Source<T> source,
            global::TestCase.Destination<T>? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination<T> __Create(
            global::TestCase.Source<T> source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination<T>()
            {
                Value = source.Value
            };
        }

        private global::TestCase.Destination<T> __Update(
            global::TestCase.Source<T> source,
            global::TestCase.Destination<T> destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Value = source.Value;

            return destination;
        }
    }
}
""";

        // lang=c#
        const string valueMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper<T> :
        global::Morphant.ITypeMapper<global::TestCase.Source<T>, global::TestCase.Destination<T>>
    {
        /// <inheritdoc/>
        global::TestCase.Destination<T> global::Morphant.ITypeMapper<global::TestCase.Source<T>, global::TestCase.Destination<T>>.Create(
            global::TestCase.Source<T> source,
            global::Morphant.Context.MappingContext context)
            => __Create(source, context);

        /// <inheritdoc/>
        global::TestCase.Destination<T> global::Morphant.ITypeMapper<global::TestCase.Source<T>, global::TestCase.Destination<T>>.Update(
            global::TestCase.Source<T> source,
            global::TestCase.Destination<T>? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination<T> __Create(
            global::TestCase.Source<T> source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination<T>()
            {
                Value = source.Value
            };
        }

        private global::TestCase.Destination<T> __Update(
            global::TestCase.Source<T> source,
            global::TestCase.Destination<T> destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Value = source.Value;

            return destination;
        }
    }
}
""";

        const string hintName =
            "Morphant.Generated.TypeMapper.TestCase_TestMapper_1.g.cs";

        RunAndAssert(
            LanguageVersion.CSharp9,
            new TestConventionTypeMapperGenerator(),
            ExecutableStep(
                "reference constraint",
                referenceSource,
                "TestCase.Scenario",
                (hintName, referenceMapper)),
            ExecutableStep(
                "value constraint",
                valueSource,
                "TestCase.Scenario",
                (hintName, valueMapper)),
            ExecutableStep(
                "reference constraint restored",
                referenceSource,
                "TestCase.Scenario",
                (hintName, referenceMapper)));
    }
}
