using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperNestedMapTests;

[TestFixture]
internal sealed class RuntimeDispatchTests
{
    [Test]
    public async Task Emits_runtime_dispatch_and_graph_sharing()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed record ChildSource(int Value);
    public sealed record ChildDestination(int Value);
    public sealed record Source(
        ChildSource Child,
        ChildDestination Previous,
        ChildSource Inferred,
        ChildSource Typed);

    public sealed class Destination
    {
        public Destination(ChildDestination constructed) =>
            Constructed = constructed;

        public ChildDestination Constructed { get; }
        public ChildDestination Created { get; set; } = new(-1);
        public ChildDestination Updated { get; set; } = new(-1);
        public ChildDestination Inferred { get; set; } = new(-1);
        public ChildDestination Typed { get; set; } = new(-1);
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper<TestMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Construct(source => new(Create(source.Child)))
                .Members((source, _) => new()
                {
                    Created = Create<ChildDestination>(source.Child),
                    Updated = Update(source.Child, source.Previous),
                    Inferred = Map(),
                    Typed = Map<ChildDestination>()
                });
    }
}
""";

        // lang=c#
        const string expectedConstruction =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.N_TestCase.Plans
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Maps the <c>constructed</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<global::TestCase.ChildDestination> constructed = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="constructed">Maps the <c>constructed</c> argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<global::TestCase.ChildDestination> constructed)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::TestCase.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedMappingExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination construction when none exists.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline lambda using new(...) without a type name.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Construct<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination construction with access to the current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">An inline lambda using new(...) without a type name.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Construct<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines how to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline lambda returning previous or using new(...) without a type name.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Resolve<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines destination resolution with access to the current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">An inline lambda returning previous or using new(...) without a type name.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Resolve<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Resolve<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationConstruction> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to construct a destination when none exists.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::TestCase.Destination> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to construct a destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ConstructUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, global::TestCase.Destination> construct)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to select or construct the destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> ResolveUsing<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> resolve)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination and context as the complete mapping algorithm.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Convert<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::Morphant.Context.MappingContext, global::TestCase.Destination> mapping)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedMember =
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.Types.N_TestCase.Plans
{
    /// <summary>
    /// Maps members of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Selects <see cref="global::TestCase.Destination.Constructed"/>.
        /// </summary>
        public global::Morphant.Members.Member<global::TestCase.ChildDestination> Constructed
        {
            get => null!;
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Created"/>.
        /// </summary>
        public global::Morphant.Members.Member<global::TestCase.ChildDestination> Created
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Updated"/>.
        /// </summary>
        public global::Morphant.Members.Member<global::TestCase.ChildDestination> Updated
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Inferred"/>.
        /// </summary>
        public global::Morphant.Members.Member<global::TestCase.ChildDestination> Inferred
        {
            get => null!;
            set { }
        }

        /// <summary>
        /// Maps <see cref="global::TestCase.Destination.Typed"/>.
        /// </summary>
        public global::Morphant.Members.Member<global::TestCase.ChildDestination> Typed
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string expectedMemberExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Defines destination member mappings.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the optional existing destination.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings using the selected result.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Defines member mappings with access to the selected result and current mapping context.
        /// </summary>
        /// <typeparam name="TMapper">A type parameter from the mapping declaration.</typeparam>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">The member plan.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination> Members<TMapper>(
            this global::Morphant.MapperBuilderBase<global::Morphant.MappingBuilder<TMapper, global::TestCase.Source, global::TestCase.Destination>> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.Types.N_TestCase.Plans.DestinationMembers> members)
            where TMapper : global::Morphant.TypeMapper<TMapper>
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedTypeMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            global::TestCase.ChildSource sourceChild = source.Child;
            global::TestCase.ChildDestination value = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(sourceChild);

            return new global::TestCase.Destination(
                constructed: value)
            {
                Created = value,
                Updated = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(sourceChild, source.Previous),
                Inferred = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(source.Inferred),
                Typed = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(source.Typed)
            };
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            global::TestCase.ChildSource sourceChild = source.Child;

            destination.Created = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(sourceChild);
            destination.Updated = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(sourceChild, source.Previous);
            destination.Inferred = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(source.Inferred, destination: destination.Inferred);
            destination.Typed = context.Mapper.Map<global::TestCase.ChildSource, global::TestCase.ChildDestination>(source.Typed, destination: destination.Typed);

            return destination;
        }
    }
}
""";

        await BasicMembersTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination.g.cs",
                expectedConstruction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__TestCase_Destination.g.cs",
                expectedMappingExtension
            ),
            (
                "Morphant.Generated.Member.TestCase_Destination.g.cs",
                expectedMember
            ),
            (
                "Morphant.Generated.MemberExtension.TestCase_Source__TestCase_Destination.g.cs",
                expectedMemberExtension
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expectedTypeMapper
            ));
    }
}
