namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Inheritance;

internal sealed partial class InheritanceTests
{
    [Test]
    [Description("Including a different destination mapping can inherit member rules while keeping the derived constructor.")]
    public void DifferentDestinationIncludesMembersButKeepsItsConstructor()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;

namespace TestCase
{
    public sealed class Source { public string Read(string site) => site; }

    public class BaseDestination
    {
        public BaseDestination(string name) => Name = name;
        public string Name { get; set; }
    }

    public sealed class Destination : BaseDestination
    {
        public Destination() : base("derived constructor") { }
        public string Label { get; set; } = "";
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Source, BaseDestination>()
                .Construct(source => new(source.Read("base constructor")))
                .Members(source => new() { Name = source.Read("base member") });

            builder.Map<Source, Destination>()
                .IncludeBase<Source, BaseDestination>()
                .Members(source => new() { Label = source.Read("local member") });
        }
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.BaseDestination>,
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.BaseDestination)) ||
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.BaseDestination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.BaseDestination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.BaseDestination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.BaseDestination>.Update(
            global::TestCase.Source? source,
            global::TestCase.BaseDestination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.BaseDestination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.BaseDestination(
                name: source.Read("base constructor"))
            {
                Name = source.Read("base member")
            };
        }

        private global::TestCase.BaseDestination __Update(
            global::TestCase.Source source,
            global::TestCase.BaseDestination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Name = source.Read("base member");

            return destination;
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create1(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create1(source, context);
            }

            return __Update1(source, destination, context);
        }

        private global::TestCase.Destination __Create1(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Name = source.Read("base member"),
                Label = source.Read("local member")
            };
        }

        private global::TestCase.Destination __Update1(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Name = source.Read("base member");
            destination.Label = source.Read("local member");

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: DifferentDestinationIncludesMembersButKeepsItsConstructorSurfaces);
    }
}
