namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Inheritance;

internal sealed partial class InheritanceTests
{
    [Test]
    [Description("IncludeBase combines inherited configuration with a local member rule.")]
    public void InheritedTupleConstructorWithLocalMember()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public string Read(string site) => site;
    }



    public abstract class BaseMapper<TMapper> : TypeMapper<TMapper>
        where TMapper : BaseMapper<TMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, (int Id, string Name)>()
                .Construct(source => new(7, source.Read("base constructor")));
    }

    [MorphantMapper]
    public partial class Mapper : BaseMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder)
        {
            base.Configure(builder);
            builder.Map<Source, (int Id, string Name)>()
                .IncludeBase<Source, (int Id, string Name)>()
                .Members(source => new() { Name = source.Read("local member") });
        }
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof((int Id, string Name))) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        (int Id, string Name) global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        (int Id, string Name) global::Morphant.ITypeMapper<global::TestCase.Source, (int Id, string Name)>.Update(
            global::TestCase.Source? source,
            (int Id, string Name) destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Update(source, destination, context);
        }

        private (int Id, string Name) __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return (Id: 7, Name: source.Read("local member"));
        }

        private (int Id, string Name) __Update(
            global::TestCase.Source source,
            (int Id, string Name) destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Name = source.Read("local member");

            return destination;
        }
    }
}
""")
            ],
            expectedSurfaces: InheritedTupleConstructorWithLocalMemberSurfaces);
    }
}
