namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Inheritance;

internal sealed partial class InheritanceTests
{
    [Test]
    [Description("An inherited Resolve keeps its reuse and construction rules when the derived mapper adds Members.")]
    public void ResolveInheritedConstructorWithLocalMember()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public bool Reuse { get; set; }
        public string Read(string site) => site;
    }

    public sealed class Destination
    {
        public Destination(string name) => Name = name;
        public string Name { get; set; }
    }

    public abstract class BaseMapper<TMapper> : TypeMapper<TMapper>
        where TMapper : BaseMapper<TMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Resolve((source, previous) =>
                {
                    if (previous.TryGetValue(out var current) && source.Reuse)
                        return current;
                    return new(source.Read("base constructor"));
                });
    }

    [MorphantMapper]
    public partial class Mapper : BaseMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder)
        {
            base.Configure(builder);
            builder.Map<Source, Destination>()
                .IncludeBase<Source, Destination>()
                .Members(source => new() { Name = source.Read("local member") });
        }
    }
}
""";

        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.Mapper__b93622f58bb33946b8901b3146112f51.g.cs",
            // lang=c#
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            _ = global::Morphant.Option<global::TestCase.Destination>.None.TryGetValue(out global::TestCase.Destination? current) && source.Reuse;

            return __Construct(source, context);
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            if (global::Morphant.Option<global::TestCase.Destination>.Some(destination).TryGetValue(out global::TestCase.Destination? current) && source.Reuse)
            {
                destination.Name = source.Read("local member");

                return destination;
            }

            return __Construct(source, context);
        }

        private global::TestCase.Destination __Construct(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination(
                name: source.Read("base constructor"))
            {
                Name = source.Read("local member")
            };
        }
    }
}
""")
            ],
            expectedSurfaces: LocalMemberOverridesInheritedMemberSurfaces);
    }
}
