using Microsoft.CodeAnalysis.CSharp;

namespace Morphant.Generator.UnitTests.NamespaceStyleTests;

internal sealed partial class NamespaceStyleTests
{
    [TestCase(LanguageVersion.CSharp9, "\n")]
    [TestCase(LanguageVersion.CSharp9, "\r\n")]
    [TestCase(LanguageVersion.CSharp10, "\n")]
    [TestCase(LanguageVersion.CSharp10, "\r\n")]
    public void Query_namespace_preserves_all_generated_sources(
        LanguageVersion version, string lineEnding)
    {
        Verify(QuerySource.ReplaceLineEndings(lineEnding), version,
            version == LanguageVersion.CSharp9 ? QueryBlockSources : QueryFileSources);
    }

    [TestCase(LanguageVersion.CSharp9)]
    [TestCase(LanguageVersion.CSharp10)]
    public void Query_names_remain_stable_after_line_ending_and_adjacent_edits(
        LanguageVersion version)
    {
        var expected = version == LanguageVersion.CSharp9
            ? QueryBlockSources : QueryFileSources;
        var initial = Verify(QuerySource.ReplaceLineEndings("\n"), version, expected);
        var updated = Verify(QuerySource.ReplaceLineEndings("\r\n"), version,
            expected, initial.Driver);
        Verify("// Unrelated edit before the mapper.\r\n\r\n" +
            QuerySource.ReplaceLineEndings("\r\n"), version, expected, updated.Driver);
    }

    // lang=c#
    private const string QuerySource =
"""
#nullable enable
#pragma warning disable CS1591
using Morphant;

using System.Linq;

namespace Example
{
    public static class System { }

    public sealed class Source
    {
        public int[] Values { get; set; } = new int[0];
    }

    public sealed class Destination
    {
        public Destination(string value) => Value = value;
        public string Value { get; set; }
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Construct(source => new(string.Join(",", from value in source.Values select value + 1)));
    }
}
""";

    private static readonly (string FileName, string Content)[] QueryBlockSources =
    [
        ("Morphant.Generated.Construction.Destination__280a40dec1f3e631cea946176332d021.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_280a40dec1f3e631cea946176332d021
{
    /// <summary>
    /// Maps constructor arguments for <see cref="global::Example.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstructorParameters
    {
        /// <summary>
        /// Maps the <c>value</c> argument.
        /// </summary>
        public global::Morphant.Members.ConstructorParameter<string> value = null!;
    }

    /// <summary>
    /// Defines construction of <see cref="global::Example.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Uses convention-based construction.
        /// </summary>
        /// <param name="marker">The convention marker.</param>
        /// <param name="parameters">Optional argument mappings.</param>
        public DestinationConstruction(
            global::Morphant.Markers.ByConventionMarker marker,
            DestinationConstructorParameters? parameters = null)
        {
        }

        /// <summary>
        /// Uses the corresponding destination constructor.
        /// </summary>
        /// <param name="value">Maps the <c>value</c> argument.</param>
        public DestinationConstruction(global::Morphant.Members.ConstructorParameter<string> value)
        {
        }

        /// <summary>
        /// Uses the existing destination as the result.
        /// </summary>
        /// <param name="previous">The existing destination.</param>
        public static implicit operator DestinationConstruction(
            global::Example.Destination previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
        ("Morphant.Generated.MappingExtension.Mapper.SourceToDestination__4734622e4b7330925071bb2eb958cbf3.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Construct(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Construct<global::Example.Source, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Supplies constructor arguments when no destination exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Inline lambda returning a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Construct(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Construct<global::Example.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Resolve(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Resolve<global::Example.Source, global::Example.Destination, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses reuse or construction on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Resolve(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Resolve<global::Example.Source, global::Example.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationConstruction> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::Example.Source, global::Example.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Creates a destination through a callback only when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> ConstructUsing(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.ConstructUsing<global::Example.Source, global::Morphant.Context.MappingContext, global::Example.Destination> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::Example.Source, global::Example.Destination, global::Example.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Chooses the destination through a callback on Create and Update.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> ResolveUsing(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.ResolveUsing<global::Example.Source, global::Example.Destination, global::Morphant.Context.MappingContext, global::Example.Destination> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Convert(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Convert<global::Example.Source?, global::Example.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Convert(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Convert<global::Example.Source?, global::Example.Destination, global::Example.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Maps with ordinary C#, bypassing null policies and member rules.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Convert(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Convert<global::Example.Source?, global::Example.Destination, global::Morphant.Context.MappingContext, global::Example.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
        ("Morphant.Generated.Member.Destination__280a40dec1f3e631cea946176332d021.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_280a40dec1f3e631cea946176332d021
{
    /// <summary>
    /// Maps members of <see cref="global::Example.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Maps <see cref="global::Example.Destination.Value"/>.
        /// </summary>
        public global::Morphant.Members.Member<string> Value
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
"""),
        ("Morphant.Generated.MemberExtension.Mapper.SourceToDestination__4734622e4b7330925071bb2eb958cbf3.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Members(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Members<global::Example.Source, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Members(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Members<global::Example.Source, global::Example.Destination, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Members(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Members<global::Example.Source, global::Example.Destination, global::Example.Destination, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures destination members and matching constructor arguments.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
        /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
        public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Members(
            this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
            global::Morphant.Delegates.Members<global::Example.Source, global::Example.Destination, global::Example.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__915e28902a703dc5a0e72519738253ae.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

using global::System.Linq;

namespace Example
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::Example.Source, global::Example.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::Example.Source) &&
                    destinationType == typeof(global::Example.Destination)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::Example.Destination global::Morphant.ITypeMapper<global::Example.Source, global::Example.Destination>.Create(
            global::Example.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source);
        }

        /// <inheritdoc/>
        global::Example.Destination global::Morphant.ITypeMapper<global::Example.Source, global::Example.Destination>.Update(
            global::Example.Source? source,
            global::Example.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source);
            }

            return __Update(destination);
        }

        private global::Example.Destination __Create(
            global::Example.Source source)
        {
            return new global::Example.Destination(
                value: string.Join(",", from value in source.Values
                    select value + 1));
        }

        private global::Example.Destination __Update(
            global::Example.Destination destination)
        {
            return destination;
        }
    }
}
"""),
    ];
    private static readonly (string FileName, string Content)[] QueryFileSources =
    [
        ("Morphant.Generated.Construction.Destination__280a40dec1f3e631cea946176332d021.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_280a40dec1f3e631cea946176332d021;

/// <summary>
/// Maps constructor arguments for <see cref="global::Example.Destination"/>.
/// </summary>
internal sealed class DestinationConstructorParameters
{
    /// <summary>
    /// Maps the <c>value</c> argument.
    /// </summary>
    public global::Morphant.Members.ConstructorParameter<string> value = null!;
}

/// <summary>
/// Defines construction of <see cref="global::Example.Destination"/>.
/// </summary>
internal sealed class DestinationConstruction
{
    /// <summary>
    /// Uses convention-based construction.
    /// </summary>
    /// <param name="marker">The convention marker.</param>
    /// <param name="parameters">Optional argument mappings.</param>
    public DestinationConstruction(
        global::Morphant.Markers.ByConventionMarker marker,
        DestinationConstructorParameters? parameters = null)
    {
    }

    /// <summary>
    /// Uses the corresponding destination constructor.
    /// </summary>
    /// <param name="value">Maps the <c>value</c> argument.</param>
    public DestinationConstruction(global::Morphant.Members.ConstructorParameter<string> value)
    {
    }

    /// <summary>
    /// Uses the existing destination as the result.
    /// </summary>
    /// <param name="previous">The existing destination.</param>
    public static implicit operator DestinationConstruction(
        global::Example.Destination previous) =>
        throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
}
"""),
        ("Morphant.Generated.MappingExtension.Mapper.SourceToDestination__4734622e4b7330925071bb2eb958cbf3.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant;

internal static partial class MorphantGeneratedMappingExtensions
{
    /// <summary>
    /// Supplies constructor arguments when no destination exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Inline lambda returning a construction expression.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Construct(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Construct<global::Example.Source, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationConstruction> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Supplies constructor arguments when no destination exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Inline lambda returning a construction expression.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Construct(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Construct<global::Example.Source, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationConstruction> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses reuse or construction on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Resolve(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Resolve<global::Example.Source, global::Example.Destination, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationConstruction> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses reuse or construction on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Inline lambda returning the existing destination value or a construction expression.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Resolve(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Resolve<global::Example.Source, global::Example.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationConstruction> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> ConstructUsing(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.ConstructUsing<global::Example.Source, global::Example.Destination> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Creates a destination through a callback only when none exists.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="construct">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/construct-using.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> ConstructUsing(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.ConstructUsing<global::Example.Source, global::Morphant.Context.MappingContext, global::Example.Destination> construct)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> ResolveUsing(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.ResolveUsing<global::Example.Source, global::Example.Destination, global::Example.Destination> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Chooses the destination through a callback on Create and Update.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="resolve">Callback returning the destination; null ends the mapping.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/resolve-using.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> ResolveUsing(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.ResolveUsing<global::Example.Source, global::Example.Destination, global::Morphant.Context.MappingContext, global::Example.Destination> resolve)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Convert(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Convert<global::Example.Source?, global::Example.Destination> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Convert(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Convert<global::Example.Source?, global::Example.Destination, global::Example.Destination> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Maps with ordinary C#, bypassing null policies and member rules.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="mapping">Lambda, method group, or delegate returning the final result.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/convert.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Convert(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Convert<global::Example.Source?, global::Example.Destination, global::Morphant.Context.MappingContext, global::Example.Destination> mapping)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
}
"""),
        ("Morphant.Generated.Member.Destination__280a40dec1f3e631cea946176332d021.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant.Generated.N_280a40dec1f3e631cea946176332d021;

/// <summary>
/// Maps members of <see cref="global::Example.Destination"/>.
/// </summary>
internal sealed record DestinationMembers
{
    /// <summary>
    /// Maps <see cref="global::Example.Destination.Value"/>.
    /// </summary>
    public global::Morphant.Members.Member<string> Value
    {
        get => null!;
        set { }
    }

    public bool Equals(DestinationMembers? other) => false;

    public override int GetHashCode() => 0;

    public override string ToString() => string.Empty;

    private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
}
"""),
        ("Morphant.Generated.MemberExtension.Mapper.SourceToDestination__4734622e4b7330925071bb2eb958cbf3.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

namespace Morphant;

internal static partial class MorphantGeneratedMappingExtensions
{
    /// <summary>
    /// Configures destination members and matching constructor arguments.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Members(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Members<global::Example.Source, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationMembers> members)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Configures destination members and matching constructor arguments.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="members">Inline lambda. Unspecified members follow MemberSelection.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Members(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Members<global::Example.Source, global::Example.Destination, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationMembers> members)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Configures destination members and matching constructor arguments.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Members(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Members<global::Example.Source, global::Example.Destination, global::Example.Destination, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationMembers> members)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

    /// <summary>
    /// Configures destination members and matching constructor arguments.
    /// </summary>
    /// <param name="builder">The mapping to configure.</param>
    /// <param name="members">Inline lambda; constructor inputs cannot read result before construction.</param>
    /// <seealso href="https://github.com/strangeman375/Morphant/blob/main/docs/api/members.md"/>
    public static global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> Members(
        this global::Morphant.MappingBuilder<global::Example.Mapper, global::Example.Source, global::Example.Destination> builder,
        global::Morphant.Delegates.Members<global::Example.Source, global::Example.Destination, global::Example.Destination, global::Morphant.Context.MappingContextMarker, global::Morphant.Generated.N_280a40dec1f3e631cea946176332d021.DestinationMembers> members)
        => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
}
"""),
        ("Morphant.Generated.TypeMapper.Mapper__915e28902a703dc5a0e72519738253ae.g.cs",
        // lang=c#
"""
// <auto-generated />
#nullable enable

using global::System.Linq;

namespace Example;

public partial class Mapper :
    global::Morphant.ITypeMapper<global::Example.Source, global::Example.Destination>
{
    /// <inheritdoc/>
    protected override bool Supports(
        global::System.Type sourceType,
        global::System.Type destinationType) =>
            (sourceType == typeof(global::Example.Source) &&
                destinationType == typeof(global::Example.Destination)) ||
            base.Supports(sourceType, destinationType);

    /// <inheritdoc/>
    global::Example.Destination global::Morphant.ITypeMapper<global::Example.Source, global::Example.Destination>.Create(
        global::Example.Source? source,
        global::Morphant.Context.MappingContext context)
    {
        if (source is null)
        {
            return default!;
        }

        return __Create(source);
    }

    /// <inheritdoc/>
    global::Example.Destination global::Morphant.ITypeMapper<global::Example.Source, global::Example.Destination>.Update(
        global::Example.Source? source,
        global::Example.Destination? destination,
        global::Morphant.Context.MappingContext context)
    {
        if (source is null)
        {
            return default!;
        }

        if (destination is null)
        {
            return __Create(source);
        }

        return __Update(destination);
    }

    private global::Example.Destination __Create(
        global::Example.Source source)
    {
        return new global::Example.Destination(
            value: string.Join(",", from value in source.Values
                select value + 1));
    }

    private global::Example.Destination __Update(
        global::Example.Destination destination)
    {
        return destination;
    }
}
"""),
    ];
}
