<Project>

    <PropertyGroup>
        <LangVersion>10.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

</Project>
