using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperConventionTests;

[TestFixture]
internal sealed class ConstructorTests
{
    [Test]
    public async Task Omits_an_unmatched_optional_constructor_parameter()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; init; }
    }

    public sealed class Destination
    {
        public Destination(int id, string label = "fallback")
        {
            Id = id;
            Label = label;
        }

        public int Id { get; }

        public string Label { get; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source, Destination>)new TestMapper();
            var result = mapper.Create(
                new Source
                {
                    Id = 83
                },
                default(MappingContext));

            if (result.Id != 83 || result.Label != "fallback")
            {
                throw new InvalidOperationException(
                    "An optional constructor parameter was not omitted.");
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination(
                id: source.Id);
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }

    [Test]
    public async Task Does_not_use_mapper_lexical_access_to_a_private_constructor()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; init; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        public sealed class Destination
        {
            private Destination()
            {
            }

            public int Value { get; set; }

            public static Destination Existing() => new();
        }

        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source, TestMapper.Destination>)
                new TestMapper();
            var previous = TestMapper.Destination.Existing();
            var updated = mapper.Update(
                new Source
                {
                    Value = 67
                },
                previous,
                default(MappingContext));

            if (!ReferenceEquals(updated, previous) || updated.Value != 67)
            {
                throw new InvalidOperationException(
                    "Update through an assembly-stable surface failed.");
            }

            try
            {
                _ = mapper.Create(
                    new Source(),
                    default(MappingContext));
            }
            catch (NotSupportedException)
            {
                return;
            }

            throw new InvalidOperationException(
                "Mapper lexical access leaked into constructor selection.");
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.TestMapper.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.TestMapper.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.TestMapper.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.TestMapper.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.TestMapper.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.TestMapper.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.TestMapper.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            throw new global::Morphant.Exceptions.MappingConfigurationException(
                typeof(global::TestCase.Source),
                typeof(global::TestCase.TestMapper.Destination),
                "Convention construction is not available for this destination.");
        }

        private global::TestCase.TestMapper.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.TestMapper.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Value = source.Value;

            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }

    [Test]
    public async Task Evaluates_a_shared_constructor_and_required_member_value_once()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public sealed class Source
    {
        private int reads;

        public int Value
        {
            get
            {
                reads++;
                return 61;
            }
        }

        public int Reads => reads;
    }

    public sealed class Destination
    {
        public Destination(int value)
        {
            ConstructorValue = value;
        }

        public int ConstructorValue { get; }

        public required int Value { get; init; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source, Destination>)new TestMapper();
            var source = new Source();
            var result = mapper.Create(source, default(MappingContext));

            if (result.ConstructorValue != 61 ||
                result.Value != 61 ||
                source.Reads != 1)
            {
                throw new InvalidOperationException(
                    "A shared convention value was evaluated more than once.");
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            var sourceValue = source.Value;

            return new global::TestCase.Destination(
                value: sourceValue)
            {
                Value = sourceValue
            };
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            expected);
    }

    [Test]
    public async Task Honors_SetsRequiredMembers_without_synthesizing_a_required_assignment()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;
using System.Diagnostics.CodeAnalysis;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; init; }
    }

    public sealed class Destination
    {
        [SetsRequiredMembers]
        internal Destination()
        {
            Name = "constructor";
        }

        public required string Name { get; set; }

        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source, Destination>)new TestMapper();
            var result = mapper.Create(
                new Source
                {
                    Value = 59
                },
                default(MappingContext));

            if (result.Name != "constructor" || result.Value != 59)
            {
                throw new InvalidOperationException(
                    "SetsRequiredMembers was not honored.");
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Value = source.Value
            };
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Value = source.Value;

            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp11,
            source,
            expected);
    }

    [Test]
    public async Task Selects_the_only_parameterized_constructor_and_maps_its_arguments()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; init; }

        public string Name { get; init; } = string.Empty;
    }

    public sealed class Destination
    {
        public Destination()
        {
            Id = -1;
            Name = "parameterless";
        }

        internal Destination(int id, string name = "optional")
        {
            Id = id;
            Name = name;
        }

        public int Id { get; }

        public string Name { get; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source, Destination>)new TestMapper();
            var result = mapper.Create(
                new Source
                {
                    Id = 23,
                    Name = "parameterized"
                },
                default(MappingContext));

            if (result.Id != 23 || result.Name != "parameterized")
            {
                throw new InvalidOperationException(
                    "The unambiguous constructor was not used.");
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination(
                id: source.Id,
                name: source.Name);
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }

    [Test]
    public async Task Does_not_fallback_from_an_ambiguous_constructor_selection()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; init; }
    }

    public sealed class Destination
    {
        public Destination()
        {
        }

        public Destination(int value)
        {
            Value = value;
        }

        public Destination(long value)
        {
            Value = (int)value;
        }

        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source, Destination>)new TestMapper();
            var previous = new Destination
            {
                Value = 1
            };
            var updated = mapper.Update(
                new Source
                {
                    Value = 9
                },
                previous,
                default(MappingContext));

            if (!ReferenceEquals(updated, previous) || updated.Value != 9)
            {
                throw new InvalidOperationException(
                    "Update must remain available without construction.");
            }

            try
            {
                _ = mapper.Create(
                    new Source(),
                    default(MappingContext));
            }
            catch (NotSupportedException)
            {
                return;
            }

            throw new InvalidOperationException(
                "Ambiguous convention construction unexpectedly fell back.");
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            throw new global::Morphant.Exceptions.MappingConfigurationException(
                typeof(global::TestCase.Source),
                typeof(global::TestCase.Destination),
                "Convention construction is not available for this destination.");
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Value = source.Value;

            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }
}
