using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperConventionTests;

[TestFixture]
internal sealed class CreateTests
{
    [Test]
    public async Task Creates_a_new_result_and_applies_creation_member_conventions()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; init; }

        public string Name { get; init; } = string.Empty;
    }

    public sealed class Destination
    {
        public int Id { get; init; }

        public string Name { get; set; } = string.Empty;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source, Destination>)new TestMapper();
            var source = new Source
            {
                Id = 17,
                Name = "created"
            };
            var first = mapper.Map(source, default(MappingContext));
            var second = mapper.Map(source, default(MappingContext));

            if (first.Id != 17 ||
                first.Name != "created" ||
                second.Id != 17 ||
                second.Name != "created" ||
                ReferenceEquals(first, second))
            {
                throw new InvalidOperationException(
                    "Convention Create produced an unexpected result.");
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return CreateImpl(source);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return CreateImpl(source);
            }

            destination.Name = source.Name;

            return destination;
        }

        private global::TestCase.Destination CreateImpl(
            global::TestCase.Source source)
        {
            return new global::TestCase.Destination()
            {
                Id = source.Id,
                Name = source.Name
            };
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
        ConventionTypeMapperGeneratorTest.RunAndExecute(
            LanguageVersion.CSharp9,
            source,
            "TestCase.Scenario");
    }
}
