using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperConventionTests;

[TestFixture]
// TODO: Move full production-generator composition to
// Morphant.Generator.IntegrationTests.
internal sealed class ProductionCompositionTests
{
    [Test]
    public async Task Production_generator_composes_the_surface_with_the_mapper_bridge()
    {
        // lang=c#
        const string source =
"""
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
    }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string members =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes member mappings for <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed record DestinationMembers
    {
        /// <summary>
        /// Configures mapping for <see cref="global::TestCase.Destination.Value"/>.
        /// </summary>
        public global::Morphant.Members.Member<int> Value
        {
            get => null!;
            set { }
        }

        public bool Equals(DestinationMembers? other) => false;

        public override int GetHashCode() => 0;

        public override string ToString() => string.Empty;

        private bool PrintMembers(global::System.Text.StringBuilder builder) => false;
    }
}
""";

        // lang=c#
        const string memberExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures mappings for destination members from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="members">A lambda expression that receives the non-null source and the optional existing destination and describes destination member mappings.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures mappings for destination members with access to the selected mapping result.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="members">A lambda expression that receives the non-null source, the optional existing destination, and the non-null selected result and describes destination member mappings.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Members(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Members<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationMembers> members)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string construction =
"""
// <auto-generated />
#nullable enable

namespace TestCase.Morphant.Generated
{
    /// <summary>
    /// Describes construction of <see cref="global::TestCase.Destination"/>.
    /// </summary>
    internal sealed class DestinationConstruction
    {
        /// <summary>
        /// Creates a destination instance using convention-based mapping.
        /// </summary>
        /// <param name="marker">Selects convention-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.ByConventionMarker marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using factory-based construction.
        /// </summary>
        /// <param name="marker">Selects factory-based construction.</param>
        public DestinationConstruction(global::Morphant.Markers.IByFactoryMarker<global::TestCase.Destination> marker)
        {
        }

        /// <summary>
        /// Creates a destination instance using a corresponding constructor.
        /// </summary>
        public DestinationConstruction()
        {
        }

        /// <summary>
        /// Selects an existing destination as the mapping result.
        /// </summary>
        /// <param name="previous">The existing destination to select.</param>
        public static implicit operator DestinationConstruction(
            global::Morphant.Option<global::TestCase.Destination> previous) =>
            throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string extension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Configures how to construct a destination when no existing destination is used.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::TestCase.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures how to select or construct the destination from the source and an optional existing destination.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="construct">A lambda expression that receives the non-null source and the optional existing destination and describes destination construction.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Construct(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Construct<global::TestCase.Source, global::TestCase.Destination, global::TestCase.Morphant.Generated.DestinationConstruction> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Configures a fully manual mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping builder to configure.</param>
        /// <param name="mapping">A lambda expression that receives the original source, the optional existing destination, and the current mapping context.</param>
        /// <returns>The <paramref name="builder"/> instance.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, global::TestCase.Destination> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, global::TestCase.Destination, global::TestCase.Destination> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string mapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return CreateImpl(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Map(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return CreateImpl(source, context);
            }

            return UpdateImpl(source, destination, context);
        }

        private global::TestCase.Destination CreateImpl(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination();
        }

        private global::TestCase.Destination UpdateImpl(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }
    }
}
""";

        await ProductionGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.Construction.TestCase_Destination.g.cs",
                construction
            ),
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__TestCase_Destination.g.cs",
                extension
            ),
            (
                "Morphant.Generated.Member.TestCase_Destination.g.cs",
                members
            ),
            (
                "Morphant.Generated.MemberExtension.TestCase_Source__TestCase_Destination.g.cs",
                memberExtension
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                mapper
            ));
    }
}
