using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperConventionTests;

[TestFixture]
internal sealed class UpdateTests
{
    [Test]
    public async Task Reuses_the_previous_reference_and_only_applies_post_construction_conventions()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;
using Morphant.Context;
using System;

namespace TestCase
{
    public sealed class Source
    {
        public int Mutable { get; init; }

        public int CreationOnly { get; init; }
    }

    public sealed class Destination
    {
        public int Mutable { get; set; }

        public int CreationOnly { get; init; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }

    public static class Scenario
    {
        public static void Verify()
        {
            var mapper =
                (ITypeMapper<Source, Destination>)new TestMapper();
            var previous = new Destination
            {
                Mutable = 1,
                CreationOnly = 41
            };
            var result = mapper.Update(
                new Source
                {
                    Mutable = 7,
                    CreationOnly = 99
                },
                previous,
                default(MappingContext));

            if (!ReferenceEquals(result, previous) ||
                result.Mutable != 7 ||
                result.CreationOnly != 41)
            {
                throw new InvalidOperationException(
                    "Convention Update produced an unexpected result.");
            }
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Mutable = source.Mutable,
                CreationOnly = source.CreationOnly
            };
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Mutable = source.Mutable;

            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
        ConventionTypeMapperGeneratorTest.RunAndExecute(
            LanguageVersion.CSharp9,
            source,
            "TestCase.Scenario");
    }

    [Test]
    public async Task Allocates_collision_safe_Create_and_Update_helper_names()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public readonly struct Source
    {
        public int Value { get; init; }
    }

    public sealed class Destination
    {
        public int Value { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        private static void __Create() { }

        private static void __Update() { }

        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
            => __Create1(source, context);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (destination is null)
            {
                return __Create1(source, context);
            }

            return __Update1(source, destination, context);
        }

        private global::TestCase.Destination __Create1(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination()
            {
                Value = source.Value
            };
        }

        private global::TestCase.Destination __Update1(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            destination.Value = source.Value;

            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }
}
