using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using Morphant.Generator.MappingPair;
using Morphant.Generator.Settings;
using Morphant.Generator.TypeMapperGeneration;

namespace Morphant.Generator.UnitTests;

[TestFixture]
internal sealed class TypeMapperGenerationObservationTests
{
    [Test]
    public async Task Captures_constructor_candidates_and_parameter_rules()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source
    {
        public int Id { get; init; }
    }

    public sealed class Destination
    {
        public Destination(int id)
        {
        }

        public Destination(string name)
        {
        }
    }

    public abstract partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
        }

        public static Destination Build(Source source) =>
            new Destination(source.Id);
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

// Convention: strategy=Greediest; selected=Destination(System_Int32:id); origin=<none>
// Convention candidate 0: Destination(System_Int32:id); rejection=None
// Convention candidate 0 rule 0: parameter=id; origin=Convention; source=Id; applicable=True; rejection=None; origin-node=<none>
// Convention candidate 1: Destination(System_String:name); rejection=MissingSourceMember
// Convention candidate 1 rule 0: parameter=name; origin=Convention; source=<none>; applicable=False; rejection=MissingSourceMember; origin-node=<none>
// Explicit: strategy=Explicit; selected=Destination(System_Int32:id); origin=ObjectCreationExpression
// Explicit candidate 0: Destination(System_Int32:id); rejection=None
// Explicit candidate 0 rule 0: parameter=id; origin=Value; source=<none>; applicable=True; rejection=None; origin-node=SimpleMemberAccessExpression
// Explicit candidate 1: Destination(System_String:name); rejection=StrategyShape
""";

        await ObservationGeneratorTest.RunAndAssert(source, expected);
    }

    private sealed class ObservationGeneratorTest
        : CSharpSourceGeneratorTest<
            TestTypeMapperGenerationObservationGenerator,
            DefaultVerifier>
    {
        private const string NewLine = "\r\n";

        private ObservationGeneratorTest()
        {
            CompilerDiagnostics = CompilerDiagnostics.Warnings;
            TestState.AdditionalReferences.Add(typeof(TypeMapper).Assembly);
        }

        protected override ParseOptions CreateParseOptions()
        {
            return new CSharpParseOptions(
                LanguageVersion.CSharp9,
                DocumentationMode.Diagnose);
        }

        public static async Task RunAndAssert(
            string source,
            string expected)
        {
            var test = new ObservationGeneratorTest
            {
                TestCode = source
            };

            test.TestState.GeneratedSources.Add(
            (
                typeof(TestTypeMapperGenerationObservationGenerator),
                "Morphant.Generated.Test.MappingPlanObservations.g.cs",
                NormalizeGeneratedSource(expected)
            ));

            await test.RunAsync();
        }

        private static string NormalizeGeneratedSource(string source)
        {
            var normalized = source
                .Replace("\r\n", "\n")
                .Replace('\r', '\n')
                .Replace("\n", NewLine);

            return normalized.EndsWith(NewLine, StringComparison.Ordinal)
                ? normalized
                : normalized + NewLine;
        }
    }
}

internal sealed class TestTypeMapperGenerationObservationGenerator
    : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var snapshot = context.CompilationProvider.Select(
            static (compilation, cancellationToken) =>
                BuildSnapshot(
                    (CSharpCompilation)compilation,
                    cancellationToken));

        context.RegisterSourceOutput(
            snapshot,
            static (productionContext, source) =>
                productionContext.AddSource(
                    "Morphant.Generated.Test.MappingPlanObservations.g.cs",
                    SourceText.From(source, Encoding.UTF8)));
    }

    private static string BuildSnapshot(
        CSharpCompilation compilation,
        CancellationToken cancellationToken)
    {
        var source = compilation.GetTypeByMetadataName("TestCase.Source") ??
            throw new InvalidOperationException("Source type is missing.");
        var destination =
            compilation.GetTypeByMetadataName("TestCase.Destination") ??
            throw new InvalidOperationException(
                "Destination type is missing.");
        var mapper =
            compilation.GetTypeByMetadataName("TestCase.TestMapper") ??
            throw new InvalidOperationException("Mapper type is missing.");
        var capabilities = new MappingPairCapabilities(
            Runtime: true,
            Manual: true,
            MappingConstructionKind.Structured,
            Members: true);
        var memberMappings = ConventionMemberMappingPlanner.Build(
            source,
            destination,
            capabilities,
            compilation,
            mapper,
            cancellationToken);
        var convention = ConventionConstructorMappingPlanner.Build(
            source,
            destination,
            memberMappings.BuildConstructorInitializationPlan(
                replacement: false),
            capabilities,
            ConstructorSelectionValue.Greediest,
            compilation,
            mapper,
            nonNullSourceName: "source",
            cancellationToken);
        var creation = compilation.SyntaxTrees.Single()
            .GetRoot(cancellationToken)
            .DescendantNodes()
            .OfType<ObjectCreationExpressionSyntax>()
            .Single();
        var semanticModel = compilation.GetSemanticModel(
            creation.SyntaxTree);
        var arguments = creation.ArgumentList!.Arguments.Select(argument =>
                new StructuredObjectArgument(
                    argument,
                    argument.Expression))
            .ToImmutableArray();
        var explicitPlanning = ExplicitStructuredConstructorPlanner.Build(
            arguments,
            source,
            destination,
            compilation,
            mapper,
            semanticModel,
            static expression => expression.ToString(),
            static (expression, _) =>
                new TypeMapperRewrittenDependencyExpression(
                    expression.ToString(),
                    DependencyExpression: null),
            creation,
            cancellationToken);
        var result = new StringBuilder();

        result.AppendLine("// <auto-generated />");
        result.AppendLine("#nullable enable");
        result.AppendLine();
        AppendObservation(
            result,
            "Convention",
            convention.Observation);
        AppendObservation(
            result,
            "Explicit",
            explicitPlanning.Observation);

        return result.ToString()
            .Replace("\r\n", "\n")
            .Replace('\r', '\n')
            .Replace("\n", "\r\n");
    }

    private static void AppendObservation(
        StringBuilder result,
        string label,
        ConstructorPlanningObservation observation)
    {
        result.Append("// ")
            .Append(label)
            .Append(": strategy=")
            .Append(observation.Strategy?.ToString() ?? "<none>")
            .Append("; selected=")
            .Append(FormatConstructor(observation.SelectedConstructor))
            .Append("; origin=")
            .Append(observation.StrategyOrigin?.Kind().ToString() ?? "<none>")
            .AppendLine();

        for (var candidateIndex = 0;
             candidateIndex < observation.Candidates.Length;
             candidateIndex++)
        {
            var candidate = observation.Candidates[candidateIndex];

            result.Append("// ")
                .Append(label)
                .Append(" candidate ")
                .Append(candidateIndex)
                .Append(": ")
                .Append(FormatConstructor(candidate.Constructor))
                .Append("; rejection=")
                .Append(candidate.RejectionReason)
                .AppendLine();

            for (var ruleIndex = 0;
                 ruleIndex < candidate.ParameterRules.Length;
                 ruleIndex++)
            {
                var rule = candidate.ParameterRules[ruleIndex];

                result.Append("// ")
                    .Append(label)
                    .Append(" candidate ")
                    .Append(candidateIndex)
                    .Append(" rule ")
                    .Append(ruleIndex)
                    .Append(": parameter=")
                    .Append(rule.ParameterName)
                    .Append("; origin=")
                    .Append(rule.Origin)
                    .Append("; source=")
                    .Append(rule.SourceMember?.Name ?? "<none>")
                    .Append("; applicable=")
                    .Append(rule.IsApplicable)
                    .Append("; rejection=")
                    .Append(rule.RejectionReason)
                    .Append("; origin-node=")
                    .Append(rule.OriginNode?.Kind().ToString() ?? "<none>")
                    .AppendLine();
            }
        }
    }

    private static string FormatConstructor(IMethodSymbol? constructor)
    {
        if (constructor is null)
        {
            return "<none>";
        }

        return constructor.ContainingType.Name + "(" +
            string.Join(
                ",",
                constructor.Parameters.Select(parameter =>
                    parameter.Type.SpecialType + ":" + parameter.Name)) +
            ")";
    }
}
