using Microsoft.CodeAnalysis.CSharp;
using Morphant.Context;
using Morphant.Exceptions;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests;

[TestFixture]
internal sealed class TypeMapperObservableFailureTests
{
    [Test]
    public void Exposes_stable_failure_types_and_messages()
    {
        var failures = new (MorphantException Failure, string Message)[]
        {
            (
                new MappingConfigurationException(
                    typeof(string),
                    typeof(int),
                    "The plan is invalid."),
                "Mapping from 'System.String' to 'System.Int32' could not " +
                "be generated. The plan is invalid."
            ),
            (
                new MappingOperationNotSupportedException(
                    MappingOperation.Update,
                    typeof(string),
                    typeof(int)),
                "The Update operation is disabled by the effective " +
                "MappingMode for mapping from 'System.String' to " +
                "'System.Int32'."
            ),
            (
                new NullSourceException(typeof(string), typeof(int)),
                "The source is null for mapping from 'System.String' to " +
                "'System.Int32', while the effective NullSourceHandling " +
                "is Throw."
            ),
            (
                new NullDestinationException(typeof(string), typeof(int)),
                "The destination is null for mapping from 'System.String' " +
                "to 'System.Int32', while the effective " +
                "NullDestinationHandling is Throw."
            ),
            (
                new MappingNotFoundException(typeof(string), typeof(int)),
                "No mapping is registered from 'System.String' to " +
                "'System.Int32'."
            ),
            (
                new AmbiguousMappingException(typeof(string), typeof(int)),
                "Multiple mappings are registered from 'System.String' to " +
                "'System.Int32'. Exactly one mapping is required."
            ),
            (
                new InvalidMappingRegistrationException(
                    typeof(string),
                    typeof(int)),
                "The registered mapping from 'System.String' to " +
                "'System.Int32' resolved to null."
            ),
            (
                new MappingScopeCompletedException(
                    typeof(string),
                    typeof(int)),
                "The mapping scope has already completed; mapping from " +
                "'System.String' to 'System.Int32' cannot start."
            ),
            (
                new MappingServiceProviderMissingException(),
                "A service provider is required to create a Morphant " +
                "mapper."
            ),
            (
                new NestedDestinationTypeMismatchException(
                    typeof(string),
                    typeof(int)),
                "The current nested destination has runtime type " +
                "'System.Int32', which cannot be used as 'System.String'."
            ),
            (
                new NestedDestinationTypeMismatchException(
                    typeof(string),
                    null),
                "The current nested destination is null and cannot be " +
                "used as 'System.String'."
            ),
            (
                new OptionValueMissingException(),
                "Option contains no value."
            ),
            (
                new RuntimeInvocationNotSupportedException(),
                "This API is intended for use by source generators only " +
                "and must not be invoked at runtime."
            ),
            (
                new UnmatchedMappingSwitchException(),
                "No branch of the declarative mapping switch matched the " +
                "runtime value."
            )
        };

        Assert.Multiple(() =>
        {
            foreach (var (failure, message) in failures)
            {
                Assert.That(failure.Message, Is.EqualTo(message));
            }
        });
    }

    [Test]
    public async Task Emits_complete_stubs_for_an_invalid_effective_setting()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Source { }
    public sealed class Destination { }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>();
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
            => throw new global::Morphant.Exceptions.MappingConfigurationException(
                typeof(global::TestCase.Source),
                typeof(global::TestCase.Destination),
                "The effective MappingMode is invalid.");

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
            => throw new global::Morphant.Exceptions.MappingConfigurationException(
                typeof(global::TestCase.Source),
                typeof(global::TestCase.Destination),
                "The effective MappingMode is invalid.");
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssertWithAnalyzerConfig(
            LanguageVersion.CSharp9,
            source,
            """
is_global = true

build_property.MorphantMappingMode = Unexpected
""",
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Emits_only_a_runtime_stub_for_an_unsupported_root()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System.Collections.Generic;
using Morphant;

namespace TestCase
{
    public sealed class Destination { }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<List<int>, Destination>();
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::System.Collections.Generic.List<int>, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::System.Collections.Generic.List<int>, global::TestCase.Destination>.Create(
            global::System.Collections.Generic.List<int>? source,
            global::Morphant.Context.MappingContext context)
            => throw new global::Morphant.Exceptions.MappingConfigurationException(
                typeof(global::System.Collections.Generic.List<int>),
                typeof(global::TestCase.Destination),
                "The source type 'global::System.Collections.Generic.List<int>' is a collection or buffer root. Collection mapping is not available.");

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::System.Collections.Generic.List<int>, global::TestCase.Destination>.Update(
            global::System.Collections.Generic.List<int>? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
            => throw new global::Morphant.Exceptions.MappingConfigurationException(
                typeof(global::System.Collections.Generic.List<int>),
                typeof(global::TestCase.Destination),
                "The source type 'global::System.Collections.Generic.List<int>' is a collection or buffer root. Collection mapping is not available.");
    }
}
""";

        await ProductionGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper.g.cs",
                expected
            ));
    }

    [Test]
    public async Task Keeps_independent_pairs_when_generic_contracts_unify()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed class Envelope<T> { }
    public sealed class Result<T> { }
    public sealed class Source { }
    public sealed class Destination { }

    [MorphantMapper]
    public partial class TestMapper<T> : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
            builder.Map<Envelope<T>, Result<string>>();
            builder.Map<Envelope<string>, Result<T>>();
            builder.Map<Source, Destination>();
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper<T> :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::TestCase.Destination __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            return new global::TestCase.Destination();
        }

        private global::TestCase.Destination __Update(
            global::TestCase.Source source,
            global::TestCase.Destination destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssertWithAnalyzerConfig(
            LanguageVersion.CSharp9,
            source,
            "is_global = true",
            (
                "Morphant.Generated.TypeMapper.TestCase_TestMapper_1.g.cs",
                expected
            ));
    }
}
