using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests;

[TestFixture]
internal sealed class TypeMapperExpressionTransferTests
{
    [Test]
    public async Task Keeps_a_source_owned_warning_and_suppresses_only_its_generated_duplicate()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System;
using Morphant;

namespace Morphant
{
    // Makes the input compile before generation; the exact generated overload
    // remains the better candidate after generation.
    internal static partial class MorphantGeneratedMappingExtensions
    {
        public static global::Morphant.MapperBuilder<
            global::TestCase.Source,
            global::TestCase.Destination> Convert(
                this global::Morphant.MapperBuilder<
                    global::TestCase.Source,
                    global::TestCase.Destination> builder,
                global::Morphant.Delegates.Convert<
                    global::TestCase.Source?,
                    global::TestCase.Destination> mapping,
                int testOnly = 0) =>
            throw new global::Morphant.Exceptions
                .RuntimeInvocationNotSupportedException();
    }
}

namespace TestCase
{
    public sealed class Source
    {
        public int Value { get; set; }
    }

    public sealed class Destination
    {
        public Destination(int value) => Value = value;

        public int Value { get; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Destination>()
                .Convert(source => new Destination(
                    {|CS0618:Read(source)|}));

        [Obsolete("intentional transfer warning")]
        private static int Read(Source? source) => source?.Value ?? 0;
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::TestCase.Destination)) ||
                base.Supports(sourceType, destinationType);

        #pragma warning disable CS0618

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        /// <inheritdoc/>
        global::TestCase.Destination global::Morphant.ITypeMapper<global::TestCase.Source, global::TestCase.Destination>.Update(
            global::TestCase.Source? source,
            global::TestCase.Destination? destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        private global::TestCase.Destination __ConvertDestination(global::TestCase.Source? source) => new global::TestCase.Destination(global::TestCase.TestMapper.Read(source));

        #pragma warning restore CS0618
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }

    [Test]
    public async Task Emits_async_warning_and_extension_transfer_context()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System.Threading.Tasks;
using Morphant;
using TransferExtensions;

namespace Morphant
{
    // Makes the input compile before generation; the exact generated overload
    // remains the better candidate after generation.
    internal static partial class MorphantGeneratedMappingExtensions
    {
        public static global::Morphant.MapperBuilder<
            global::TestCase.Source,
            global::System.Threading.Tasks.Task<int>> Convert(
                this global::Morphant.MapperBuilder<
                    global::TestCase.Source,
                    global::System.Threading.Tasks.Task<int>> builder,
                global::Morphant.Delegates.Convert<
                    global::TestCase.Source?,
                    global::System.Threading.Tasks.Task<int>> mapping,
                int testOnly = 0) =>
            throw new global::Morphant.Exceptions
                .RuntimeInvocationNotSupportedException();
    }
}

namespace TransferExtensions
{
    public static class TextExtensions
    {
        public static int Measure(this string value) => value.Length;
    }
}

namespace TestCase
{
    public sealed class Source
    {
        public string? Text { get; set; }

        public string? ReadText() => Text;
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override void Configure(MapperBuilder builder)
        {
#pragma warning disable CS8602
            builder.Map<Source, Task<int>>()
                .Convert(async source =>
                {
                    await Task.Yield();
                    return (source!.ReadText()?.Measure() ?? 0) +
                        source.Text.Length;
                });
#pragma warning restore CS8602
        }
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Threading.Tasks.Task<int>>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::System.Threading.Tasks.Task<int>)) ||
                base.Supports(sourceType, destinationType);

        #pragma warning disable CS8602

        /// <inheritdoc/>
        global::System.Threading.Tasks.Task<int> global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Threading.Tasks.Task<int>>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        /// <inheritdoc/>
        global::System.Threading.Tasks.Task<int> global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Threading.Tasks.Task<int>>.Update(
            global::TestCase.Source? source,
            global::System.Threading.Tasks.Task<int>? destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        private async global::System.Threading.Tasks.Task<int> __ConvertDestination(global::TestCase.Source? source)
        {
            await global::System.Threading.Tasks.Task.Yield();
            return ((source!.ReadText())is { } conditionalReceiver ? global::TransferExtensions.TextExtensions.Measure(conditionalReceiver) : default(int? ) ?? 0) + source.Text.Length;
        }

        #pragma warning restore CS8602
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            expected);
    }

    [Test]
    public async Task Emits_unsafe_only_for_the_transferred_mapping()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using System;
using Morphant;

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        public static global::Morphant.MapperBuilder<
            global::TestCase.Source,
            int> ConstructUsing(
                this global::Morphant.MapperBuilder<
                    global::TestCase.Source,
                    int> builder,
                global::Morphant.Delegates.ConstructUsing<
                    global::TestCase.Source,
                    int> construct,
                int testOnly = 0) =>
            throw new global::Morphant.Exceptions
                .RuntimeInvocationNotSupportedException();
    }
}

namespace TestCase
{
    public sealed class Source
    {
        public IntPtr Pointer { get; set; }
    }

    [MorphantMapper]
    public partial class TestMapper : TypeMapper
    {
        protected override unsafe void Configure(MapperBuilder builder) =>
            builder.Map<Source, int>()
                .ConstructUsing(source => *(int*)source.Pointer);
    }
}
""";

        // lang=c#
        const string expected =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class TestMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(int)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::TestCase.Source, int>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        int global::Morphant.ITypeMapper<global::TestCase.Source, int>.Update(
            global::TestCase.Source? source,
            int destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Update(source, destination, context);
        }

        private unsafe int __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            int result = __ConstructUsing(source);

            return result;
        }

        private unsafe int __Update(
            global::TestCase.Source source,
            int destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }

        private unsafe int __ConstructUsing(global::TestCase.Source source) => *(int*)source.Pointer;
    }
}
""";

        await ConventionTypeMapperGeneratorTest.RunAndAssertUnsafe(
            LanguageVersion.CSharp9,
            source,
            expected);
    }
}
