using Microsoft.CodeAnalysis.CSharp;
using Morphant.Generator.UnitTests.TestUtils;

namespace Morphant.Generator.UnitTests.TypeMapperConvertTests;

[TestFixture]
internal sealed class OverloadTests
{
    [Test]
    public async Task Emits_source_only_and_previous_aware_Convert_callbacks_with_operation_modes()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591

using Morphant;

namespace TestCase
{
    public sealed record Source(int Value, string Text);

    [MorphantMapper]
    public partial class SourceOnlyMapper : TypeMapper<SourceOnlyMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, int?>()
                .Convert(source => source?.Value);
    }

    [MorphantMapper]
    public partial class PreviousMapper : TypeMapper<PreviousMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, int?>()
                .Convert((source, previous) =>
                    previous.HasValue
                        ? previous.Value + (source?.Value ?? 0)
                        : source?.Value);
    }

    [MorphantMapper]
    public partial class CreateOnlyMapper : TypeMapper<CreateOnlyMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, int?>(MappingMode.Create)
                .Convert(source => source?.Value);
    }

    [MorphantMapper]
    public partial class UpdateOnlyMapper : TypeMapper<UpdateOnlyMapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, int?>(MappingMode.Update)
                .Convert((source, previous) =>
                    previous.HasValue
                        ? previous.Value
                        : source?.Value);
    }
}
""";

        // lang=c#
        const string expectedMappingExtension =
"""
// <auto-generated />
#nullable enable

namespace Morphant
{
    internal static partial class MorphantGeneratedMappingExtensions
    {
        /// <summary>
        /// Uses a callback to construct a destination when none exists.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, int?> ConstructUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, int?> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, int?> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to construct a destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="construct">The construction callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, int?> ConstructUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, int?> builder,
            global::Morphant.Delegates.ConstructUsing<global::TestCase.Source, global::Morphant.Context.MappingContext, int?> construct)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, int?> ResolveUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, int?> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, int, int?> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with context to select or construct the destination.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="resolve">The result callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, int?> ResolveUsing(
            this global::Morphant.MapperBuilder<global::TestCase.Source, int?> builder,
            global::Morphant.Delegates.ResolveUsing<global::TestCase.Source, int, global::Morphant.Context.MappingContext, int?> resolve)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, int?> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, int?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, int?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, int?> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, int?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, int, int?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();

        /// <summary>
        /// Uses a callback with the optional existing destination and context as the complete mapping algorithm.
        /// </summary>
        /// <param name="builder">The mapping to configure.</param>
        /// <param name="mapping">The mapping callback.</param>
        /// <returns>The same mapping builder.</returns>
        public static global::Morphant.MapperBuilder<global::TestCase.Source, int?> Convert(
            this global::Morphant.MapperBuilder<global::TestCase.Source, int?> builder,
            global::Morphant.Delegates.Convert<global::TestCase.Source?, int, global::Morphant.Context.MappingContext, int?> mapping)
            => throw new global::Morphant.Exceptions.RuntimeInvocationNotSupportedException();
    }
}
""";

        // lang=c#
        const string expectedSourceOnlyMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class SourceOnlyMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int?>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(int?)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Update(
            global::TestCase.Source? source,
            int? destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        private int? __ConvertDestination(global::TestCase.Source? source) => source?.Value;
    }
}
""";

        // lang=c#
        const string expectedPreviousMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class PreviousMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int?>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(int?)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(
                source,
                global::Morphant.Option<int>.None);

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Update(
            global::TestCase.Source? source,
            int? destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(
                source,
                destination is null
                    ? global::Morphant.Option<int>.None
                    : global::Morphant.Option<int>.Some(destination.Value));

        private int? __ConvertDestination(global::TestCase.Source? source, global::Morphant.Option<int> previous) => previous.HasValue ? previous.Value + (source?.Value ?? 0) : source?.Value;
    }
}
""";

        // lang=c#
        const string expectedCreateOnlyMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class CreateOnlyMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int?>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(int?)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(source);

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Update(
            global::TestCase.Source? source,
            int? destination,
            global::Morphant.Context.MappingContext context)
            => throw new global::Morphant.Exceptions.MappingOperationNotSupportedException(
                global::Morphant.Context.MappingOperation.Update,
                typeof(global::TestCase.Source),
                typeof(int?),
                global::Morphant.MappingMode.Create);

        private int? __ConvertDestination(global::TestCase.Source? source) => source?.Value;
    }
}
""";

        // lang=c#
        const string expectedUpdateOnlyMapper =
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class UpdateOnlyMapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, int?>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(int?)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
            => throw new global::Morphant.Exceptions.MappingOperationNotSupportedException(
                global::Morphant.Context.MappingOperation.Create,
                typeof(global::TestCase.Source),
                typeof(int?),
                global::Morphant.MappingMode.Update);

        /// <inheritdoc/>
        int? global::Morphant.ITypeMapper<global::TestCase.Source, int?>.Update(
            global::TestCase.Source? source,
            int? destination,
            global::Morphant.Context.MappingContext context)
            => __ConvertDestination(
                source,
                destination is null
                    ? global::Morphant.Option<int>.None
                    : global::Morphant.Option<int>.Some(destination.Value));

        private int? __ConvertDestination(global::TestCase.Source? source, global::Morphant.Option<int> previous) => previous.HasValue ? previous.Value : source?.Value;
    }
}
""";

        await ProductionGeneratorTest.RunAndAssert(
            LanguageVersion.CSharp9,
            source,
            (
                "Morphant.Generated.MappingExtension.TestCase_Source__System_Nullable_System_Int32_.g.cs",
                expectedMappingExtension
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_SourceOnlyMapper.g.cs",
                expectedSourceOnlyMapper
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_PreviousMapper.g.cs",
                expectedPreviousMapper
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_CreateOnlyMapper.g.cs",
                expectedCreateOnlyMapper
            ),
            (
                "Morphant.Generated.TypeMapper.TestCase_UpdateOnlyMapper.g.cs",
                expectedUpdateOnlyMapper
            ));
    }
}
