using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Morphant.Generator.Settings;

namespace Morphant.Generator.TypeMapperGeneration;

internal static class TypeMapperEmitter
{
    private const string TransferProbePathPrefix =
        "Morphant.TransferProbe.Mapping.";

    private const string InvalidMappingModeExceptionMessage =
        "MappingMode has an invalid value.";

    private const string InvalidNullSourceHandlingExceptionMessage =
        "NullSourceHandling has an invalid value.";

    private const string InvalidNullDestinationHandlingExceptionMessage =
        "NullDestinationHandling has an invalid value.";

    public static SourceText Emit(TypeMapperModel model)
    {
        return Emit(model, includeTransferProbeLocations: false);
    }

    internal static SourceText EmitTransferProbe(TypeMapperModel model)
    {
        return Emit(model, includeTransferProbeLocations: true);
    }

    internal static bool TryGetTransferProbeMappingIndex(
        Diagnostic diagnostic,
        out int mappingIndex)
    {
        var path = diagnostic.Location.GetMappedLineSpan().Path;

        if (path.StartsWith(
                TransferProbePathPrefix,
                StringComparison.Ordinal) &&
            path.EndsWith(".g.cs", StringComparison.Ordinal) &&
            int.TryParse(
                path.Substring(
                    TransferProbePathPrefix.Length,
                    path.Length - TransferProbePathPrefix.Length -
                    ".g.cs".Length),
                out mappingIndex))
        {
            return true;
        }

        mappingIndex = -1;
        return false;
    }

    private static SourceText Emit(
        TypeMapperModel model,
        bool includeTransferProbeLocations)
    {
        var writer = new CodeWriter();

        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();

        if (model.RequiresSystemLinq)
        {
            writer.Line("using global::System.Linq;");
            writer.Line();
        }

        if (model.Namespace.Length > 0)
        {
            writer.OpenBlock($"namespace {model.Namespace}");
        }

        foreach (var containingType in model.ContainingTypes)
        {
            writer.OpenBlock(
                $"partial {containingType.DeclarationKind} " +
                containingType.TypeName +
                containingType.TypeParameterList);
        }

        WriteType(
            writer,
            model,
            includeTransferProbeLocations);

        for (var index = model.ContainingTypes.Length - 1;
             index >= 0;
             index--)
        {
            writer.CloseBlock();
        }

        if (model.Namespace.Length > 0)
        {
            writer.CloseBlock();
        }

        return SourceText.From(
            IncludedPatternLocalNameRewriter.Rewrite(
                writer.ToString()),
            Encoding.UTF8);
    }

    private static void WriteType(
        CodeWriter writer,
        TypeMapperModel model,
        bool includeTransferProbeLocations)
    {
        writer.Line(
            $"{model.Accessibility} " +
            "partial class " +
            model.TypeName +
            model.TypeParameterList +
            " :");
        writer.Indent();

        for (var index = 0; index < model.Mappings.Length; index++)
        {
            var suffix = index < model.Mappings.Length - 1
                ? ","
                : string.Empty;

            writer.Line(
                model.Mappings[index].InterfaceTypeName + suffix);
        }

        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WriteSupports(writer, model.Mappings);

        for (var index = 0; index < model.Mappings.Length; index++)
        {
            writer.Line();

            if (includeTransferProbeLocations)
            {
                writer.Line(
                    $"#line 1 \"{TransferProbePathPrefix}{index}.g.cs\"");
            }

            WriteMapping(writer, model.Mappings[index]);

            if (includeTransferProbeLocations)
            {
                writer.Line("#line default");
                writer.Line("#line hidden");
            }
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteSupports(
        CodeWriter writer,
        ImmutableArray<TypeMapperMappingModel> mappings)
    {
        writer.Line("/// <inheritdoc/>");
        writer.Line("protected override bool Supports(");
        writer.Indent();
        writer.Line("global::System.Type sourceType,");
        writer.Line("global::System.Type destinationType) =>");
        writer.Indent();

        foreach (var mapping in mappings)
        {
            writer.Line(
                $"(sourceType == typeof({mapping.SourceRuntimeTypeName}) &&");
            writer.Indent();
            writer.Line(
                "destinationType == typeof(" +
                mapping.DestinationRuntimeTypeName +
                ")) ||");
            writer.Unindent();
        }

        writer.Line("base.Supports(sourceType, destinationType);");
        writer.Unindent();
        writer.Unindent();
    }

    private static void WriteMapping(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var warningSuppressions =
            mapping.TransferredWarningSuppressions.IsDefault
                ? ImmutableArray<string>.Empty
                : mapping.TransferredWarningSuppressions;

        if (!warningSuppressions.IsEmpty)
        {
            writer.Line(
                "#pragma warning disable " +
                string.Join(", ", warningSuppressions));
            writer.Line();
        }

        WriteCreate(writer, mapping);
        writer.Line();
        WriteUpdate(writer, mapping);

        if (mapping.CreateImplMethodName is not null)
        {
            writer.Line();
            WriteCreateImpl(writer, mapping);
        }

        if (mapping.UpdateImplMethodName is not null)
        {
            writer.Line();
            WriteUpdateImpl(writer, mapping);
        }

        if (mapping.EffectiveSettings.IsMappingModeValid &&
            !mapping.HelperMethodDeclarations.IsDefaultOrEmpty)
        {
            foreach (var declaration in
                     mapping.HelperMethodDeclarations)
            {
                writer.Line();
                WriteMultilineDeclaration(
                    writer,
                    declaration);
            }
        }

        if (!warningSuppressions.IsEmpty)
        {
            writer.Line();
            writer.Line(
                "#pragma warning restore " +
                string.Join(", ", warningSuppressions));
        }
    }

    private static void WriteCreate(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        writer.Line("/// <inheritdoc/>");
        writer.Line(
            $"{mapping.DestinationTypeName} " +
            $"{mapping.InterfaceTypeName}.Create(");
        writer.Indent();
        writer.Line(
            $"{mapping.MaybeNullSourceTypeName} source,");
        writer.Line("global::Morphant.Context.MappingContext context)");

        if (mapping.Failure is
            { } configurationFailure)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                configurationFailure,
                update: false);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsMappingModeValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidMappingModeExceptionMessage,
                update: false);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.SupportsCreate)
        {
            WriteUnsupportedOperation(
                writer,
                mapping,
                "Create");
            writer.Unindent();
            return;
        }

        if (mapping.CreateOperationFailure is { } operationFailure)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                operationFailure,
                update: false);
            writer.Unindent();
            return;
        }

        if (mapping.ManualMapping is { } manualMapping)
        {
            WriteManualMapping(
                writer,
                mapping,
                manualMapping,
                update: false);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsNullSourceHandlingValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidNullSourceHandlingExceptionMessage,
                update: false);
            writer.Unindent();
            return;
        }

        if (mapping.SourceCanBeNull)
        {
            WriteCreateBody(
                writer,
                mapping);
            return;
        }

        var methodName =
            mapping.CreateImplMethodName ??
            throw new InvalidOperationException(
                "A Create implementation method name is required.");

        writer.Line(
            $"=> {BuildCreateImplCall(mapping, methodName, update: false)};");
        writer.Unindent();
    }

    private static void WriteCreateBody(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WriteSourceNullHandling(
            writer,
            mapping,
            update: false);
        writer.Line();
        WriteNonNullSourceNormalization(writer, mapping);
        WriteCreateCallOrStatements(
            writer,
            mapping,
            update: false);

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteCreateCallOrStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update)
    {
        if (mapping.CreateImplMethodName is
            { } createImplMethodName)
        {
            var call = BuildCreateImplCall(
                mapping,
                createImplMethodName,
                update);
            writer.Line($"return {call};");
            return;
        }

        WriteCreateStatements(
            writer,
            mapping,
            update);
    }

    private static void WriteCreateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update) =>
        WriteCreateStatements(
            writer,
            mapping,
            MappingOperationExpression(update));

    private static void WriteCreateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string operationExpression)
    {
        if (mapping.Failure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedExceptionMessage,
                operationExpression);
            return;
        }

        if (mapping.ControlFlow is { } controlFlow)
        {
            WriteControlFlowCreateNode(
                writer,
                controlFlow.CreateRoot,
                operationExpression);
            return;
        }

        WriteControlFlowCreateLeaf(
            writer,
            mapping,
            operationExpression);
    }

    private static void WriteControlFlowCreateNode(
        CodeWriter writer,
        TypeMapperControlFlowNode node,
        string operationExpression)
    {
        WriteLocalValues(
            writer,
            node.Locals);

        if (node.EvaluationExpression is
                { } evaluationExpression)
        {
            writer.Line($"_ = {evaluationExpression};");
            writer.Line();
            WriteControlFlowCreateNode(
                writer,
                node.EvaluationContinuation!,
                operationExpression);
            return;
        }

        if (node.SwitchExpression is
                { } switchExpression)
        {
            writer.Line($"switch ({switchExpression})");
            writer.Line("{");
            writer.Indent();

            foreach (var section in node.SwitchSections)
            {
                foreach (var label in section.Labels)
                {
                    writer.Line(label);
                }

                writer.Line("{");
                writer.Indent();
                WriteControlFlowCreateNode(
                    writer,
                    section.Branch,
                    operationExpression);
                writer.Unindent();
                writer.Line("}");
            }

            writer.Unindent();
            writer.Line("}");

            if (node.SwitchContinuation is
                    { } continuation)
            {
                writer.Line();
                WriteControlFlowCreateNode(
                    writer,
                    continuation,
                    operationExpression);
            }

            return;
        }

        if (node.Condition is { } condition)
        {
            writer.Line($"if ({condition})");
            writer.Line("{");
            writer.Indent();
            WriteControlFlowCreateNode(
                writer,
                node.WhenTrue!,
                operationExpression);
            writer.Unindent();
            writer.Line("}");
            writer.Line("else");
            writer.Line("{");
            writer.Indent();
            WriteControlFlowCreateNode(
                writer,
                node.WhenFalse!,
                operationExpression);
            writer.Unindent();
            writer.Line("}");
            return;
        }

        if (node.ThrowExpression is { } throwExpression)
        {
            var resolvedThrowExpression = ResolveThrowExpression(
                throwExpression,
                node.ThrowUsesCurrentMappingOperation,
                operationExpression);
            writer.Line($"throw {resolvedThrowExpression};");
            return;
        }

        WriteControlFlowCreateLeaf(
            writer,
            node.Leaf!.Value,
            operationExpression);
    }

    private static void WriteControlFlowCreateLeaf(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string operationExpression)
    {
        if (mapping.Failure is
            { } unsupportedMappingMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedMappingMessage,
                operationExpression);
            return;
        }

        if (mapping.CreateFailure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedExceptionMessage,
                operationExpression);
            return;
        }

        if (mapping.CreateDirectExpression is
            { } directExpression)
        {
            writer.Line($"return {directExpression};");
            return;
        }

        if (mapping.CreateFactory is { } factory)
        {
            WriteFactoryCreateStatements(
                writer,
                mapping,
                factory,
                operationExpression);
            return;
        }

        if (mapping.CreateConstructor is
            { } constructor)
        {
            WriteConstructorCreateStatements(
                writer,
                mapping,
                constructor,
                operationExpression);
            return;
        }

        WriteMappingConfigurationFailureStatement(
            writer,
            mapping,
            "Morphant could not generate Create for this mapping.",
            operationExpression);
    }

    private static void WriteConstructorCreateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperConstructorMappingModel constructor,
        string operationExpression)
    {
        var hasValueLocals = false;

        foreach (var argument in constructor.Arguments)
        {
            foreach (var local in argument.EvaluationLocals.IsDefault
                         ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                         : argument.EvaluationLocals)
            {
                hasValueLocals = true;
                WriteLocalValue(writer, local);
            }

            if (argument.ValueLocalName is not
                { } valueLocalName)
            {
                continue;
            }

            hasValueLocals = true;
            writer.Line(
                (argument.ValueLocalTypeName ?? "var") +
                $" {valueLocalName} = " +
                ConstructorArgumentUncachedValueExpression(
                    mapping,
                    argument) +
                ";");
        }

        foreach (var local in constructor.ValueLocals.IsDefault
                     ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                     : constructor.ValueLocals)
        {
            hasValueLocals = true;
            WriteLocalValue(writer, local);
        }

        if (hasValueLocals)
        {
            writer.Line();
        }

        var hasPostMappings =
            !mapping.CreatePostMemberMappings.IsEmpty ||
            mapping.PostMemberControlFlow is not null;
        var constructionPrefix = hasPostMappings
            ? $"var {Identifier(mapping.ResultLocalName)} = "
            : "return ";

        if (constructor.Arguments.IsEmpty)
        {
            writer.Line(
                $"{constructionPrefix}new " +
                $"{constructor.ConstructedTypeName}()" +
                (mapping.CreateMemberMappings.IsEmpty
                    ? ";"
                    : string.Empty));
        }
        else
        {
            writer.Line(
                $"{constructionPrefix}new " +
                $"{constructor.ConstructedTypeName}(");
            writer.Indent();

            for (var index = 0;
                 index < constructor.Arguments.Length;
                 index++)
            {
                var argument = constructor.Arguments[index];
                var isLast =
                    index == constructor.Arguments.Length - 1;
                var suffix = isLast
                    ? mapping.CreateMemberMappings.IsEmpty
                        ? ");"
                        : ")"
                    : ",";

                writer.Line(
                    $"{Identifier(argument.ParameterName)}: " +
                    ConstructorArgumentValueExpression(
                        mapping,
                        argument) +
                    suffix);
            }

            writer.Unindent();
        }

        if (mapping.CreateMemberMappings.IsEmpty)
        {
            if (!hasPostMappings)
            {
                return;
            }
        }
        else
        {
            writer.Line("{");
            writer.Indent();

            for (var index = 0;
                 index < mapping.CreateMemberMappings.Length;
                 index++)
            {
                var memberMapping =
                    mapping.CreateMemberMappings[index];
                var suffix =
                    index < mapping.CreateMemberMappings.Length - 1
                        ? ","
                        : string.Empty;

                writer.Line(
                    $"{Identifier(memberMapping.DestinationMemberName)} = " +
                    MemberValueExpression(mapping, memberMapping) +
                    suffix);
            }

            writer.Unindent();
            writer.Line("};");
        }

        if (!hasPostMappings)
        {
            return;
        }

        writer.Line();

        if (mapping.PostMemberControlFlow is { } postControlFlow)
        {
            WritePostMemberControlFlow(
                writer,
                mapping,
                postControlFlow,
                Identifier(mapping.ResultLocalName),
                operationExpression: operationExpression);
            return;
        }

        WriteMemberValueLocals(
            writer,
            mapping.CreatePostMemberMappings);

        var resultLocalName =
            Identifier(mapping.ResultLocalName);

        foreach (var memberMapping in
                 mapping.CreatePostMemberMappings)
        {
            writer.Line(
                $"{resultLocalName}." +
                $"{Identifier(memberMapping.DestinationMemberName)} = " +
                MemberValueExpression(mapping, memberMapping) +
                ";");
        }

        writer.Line();
        writer.Line($"return {resultLocalName};");
    }

    private static void WriteFactoryCreateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperFactoryMappingModel factory,
        string operationExpression)
    {
        var destinationLocalName =
            Identifier(factory.DestinationLocalName);

        writer.Line(
            $"{mapping.DestinationTypeName} {destinationLocalName} = " +
            factory.ValueExpression +
            ";");

        if (factory.RequiresNullGuard)
        {
            writer.Line();
            writer.Line($"if ({destinationLocalName} is null)");
            writer.Line("{");
            writer.Indent();
            writer.Line("return default!;");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
        }

        var assignmentTarget = destinationLocalName;
        var returnExpression = destinationLocalName;
        var hasPostMappings =
            !mapping.CreatePostMemberMappings.IsEmpty ||
            mapping.PostMemberControlFlow is not null;

        if (hasPostMappings &&
            factory.NullableValueLocalName is
                { } nullableValueLocalName)
        {
            var valueLocalName =
                Identifier(nullableValueLocalName);

            writer.Line(
                $"var {valueLocalName} = " +
                $"{destinationLocalName}.Value;");
            writer.Line();

            assignmentTarget = valueLocalName;
            returnExpression = valueLocalName;
        }
        else if (!factory.RequiresNullGuard &&
                 factory.DestinationRequiresNullForgivingOperator)
        {
            assignmentTarget += "!";
        }

        if (hasPostMappings &&
            !factory.RequiresNullGuard &&
            factory.NullableValueLocalName is null)
        {
            writer.Line();
        }

        if (mapping.PostMemberControlFlow is { } postControlFlow)
        {
            WritePostMemberControlFlow(
                writer,
                mapping,
                postControlFlow,
                assignmentTarget,
                returnExpression,
                operationExpression);
            return;
        }

        foreach (var memberMapping in
                 mapping.CreatePostMemberMappings)
        {
            writer.Line(
                $"{assignmentTarget}." +
                $"{Identifier(memberMapping.DestinationMemberName)} = " +
                MemberValueExpression(mapping, memberMapping) +
                ";");
        }

        writer.Line();
        writer.Line($"return {returnExpression};");
    }

    private static void WriteUpdate(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        writer.Line("/// <inheritdoc/>");
        writer.Line(
            $"{mapping.DestinationTypeName} " +
            $"{mapping.InterfaceTypeName}.Update(");
        writer.Indent();
        writer.Line(
            $"{mapping.MaybeNullSourceTypeName} source,");
        writer.Line(
            $"{mapping.MaybeNullDestinationTypeName} destination,");
        writer.Line("global::Morphant.Context.MappingContext context)");

        if (mapping.Failure is
            { } configurationFailure)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                configurationFailure,
                update: true);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsMappingModeValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidMappingModeExceptionMessage,
                update: true);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.SupportsUpdate)
        {
            WriteUnsupportedOperation(
                writer,
                mapping,
                "Update");
            writer.Unindent();
            return;
        }

        if (mapping.UpdateOperationFailure is { } operationFailure)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                operationFailure,
                update: true);
            writer.Unindent();
            return;
        }

        if (mapping.ManualMapping is { } manualMapping)
        {
            WriteManualMapping(
                writer,
                mapping,
                manualMapping,
                update: true);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsNullSourceHandlingValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidNullSourceHandlingExceptionMessage,
                update: true);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsNullDestinationHandlingValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidNullDestinationHandlingExceptionMessage,
                update: true);
            writer.Unindent();
            return;
        }

        if (mapping.SourceCanBeNull ||
            mapping.DestinationCanBeNull)
        {
            WriteUpdateBody(
                writer,
                mapping);
            return;
        }

        var methodName =
            mapping.UpdateImplMethodName ??
            throw new InvalidOperationException(
                "An Update implementation method name is required.");

        writer.Line(
            $"=> {BuildUpdateImplCall(mapping, methodName)};");
        writer.Unindent();
    }

    private static void WriteManualMapping(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperManualMappingModel manualMapping,
        bool update)
    {
        if (mapping.Failure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                unsupportedExceptionMessage,
                update);
            return;
        }

        var helperMethodName = manualMapping.HelperMethodName ??
            throw new InvalidOperationException(
                "A Convert helper method name is required.");

        if (manualMapping.Form ==
            PairConfiguration.ConvertConfigurationForm.Source)
        {
            writer.Line($"=> {helperMethodName}(source);");
            return;
        }

        writer.Line($"=> {helperMethodName}(");
        writer.Indent();
        writer.Line("source,");
        var hasContext = manualMapping.Form ==
            PairConfiguration.ConvertConfigurationForm
                .SourcePreviousAndContext;
        var previousSuffix = hasContext ? "," : ");";

        if (!update)
        {
            writer.Line(
                BuildOptionTypeName(mapping) +
                ".None" +
                previousSuffix);
        }
        else if (!mapping.DestinationCanBeNull)
        {
            writer.Line(
                BuildOptionTypeName(mapping) +
                ".Some(destination)" +
                previousSuffix);
        }
        else
        {
            writer.Line("destination is null");
            writer.Indent();
            writer.Line(
                "? " + BuildOptionTypeName(mapping) + ".None");
            writer.Line(
                ": " + BuildOptionTypeName(mapping) +
                ".Some(" +
                (mapping.UpdateKind ==
                    TypeMapperUpdateKind.NullableValue
                    ? "destination.Value"
                    : "destination") +
                ")" +
                previousSuffix);
            writer.Unindent();
        }

        if (hasContext)
        {
            writer.Line("context);");
        }
        else
        {
            writer.Unindent();
            return;
        }

        writer.Unindent();
    }

    private static string BuildOptionTypeName(
        TypeMapperMappingModel mapping)
    {
        return "global::Morphant.Option<" +
               mapping.NonNullDestinationTypeName +
               ">";
    }

    private static void WriteUpdateBody(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        if (mapping.SourceCanBeNull)
        {
            WriteSourceNullHandling(
                writer,
                mapping,
                update: true);
            writer.Line();
            WriteNonNullSourceNormalization(writer, mapping);
        }

        if (mapping.DestinationCanBeNull)
        {
            WriteDestinationNullHandling(
                writer,
                mapping);
            writer.Line();
        }

        var methodName =
            mapping.UpdateImplMethodName ??
            throw new InvalidOperationException(
                "An Update implementation method name is required.");

        writer.Line(
            $"return {BuildUpdateImplCall(mapping, methodName)};");

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteUpdateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        if (mapping.Failure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedExceptionMessage,
                update: true);
            return;
        }

        if (mapping.ControlFlow is { } controlFlow)
        {
            WriteControlFlowUpdateNode(
                writer,
                controlFlow.UpdateRoot);
            return;
        }

        WriteUpdateLeafStatements(
            writer,
            mapping,
            allowReplacement: false);
    }

    private static void WriteSourceNullHandling(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update)
    {
        writer.Line("if (source is null)");
        writer.Line("{");
        writer.Indent();

        switch (mapping.EffectiveSettings.NullSourceHandling)
        {
            case NullSourceHandlingValue.ReturnNull:
                writer.Line("return default!;");
                break;

            case NullSourceHandlingValue.ReturnDestination
                when update:
                writer.Line("return destination!;");
                break;

            case NullSourceHandlingValue.ReturnDestination:
                writer.Line("return default!;");
                break;

            case NullSourceHandlingValue.Throw:
                WriteNullSourceException(
                    writer,
                    mapping,
                    update);
                break;

            default:
                throw new InvalidOperationException(
                    "NullSourceHandling has an invalid value.");
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteNonNullSourceNormalization(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        if (!mapping.SourceIsNullableValue)
        {
            return;
        }

        writer.Line(
            $"var {mapping.NonNullSourceName} = source.Value;");
        writer.Line();
    }

    private static void WriteDestinationNullHandling(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        writer.Line("if (destination is null)");
        writer.Line("{");
        writer.Indent();

        switch (mapping.EffectiveSettings.NullDestinationHandling)
        {
            case NullDestinationHandlingValue.Create:
                WriteCreateCallOrStatements(
                    writer,
                    mapping,
                    update: true);
                break;

            case NullDestinationHandlingValue.Throw:
                WriteNullDestinationException(
                    writer,
                    mapping);
                break;

            default:
                throw new InvalidOperationException(
                    "NullDestinationHandling has an invalid value.");
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteCreateImpl(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var methodName =
            mapping.CreateImplMethodName ??
            throw new InvalidOperationException(
                "A Create implementation method name is required.");

        writer.Line(
            "private " +
            (mapping.RequiresUnsafeContext ? "unsafe " : string.Empty) +
            $"{mapping.DestinationTypeName} " +
            $"{methodName}(");
        writer.Indent();
        writer.Line(
            $"{mapping.NonNullSourceTypeName} " +
            mapping.NonNullSourceName + ",");
        if (mapping.CreateImplUsesOperation)
        {
            writer.Line(
                "global::Morphant.Context.MappingOperation operation,");
        }
        writer.Line(
            "global::Morphant.Context.MappingContext context)");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WriteCreateStatements(
            writer,
            mapping,
            mapping.CreateImplUsesOperation
                ? "operation"
                : MappingOperationExpression(update: false));

        writer.Unindent();
        writer.Line("}");
    }

    private static string BuildCreateImplCall(
        TypeMapperMappingModel mapping,
        string methodName,
        bool update)
    {
        var operationArgument = mapping.CreateImplUsesOperation
            ? MappingOperationExpression(update) + ", "
            : string.Empty;

        return $"{methodName}({mapping.NonNullSourceName}, " +
               operationArgument +
               "context)";
    }

    private static void WriteUpdateImpl(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var methodName =
            mapping.UpdateImplMethodName ??
            throw new InvalidOperationException(
                "An Update implementation method name is required.");

        writer.Line(
            "private " +
            (mapping.RequiresUnsafeContext ? "unsafe " : string.Empty) +
            $"{mapping.DestinationTypeName} " +
            $"{methodName}(");
        writer.Indent();
        writer.Line(
            $"{mapping.NonNullSourceTypeName} " +
            mapping.NonNullSourceName + ",");
        writer.Line(
            $"{mapping.NonNullDestinationTypeName} destination,");
        writer.Line(
            "global::Morphant.Context.MappingContext context)");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WriteUpdateStatements(
            writer,
            mapping);

        writer.Unindent();
        writer.Line("}");
    }

    private static string BuildUpdateImplCall(
        TypeMapperMappingModel mapping,
        string methodName)
    {
        var destination = mapping.UpdateKind ==
            TypeMapperUpdateKind.NullableValue
                ? "destination.Value"
                : "destination";
        var arguments =
            $"{mapping.NonNullSourceName}, {destination}";

        return $"{methodName}({arguments}, context)";
    }

    private static void WriteNullSourceException(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update)
    {
        writer.Line(
            "throw new global::Morphant.Exceptions.NullSourceException(");
        writer.Indent();
        writer.Line(MappingOperationExpression(update) + ",");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}));");
        writer.Unindent();
    }

    private static void WriteNullDestinationException(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        writer.Line(
            "throw new global::Morphant.Exceptions.NullDestinationException(");
        writer.Indent();
        writer.Line(MappingOperationExpression(update: true) + ",");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}));");
        writer.Unindent();
    }

    private static void WriteControlFlowUpdateNode(
        CodeWriter writer,
        TypeMapperControlFlowNode node)
    {
        WriteLocalValues(
            writer,
            node.Locals);

        if (node.EvaluationExpression is
                { } evaluationExpression)
        {
            writer.Line($"_ = {evaluationExpression};");
            writer.Line();
            WriteControlFlowUpdateNode(
                writer,
                node.EvaluationContinuation!);
            return;
        }

        if (node.SwitchExpression is
                { } switchExpression)
        {
            writer.Line($"switch ({switchExpression})");
            writer.Line("{");
            writer.Indent();

            foreach (var section in node.SwitchSections)
            {
                foreach (var label in section.Labels)
                {
                    writer.Line(label);
                }

                writer.Line("{");
                writer.Indent();
                WriteControlFlowUpdateNode(
                    writer,
                    section.Branch);
                writer.Unindent();
                writer.Line("}");
            }

            writer.Unindent();
            writer.Line("}");

            if (node.SwitchContinuation is
                    { } continuation)
            {
                writer.Line();
                WriteControlFlowUpdateNode(
                    writer,
                    continuation);
            }

            return;
        }

        if (node.Condition is { } condition)
        {
            writer.Line($"if ({condition})");
            writer.Line("{");
            writer.Indent();
            WriteControlFlowUpdateNode(
                writer,
                node.WhenTrue!);
            writer.Unindent();
            writer.Line("}");
            writer.Line("else");
            writer.Line("{");
            writer.Indent();
            WriteControlFlowUpdateNode(
                writer,
                node.WhenFalse!);
            writer.Unindent();
            writer.Line("}");
            return;
        }

        if (node.ThrowExpression is { } throwExpression)
        {
            var resolvedThrowExpression = ResolveThrowExpression(
                throwExpression,
                node.ThrowUsesCurrentMappingOperation,
                MappingOperationExpression(update: true));
            writer.Line($"throw {resolvedThrowExpression};");
            return;
        }

        WriteUpdateLeafStatements(
            writer,
            node.Leaf!.Value,
            allowReplacement: true);
    }

    private static void WriteUpdateLeafStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool allowReplacement)
    {
        if (mapping.Failure is
            { } unsupportedMappingMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedMappingMessage,
                update: true);
            return;
        }

        if (mapping.UpdateFailure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedExceptionMessage,
                update: true);
            return;
        }

        if (mapping.UpdateDirectExpression is
            { } directExpression)
        {
            writer.Line($"return {directExpression};");
            return;
        }

        if (allowReplacement &&
            mapping.CreateFactory is { } factory)
        {
            WriteFactoryCreateStatements(
                writer,
                mapping,
                factory,
                MappingOperationExpression(update: true));
            return;
        }

        if (allowReplacement &&
            mapping.CreateConstructor is { } constructor)
        {
            WriteConstructorCreateStatements(
                writer,
                mapping,
                constructor,
                MappingOperationExpression(update: true));
            return;
        }

        if (mapping.UpdateKind ==
            TypeMapperUpdateKind.Unsupported)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                "Morphant could not generate Update for this mapping.",
                update: true);
            return;
        }

        if (mapping.PostMemberControlFlow is { } postControlFlow)
        {
            WritePostMemberControlFlow(
                writer,
                mapping,
                postControlFlow,
                "destination",
                operationExpression:
                    MappingOperationExpression(update: true));
            return;
        }

        if (mapping.UpdateMemberMappings.IsEmpty)
        {
            writer.Line("return destination;");
            return;
        }

        WriteMemberValueLocals(
            writer,
            mapping.UpdateMemberMappings);

        foreach (var memberMapping in
                 mapping.UpdateMemberMappings)
        {
            writer.Line(
                "destination." +
                $"{Identifier(memberMapping.DestinationMemberName)} = " +
                MemberValueExpression(mapping, memberMapping) +
                ";");
        }

        writer.Line();
        writer.Line("return destination;");
    }

    private static void WritePostMemberControlFlow(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperMemberControlFlowNode node,
        string assignmentTarget,
        string? returnExpression = null,
        string? operationExpression = null)
    {
        operationExpression ??=
            MappingOperationExpression(update: false);

        WriteLocalValues(writer, node.Locals);

        if (node.EvaluationExpression is { } evaluationExpression)
        {
            writer.Line($"_ = {evaluationExpression};");
            writer.Line();
            WritePostMemberControlFlow(
                writer,
                mapping,
                node.EvaluationContinuation!,
                assignmentTarget,
                returnExpression,
                operationExpression);
            return;
        }

        if (node.SwitchExpression is { } switchExpression)
        {
            writer.Line($"switch ({switchExpression})");
            writer.Line("{");
            writer.Indent();

            foreach (var section in node.SwitchSections)
            {
                foreach (var label in section.Labels)
                {
                    writer.Line(label);
                }

                writer.Line("{");
                writer.Indent();
                WritePostMemberControlFlow(
                    writer,
                    mapping,
                    section.Branch,
                    assignmentTarget,
                    returnExpression,
                    operationExpression);
                writer.Unindent();
                writer.Line("}");
            }

            writer.Unindent();
            writer.Line("}");

            if (node.SwitchContinuation is { } continuation)
            {
                writer.Line();
                WritePostMemberControlFlow(
                    writer,
                    mapping,
                    continuation,
                    assignmentTarget,
                    returnExpression,
                    operationExpression);
            }

            return;
        }

        if (node.Condition is { } condition)
        {
            writer.Line($"if ({condition})");
            writer.Line("{");
            writer.Indent();
            WritePostMemberControlFlow(
                writer,
                mapping,
                node.WhenTrue!,
                assignmentTarget,
                returnExpression,
                operationExpression);
            writer.Unindent();
            writer.Line("}");
            writer.Line("else");
            writer.Line("{");
            writer.Indent();
            WritePostMemberControlFlow(
                writer,
                mapping,
                node.WhenFalse!,
                assignmentTarget,
                returnExpression,
                operationExpression);
            writer.Unindent();
            writer.Line("}");
            return;
        }

        if (node.ThrowExpression is { } throwExpression)
        {
            var resolvedThrowExpression = ResolveThrowExpression(
                throwExpression,
                node.ThrowUsesCurrentMappingOperation,
                operationExpression);
            writer.Line($"throw {resolvedThrowExpression};");
            return;
        }

        if (node.Failure is { } unsupportedMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedMessage,
                operationExpression);
            return;
        }

        WriteMemberValueLocals(writer, node.MemberMappings);

        foreach (var memberMapping in node.MemberMappings)
        {
            writer.Line(
                assignmentTarget + "." +
                $"{Identifier(memberMapping.DestinationMemberName)} = " +
                MemberValueExpression(mapping, memberMapping) +
                ";");
        }

        if (!node.MemberMappings.IsEmpty)
        {
            writer.Line();
        }

        writer.Line($"return {returnExpression ?? assignmentTarget};");
    }

    private static void WriteMappingConfigurationFailure(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        MappingFailureObservation failure,
        bool update) =>
        WriteMappingConfigurationFailure(
            writer,
            mapping,
            failure.RecoveryMessage,
            update);

    private static void WriteMappingConfigurationFailure(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string reason,
        bool update) =>
        WriteMappingConfigurationFailure(
            writer,
            mapping,
            reason,
            MappingOperationExpression(update));

    private static void WriteMappingConfigurationFailure(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        MappingFailureObservation failure,
        string operationExpression) =>
        WriteMappingConfigurationFailure(
            writer,
            mapping,
            failure.RecoveryMessage,
            operationExpression);

    private static void WriteMappingConfigurationFailure(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string reason,
        string operationExpression)
    {
        var reasonLiteral =
            SyntaxFactory.LiteralExpression(
                    SyntaxKind.StringLiteralExpression,
                    SyntaxFactory.Literal(reason))
                .ToString();

        writer.Line(
            "=> throw new global::Morphant.Exceptions." +
            "MappingConfigurationException(");
        writer.Indent();
        writer.Line(operationExpression + ",");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}),");
        writer.Line($"{reasonLiteral});");
        writer.Unindent();
    }

    private static void WriteMappingConfigurationFailureStatement(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        MappingFailureObservation failure,
        bool update) =>
        WriteMappingConfigurationFailureStatement(
            writer,
            mapping,
            failure.RecoveryMessage,
            update);

    private static void WriteMappingConfigurationFailureStatement(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string reason,
        bool update) =>
        WriteMappingConfigurationFailureStatement(
            writer,
            mapping,
            reason,
            MappingOperationExpression(update));

    private static void WriteMappingConfigurationFailureStatement(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        MappingFailureObservation failure,
        string operationExpression) =>
        WriteMappingConfigurationFailureStatement(
            writer,
            mapping,
            failure.RecoveryMessage,
            operationExpression);

    private static void WriteMappingConfigurationFailureStatement(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string reason,
        string operationExpression)
    {
        var reasonLiteral =
            SyntaxFactory.LiteralExpression(
                    SyntaxKind.StringLiteralExpression,
                    SyntaxFactory.Literal(reason))
                .ToString();

        writer.Line(
            "throw new global::Morphant.Exceptions." +
            "MappingConfigurationException(");
        writer.Indent();
        writer.Line(operationExpression + ",");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}),");
        writer.Line($"{reasonLiteral});");
        writer.Unindent();
    }

    private static void WriteUnsupportedOperation(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string operation)
    {
        writer.Line(
            "=> throw new global::Morphant.Exceptions." +
            "MappingOperationNotSupportedException(");
        writer.Indent();
        writer.Line(
            $"global::Morphant.Context.MappingOperation.{operation},");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}),");
        writer.Line(
            "global::Morphant.MappingMode." +
            mapping.EffectiveSettings.MappingMode + ");");
        writer.Unindent();
    }

    private static void WriteLocalValues(
        CodeWriter writer,
        ImmutableArray<TypeMapperLocalValueModel> locals)
    {
        foreach (var local in locals)
        {
            WriteLocalValue(writer, local);
        }

        if (!locals.IsEmpty)
        {
            writer.Line();
        }
    }

    private static void WriteMultilineDeclaration(
        CodeWriter writer,
        string declaration)
    {
        foreach (var line in declaration
                     .Replace("\r\n", "\n")
                     .Replace('\r', '\n')
                     .Split('\n'))
        {
            writer.Line(line);
        }
    }

    private static string SourceValueExpression(
        TypeMapperMappingModel mapping,
        string sourceMemberName,
        string? sourceValueLocalName)
    {
        return sourceValueLocalName ??
               $"{mapping.NonNullSourceName}." +
               Identifier(sourceMemberName);
    }

    private static string MemberValueExpression(
        TypeMapperMappingModel owner,
        TypeMapperMemberMappingModel mapping)
    {
        return mapping.ValueLocalName ??
               mapping.ExplicitValueExpression ??
               mapping.SourceValueLocalName ??
               mapping.ConventionValueExpression ??
               SourceValueExpression(
                   owner,
                   mapping.SourceMemberName,
                   mapping.SourceValueLocalName);
    }

    private static void WriteMemberValueLocals(
        CodeWriter writer,
        IEnumerable<TypeMapperMemberMappingModel> mappings)
    {
        var wroteLocal = false;

        foreach (var mapping in mappings)
        {
            foreach (var local in mapping.EvaluationLocals.IsDefault
                         ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                         : mapping.EvaluationLocals)
            {
                WriteLocalValue(writer, local);
                wroteLocal = true;
            }

            if (mapping.ValueLocalName is not { } valueLocalName)
            {
                continue;
            }

            var valueTypeName =
                mapping.ExplicitValueTypeName ??
                throw new InvalidOperationException(
                    "A member value local requires a value type.");
            var valueExpression =
                mapping.ExplicitValueExpression ??
                throw new InvalidOperationException(
                    "A member value local requires an explicit expression.");

            writer.Line(
                $"{valueTypeName} {valueLocalName} = " +
                valueExpression +
                ";");
            wroteLocal = true;
        }

        if (wroteLocal)
        {
            writer.Line();
        }
    }

    private static void WriteLocalValue(
        CodeWriter writer,
        TypeMapperLocalValueModel local)
    {
        writer.Line(
            (local.IsConst
                ? "const "
                : string.Empty) +
            $"{local.DeclarationType} {local.Name} = " +
            local.ValueExpression +
            ";");
    }

    private static string ConstructorArgumentValueExpression(
        TypeMapperMappingModel owner,
        TypeMapperConstructorArgumentMappingModel mapping)
    {
        return mapping.ValueLocalName ??
               ConstructorArgumentUncachedValueExpression(
                   owner,
                   mapping);
    }

    private static string ConstructorArgumentUncachedValueExpression(
        TypeMapperMappingModel owner,
        TypeMapperConstructorArgumentMappingModel mapping)
    {
        return mapping.ExplicitValueExpression ??
               mapping.ConventionValueExpression ??
               SourceValueExpression(
                   owner,
                   mapping.SourceMemberName,
                   sourceValueLocalName: null);
    }

    private static string ResolveThrowExpression(
        string throwExpression,
        bool usesCurrentMappingOperation,
        string operationExpression)
    {
        if (!usesCurrentMappingOperation)
        {
            return throwExpression;
        }

        return throwExpression.Replace(
            "context.Operation",
            operationExpression);
    }

    private static string MappingOperationExpression(bool update) =>
        "global::Morphant.Context.MappingOperation." +
        (update ? "Update" : "Create");

    private static string Identifier(string value)
    {
        return SyntaxFacts.GetKeywordKind(value) != SyntaxKind.None ||
               SyntaxFacts.GetContextualKeywordKind(value) != SyntaxKind.None
            ? "@" + value
            : value;
    }
}
