using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Morphant.Generator.Settings;

namespace Morphant.Generator.TypeMapperGeneration;

internal static class TypeMapperEmitter
{
    private const string TransferProbePathPrefix =
        "Morphant.TransferProbe.Mapping.";

    private const string InvalidMappingModeExceptionMessage =
        "MappingMode has an invalid value.";

    private const string InvalidNullSourceHandlingExceptionMessage =
        "NullSourceHandling has an invalid value.";

    private const string InvalidNullDestinationHandlingExceptionMessage =
        "NullDestinationHandling has an invalid value.";

    private const string InvalidUnknownDerivedTypeHandlingExceptionMessage =
        "UnknownDerivedTypeHandling has an invalid value.";

    public static SourceText Emit(TypeMapperModel model)
    {
        return Emit(model, includeTransferProbeLocations: false);
    }

    internal static SourceText EmitTransferProbe(TypeMapperModel model)
    {
        return Emit(model, includeTransferProbeLocations: true);
    }

    internal static bool TryGetTransferProbeMappingIndex(
        Diagnostic diagnostic,
        out int mappingIndex)
    {
        var path = diagnostic.Location.GetMappedLineSpan().Path;

        if (path.StartsWith(
                TransferProbePathPrefix,
                StringComparison.Ordinal) &&
            path.EndsWith(".g.cs", StringComparison.Ordinal) &&
            int.TryParse(
                path.Substring(
                    TransferProbePathPrefix.Length,
                    path.Length - TransferProbePathPrefix.Length -
                    ".g.cs".Length),
                out mappingIndex))
        {
            return true;
        }

        mappingIndex = -1;
        return false;
    }

    private static SourceText Emit(
        TypeMapperModel model,
        bool includeTransferProbeLocations)
    {
        var writer = new CodeWriter();

        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line();

        if (model.RequiresSystemLinq)
        {
            writer.Line("using global::System.Linq;");
            writer.Line();
        }

        if (model.Namespace.Length > 0)
        {
            writer.OpenBlock($"namespace {model.Namespace}");
        }

        foreach (var containingType in model.ContainingTypes)
        {
            writer.OpenBlock(
                $"partial {containingType.DeclarationKind} " +
                containingType.TypeName +
                containingType.TypeParameterList);
        }

        WriteType(
            writer,
            model,
            includeTransferProbeLocations);

        for (var index = model.ContainingTypes.Length - 1;
             index >= 0;
             index--)
        {
            writer.CloseBlock();
        }

        if (model.Namespace.Length > 0)
        {
            writer.CloseBlock();
        }

        return SourceText.From(writer.ToString(), Encoding.UTF8);
    }

    private static void WriteType(
        CodeWriter writer,
        TypeMapperModel model,
        bool includeTransferProbeLocations)
    {
        writer.Line(
            $"{model.Accessibility} " +
            "partial class " +
            model.TypeName +
            model.TypeParameterList +
            " :");
        writer.Indent();

        for (var index = 0; index < model.Mappings.Length; index++)
        {
            var suffix = index < model.Mappings.Length - 1
                ? ","
                : string.Empty;

            writer.Line(
                model.Mappings[index].InterfaceTypeName + suffix);
        }

        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WriteSupports(writer, model.Mappings);

        for (var index = 0; index < model.Mappings.Length; index++)
        {
            writer.Line();

            if (includeTransferProbeLocations)
            {
                writer.Line(
                    $"#line 1 \"{TransferProbePathPrefix}{index}.g.cs\"");
            }

            WriteMapping(writer, model.Mappings[index]);

            if (includeTransferProbeLocations)
            {
                writer.Line("#line default");
                writer.Line("#line hidden");
            }
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteSupports(
        CodeWriter writer,
        ImmutableArray<TypeMapperMappingModel> mappings)
    {
        writer.Line("/// <inheritdoc/>");
        writer.Line("protected override bool Supports(");
        writer.Indent();
        writer.Line("global::System.Type sourceType,");
        writer.Line("global::System.Type destinationType) =>");
        writer.Indent();

        foreach (var mapping in mappings)
        {
            writer.Line(
                $"(sourceType == typeof({mapping.SourceRuntimeTypeName}) &&");
            writer.Indent();
            writer.Line(
                "destinationType == typeof(" +
                mapping.DestinationRuntimeTypeName +
                ")) ||");
            writer.Unindent();
        }

        writer.Line("base.Supports(sourceType, destinationType);");
        writer.Unindent();
        writer.Unindent();
    }

    private static void WriteMapping(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var warningSuppressions =
            mapping.TransferredWarningSuppressions.IsDefault
                ? ImmutableArray<string>.Empty
                : mapping.TransferredWarningSuppressions;

        if (!warningSuppressions.IsEmpty)
        {
            writer.Line(
                "#pragma warning disable " +
                string.Join(", ", warningSuppressions));
            writer.Line();
        }

        WriteCreate(writer, mapping);
        writer.Line();
        WriteUpdate(writer, mapping);

        if (mapping.TryCreatePolymorphicMethodName is not null)
        {
            writer.Line();
            WriteTryCreatePolymorphic(writer, mapping);
        }

        if (mapping.TryUpdatePolymorphicMethodName is not null)
        {
            writer.Line();
            WriteTryUpdatePolymorphic(writer, mapping);
        }

        if (mapping.CreateImplMethodName is not null)
        {
            writer.Line();
            WriteCreateImpl(writer, mapping);
        }

        if (mapping.UpdateImplMethodName is not null)
        {
            writer.Line();
            WriteUpdateImpl(writer, mapping);
        }

        if (mapping.EffectiveSettings.IsMappingModeValid &&
            !mapping.HelperMethodDeclarations.IsDefaultOrEmpty)
        {
            foreach (var declaration in
                     mapping.HelperMethodDeclarations)
            {
                writer.Line();
                WriteMultilineDeclaration(
                    writer,
                    declaration);
            }
        }

        if (!warningSuppressions.IsEmpty)
        {
            writer.Line();
            writer.Line(
                "#pragma warning restore " +
                string.Join(", ", warningSuppressions));
        }
    }

    private static void WriteCreate(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var localNames = TypeMapperMethodLocalNames.Build(
            mapping,
            create: true);

        writer.Line("/// <inheritdoc/>");
        writer.Line(
            $"{mapping.DestinationTypeName} " +
            $"{mapping.InterfaceTypeName}.Create(");
        writer.Indent();
        writer.Line(
            $"{mapping.MaybeNullSourceTypeName} source,");
        writer.Line("global::Morphant.Context.MappingContext context)");

        if (mapping.Failure is
            { } configurationFailure)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                configurationFailure,
                update: false);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsMappingModeValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidMappingModeExceptionMessage,
                update: false);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.SupportsCreate)
        {
            WriteUnsupportedOperation(
                writer,
                mapping,
                "Create");
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsUnknownDerivedTypeHandlingValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidUnknownDerivedTypeHandlingExceptionMessage,
                update: false);
            writer.Unindent();
            return;
        }

        if (!PolymorphicBasePlanReachability.RequiresDispatch(mapping) &&
            mapping.CreateOperationFailure is { } operationFailure)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                operationFailure,
                update: false);
            writer.Unindent();
            return;
        }

        if (mapping.ManualMapping is { } manualMapping)
        {
            if (!PolymorphicBasePlanReachability.RequiresDispatch(mapping))
            {
                WriteManualMapping(
                    writer,
                    mapping,
                    manualMapping,
                    update: false);
                writer.Unindent();
            }
            else
            {
                writer.Unindent();
                writer.Line("{");
                writer.Indent();
                WriteTryPolymorphicCall(
                    writer,
                    mapping,
                    update: false,
                    sourceExpression: "source",
                    localNames);
                writer.Line();
                WriteManualMapping(
                    writer,
                    mapping,
                    manualMapping,
                    update: false,
                    asStatement: true);
                writer.Unindent();
                writer.Line("}");
            }
            return;
        }

        if (!mapping.EffectiveSettings.IsNullSourceHandlingValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidNullSourceHandlingExceptionMessage,
                update: false);
            writer.Unindent();
            return;
        }

        if (mapping.SourceCanBeNull ||
            PolymorphicBasePlanReachability.RequiresDispatch(mapping))
        {
            WriteCreateBody(
                writer,
                mapping,
                localNames);
            return;
        }

        var methodName =
            mapping.CreateImplMethodName ??
            throw new InvalidOperationException(
                "A Create implementation method name is required.");

        writer.Line(
            $"=> {BuildCreateImplCall(mapping, methodName, update: false)};");
        writer.Unindent();
    }

    private static void WriteCreateBody(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        GeneratedLocalNameAllocator localNames)
    {
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        if (mapping.SourceCanBeNull)
        {
            WriteSourceNullHandling(
                writer,
                mapping,
                update: false);
            writer.Line();
        }

        WriteNonNullSourceNormalization(writer, mapping);

        if (mapping.TryCreatePolymorphicMethodName is not null)
        {
            WriteTryPolymorphicCall(
                writer,
                mapping,
                update: false,
                mapping.NonNullSourceName,
                localNames);
            writer.Line();
        }

        if (mapping.CreateOperationFailure is { } operationFailure)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                operationFailure,
                update: false);
            writer.Unindent();
            writer.Line("}");
            return;
        }

        WriteCreateCallOrStatements(
            writer,
            mapping,
            update: false,
            localNames: localNames);

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteTryPolymorphicCall(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update,
        string sourceExpression,
        GeneratedLocalNameAllocator localNames)
    {
        var methodName = update
            ? mapping.TryUpdatePolymorphicMethodName
            : mapping.TryCreatePolymorphicMethodName;
        var resultName = localNames.Allocate(
            "polymorphicDestination");

        if (methodName is null)
        {
            throw new InvalidOperationException(
                "A polymorphic method name is required.");
        }

        var arguments = update
            ? sourceExpression + ", destination, context, out var " +
              resultName
            : sourceExpression + ", context, out var " + resultName;

        writer.Line($"if ({methodName}({arguments}))");
        writer.Line("{");
        writer.Indent();
        writer.Line($"return {resultName};");
        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteCreateCallOrStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update,
        GeneratedLocalNameAllocator localNames)
    {
        if (mapping.CreateImplMethodName is
            { } createImplMethodName)
        {
            var call = BuildCreateImplCall(
                mapping,
                createImplMethodName,
                update);
            writer.Line($"return {call};");
            return;
        }

        WriteCreateStatements(
            writer,
            mapping,
            update,
            localNames);
    }

    private static void WriteCreateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update,
        GeneratedLocalNameAllocator localNames) =>
        WriteCreateStatements(
            writer,
            mapping,
            MappingOperationExpression(update),
            localNames);

    private static void WriteCreateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string operationExpression,
        GeneratedLocalNameAllocator localNames)
    {
        if (mapping.Failure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedExceptionMessage,
                operationExpression);
            return;
        }

        if (mapping.ControlFlow is { } controlFlow)
        {
            WriteControlFlowCreateNode(
                writer,
                controlFlow.CreateRoot,
                operationExpression,
                localNames);
            return;
        }

        WriteControlFlowCreateLeaf(
            writer,
            mapping,
            operationExpression,
            localNames);
    }

    private static void WriteControlFlowCreateNode(
        CodeWriter writer,
        TypeMapperControlFlowNode node,
        string operationExpression,
        GeneratedLocalNameAllocator localNames)
    {
        WriteLocalValues(
            writer,
            node.Locals);

        if (node.EvaluationExpression is
                { } evaluationExpression)
        {
            WriteEvaluation(
                writer,
                evaluationExpression,
                node.EvaluationCondition,
                node.EvaluationLocals);
            WriteControlFlowCreateNode(
                writer,
                node.EvaluationContinuation!,
                operationExpression,
                localNames);
            return;
        }

        if (node.SwitchExpression is
                { } switchExpression)
        {
            writer.Line($"switch ({switchExpression})");
            writer.Line("{");
            writer.Indent();

            foreach (var section in node.SwitchSections)
            {
                foreach (var label in section.Labels)
                {
                    writer.Line(label);
                }

                writer.Line("{");
                writer.Indent();
                WriteControlFlowCreateNode(
                    writer,
                    section.Branch,
                    operationExpression,
                    localNames);
                writer.Unindent();
                writer.Line("}");
            }

            writer.Unindent();
            writer.Line("}");

            if (node.SwitchContinuation is
                    { } continuation)
            {
                writer.Line();
                WriteControlFlowCreateNode(
                    writer,
                    continuation,
                    operationExpression,
                    localNames);
            }

            return;
        }

        if (node.Condition is { } condition)
        {
            writer.Line($"if ({condition})");
            writer.Line("{");
            writer.Indent();
            WriteControlFlowCreateNode(
                writer,
                node.WhenTrue!,
                operationExpression,
                localNames);
            writer.Unindent();
            writer.Line("}");
            writer.Line("else");
            writer.Line("{");
            writer.Indent();
            WriteControlFlowCreateNode(
                writer,
                node.WhenFalse!,
                operationExpression,
                localNames);
            writer.Unindent();
            writer.Line("}");
            return;
        }

        if (node.ThrowExpression is { } throwExpression)
        {
            var resolvedThrowExpression = ResolveThrowExpression(
                throwExpression,
                node.ThrowUsesCurrentMappingOperation,
                operationExpression);
            writer.Line($"throw {resolvedThrowExpression};");
            return;
        }

        WriteControlFlowCreateLeaf(
            writer,
            node.Leaf!.Value,
            operationExpression,
            localNames);
    }

    private static void WriteControlFlowCreateLeaf(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string operationExpression,
        GeneratedLocalNameAllocator localNames)
    {
        if (mapping.Failure is
            { } unsupportedMappingMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedMappingMessage,
                operationExpression);
            return;
        }

        if (mapping.CreateFailure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedExceptionMessage,
                operationExpression);
            return;
        }

        if (mapping.CreateDirectExpression is
            { } directExpression)
        {
            writer.Line($"return {directExpression};");
            return;
        }

        if (mapping.CreateFactory is { } factory)
        {
            WriteFactoryCreateStatements(
                writer,
                mapping,
                factory,
                operationExpression,
                localNames);
            return;
        }

        if (mapping.CreateConstructor is
            { } constructor)
        {
            WriteConstructorCreateStatements(
                writer,
                mapping,
                constructor,
                operationExpression,
                localNames);
            return;
        }

        WriteMappingConfigurationFailureStatement(
            writer,
            mapping,
            "Morphant could not generate Create for this mapping.",
            operationExpression);
    }

    private static void WriteConstructorCreateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperConstructorMappingModel constructor,
        string operationExpression,
        GeneratedLocalNameAllocator localNames)
    {
        var hasValueLocals = false;

        foreach (var argument in constructor.Arguments)
        {
            foreach (var local in argument.EvaluationLocals.IsDefault
                         ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                         : argument.EvaluationLocals)
            {
                hasValueLocals = true;
                WriteLocalValue(writer, local);
            }

            if (argument.ValueLocalName is not
                { } valueLocalName)
            {
                continue;
            }

            hasValueLocals = true;
            writer.Line(
                (argument.ValueLocalTypeName ?? "var") +
                $" {valueLocalName} = " +
                ConstructorArgumentUncachedValueExpression(
                    mapping,
                    argument,
                    localNames) +
                ";");
        }

        foreach (var local in constructor.ValueLocals.IsDefault
                     ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                     : constructor.ValueLocals)
        {
            hasValueLocals = true;
            WriteLocalValue(writer, local);
        }

        if (hasValueLocals)
        {
            writer.Line();
        }

        var hasPostMappings =
            !mapping.CreatePostMemberMappings.IsEmpty ||
            mapping.PostMemberControlFlow is not null;
        var constructionPrefix = hasPostMappings
            ? $"var {Identifier(mapping.ResultLocalName)} = "
            : "return ";

        if (constructor.Arguments.IsEmpty)
        {
            writer.Line(
                $"{constructionPrefix}new " +
                $"{constructor.ConstructedTypeName}()" +
                (mapping.CreateMemberMappings.IsEmpty
                    ? ";"
                    : string.Empty));
        }
        else
        {
            writer.Line(
                $"{constructionPrefix}new " +
                $"{constructor.ConstructedTypeName}(");
            writer.Indent();

            for (var index = 0;
                 index < constructor.Arguments.Length;
                 index++)
            {
                var argument = constructor.Arguments[index];
                var isLast =
                    index == constructor.Arguments.Length - 1;
                var suffix = isLast
                    ? mapping.CreateMemberMappings.IsEmpty
                        ? ");"
                        : ")"
                    : ",";

                writer.Line(
                    $"{Identifier(argument.ParameterName)}: " +
                    ConstructorArgumentValueExpression(
                        mapping,
                        argument,
                        localNames) +
                    suffix);
            }

            writer.Unindent();
        }

        if (mapping.CreateMemberMappings.IsEmpty)
        {
            if (!hasPostMappings)
            {
                return;
            }
        }
        else
        {
            writer.Line("{");
            writer.Indent();

            for (var index = 0;
                 index < mapping.CreateMemberMappings.Length;
                 index++)
            {
                var memberMapping =
                    mapping.CreateMemberMappings[index];
                var suffix =
                    index < mapping.CreateMemberMappings.Length - 1
                        ? ","
                        : string.Empty;

                writer.Line(
                    $"{Identifier(memberMapping.DestinationMemberName)} = " +
                    MemberValueExpression(
                        mapping,
                        memberMapping,
                        localNames) +
                    suffix);
            }

            writer.Unindent();
            writer.Line("};");
        }

        if (!hasPostMappings)
        {
            return;
        }

        writer.Line();

        if (mapping.PostMemberControlFlow is { } postControlFlow)
        {
            WritePostMemberControlFlow(
                writer,
                mapping,
                postControlFlow,
                Identifier(mapping.ResultLocalName),
                localNames,
                operationExpression: operationExpression);
            return;
        }

        WriteMemberValueLocals(
            writer,
            mapping.CreatePostMemberMappings);

        var resultLocalName =
            Identifier(mapping.ResultLocalName);

        foreach (var memberMapping in
                 mapping.CreatePostMemberMappings)
        {
            WriteInvocationArgumentLocals(writer, memberMapping);
            writer.Line(
                $"{resultLocalName}." +
                $"{Identifier(memberMapping.DestinationMemberName)} = " +
                MemberValueExpression(
                    mapping,
                    memberMapping,
                    localNames) +
                ";");
        }

        writer.Line();
        writer.Line($"return {resultLocalName};");
    }

    private static void WriteFactoryCreateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperFactoryMappingModel factory,
        string operationExpression,
        GeneratedLocalNameAllocator localNames)
    {
        var destinationLocalName =
            Identifier(factory.DestinationLocalName);

        writer.Line(
            $"{mapping.DestinationTypeName} {destinationLocalName} = " +
            factory.ValueExpression +
            ";");

        if (factory.RequiresNullGuard)
        {
            writer.Line();
            writer.Line($"if ({destinationLocalName} is null)");
            writer.Line("{");
            writer.Indent();
            writer.Line("return default!;");
            writer.Unindent();
            writer.Line("}");
            writer.Line();
        }

        var assignmentTarget = destinationLocalName;
        var returnExpression = destinationLocalName;
        var hasPostMappings =
            !mapping.CreatePostMemberMappings.IsEmpty ||
            mapping.PostMemberControlFlow is not null;

        if (hasPostMappings &&
            factory.NullableValueLocalName is
                { } nullableValueLocalName)
        {
            var valueLocalName =
                Identifier(nullableValueLocalName);

            writer.Line(
                $"var {valueLocalName} = " +
                $"{destinationLocalName}.Value;");
            writer.Line();

            assignmentTarget = valueLocalName;
            returnExpression = valueLocalName;
        }
        else if (!factory.RequiresNullGuard &&
                 factory.DestinationRequiresNullForgivingOperator)
        {
            assignmentTarget += "!";
        }

        if (hasPostMappings &&
            !factory.RequiresNullGuard &&
            factory.NullableValueLocalName is null)
        {
            writer.Line();
        }

        if (mapping.PostMemberControlFlow is { } postControlFlow)
        {
            WritePostMemberControlFlow(
                writer,
                mapping,
                postControlFlow,
                assignmentTarget,
                localNames,
                returnExpression,
                operationExpression);
            return;
        }

        foreach (var memberMapping in
                 mapping.CreatePostMemberMappings)
        {
            WriteInvocationArgumentLocals(writer, memberMapping);
            writer.Line(
                $"{assignmentTarget}." +
                $"{Identifier(memberMapping.DestinationMemberName)} = " +
                MemberValueExpression(
                    mapping,
                    memberMapping,
                    localNames) +
                ";");
        }

        writer.Line();
        writer.Line($"return {returnExpression};");
    }

    private static void WriteUpdate(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var localNames = TypeMapperMethodLocalNames.Build(
            mapping,
            create: true);

        writer.Line("/// <inheritdoc/>");
        writer.Line(
            $"{mapping.DestinationTypeName} " +
            $"{mapping.InterfaceTypeName}.Update(");
        writer.Indent();
        writer.Line(
            $"{mapping.MaybeNullSourceTypeName} source,");
        writer.Line(
            $"{mapping.MaybeNullDestinationTypeName} destination,");
        writer.Line("global::Morphant.Context.MappingContext context)");

        if (mapping.Failure is
            { } configurationFailure)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                configurationFailure,
                update: true);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsMappingModeValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidMappingModeExceptionMessage,
                update: true);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.SupportsUpdate)
        {
            WriteUnsupportedOperation(
                writer,
                mapping,
                "Update");
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsUnknownDerivedTypeHandlingValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidUnknownDerivedTypeHandlingExceptionMessage,
                update: true);
            writer.Unindent();
            return;
        }

        if (!PolymorphicBasePlanReachability.RequiresDispatch(mapping) &&
            mapping.UpdateOperationFailure is { } operationFailure)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                operationFailure,
                update: true);
            writer.Unindent();
            return;
        }

        if (mapping.ManualMapping is { } manualMapping)
        {
            if (!PolymorphicBasePlanReachability.RequiresDispatch(mapping))
            {
                WriteManualMapping(
                    writer,
                    mapping,
                    manualMapping,
                    update: true);
                writer.Unindent();
            }
            else
            {
                writer.Unindent();
                writer.Line("{");
                writer.Indent();
                WriteTryPolymorphicCall(
                    writer,
                    mapping,
                    update: true,
                    sourceExpression: "source",
                    localNames);
                writer.Line();
                WriteManualMapping(
                    writer,
                    mapping,
                    manualMapping,
                    update: true,
                    asStatement: true);
                writer.Unindent();
                writer.Line("}");
            }
            return;
        }

        if (!mapping.EffectiveSettings.IsNullSourceHandlingValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidNullSourceHandlingExceptionMessage,
                update: true);
            writer.Unindent();
            return;
        }

        if (!mapping.EffectiveSettings.IsNullDestinationHandlingValid)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                InvalidNullDestinationHandlingExceptionMessage,
                update: true);
            writer.Unindent();
            return;
        }

        if (mapping.SourceCanBeNull ||
            mapping.DestinationCanBeNull ||
            PolymorphicBasePlanReachability.RequiresDispatch(mapping))
        {
            WriteUpdateBody(
                writer,
                mapping,
                localNames);
            return;
        }

        var methodName =
            mapping.UpdateImplMethodName ??
            throw new InvalidOperationException(
                "An Update implementation method name is required.");

        writer.Line(
            $"=> {BuildUpdateImplCall(mapping, methodName)};");
        writer.Unindent();
    }

    private static void WriteManualMapping(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperManualMappingModel manualMapping,
        bool update,
        bool asStatement = false)
    {
        if (mapping.Failure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailure(
                writer,
                mapping,
                unsupportedExceptionMessage,
                update);
            return;
        }

        var helperMethodName = manualMapping.HelperMethodName ??
            throw new InvalidOperationException(
                "A Convert helper method name is required.");

        if (manualMapping.Form ==
            PairConfiguration.ConvertConfigurationForm.Source)
        {
            writer.Line(
                (asStatement ? "return " : "=> ") +
                $"{helperMethodName}(source);");
            return;
        }

        writer.Line(
            (asStatement ? "return " : "=> ") +
            $"{helperMethodName}(");
        writer.Indent();
        writer.Line("source,");
        var hasContext = manualMapping.Form ==
            PairConfiguration.ConvertConfigurationForm
                .SourcePreviousAndContext;
        var previousSuffix = hasContext ? "," : ");";

        if (!update)
        {
            writer.Line(
                BuildOptionTypeName(mapping) +
                ".None" +
                previousSuffix);
        }
        else if (!mapping.DestinationCanBeNull)
        {
            writer.Line(
                BuildOptionTypeName(mapping) +
                ".Some(destination)" +
                previousSuffix);
        }
        else
        {
            writer.Line("destination is null");
            writer.Indent();
            writer.Line(
                "? " + BuildOptionTypeName(mapping) + ".None");
            writer.Line(
                ": " + BuildOptionTypeName(mapping) +
                ".Some(" +
                (mapping.UpdateKind ==
                    TypeMapperUpdateKind.NullableValue
                    ? "destination.Value"
                    : "destination") +
                ")" +
                previousSuffix);
            writer.Unindent();
        }

        if (hasContext)
        {
            writer.Line("context);");
        }
        else
        {
            writer.Unindent();
            return;
        }

        writer.Unindent();
    }

    private static string BuildOptionTypeName(
        TypeMapperMappingModel mapping)
    {
        return "global::Morphant.Option<" +
               mapping.NonNullDestinationTypeName +
               ">";
    }

    private static void WriteUpdateBody(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        GeneratedLocalNameAllocator localNames)
    {
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        if (mapping.SourceCanBeNull)
        {
            WriteSourceNullHandling(
                writer,
                mapping,
                update: true);
            writer.Line();
            WriteNonNullSourceNormalization(writer, mapping);
        }

        if (mapping.TryUpdatePolymorphicMethodName is not null)
        {
            WriteTryPolymorphicCall(
                writer,
                mapping,
                update: true,
                mapping.NonNullSourceName,
                localNames);
            writer.Line();
        }

        if (mapping.UpdateOperationFailure is { } operationFailure)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                operationFailure,
                update: true);
            writer.Unindent();
            writer.Line("}");
            return;
        }

        if (mapping.DestinationCanBeNull)
        {
            WriteDestinationNullHandling(
                writer,
                mapping,
                localNames);
            writer.Line();
        }

        var methodName =
            mapping.UpdateImplMethodName ??
            throw new InvalidOperationException(
                "An Update implementation method name is required.");

        writer.Line(
            $"return {BuildUpdateImplCall(mapping, methodName)};");

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteUpdateStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        GeneratedLocalNameAllocator localNames)
    {
        if (mapping.Failure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedExceptionMessage,
                update: true);
            return;
        }

        if (mapping.ControlFlow is { } controlFlow)
        {
            WriteControlFlowUpdateNode(
                writer,
                controlFlow.UpdateRoot,
                localNames);
            return;
        }

        WriteUpdateLeafStatements(
            writer,
            mapping,
            allowReplacement: false,
            localNames: localNames);
    }

    private static void WriteSourceNullHandling(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update)
    {
        writer.Line("if (source is null)");
        writer.Line("{");
        writer.Indent();

        switch (mapping.EffectiveSettings.NullSourceHandling)
        {
            case NullSourceHandlingValue.ReturnNull:
                writer.Line("return default!;");
                break;

            case NullSourceHandlingValue.ReturnDestination
                when update:
                writer.Line("return destination!;");
                break;

            case NullSourceHandlingValue.ReturnDestination:
                writer.Line("return default!;");
                break;

            case NullSourceHandlingValue.Throw:
                WriteNullSourceException(
                    writer,
                    mapping,
                    update);
                break;

            default:
                throw new InvalidOperationException(
                    "NullSourceHandling has an invalid value.");
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteNonNullSourceNormalization(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        if (!mapping.SourceIsNullableValue)
        {
            return;
        }

        writer.Line(
            $"var {mapping.NonNullSourceName} = source.Value;");
        writer.Line();
    }

    private static void WritePolymorphicDispatch(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update,
        GeneratedLocalNameAllocator localNames,
        string sourceExpression,
        string resultExpression)
    {
        var derivedMappings = mapping.DerivedMappings;

        if (!PolymorphicBasePlanReachability.RequiresDispatch(mapping))
        {
            return;
        }

        var sourceLocalName = localNames.Allocate(
            "polymorphicSource");
        var destinationLocalName = update && derivedMappings.Any(
            static derivedMapping =>
                !derivedMapping.DestinationMatchesBase)
            ? localNames.Allocate("polymorphicDestination")
            : null;

        writer.Line("switch (" + sourceExpression + ")");
        writer.Line("{");
        writer.Indent();

        for (var index = 0; index < derivedMappings.Length; index++)
        {
            var derivedMapping = derivedMappings[index];
            WritePolymorphicSourceCase(
                writer,
                sourceExpression,
                derivedMappings,
                index,
                derivedMapping.DisqualifyingMappingIndexes,
                sourceLocalName);
            writer.Indent();

            if (update)
            {
                WritePolymorphicUpdateBranch(
                    writer,
                    mapping,
                    derivedMapping,
                    sourceLocalName,
                    destinationLocalName,
                    resultExpression);
            }
            else
            {
                writer.Line(
                    resultExpression + " = " + BuildPolymorphicMapCall(
                        derivedMapping,
                        sourceLocalName,
                        destinationExpression: null) + ";");
                writer.Line("return true;");
            }

            writer.Unindent();
            writer.Line();
        }

        var ambiguousMappingIndexes =
            GetPotentiallyAmbiguousMappingIndexes(derivedMappings);

        if (!ambiguousMappingIndexes.IsEmpty)
        {
            WritePolymorphicAmbiguityCase(
                writer,
                mapping,
                derivedMappings,
                ambiguousMappingIndexes,
                sourceExpression,
                update);
            writer.Line();
        }

        switch (mapping.EffectiveSettings.UnknownDerivedTypeHandling)
        {
            case UnknownDerivedTypeHandlingValue.Throw:
                WriteUnmatchedPolymorphicCase(
                    writer,
                    mapping,
                    sourceExpression,
                    update);
                writer.Line();
                break;

            case UnknownDerivedTypeHandlingValue.UseBaseMapping:
                break;

            default:
                throw new InvalidOperationException(
                    "UnknownDerivedTypeHandling has an invalid value.");
        }

        writer.Line("default:");
        writer.Indent();
        writer.Line(resultExpression + " = default!;");
        writer.Line("return false;");
        writer.Unindent();
        writer.Unindent();
        writer.Line("}");
    }

    private static void WritePolymorphicSourceCase(
        CodeWriter writer,
        string sourceExpression,
        ImmutableArray<TypeMapperDerivedMappingModel> derivedMappings,
        int mappingIndex,
        ImmutableArray<int> excludedMappingIndexes,
        string sourceLocalName)
    {
        var mapping = derivedMappings[mappingIndex];
        var caseLabel = "case " + mapping.SourceMatchTypeName + " " +
                        sourceLocalName;

        if (excludedMappingIndexes.IsEmpty)
        {
            writer.Line(caseLabel + ":");
            return;
        }

        writer.Line(caseLabel);
        writer.Indent();
        writer.Line(
            "when " + sourceExpression + " is not " +
            derivedMappings[excludedMappingIndexes[0]].SourceMatchTypeName +
            (excludedMappingIndexes.Length == 1 ? ":" : " &&"));

        for (var index = 1; index < excludedMappingIndexes.Length; index++)
        {
            var excludedIndex = excludedMappingIndexes[index];
            var suffix = index == excludedMappingIndexes.Length - 1
                ? ":"
                : " &&";

            writer.Line(
                sourceExpression + " is not " +
                derivedMappings[excludedIndex].SourceMatchTypeName +
                suffix);
        }

        writer.Unindent();
    }

    private static ImmutableArray<int>
        GetPotentiallyAmbiguousMappingIndexes(
        ImmutableArray<TypeMapperDerivedMappingModel> mappings)
    {
        var indexes = ImmutableArray.CreateBuilder<int>();

        for (var index = 0; index < mappings.Length; index++)
        {
            for (var other = 0; other < mappings.Length; other++)
            {
                if (index != other &&
                    mappings[index].DisqualifyingMappingIndexes.Contains(
                        other) &&
                    mappings[other].DisqualifyingMappingIndexes.Contains(
                        index))
                {
                    indexes.Add(index);
                    break;
                }
            }
        }

        return indexes.ToImmutable();
    }

    private static void WritePolymorphicAmbiguityCase(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        ImmutableArray<TypeMapperDerivedMappingModel> derivedMappings,
        ImmutableArray<int> ambiguousMappingIndexes,
        string sourceExpression,
        bool update)
    {
        writer.Line(
            "case { } when " + sourceExpression + " is " +
            derivedMappings[ambiguousMappingIndexes[0]]
                .SourceMatchTypeName +
            (ambiguousMappingIndexes.Length == 1 ? ":" : " ||"));
        writer.Indent();

        for (var index = 1;
             index < ambiguousMappingIndexes.Length;
             index++)
        {
            var suffix = index == ambiguousMappingIndexes.Length - 1
                ? ":"
                : " ||";

            writer.Line(
                sourceExpression + " is " +
                derivedMappings[ambiguousMappingIndexes[index]]
                    .SourceMatchTypeName + suffix);
        }

        writer.Unindent();
        writer.Indent();
        writer.Line(
            "throw global::Morphant.Exceptions." +
            "AmbiguousPolymorphicMappingException.Create<");
        writer.Indent();
        writer.Line(
            mapping.SourceRuntimeTypeName + ",");
        writer.Line(
            mapping.DestinationRuntimeTypeName + ">(");
        writer.Unindent();
        writer.Indent();
        writer.Line(MappingOperationExpression(update) + ",");
        writer.Line(sourceExpression + ",");

        for (var index = 0;
             index < ambiguousMappingIndexes.Length;
             index++)
        {
            var mappingIndex = ambiguousMappingIndexes[index];
            WritePolymorphicBranchMatch(
                writer,
                sourceExpression,
                derivedMappings,
                mappingIndex,
                isLast: index == ambiguousMappingIndexes.Length - 1);
        }

        writer.Unindent();
        writer.Unindent();
    }

    private static void WritePolymorphicBranchMatch(
        CodeWriter writer,
        string sourceExpression,
        ImmutableArray<TypeMapperDerivedMappingModel> derivedMappings,
        int mappingIndex,
        bool isLast)
    {
        var mapping = derivedMappings[mappingIndex];
        var moreSpecificMappings = mapping.MoreSpecificMappingIndexes;

        writer.Line("(");
        writer.Indent();
        writer.Line(
            sourceExpression + " is " + mapping.SourceMatchTypeName +
            (moreSpecificMappings.IsEmpty ? "," : " &&"));

        for (var index = 0; index < moreSpecificMappings.Length; index++)
        {
            var suffix = index == moreSpecificMappings.Length - 1
                ? ","
                : " &&";
            writer.Line(
                sourceExpression + " is not " +
                derivedMappings[moreSpecificMappings[index]]
                    .SourceMatchTypeName + suffix);
        }

        writer.Line("typeof(" + mapping.SourceRuntimeTypeName + "),");
        writer.Line(
            "typeof(" + mapping.DestinationRuntimeTypeName + "))" +
            (isLast ? ");" : ","));
        writer.Unindent();
    }

    private static void WriteUnmatchedPolymorphicCase(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string sourceExpression,
        bool update)
    {
        writer.Line(
            "case { } when " + sourceExpression + ".GetType() !=");
        writer.Indent();
        writer.Line("typeof(" + mapping.SourceMatchTypeName + "):");
        writer.Unindent();
        writer.Indent();
        writer.Line(
            "throw global::Morphant.Exceptions." +
            "UnmatchedPolymorphicMappingException.Create<");
        writer.Indent();
        writer.Line(mapping.SourceRuntimeTypeName + ",");
        writer.Line(mapping.DestinationRuntimeTypeName + ">(");
        writer.Unindent();
        writer.Indent();
        writer.Line(MappingOperationExpression(update) + ",");
        writer.Line(sourceExpression + ");");
        writer.Unindent();
        writer.Unindent();
    }

    private static void WritePolymorphicUpdateBranch(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperDerivedMappingModel derivedMapping,
        string sourceLocalName,
        string? destinationLocalName,
        string resultExpression)
    {
        if (derivedMapping.DestinationMatchesBase)
        {
            writer.Line(
                resultExpression + " = " + BuildPolymorphicMapCall(
                    derivedMapping,
                    sourceLocalName,
                    "destination") + ";");
            writer.Line("return true;");
            return;
        }

        if (destinationLocalName is null)
        {
            throw new InvalidOperationException(
                "A polymorphic destination local was not allocated.");
        }

        writer.Line(resultExpression + " = destination switch");
        writer.Line("{");
        writer.Indent();

        if (mapping.DestinationCanBeNull)
        {
            if (derivedMapping.DestinationCanBeNull)
            {
                WritePolymorphicMapSwitchArm(
                    writer,
                    derivedMapping,
                    pattern: "null",
                    sourceLocalName,
                    "default(" +
                    derivedMapping.DestinationTypeName + ")");
            }
            else
            {
                WritePolymorphicDestinationMismatchSwitchArm(
                    writer,
                    mapping,
                    derivedMapping,
                    pattern: "null",
                    sourceLocalName);
            }
        }

        WritePolymorphicMapSwitchArm(
            writer,
            derivedMapping,
            derivedMapping.DestinationMatchTypeName + " " +
            destinationLocalName,
            sourceLocalName,
            destinationLocalName);

        WritePolymorphicDestinationMismatchSwitchArm(
            writer,
            mapping,
            derivedMapping,
            pattern: "_",
            sourceLocalName,
            isLast: true);

        writer.Unindent();
        writer.Line("};");
        writer.Line("return true;");
    }

    private static void WritePolymorphicMapSwitchArm(
        CodeWriter writer,
        TypeMapperDerivedMappingModel derivedMapping,
        string pattern,
        string sourceExpression,
        string destinationExpression)
    {
        writer.Line(pattern + " =>");
        writer.Indent();
        writer.Line(
            "context.Mapper.Map<" +
            derivedMapping.SourceTypeName + ", " +
            derivedMapping.DestinationTypeName + ">(");
        writer.Indent();
        writer.Line(sourceExpression + ",");
        writer.Line(destinationExpression + "),");
        writer.Unindent();
        writer.Unindent();
    }

    private static string BuildPolymorphicMapCall(
        TypeMapperDerivedMappingModel derivedMapping,
        string sourceExpression,
        string? destinationExpression)
    {
        var arguments = destinationExpression is null
            ? sourceExpression
            : sourceExpression + ", " + destinationExpression;

        return "context.Mapper.Map<" +
               derivedMapping.SourceTypeName + ", " +
               derivedMapping.DestinationTypeName + ">(" +
               arguments + ")";
    }

    private static void WritePolymorphicDestinationMismatchSwitchArm(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperDerivedMappingModel derivedMapping,
        string pattern,
        string sourceExpression,
        bool isLast = false)
    {
        writer.Line(
            pattern + " => throw global::Morphant.Exceptions");
        writer.Indent();
        writer.Line(".PolymorphicDestinationTypeMismatchException");
        writer.Line(".CreateForUpdate<");
        writer.Indent();
        writer.Line(mapping.SourceRuntimeTypeName + ",");
        writer.Line(mapping.DestinationRuntimeTypeName + ",");
        writer.Line(derivedMapping.SourceRuntimeTypeName + ",");
        writer.Line(
            derivedMapping.DestinationRuntimeTypeName + ">(");
        writer.Unindent();
        writer.Indent();
        writer.Line(sourceExpression + ",");
        writer.Line(
            "destination)" +
            (isLast ? string.Empty : ","));
        writer.Unindent();
        writer.Unindent();
    }

    private static void WriteDestinationNullHandling(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        GeneratedLocalNameAllocator localNames)
    {
        writer.Line("if (destination is null)");
        writer.Line("{");
        writer.Indent();

        switch (mapping.EffectiveSettings.NullDestinationHandling)
        {
            case NullDestinationHandlingValue.Create:
                WriteCreateCallOrStatements(
                    writer,
                    mapping,
                    update: true,
                    localNames: localNames);
                break;

            case NullDestinationHandlingValue.Throw:
                WriteNullDestinationException(
                    writer,
                    mapping);
                break;

            default:
                throw new InvalidOperationException(
                    "NullDestinationHandling has an invalid value.");
        }

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteTryCreatePolymorphic(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var methodName =
            mapping.TryCreatePolymorphicMethodName ??
            throw new InvalidOperationException(
                "A polymorphic Create method name is required.");
        var manualMapping = mapping.ManualMapping;
        var sourceTypeName = manualMapping is null
            ? mapping.NonNullSourceTypeName
            : mapping.MaybeNullSourceTypeName;
        var sourceName = manualMapping is null
            ? mapping.NonNullSourceName
            : "source";
        const string resultName = "result";
        var localNames = new GeneratedLocalNameAllocator(
            mapping.AnalysisContext.TargetMapper,
            sourceName,
            "context",
            resultName);

        writer.Line(
            $"private bool {methodName}(");
        writer.Indent();
        writer.Line($"{sourceTypeName} {sourceName},");
        writer.Line(
            "global::Morphant.Context.MappingContext context,");
        writer.Line(
            $"out {mapping.DestinationTypeName} {resultName})");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WritePolymorphicDispatch(
            writer,
            mapping,
            update: false,
            localNames,
            sourceName,
            resultName);

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteTryUpdatePolymorphic(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var methodName =
            mapping.TryUpdatePolymorphicMethodName ??
            throw new InvalidOperationException(
                "A polymorphic Update method name is required.");
        var manualMapping = mapping.ManualMapping;
        var sourceTypeName = manualMapping is null
            ? mapping.NonNullSourceTypeName
            : mapping.MaybeNullSourceTypeName;
        var sourceName = manualMapping is null
            ? mapping.NonNullSourceName
            : "source";
        const string resultName = "result";
        var localNames = new GeneratedLocalNameAllocator(
            mapping.AnalysisContext.TargetMapper,
            sourceName,
            "destination",
            "context",
            resultName);

        writer.Line(
            $"private bool {methodName}(");
        writer.Indent();
        writer.Line($"{sourceTypeName} {sourceName},");
        writer.Line(
            $"{mapping.MaybeNullDestinationTypeName} destination,");
        writer.Line(
            "global::Morphant.Context.MappingContext context,");
        writer.Line(
            $"out {mapping.DestinationTypeName} {resultName})");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WritePolymorphicDispatch(
            writer,
            mapping,
            update: true,
            localNames,
            sourceName,
            resultName);

        writer.Unindent();
        writer.Line("}");
    }

    private static void WriteCreateImpl(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var localNames = TypeMapperMethodLocalNames.Build(
            mapping,
            create: true);
        var methodName =
            mapping.CreateImplMethodName ??
            throw new InvalidOperationException(
                "A Create implementation method name is required.");

        writer.Line(
            "private " +
            (mapping.RequiresUnsafeContext ? "unsafe " : string.Empty) +
            $"{mapping.DestinationTypeName} " +
            $"{methodName}(");
        writer.Indent();
        writer.Line(
            $"{mapping.NonNullSourceTypeName} " +
            mapping.NonNullSourceName + ",");
        if (mapping.CreateImplUsesOperation)
        {
            writer.Line(
                "global::Morphant.Context.MappingOperation operation,");
        }
        writer.Line(
            "global::Morphant.Context.MappingContext context)");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WriteCreateStatements(
            writer,
            mapping,
            mapping.CreateImplUsesOperation
                ? "operation"
                : MappingOperationExpression(update: false),
            localNames);

        writer.Unindent();
        writer.Line("}");
    }

    private static string BuildCreateImplCall(
        TypeMapperMappingModel mapping,
        string methodName,
        bool update)
    {
        var operationArgument = mapping.CreateImplUsesOperation
            ? MappingOperationExpression(update) + ", "
            : string.Empty;

        return $"{methodName}({mapping.NonNullSourceName}, " +
               operationArgument +
               "context)";
    }

    private static void WriteUpdateImpl(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        var localNames = TypeMapperMethodLocalNames.Build(
            mapping,
            create: false);
        var methodName =
            mapping.UpdateImplMethodName ??
            throw new InvalidOperationException(
                "An Update implementation method name is required.");

        writer.Line(
            "private " +
            (mapping.RequiresUnsafeContext ? "unsafe " : string.Empty) +
            $"{mapping.DestinationTypeName} " +
            $"{methodName}(");
        writer.Indent();
        writer.Line(
            $"{mapping.NonNullSourceTypeName} " +
            mapping.NonNullSourceName + ",");
        writer.Line(
            $"{mapping.NonNullDestinationTypeName} destination,");
        writer.Line(
            "global::Morphant.Context.MappingContext context)");
        writer.Unindent();
        writer.Line("{");
        writer.Indent();

        WriteUpdateStatements(
            writer,
            mapping,
            localNames);

        writer.Unindent();
        writer.Line("}");
    }

    private static string BuildUpdateImplCall(
        TypeMapperMappingModel mapping,
        string methodName)
    {
        var destination = mapping.UpdateKind ==
            TypeMapperUpdateKind.NullableValue
                ? "destination.Value"
                : "destination";
        var arguments =
            $"{mapping.NonNullSourceName}, {destination}";

        return $"{methodName}({arguments}, context)";
    }

    private static void WriteNullSourceException(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool update)
    {
        writer.Line(
            "throw new global::Morphant.Exceptions.NullSourceException(");
        writer.Indent();
        writer.Line(MappingOperationExpression(update) + ",");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}));");
        writer.Unindent();
    }

    private static void WriteNullDestinationException(
        CodeWriter writer,
        TypeMapperMappingModel mapping)
    {
        writer.Line(
            "throw new global::Morphant.Exceptions.NullDestinationException(");
        writer.Indent();
        writer.Line(MappingOperationExpression(update: true) + ",");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}));");
        writer.Unindent();
    }

    private static void WriteControlFlowUpdateNode(
        CodeWriter writer,
        TypeMapperControlFlowNode node,
        GeneratedLocalNameAllocator localNames)
    {
        WriteLocalValues(
            writer,
            node.Locals);

        if (node.EvaluationExpression is
                { } evaluationExpression)
        {
            WriteEvaluation(
                writer,
                evaluationExpression,
                node.EvaluationCondition,
                node.EvaluationLocals);
            WriteControlFlowUpdateNode(
                writer,
                node.EvaluationContinuation!,
                localNames);
            return;
        }

        if (node.SwitchExpression is
                { } switchExpression)
        {
            writer.Line($"switch ({switchExpression})");
            writer.Line("{");
            writer.Indent();

            foreach (var section in node.SwitchSections)
            {
                foreach (var label in section.Labels)
                {
                    writer.Line(label);
                }

                writer.Line("{");
                writer.Indent();
                WriteControlFlowUpdateNode(
                    writer,
                    section.Branch,
                    localNames);
                writer.Unindent();
                writer.Line("}");
            }

            writer.Unindent();
            writer.Line("}");

            if (node.SwitchContinuation is
                    { } continuation)
            {
                writer.Line();
                WriteControlFlowUpdateNode(
                    writer,
                    continuation,
                    localNames);
            }

            return;
        }

        if (node.Condition is { } condition)
        {
            writer.Line($"if ({condition})");
            writer.Line("{");
            writer.Indent();
            WriteControlFlowUpdateNode(
                writer,
                node.WhenTrue!,
                localNames);
            writer.Unindent();
            writer.Line("}");
            writer.Line("else");
            writer.Line("{");
            writer.Indent();
            WriteControlFlowUpdateNode(
                writer,
                node.WhenFalse!,
                localNames);
            writer.Unindent();
            writer.Line("}");
            return;
        }

        if (node.ThrowExpression is { } throwExpression)
        {
            var resolvedThrowExpression = ResolveThrowExpression(
                throwExpression,
                node.ThrowUsesCurrentMappingOperation,
                MappingOperationExpression(update: true));
            writer.Line($"throw {resolvedThrowExpression};");
            return;
        }

        WriteUpdateLeafStatements(
            writer,
            node.Leaf!.Value,
            allowReplacement: true,
            localNames: localNames);
    }

    private static void WriteUpdateLeafStatements(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        bool allowReplacement,
        GeneratedLocalNameAllocator localNames)
    {
        if (mapping.Failure is
            { } unsupportedMappingMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedMappingMessage,
                update: true);
            return;
        }

        if (mapping.UpdateFailure is
            { } unsupportedExceptionMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedExceptionMessage,
                update: true);
            return;
        }

        if (mapping.UpdateDirectExpression is
            { } directExpression)
        {
            writer.Line($"return {directExpression};");
            return;
        }

        if (allowReplacement &&
            mapping.CreateFactory is { } factory)
        {
            WriteFactoryCreateStatements(
                writer,
                mapping,
                factory,
                MappingOperationExpression(update: true),
                localNames);
            return;
        }

        if (allowReplacement &&
            mapping.CreateConstructor is { } constructor)
        {
            WriteConstructorCreateStatements(
                writer,
                mapping,
                constructor,
                MappingOperationExpression(update: true),
                localNames);
            return;
        }

        if (mapping.UpdateKind ==
            TypeMapperUpdateKind.Unsupported)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                "Morphant could not generate Update for this mapping.",
                update: true);
            return;
        }

        if (mapping.PostMemberControlFlow is { } postControlFlow)
        {
            WritePostMemberControlFlow(
                writer,
                mapping,
                postControlFlow,
                "destination",
                localNames,
                operationExpression:
                    MappingOperationExpression(update: true));
            return;
        }

        if (mapping.UpdateMemberMappings.IsEmpty)
        {
            writer.Line("return destination;");
            return;
        }

        WriteMemberValueLocals(
            writer,
            mapping.UpdateMemberMappings);

        foreach (var memberMapping in
                 mapping.UpdateMemberMappings)
        {
            WriteInvocationArgumentLocals(writer, memberMapping);
            writer.Line(
                "destination." +
                $"{Identifier(memberMapping.DestinationMemberName)} = " +
                MemberValueExpression(
                    mapping,
                    memberMapping,
                    localNames) +
                ";");
        }

        writer.Line();
        writer.Line("return destination;");
    }

    private static void WritePostMemberControlFlow(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        TypeMapperMemberControlFlowNode node,
        string assignmentTarget,
        GeneratedLocalNameAllocator localNames,
        string? returnExpression = null,
        string? operationExpression = null)
    {
        operationExpression ??=
            MappingOperationExpression(update: false);

        WriteLocalValues(writer, node.Locals);

        if (node.EvaluationExpression is { } evaluationExpression)
        {
            WriteEvaluation(
                writer,
                evaluationExpression,
                node.EvaluationCondition,
                node.EvaluationLocals);
            WritePostMemberControlFlow(
                writer,
                mapping,
                node.EvaluationContinuation!,
                assignmentTarget,
                localNames,
                returnExpression,
                operationExpression);
            return;
        }

        if (node.SwitchExpression is { } switchExpression)
        {
            writer.Line($"switch ({switchExpression})");
            writer.Line("{");
            writer.Indent();

            foreach (var section in node.SwitchSections)
            {
                foreach (var label in section.Labels)
                {
                    writer.Line(label);
                }

                writer.Line("{");
                writer.Indent();
                WritePostMemberControlFlow(
                    writer,
                    mapping,
                    section.Branch,
                    assignmentTarget,
                    localNames,
                    returnExpression,
                    operationExpression);
                writer.Unindent();
                writer.Line("}");
            }

            writer.Unindent();
            writer.Line("}");

            if (node.SwitchContinuation is { } continuation)
            {
                writer.Line();
                WritePostMemberControlFlow(
                    writer,
                    mapping,
                    continuation,
                    assignmentTarget,
                    localNames,
                    returnExpression,
                    operationExpression);
            }

            return;
        }

        if (node.Condition is { } condition)
        {
            writer.Line($"if ({condition})");
            writer.Line("{");
            writer.Indent();
            WritePostMemberControlFlow(
                writer,
                mapping,
                node.WhenTrue!,
                assignmentTarget,
                localNames,
                returnExpression,
                operationExpression);
            writer.Unindent();
            writer.Line("}");
            writer.Line("else");
            writer.Line("{");
            writer.Indent();
            WritePostMemberControlFlow(
                writer,
                mapping,
                node.WhenFalse!,
                assignmentTarget,
                localNames,
                returnExpression,
                operationExpression);
            writer.Unindent();
            writer.Line("}");
            return;
        }

        if (node.ThrowExpression is { } throwExpression)
        {
            var resolvedThrowExpression = ResolveThrowExpression(
                throwExpression,
                node.ThrowUsesCurrentMappingOperation,
                operationExpression);
            writer.Line($"throw {resolvedThrowExpression};");
            return;
        }

        if (node.Failure is { } unsupportedMessage)
        {
            WriteMappingConfigurationFailureStatement(
                writer,
                mapping,
                unsupportedMessage,
                operationExpression);
            return;
        }

        WriteMemberValueLocals(writer, node.MemberMappings);

        foreach (var memberMapping in node.MemberMappings)
        {
            WriteInvocationArgumentLocals(writer, memberMapping);
            writer.Line(
                assignmentTarget + "." +
                $"{Identifier(memberMapping.DestinationMemberName)} = " +
                MemberValueExpression(
                    mapping,
                    memberMapping,
                    localNames) +
                ";");
        }

        if (!node.MemberMappings.IsEmpty)
        {
            writer.Line();
        }

        writer.Line($"return {returnExpression ?? assignmentTarget};");
    }

    private static void WriteMappingConfigurationFailure(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        MappingFailureObservation failure,
        bool update) =>
        WriteMappingConfigurationFailure(
            writer,
            mapping,
            failure.RecoveryMessage,
            update);

    private static void WriteMappingConfigurationFailure(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string reason,
        bool update) =>
        WriteMappingConfigurationFailure(
            writer,
            mapping,
            reason,
            MappingOperationExpression(update));

    private static void WriteMappingConfigurationFailure(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        MappingFailureObservation failure,
        string operationExpression) =>
        WriteMappingConfigurationFailure(
            writer,
            mapping,
            failure.RecoveryMessage,
            operationExpression);

    private static void WriteMappingConfigurationFailure(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string reason,
        string operationExpression)
    {
        var reasonLiteral =
            SyntaxFactory.LiteralExpression(
                    SyntaxKind.StringLiteralExpression,
                    SyntaxFactory.Literal(reason))
                .ToString();

        writer.Line(
            "=> throw new global::Morphant.Exceptions." +
            "MappingConfigurationException(");
        writer.Indent();
        writer.Line(operationExpression + ",");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}),");
        writer.Line($"{reasonLiteral});");
        writer.Unindent();
    }

    private static void WriteMappingConfigurationFailureStatement(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        MappingFailureObservation failure,
        bool update) =>
        WriteMappingConfigurationFailureStatement(
            writer,
            mapping,
            failure.RecoveryMessage,
            update);

    private static void WriteMappingConfigurationFailureStatement(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string reason,
        bool update) =>
        WriteMappingConfigurationFailureStatement(
            writer,
            mapping,
            reason,
            MappingOperationExpression(update));

    private static void WriteMappingConfigurationFailureStatement(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        MappingFailureObservation failure,
        string operationExpression) =>
        WriteMappingConfigurationFailureStatement(
            writer,
            mapping,
            failure.RecoveryMessage,
            operationExpression);

    private static void WriteMappingConfigurationFailureStatement(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string reason,
        string operationExpression)
    {
        var reasonLiteral =
            SyntaxFactory.LiteralExpression(
                    SyntaxKind.StringLiteralExpression,
                    SyntaxFactory.Literal(reason))
                .ToString();

        writer.Line(
            "throw new global::Morphant.Exceptions." +
            "MappingConfigurationException(");
        writer.Indent();
        writer.Line(operationExpression + ",");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}),");
        writer.Line($"{reasonLiteral});");
        writer.Unindent();
    }

    private static void WriteUnsupportedOperation(
        CodeWriter writer,
        TypeMapperMappingModel mapping,
        string operation)
    {
        writer.Line(
            "=> throw new global::Morphant.Exceptions." +
            "MappingOperationNotSupportedException(");
        writer.Indent();
        writer.Line(
            $"global::Morphant.Context.MappingOperation.{operation},");
        writer.Line($"typeof({mapping.SourceRuntimeTypeName}),");
        writer.Line($"typeof({mapping.DestinationRuntimeTypeName}),");
        writer.Line(
            "global::Morphant.MappingMode." +
            mapping.EffectiveSettings.MappingMode + ");");
        writer.Unindent();
    }

    private static void WriteLocalValues(
        CodeWriter writer,
        ImmutableArray<TypeMapperLocalValueModel> locals)
    {
        foreach (var local in locals)
        {
            WriteLocalValue(writer, local);
        }

        if (!locals.IsEmpty)
        {
            writer.Line();
        }
    }

    private static void WriteEvaluation(
        CodeWriter writer,
        string expression,
        string? condition,
        ImmutableArray<TypeMapperLocalValueModel> locals)
    {
        if (condition is null)
        {
            WriteLocalValues(
                writer,
                locals.IsDefault
                    ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                    : locals);
            writer.Line($"_ = {expression};");
            writer.Line();
            return;
        }

        writer.Line($"if ({condition})");
        writer.Line("{");
        writer.Indent();
        WriteLocalValues(
            writer,
            locals.IsDefault
                ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                : locals);
        writer.Line($"_ = {expression};");
        writer.Unindent();
        writer.Line("}");
        writer.Line();
    }

    private static void WriteMultilineDeclaration(
        CodeWriter writer,
        string declaration)
    {
        foreach (var line in declaration
                     .Replace("\r\n", "\n")
                     .Replace('\r', '\n')
                     .Split('\n'))
        {
            writer.Line(line);
        }
    }

    private static string SourceValueExpression(
        TypeMapperMappingModel mapping,
        string sourceMemberName,
        string? sourceValueLocalName)
    {
        return sourceValueLocalName ??
               $"{mapping.NonNullSourceName}." +
               Identifier(sourceMemberName);
    }

    private static string MemberValueExpression(
        TypeMapperMappingModel owner,
        TypeMapperMemberMappingModel mapping,
        GeneratedLocalNameAllocator localNames)
    {
        return mapping.ValueLocalName ??
               mapping.ExplicitValueExpression ??
               mapping.SourceValueLocalName ??
               mapping.ConventionValueExpression?.Render(localNames) ??
               SourceValueExpression(
                   owner,
                   mapping.SourceMemberName,
                   mapping.SourceValueLocalName);
    }

    private static void WriteMemberValueLocals(
        CodeWriter writer,
        IEnumerable<TypeMapperMemberMappingModel> mappings)
    {
        var wroteLocal = false;

        foreach (var mapping in mappings)
        {
            foreach (var local in mapping.EvaluationLocals.IsDefault
                         ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                         : mapping.EvaluationLocals)
            {
                WriteLocalValue(writer, local);
                wroteLocal = true;
            }

            if (mapping.ValueLocalName is not { } valueLocalName)
            {
                continue;
            }

            var valueTypeName =
                mapping.ExplicitValueTypeName ??
                throw new InvalidOperationException(
                    "A member value local requires a value type.");
            var valueExpression =
                mapping.ExplicitValueExpression ??
                throw new InvalidOperationException(
                    "A member value local requires an explicit expression.");

            writer.Line(
                $"{valueTypeName} {valueLocalName} = " +
                valueExpression +
                ";");
            wroteLocal = true;
        }

        if (wroteLocal)
        {
            writer.Line();
        }
    }

    private static void WriteLocalValue(
        CodeWriter writer,
        TypeMapperLocalValueModel local)
    {
        writer.Line(
            (local.IsConst
                ? "const "
                : string.Empty) +
            $"{local.DeclarationType} {local.Name} = " +
            local.ValueExpression +
            ";");
    }

    private static void WriteInvocationArgumentLocals(
        CodeWriter writer,
        TypeMapperMemberMappingModel mapping)
    {
        WriteLocalValues(
            writer,
            mapping.InvocationArgumentLocals.IsDefault
                ? ImmutableArray<TypeMapperLocalValueModel>.Empty
                : mapping.InvocationArgumentLocals);
    }

    private static string ConstructorArgumentValueExpression(
        TypeMapperMappingModel owner,
        TypeMapperConstructorArgumentMappingModel mapping,
        GeneratedLocalNameAllocator localNames)
    {
        return mapping.ValueLocalName ??
               ConstructorArgumentUncachedValueExpression(
                   owner,
                   mapping,
                   localNames);
    }

    private static string ConstructorArgumentUncachedValueExpression(
        TypeMapperMappingModel owner,
        TypeMapperConstructorArgumentMappingModel mapping,
        GeneratedLocalNameAllocator localNames)
    {
        return mapping.ExplicitValueExpression ??
               mapping.ConventionValueExpression?.Render(localNames) ??
               SourceValueExpression(
                   owner,
                   mapping.SourceMemberName,
                   sourceValueLocalName: null);
    }

    private static string ResolveThrowExpression(
        string throwExpression,
        bool usesCurrentMappingOperation,
        string operationExpression)
    {
        if (!usesCurrentMappingOperation)
        {
            return throwExpression;
        }

        return throwExpression.Replace(
            "context.Operation",
            operationExpression);
    }

    private static string MappingOperationExpression(bool update) =>
        "global::Morphant.Context.MappingOperation." +
        (update ? "Update" : "Create");

    private static string Identifier(string value)
    {
        return SyntaxFacts.GetKeywordKind(value) != SyntaxKind.None ||
               SyntaxFacts.GetContextualKeywordKind(value) != SyntaxKind.None
            ? "@" + value
            : value;
    }
}
