namespace Morphant.Generator.UnitTests.ConstructionAndMembersUsageTests.Factories;

internal sealed partial class FactoriesTests
{
    [Test]
    [Description("Members attempts to replace a readonly scalar on the System.Tuple returned by a factory.")]
    public void SystemTupleFactoryThenScalarMember()
    {
        // lang=c#
        const string source =
"""
#nullable enable
#pragma warning disable CS1591
using System;
using Morphant;
using Morphant.Context;

namespace TestCase
{
    public sealed class Source
    {
        public int Id => 7;
        public string Name => "from convention";
        public int Item1 => 7;
        public string Item2 => "from convention";
        public string FromConstruct() => "from constructor";
        public string FromMembers() => "from members";
    }

    [MorphantMapper]
    public partial class Mapper : TypeMapper<Mapper>
    {
        protected override void Configure(MapperBuilder builder) =>
            builder.Map<Source, Tuple<int, string>>()
                .MemberSelection(MemberSelection.Explicit)
                .ConstructUsing(source => new Tuple<int, string>(source.Id, source.FromConstruct()))
                .Members(source => new() { Item2 = source.FromMembers() });
    }
}
""";

        // Complete mapper output; the companion surface snapshots cover the generated DSL.
        ConstructionAndMembersSnapshot.Verify(
            source,
            expectedMappers:
            [
            ("Morphant.Generated.TypeMapper.TestCase_Mapper.g.cs",
"""
// <auto-generated />
#nullable enable

namespace TestCase
{
    public partial class Mapper :
        global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, string>>
    {
        /// <inheritdoc/>
        protected override bool Supports(
            global::System.Type sourceType,
            global::System.Type destinationType) =>
                (sourceType == typeof(global::TestCase.Source) &&
                    destinationType == typeof(global::System.Tuple<int, string>)) ||
                base.Supports(sourceType, destinationType);

        /// <inheritdoc/>
        global::System.Tuple<int, string> global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, string>>.Create(
            global::TestCase.Source? source,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            return __Create(source, context);
        }

        /// <inheritdoc/>
        global::System.Tuple<int, string> global::Morphant.ITypeMapper<global::TestCase.Source, global::System.Tuple<int, string>>.Update(
            global::TestCase.Source? source,
            global::System.Tuple<int, string>? destination,
            global::Morphant.Context.MappingContext context)
        {
            if (source is null)
            {
                return default!;
            }

            if (destination is null)
            {
                return __Create(source, context);
            }

            return __Update(source, destination, context);
        }

        private global::System.Tuple<int, string> __Create(
            global::TestCase.Source source,
            global::Morphant.Context.MappingContext context)
        {
            global::System.Tuple<int, string> result = __ConstructUsing(source);

            if (result is null)
            {
                return default!;
            }

            throw new global::Morphant.Exceptions.MappingConfigurationException(
                global::Morphant.Context.MappingOperation.Create,
                typeof(global::TestCase.Source),
                typeof(global::System.Tuple<int, string>),
                "This member cannot be assigned in this Create or Update case.");
        }

        private global::System.Tuple<int, string> __Update(
            global::TestCase.Source source,
            global::System.Tuple<int, string> destination,
            global::Morphant.Context.MappingContext context)
        {
            return destination;
        }

        private global::System.Tuple<int, string> __ConstructUsing(global::TestCase.Source source) => new global::System.Tuple<int, string>(source.Id, source.FromConstruct());
    }
}
""")
            ],
            expectedSurfaces: SystemTupleFactoryThenScalarMemberSurfaces,
            expectedDiagnostics: """
MORPH0042 Error: Rule for destination member 'element #2 (Item2)' cannot be applied in mapping 'TestCase.Source -> System.Tuple<int, string>': read-only tuple element cannot be assigned after ConstructUsing or ResolveUsing returns. Affected cases: Create; Update without an existing destination.
  at TestCase.cs(26,44-26,49); TestCase.cs(25,18-25,32)
""");
    }
}
